### ISSUE TITLE
Session::run should take a const parameter

### ISSUE THREAD

**Issue by michaelcowan** [catchorg/Catch2#1031]
## Description
I configure Catch programmatically like this:

```
        Catch::Session session;
        
        Catch::ConfigData config;
        config.showDurations = Catch::ShowDurations::Always;
        config.useColour = Catch::UseColour::No;
        session.useConfigData(config);
        
        char * argv[] = { "TestApp", "-r", "junit" };
        int numberFailed = session.run(3, argv);
```
This throws a compiler warning
```
ISO C++11 does not allow conversion from string literal to 'char *'
```

### Steps to reproduce
Use the code snippet above.

### Extra information
As of C++11 the implicit conversion from `char *` to `const char *` has been deprecated. 

To fix this the signatures can be changed to:
```
int run(int argc, const char* argv[]);

Args(int argc, const char *argv[]) {

int applyCommandLine(int argc, const char* argv[]);

```

I have tested this on the version below and it seems to work fine.

* Catch version: **2.0.0-develop.4**
* Operating System: **OSX**
* Compiler+version: **Clang**

**Comment by lightmare** [comment]
Standard says `main` takes `char**`, that is a pointer to `char*`. That thing doesn't implicitly convert to `const char**` (pointer to `const char*`). So there'd need to extra overloads and some `const_cast`s for this usage.

If your example is all you want this for, try
```c++
#define CATCH_CONFIG_DEFAULT_REPORTER "junit"
```

**Comment by michaelcowan** [comment]
@lightmare I see your point. Thats a real shame as the parameter is not being modified and strictly speaking _is_ `const` - but I get your point that this is painful when passing arguments to `main`.

I set the arguments programatically because I am embedding Catch into a platform abstraction, and really currently only use it to set the application name - so the junit define doesn't help but I may use it in the future - thanks.

The solution for me is to simply perform the casting myself, which seems reasonable.
Thank you for your reply.
