### ISSUE TITLE
On 2.0-dev5 option arguments that start with "/" do not work

### ISSUE THREAD

**Issue by eiennohito** [catchorg/Catch2#1054]
## Description
And if you want to output your log to an absolute path on Unix...

### Steps to reproduce
Run a compiled binary with `-o /tmp/results`.

### Extra information
* Catch version: **2.0.0-develop.5**

### Error message
```
Error(s) in input:
  Expected argument following -o
```

### Workaround
Use --out=/tmp/test

**Comment by philsquared** [comment]
Thanks for this.
I see the problem (some leakage from the Windows support). I've fixed it locally, but just need a chance to double check on Windows, too, before I commit.

**Comment by philsquared** [comment]
That's in. There will be a new single include in the near future (but you can always run the generate script in the scripts folder if you want to check it out sooner)

**Comment by horenmar** [comment]
Final is out
