### ISSUE TITLE
[Feature Request] support for stream insertion as argument to sections, equivalent to behaviour of warn/info

### ISSUE THREAD

**Issue by alwaysmpe** [catchorg/Catch2#1073]
The WARN and INFO macros expand to permit stream insertion. It would be a nice addition, more syntactically consistent and easier for beginners for the same to apply to SECTION and the BDD equivalents.

Where these macros expand strings to arguments of constructors this could be implemented as below to reduce the need to restructure
```
#include <sstream>
#define CATCH_SS( desc ) ( static_cast<std::stringstream&>(std::stringstream() << desc ).str() )
```
This trivially works with the given/when/then macros:
`#define GIVEN( desc )    SECTION( std::string("   Given: ") + CATCH_SS( desc ), "" )`

However I'm not certain of compatibility with the rest of the code base.

**Comment by alwaysmpe** [comment]
It seems this has now been implemented with DYNAMIC_SECTION and given/when/then all forward onto this, so I'm closing.

**Comment by horenmar** [comment]
Yeah. Sorry for not closing the issue, but sometimes old issues can fall through the cracks.
