### ISSUE TITLE
Update the project description to not mention C++98, C++03 anymore

### ISSUE THREAD

**Issue by martinmoene** [catchorg/Catch2#1075]
Congratulations on the official release of Catch 2!

**Comment by catchorgadmin** [comment]
Give me a chance!
;-)

Done!

**Comment by horenmar** [comment]
I would argue that C++98 a C++03 is still supported via Catch classic and thus should be included.

**Comment by philsquared** [comment]
In fact it is (I just moved it to a parenthetical)
