### ISSUE TITLE
no operator found with Catch 2

### ISSUE THREAD

**Issue by GatoRat** [catchorg/Catch2#1087]
The following code fails when compiling with Catch 2.0.1 in Visual Studio 2017 15.4.3:

**Note the missing const on the equality operator.**

```
struct A
{
    struct B
    {
        int val;

        bool operator==(const B& b)
        {
            return val == b.val;
        }
    };

    B b;

    A(int val_)
    {
        b.val = val_;
    }
};

TEST_CASE("Test")
{
    A a1(1);
    A a2(2);
    A a3(2);

    REQUIRE(a1.b == a2.b);
    REQUIRE(a2.b == a3.b);
}
```

The output from this is:

1>------ Build started: Project: CatchTest, Configuration: Debug x64 ------
1>CatchTest.cpp
1>c:\dev2\test\catchtest\catch.hpp(1040): error C2678: binary '==': no operator found which takes a left-hand operand of type 'const A::B' (or there is no acceptable conversion)
1>c:\dev2\test\catchtest\catchtest.cpp(12): note: could be 'bool A::B::operator ==(const A::B &)'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.11.25503\include\system_error(372): note: or       'bool std::operator ==(const std::error_condition &,const std::error_condition &) noexcept'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.11.25503\include\system_error(366): note: or       'bool std::operator ==(const std::error_condition &,const std::error_code &) noexcept'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.11.25503\include\system_error(360): note: or       'bool std::operator ==(const std::error_code &,const std::error_condition &) noexcept'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.11.25503\include\system_error(354): note: or       'bool std::operator ==(const std::error_code &,const std::error_code &) noexcept'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.11.25503\include\exception(342): note: or       'bool std::operator ==(const std::exception_ptr &,std::nullptr_t) throw()'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.11.25503\include\exception(337): note: or       'bool std::operator ==(std::nullptr_t,const std::exception_ptr &) throw()'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.11.25503\include\exception(332): note: or       'bool std::operator ==(const std::exception_ptr &,const std::exception_ptr &) throw()'
1>c:\dev2\test\catchtest\catch.hpp(1040): note: while trying to match the argument list '(const A::B, const A::B)'
1>c:\dev2\test\catchtest\catch.hpp(1069): note: see reference to function template instantiation 'bool Catch::compareEqual<A::B,RhsT>(const LhsT &,const RhsT &)' being compiled
1>        with
1>        [
1>            RhsT=A::B,
1>            LhsT=A::B
1>        ]
1>c:\dev2\test\catchtest\catchtest.cpp(32): note: see reference to function template instantiation 'const Catch::BinaryExpr<LhsT,const A::B &> Catch::ExprLhs<LhsT>::operator ==<A::B>(const RhsT &)' being compiled
1>        with
1>        [
1>            LhsT=const A::B &,
1>            RhsT=A::B
1>        ]
1>c:\dev2\test\catchtest\catchtest.cpp(32): note: see reference to function template instantiation 'const Catch::BinaryExpr<LhsT,const A::B &> Catch::ExprLhs<LhsT>::operator ==<A::B>(const RhsT &)' being compiled
1>        with
1>        [
1>            LhsT=const A::B &,
1>            RhsT=A::B
1>        ]
1>Done building project "CatchTest.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by horenmar** [comment]
Non-const comparison ops are no longer supported. Note that the provided `operator==` has signature equivalent with `operator==(B&, B const&)`.
