### ISSUE TITLE
Release info promises `*_THROWS_WITH(expr, exception_type, matcher)`

### ISSUE THREAD

**Issue by joto** [catchorg/Catch2#1088]
## Description

The [release info for v2.0.1](https://github.com/catchorg/Catch2/releases/tag/v2.0.1) says:

> New assertion macros, *_THROWS_WITH(expr, exception_type, matcher) are provided...

This doesn't work though. Maybe `*_THROWS_MATCHES` is meant.

This still doesn't allow me to easily match the exception type and the exception message in the same macro.

**Comment by horenmar** [comment]
As you found out, it was supposed to be `THROWS_MATCHES`. Sorry about that.

And if you provide a matcher, it can do exactly what you want:

```cpp
struct ExceptionContentMatcher : Catch::MatcherBase<std::exception> {
    ExceptionContentMatcher(std::string const& target) :m_target(target) {}
    bool match(std::exception const& matchee) const override {
        return matchee.what() == m_target;
    }
    std::string describe() const override {
        return "exception message is:\"" + m_target + "\"";
    }

private:
    std::string m_target;
};

TEST_CASE("Blabla", "[SpecialTag]") {
    REQUIRE_THROWS_MATCHES(throw std::runtime_error("foo"), std::exception, ExceptionContentMatcher{ "foo" });
}
```

**Comment by philsquared** [comment]
Thanks @joto - I've fixed the release notes now.

Although what @horenmar says above is correct I do wonder if we should do better, here. After all the _actual_ `REQUIRE_THROWS_WITH` let's you use a string matcher. We could probably special case `REQUIRE_THROWS_MATCHES` to allow a string matcher, too.
I'll leave this ticket open while I think about that.

**Comment by horenmar** [comment]
Closed for inactivity
