### ISSUE TITLE
UnorderedElementsAre Container Matcher

### ISSUE THREAD

**Issue by shreyasbharath** [catchorg/Catch2#1093]
Googletest has an [UnorderedElementsAre](https://github.com/google/googletest/blob/master/googlemock/docs/CheatSheet.md) matcher which comes in very handy from time to time.

I couldn't find an equivalent in Catch, Contains comes close but doesn't quite do a full container match.

Can we implement something like this in Catch too? Something like -

```
CHECK_THAT(collection, UnorderedEquals(anotherCollection));
```

**Comment by horenmar** [comment]
If I understand you correctly, you want to check that two containers are equal, but the elements are not necessarily in the same order, correct?

**Comment by shreyasbharath** [comment]
@horenmar Yes that's correct.

**Comment by shreyasbharath** [comment]
At the moment we can achieve this in two steps as a workaround -

```
CHECK_THAT(collection.size(), Equals(expectedSize));
CHECK_THAT(collection, Contains(expectedCollection));
```

But this gets tedious pretty quickly and one can easily forget to do the first step!

**Comment by shreyasbharath** [comment]
Beautiful! Thank you for implementing!
