### ISSUE TITLE
Interesting README technique

### ISSUE THREAD

**Issue by mwpowellhtx** [catchorg/Catch2#1095]
So here's an interesting technique that I started doing. I wanted to include a little qualifying verbiage explaining what the gist of the test cases was all about, so I included a "README" no-op test case, along these lines:

```C++
TEST_CASE("README", Catch::Tags("rfc", "12345", "readme").c_str()) {
    WARN("Declare some verbiage about the test cases.");
    WARN("Declare some more verbiage about the test cases.");
    CHECK(true);
}
```

Cheers!

**Comment by philsquared** [comment]
Interesting.
BTW you could do `SUCCEED()` instead of `CHECK(true)`.

But why are you using `Catch::Tags`?

**Comment by mwpowellhtx** [comment]
Great thanks!

[Tags](1062) is a helper I came up with so that I could enumerate tag names from listed names without *[worrying][about][syntax][issues]*.

It would be better if TEST_CASE supported *std::string* instead of *const char**, but that's an acceptable tradeoff for me.

**Comment by philsquared** [comment]
You mean without having to rely on getting the square brackets right?
As for `TEST_CASE` supporting `std::string`, as of Catch2 it uses `StringRef`s (which are like `std::string_view` - and are constructible from, `std::string`s.

**Comment by mwpowellhtx** [comment]
Exactly. I'd like to just list my tags in declarative fashion, and push the syntax away a bit.

Ah, I see. Nice! I'll have a look-see at that.
