### ISSUE TITLE
Dropping support for non-const comparison breaks non-const user-defined conversion

### ISSUE THREAD

**Issue by foonathan** [catchorg/Catch2#1098]
## Description

So I'm not sure whether this needs to be fixed but I noticed it in my test.
If you have a class with a non-const conversion operator and want to compare it, this breaks as the object will be passed around via `const&` in Catch2, so the conversion operator can't be called.

### Steps to reproduce

        struct foo
        {
            friend bool operator==(const foo&, const foo&)
            {
                return true;
            }
        };

        struct bar
        {
            operator foo() /* non-const! */
            {
                return {};
            }
        };

        TEST_CASE("foo)
        {
            foo f;
            f == bar{}; // works
            REQUIRE(f == bar{}); // doesn't work
        }

**Comment by horenmar** [comment]
I didn't foresee this side-effect, but I think that conversion operators should be `const` (or have a `const` and `&&` overload).

**Comment by foonathan** [comment]
Yeah, they should. This was just an oversight on my test, I didn't have any problems.

Feel free to close it.
