### ISSUE TITLE
Robust dynamic discovery of Catch tests in CMake

### ISSUE THREAD

**Issue by garethsb** [catchorg/Catch2#1099]
Inspired by [this post](https://blog.kitware.com/dynamic-google-test-discovery-in-cmake-3-10/), I recently implemented robust dynamic discovery of Catch tests for CMake, without relying on parsing source code as implemented by ParseAndAddCatchTests in #892.

See https://gist.github.com/garethsb/a01ed0dbd4977d439c16200640549935

It allows this for instance:

```CMake
catch_discover_tests(my-target-test-runner TEST_SPEC these* EXTRA_ARGS -r compact)
catch_discover_tests(my-target-test-runner TEST_SPEC a* ~ab* abc EXTRA_ARGS -r compact)
```
(using some of the ``<test-spec>`` examples from [Specifying which tests to run](https://github.com/catchorg/Catch2/blob/master/docs/command-line.md#specifying-which-tests-to-run))

**Comment by dvirtz** [comment]
Great. I was planning to go for it as well.
Please make a PR to include it along with ParseAndAddCatchTests.

**Comment by garethsb** [comment]
My gist is derived from code in CMake repo, licensed under BSD 3-clause licence. Is it ok for inclusion in Catch2 repo? I am not a lawyer...

**Comment by dvirtz** [comment]
Maybe contribute it to CMake then, like Google test is?

**Comment by horenmar** [comment]
@garethsb Boost licence would be preferable, but having 3-clause BSD cmake script in `contrib/` should be ok.

How much is it derived from the original source versus implemented based on the linked blog post?

**Comment by garethsb** [comment]
@dvirtz I have left a comment on the Kitware blog post asking if the gist would be considered for incorporation in CMake.

@horenmar It is derived from the Google Test implementation in CMake repo. (In fact, it ought to be possible to refactor out the commonality, but I thought better to wait until I knew where `catch_discover_tests` has a home before attempting that.)

Maybe we need the opinion of @mwoehlke-kitware!

**Comment by mwoehlke-kitware** [comment]
If it goes into CMake, refactoring to share code would be interesting. (At least, I would suggest adding a comment to both spots to keep them in sync as far as bug fixes / improvements.)

**Comment by garethsb** [comment]
Thank you all for your comments so far.

@philsquared @horenmar What is your opinion for the best home for this script? In the CMake repo there is the possibility of shared code with the Google Test equivalent by @mwoehlke-kitware, but since `ParseAndAddCatchTests` is in the Catch repo and this new `catch_discover_tests` depends on the format of the output of `--list-test-names-only`, the Catch repo is also a good home. There is a high bar for the merge request procedure for CMake, so it may take some time to have it accepted into CMake, but I can attempt it. And there is the licensing to consider (I assume dual licensing isn't a possibility and probably just makes things more complicated rather than less)...

**Comment by horenmar** [comment]
@garethsb I would place it into `Catch2/contrib/` for the foreseeable future. If it gets included in CMake, nice, but then the world will need another 5 years until it can be reasonably expected to be everywhere (and another 10 for RHEL :smile:).

**Comment by sonOfRa** [comment]
Do I understand this correctly, that with CMake < 3.10.0 I cannot use catch_discover_tests multiple times, since that will always trigger the fatal error "Cannot set more than one TEST_INCLUDE_FILE"?

**Comment by horenmar** [comment]
A variant of the is merged to master

**Comment by garethsb-sony** [comment]
Thank you, @horenmar. 


> Do I understand this correctly, that with CMake < 3.10.0 I cannot use catch_discover_tests multiple times, since that will always trigger the fatal error "Cannot set more than one TEST_INCLUDE_FILE"?

@sonOfRa, short answer to your question is Yes, that's true.

If there is a CMake 3.9 compatible implementation that allows this, we'd be very happy to have a patch. But as far as I understand `TEST_INCLUDE_FILES` was added in 3.10.0 for exactly this reason, so I didn't go looking for one, just made it work for the simple case in 3.9.

**Comment by mwoehlke-kitware** [comment]
I haven't checked what the catch2 implementation does, but what I did for [KWIVER](http://www.kwiver.org/) (which has a compatibility version of the very similar GoogleTest.cmake, seen [here](https://github.com/Kitware/kwiver/blob/master/CMake/future/3.10/GoogleTest.cmake)) is set `CTEST_INCLUDE_FILE` to a wrapper that I write at configuration time to include a file per `gtest_discover_tests` invocation (and also the user's `CTEST_INCLUDE_FILE`, if they set one). This should work around the aforementioned issue, but the implementation is non-trivially more complicated. This sort of thing is **MUCH** easier with `CTEST_INCLUDE_FILES`, which is indeed why I added that to CMake 🙂.

**Comment by mwoehlke-kitware** [comment]
It should work, yes; that's basically what I said in the previous comment. I can't speak as much to your second question :slightly_smiling_face:.

**Comment by garethsb-sony** [comment]
When I wrote this version for Catch, I figured I'd focus on the tidier implementation possible with forthcoming (now, recent) CMake, with just the minimum of compatibility for old versions of CMake.

Maintain a workaround or have to encourage people to be (relatively) up to date... it's a trade-off. :-)

**Comment by horenmar** [comment]
I won't stop a person from implementing it and opening a PR, but I am completely OK with leaving it CMake 3.10 dependant and let people update their environments over time.
