### ISSUE TITLE
Change badge of AppVeyor to be in svg in Readme.md

### ISSUE THREAD

**Issue by martinmoene** [catchorg/Catch2#1100]
Append `?svg=true` to the AppVeyor status URL to get a crystal clear [![Build status](https://ci.appveyor.com/api/projects/status/hrtk60hv6tw6fght?svg=true)](https://ci.appveyor.com/project/catchorg/catch2)

**Comment by horenmar** [comment]
Wasn't it like that before the move to Catch2?
