### ISSUE TITLE
Disable summary

### ISSUE THREAD

**Issue by thetic** [catchorg/Catch2#1105]
I'd like an option to disable printing the summary in the console and compact reporters. Many use cases are interested only in failures. Alternatively, failure information could be printed to stderr and success/summary information to stdout.

**Comment by horenmar** [comment]
I assume you want to programatically parse the output and the summary is in the way? Standard Catch distribution already provides 2 parsable reporters, `junit` and `xml`. We also provide 3 extra parsable reporters in the repo: TAP, Automake and TeamCity.

Alternatively, you can write your own reporter, and base it on one of the provided ones, but I don't think that the added complexity in-repo is worth it the benefits.

**Comment by philsquared** [comment]
Any further thoughts on this, @thetic?

**Comment by thetic** [comment]
For my use case it would still be preferable to route failure reporting separately.

**Comment by helmesjo** [comment]
So... Was this added or skipped?
