### ISSUE TITLE
Exception Specification Warning with latest CL.exe

### ISSUE THREAD

**Issue by LeonineKing1199** [catchorg/Catch2#1109]
Compiling using Catch  2.0.1-1 via vcpkg yields these warnings for me msvc v15.4.4:
```
C:\vcpkg\installed\x64-windows\include\catch.hpp(4717): warning: extra ";" ignored

C:\vcpkg\installed\x64-windows\include\catch.hpp(4881): warning: exception specification for virtual function "Catch::clara::detail::ResultValueBase<T>::~ResultValueBase [with T=T]" is incompatible with that of overridden function "Catch::clara::detail::ResultBase::~ResultBase"
```

I'm compiling using the default/standard Debug CMake build type.

**Comment by horenmar** [comment]
I don't have commit rights to Clara, so fixing this is up to @philsquared

**Comment by philsquared** [comment]
From our conversation on Slack it's my understanding that the exception specification issue is moot.
As for the extra `;` - I have fixed that in Clara and will merge that in before the next release.
