### ISSUE TITLE
Make Catch_global_namespace_dummy a complete type

### ISSUE THREAD

**Issue by AndrewPaxie** [catchorg/Catch2#1110]
### Description

Compile the unit tests for the [Trompeloeil](https://github.com/rollbear/trompeloeil) mock object library,
in this particular combination of C++ Standard Library and compiler,

**Operating system**: Ubuntu 17.10 (Artful Aardvark)
**Compiler**: `g++-7` (from package `g++-7 7.2.0-8ubuntu3`)
**Standard C++ Library**: `libc++` (from package `libc++-dev:amd64 3.9.1-3`)
**Catch version**: v2.0.1

**Expected result**: The unit tests compile and pass.

**Actual result**: The compilation fails with an error message,
```
/usr/include/c++/v1/type_traits:2928:50:
error: invalid use of incomplete type ‘struct Catch_global_namespace_dummy’
   decltype(__is_constructible_test(declval<_Tp>(), declval<_Args>()...))
            ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Other combinations that fail: any other supported version of `g++` with `libc++`.

Other combinations that succeed:
- Any supported version of `g++` with `libstd++-v3`.
- Any supported version of `clang++` with `libstdc++-v3`.
- Any supported version of `clang++` with `libc++`.

### Steps to reproduce

```
# Assume packages g++-7, libc++-dev are installed

$ mkdir trompeloeil-scratch
$ git clone https://github.com/AndrewPaxie/trompeloeil trompeloeil-scratch
$ cd trompeloeil-scratch
$ git checkout c++11

$ wget https://raw.githubusercontent.com/catchorg/Catch2/v2.0.1/single_include/catch.hpp

$ g++-7 -std=c++14 -nostdinc++ \
-isystem/usr/include/c++/v1 \
-ftemplate-backtrace-limit=0 \
-Wall -Wextra -Wpedantic -Wshadow \
-I . -I ./include \
-o compiling_tests \
test/compiling_tests.cpp test/compiling_tests_11.cpp test/compiling_tests_14.cpp \
-nodefaultlibs -lc++ -lc++abi -lm -lc -lgcc_s -lgcc
```

#### Supposed cause

In `include/internal/catch_tostring.h` there is the code
```Cpp
// We need a dummy global operator<< so we can bring it into Catch namespace later
struct Catch_global_namespace_dummy;
std::ostream& operator<<(std::ostream&, Catch_global_namespace_dummy);

namespace Catch {
    // Bring in operator<< from global namespace into Catch namespace
    using ::operator<<;
```

#### Suggested fix

When `Catch_global_namespace_dummy` is changed to
```Cpp
struct Catch_global_namespace_dummy {};
```
the Trompeloeil unit test code compiles with success.

**Comment by horenmar** [comment]
Interesting.

As far as I know, there is no problem with making it complete, so I am going to fix it soonish.
