### ISSUE TITLE
Emscripten does not suport signals

### ISSUE THREAD

**Issue by Luthaf** [catchorg/Catch2#1114]
## Description

Compiling Catch2 based tests using emscripten fails with `warning: unresolved symbol: sigaltstack`, and then errors at run-time with 

```
missing function: sigaltstack
-1
-1
exception thrown: abort(-1) at Error
    [...] full backtrace
```

### Steps to reproduce

Install [emscripten](https://github.com/kripken/emscripten) and compile any catch test with `emcc test.cpp`.

A simple fix for this issue is to define `CATCH_CONFIG_NO_POSIX_SIGNALS`.

### Extra information

Here is a patch that allowed me to compile Catch and run `SelfTest` using emscripten

```
// clone catch && cd catch
mkdir build
cd build
emcmake cmake ..
make 
node SelfTest.js
```

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3792bad6..941c6a68 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -299,10 +299,19 @@ if (NOT NO_SELFTEST)
     set_property(TARGET SelfTest PROPERTY CXX_STANDARD_REQUIRED ON)
     set_property(TARGET SelfTest PROPERTY CXX_EXTENSIONS OFF)
 
+    if (EMSCRIPTEN)
+        # Enable excpetions with emscripten
+        target_compile_options(SelfTest PRIVATE -s DISABLE_EXCEPTION_CATCHING=0)
+        set_target_properties(SelfTest PROPERTIES LINK_FLAGS "-s DISABLE_EXCEPTION_CATCHING=0")
+    endif()
 
     # Add desired warnings
     if ( CMAKE_CXX_COMPILER_ID MATCHES "Clang|AppleClang|GNU" )
-        target_compile_options( SelfTest PRIVATE -Wall -Wextra -Wunreachable-code -Werror )
+        target_compile_options( SelfTest PRIVATE -Wall -Wextra -Wunreachable-code )
+        if(NOT EMSCRIPTEN)
+            # Emscripten has an unused function 'reportFatal' error
+            target_compile_options( SelfTest PRIVATE -Werror)
+        endif()
     endif()
     # Clang specific warning go here
     if ( CMAKE_CXX_COMPILER_ID MATCHES "Clang" )


diff --git a/include/internal/catch_compiler_capabilities.h b/include/internal/catch_compiler_capabilities.h
index 88180af2..dc8fc9c0 100644
--- a/include/internal/catch_compiler_capabilities.h
+++ b/include/internal/catch_compiler_capabilities.h
@@ -53,7 +53,7 @@
 
 ////////////////////////////////////////////////////////////////////////////////
 // We know some environments not to support full POSIX signals
-#if defined(__CYGWIN__) || defined(__QNX__)
+#if defined(__CYGWIN__) || defined(__QNX__) || defined(__EMSCRIPTEN__)
 
 #   if !defined(CATCH_CONFIG_POSIX_SIGNALS)
 #       define CATCH_INTERNAL_CONFIG_NO_POSIX_SIGNALS

```

The patch might still need a few tweaks to be able to run the full test suite.

**Comment by horenmar** [comment]
Sorry for taking so long.

Anyway, I couldn't get emscripten to work, so no idea if it is enough, but the changes to `catch_compiler_capabilities.h` is in.

**Comment by ynotstartups** [comment]
Thanks for the commit! 
Exact problem and the changes work for me with emcc (Emscripten gcc/clang-like replacement) 1.37.33

BTW, how can I  build catch.hpp myself from master branch?

**Comment by horenmar** [comment]
@ynotstartups  run `scripts/generateSingleHeader.py`.

**Comment by horenmar** [comment]
Since there hasn't been any followup, I am going to close this.

**Comment by hortonelectric** [comment]
Hi, can we re-open this? It feels like if I am forced to edit the source code 2 years later and support is "almost there", it should just...be there. Can somebody explain what I'm missing>?

**Comment by hortonelectric** [comment]
I put `-s DISABLE_EXCEPTION_CATCHING=0` in my build flags and it just ignores the errors, I guess this is what can be done, for now.

**Comment by horenmar** [comment]
Post what errors you are getting. POSIX signals should be disabled automatically.

**Comment by hortonelectric** [comment]
@horenmar first I put this: `-s ERROR_ON_UNDEFINED_SYMBOLS=0` and then I got `missing function: sigaltstack`.
I did have `-s DISABLE_EXCEPTION_CATCHING=0` so I put it to `1`, let's see....
