### ISSUE TITLE
Variables are shared across different SECTION's, specially in OSX

### ISSUE THREAD

**Issue by ibc** [catchorg/Catch2#1118]
## Description

Have a test.cpp file as follows:

```c++
SCENARIO("test foo")
{
  SECTION("foo 1")
  {
    uint8_t originalBuffer[] = { 0xd0, 0x80, 0x11 };

    // some REQUIRE here
  }

  SECTION("foo 2")
  {
    uint8_t originalBuffer[] = { 0x88, 0x3e, 0xe4 };

     // some REQUIRE here
  }
}
```

The test fails because, somehow, some REQUIREs in the second SECTION use the `originalBuffer` declared in the first SECTION rather than the second one.

This happens in OSX (clang) but does not happen in Linux (gcc). In the past we had similar problems when declaring the same `class` within **different* test source files.

So, how does Catch work? do `SCENARIO` and `SECTION` create code scopes? or is everything shared into a single scope?

-->
* Catch version: **v2.0.1**
* Operating System: **OSX 10.13.1 (High Sierra)**
* Compiler+version: **Apple LLVM version 9.0.0 (clang-900.0.38) Target: x86_64-apple-darwin17.2.0**

**Comment by philsquared** [comment]
They are different scopes. More specifically they are just `if` statements. Think of it like:

```c++
if( shouldIGoIntoSectionA() ) {
    // ...
}

if( shouldIGoIntoSectionB() {
    // ...
}
```

So, even if the logic that chooses which section to go into fails, there should be no way that a conforming C++ compiler should allow variables declared in the first block to leak into the second!

Regarding declaring the same class in different source files - that sounds like an ODR violation (ie One Definition Rule - so any type with the same name and scope should be the same in all translation units or else it's undefined behaviour). It's not the same thing.

Could you give a more complete example?

**Comment by ibc** [comment]
Thanks. Will re-check and provide more info on next week.

**Comment by philsquared** [comment]
Hi @ibc - did you ever follow up on this?

**Comment by ibc** [comment]
Hi @philsquared,
Not yet sorry, we have it in our TODO but we are busy with other stuff and still using Catch 1.X (since it does not fail for us). Will come back and update not so far in time (if you don't mind keeping this issue open).

**Comment by philsquared** [comment]
Sure - let me know. Thanks for getting back.

**Comment by ibc** [comment]
I no longer can reproduce this issue. However I've upgraded my Mac OSX to 10.14.1 and Catch to 2.5.0.

So let's close the issue has there is no much rationale behind it :)
