### ISSUE TITLE
Operator== overload CHECK/REQUIRE {?} == {?}

### ISSUE THREAD

**Issue by mwpowellhtx** [catchorg/Catch2#1122]
I might have asked this before, I don't recall. When I implement a user ``operator==`` overload, I see ``{?} == {?}`` in the ``Catch`` report. How can I show the correct (or user) representation?

**Comment by philsquared** [comment]
https://github.com/catchorg/Catch2/blob/master/docs/tostring.md

**Comment by mwpowellhtx** [comment]
``StringMaker``. Perfect, thank you.

**Comment by philsquared** [comment]
You're welcome :-)
