### ISSUE TITLE
std::uncaught_exception() is deprecated in C++17

### ISSUE THREAD

**Issue by GatoRat** [catchorg/Catch2#1124]
With Visual Studio 2017 v15.5 (the latest update), I now get the following warning:

catch.hpp(7196): error C4996: 'std::uncaught_exception': warning STL4006: std::uncaught_exception() is deprecated in C++17. It is superseded by std::uncaught_exceptions(), plural.

**Comment by horenmar** [comment]
Interesting, we used to suppress that in Catch Classic, wonder where that went.
