### ISSUE TITLE
In Catch v2.0.1 durations longer than 10 seconds are truncated

### ISSUE THREAD

**Issue by james-d-mitchell** [catchorg/Catch2#1125]
## Description

When running tests that last longer than 10 seconds, the duration is truncated to the last 4 digits. For example, if a `TEST_CASE` runs for 10.134s, then this is displayed as `0.134 s:` when the test executable is run with `-d yes`.

### Steps to reproduce

Run a test case lasting longer than 10 seconds.

**Comment by philsquared** [comment]
Well that's embarrassing!
Looks like timer values are being truncated to smaller int sizes too soon!
I've fixed that now (will be in next single header release)

**Comment by james-d-mitchell** [comment]
Thanks for the quick fix!

**Comment by horenmar** [comment]
2.1.0 is out with the fix.
