### ISSUE TITLE
Migrating from GoogleTest

### ISSUE THREAD

**Issue by acgetchell** [catchorg/Catch2#1126]
## Description
I'm migrating from GoogleTest.

Currently, my project is running both. I believe that I have Catch setup correctly, because the following trivial test works:

https://github.com/acgetchell/CDT-plusplus/blob/feature/Catch/tests/Vertex.cpp

However, more sophisticated tests which work in GoogleTest don't work in Catch.

### Steps to reproduce

If I uncomment Lines 22-39:

https://github.com/acgetchell/CDT-plusplus/blob/feature/Catch/tests/Vertex.cpp#L22-L39

And run my build script:

https://github.com/acgetchell/CDT-plusplus/blob/master/build.sh

I get the following mass of template compiler errors:

https://gist.github.com/acgetchell/f37ad3b17259eb4d01640e736cbb892c

Which ends with:

> > >, CGAL::Parallel_tag> > > > > > >*) in Vertex.cpp.o

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

ninja: build stopped: subcommand failed.

### Extra information
The equivalent works in GoogleTest:

https://github.com/acgetchell/CDT-plusplus/blob/master/unittests/VertexTest.cpp

* Catch version: **v42.42.42**
* Operating System: **MacOS 10.13.2**
* Compiler+version: **AppleClang 9.0.0.9000039**

**Comment by horenmar** [comment]
Are you linking in proper libraries? When I look into your cmakelists for Google tests based binary, I see this

```CMake
#Test files
  file(GLOB TEST_FILES "unittests/*.cpp")
  add_executable("${UT_EXECUTABLE_NAME}" ${TEST_FILES} ${SRC_FILES} src/date/src/tz.cpp)

#Set link libraries(order matters)
  target_link_libraries("${UT_EXECUTABLE_NAME}"
                         ${TBB_LIBRARIES} curl gmock gtest pthread)
```
OTOH when I look at where you are building the Catch tests, I see this
```CMake
add_executable(CDT_test ${TEST_SOURCE} ${CMAKE_SOURCE_DIR}/src)
```
Notice no libraries linked to the Catch test executable. This also tracks with your symptoms, where a simple test with no outside dependencies compiles fine, but one with external dependencies that need linking doesn't.

**Comment by acgetchell** [comment]
Indeed, that was the issue. I worked out what to do.

https://github.com/acgetchell/CDT-plusplus/tree/feature/Catch

Thanks again for the help.
