### ISSUE TITLE
Help include project to "who is using it"

### ISSUE THREAD

**Issue by twhuang-uiuc** [catchorg/Catch2#1128]
I have recently integrated Catch2 to our open-source project DtCraft [https://github.com/twhuang-uiuc/DtCraft]. Catch2 is really a nice work. Can you help include our DtCraft to your list of "who is using it"?

**Comment by philsquared** [comment]
Done - thanks!
https://github.com/catchorg/Catch2/blob/master/docs/opensource-users.md#dtcraft
