### ISSUE TITLE
Report time problem in multi-threads

### ISSUE THREAD

**Issue by twhuang-uiuc** [catchorg/Catch2#1129]
I ran Catch2 and found mismatch between the reported time and the real time of my program.

time -p ./reactor -d yes

0.001 s: ReactorTest.Promise
0.000 s: ReactorTest.Master
0.000 s: ReactorTest.Workers
0.201 s: ReactorTest.Notify
1.744 s: ReactorTest.TimeoutEvent
0.726 s: ReactorTest.Periodic
0.002 s: ReactorTest.EOF
0.001 s: ReactorTest.IO
===============================================================================
All tests passed (6479 assertions in 8 test cases)

real 19.86
user 2.56
sys 1.52

Apparently, the time reported by -d yes is not what I expected. Any idea?

**Comment by philsquared** [comment]
There was a bug with truncating integers in the timer code that I fixed recently. It's not in the single include yet but is likely to cause of your issue. We'll be doing a release very soon.

**Comment by philsquared** [comment]
https://github.com/catchorg/Catch2/issues/1125

**Comment by horenmar** [comment]
2.1.0 is out with the fix.
