### ISSUE TITLE
CATCH_VERSION

### ISSUE THREAD

**Issue by vpashka** [catchorg/Catch2#1131]
Hello..
How about add ?

#define CATCH_VERSION XYZ

or/and

#define CATCH_VERSION_MAJOR X
#define CATCH_VERSION_MINOR Y
#define CATCH_VERSION_RELEASE Z

**Comment by philsquared** [comment]
What do you want it for?

**Comment by vpashka** [comment]
I use the catch in my project, which should be compiled for different versions of the distribution with different versions of catch (1x and 2.x).

**Comment by vpashka** [comment]
This is not a big problem, but I think it would be convenient...

P.S. In any case, many thanks for 'catch'. It`s great project.. )

**Comment by vpashka** [comment]
Many thanks!
