### ISSUE TITLE
CLR exceptions in mixed-mode modules

### ISSUE THREAD

**Issue by davidaue** [catchorg/Catch2#1138]
## Description

In a mixed-mode (native c++ & c++/cli) module native code calls back to the CLR and a CLR exception is thrown. With the right combination of switches this will be caught by `catch(...)`. In this circumstance `std::current_exception` returns nullptr. The translators rethrow the nullptr causing a bad_exception. My fix is shown below. I believe this applies to all Windows structured exceptions but I'm a bit rusty on the details.

     std::string ExceptionTranslatorRegistry::translateActiveException() const {
        try {
    #ifdef __OBJC__
            // In Objective-C try objective-c exceptions first
            @try {
                return tryTranslators();
            }
            @catch (NSException *exception) {
                return Catch::Detail::stringify( [exception description] );
            }
    #else
            // Windows SEH exceptions caught in native code will have no current_exception
            if (std::current_exception() == nullptr)
                return "Non C++ exception";

            return tryTranslators();
    #endif
        }

* Catch version: **2.0.1**
* Operating System: **Windows 10**
* Compiler+version: **MSVC 15.5.2**

**Comment by horenmar** [comment]
That is an interesting use-case.

Can you provide the set of switches to reproduce this? I want to see what happens inside our SE handlers first.

**Comment by davidaue** [comment]
Causing any structured exception should be exactly the same and is easier to reproduce than my specific case which involves mixed-mode. This works with the just /EHa switch which allows SEH exception to be caught.

	try {
	    auto i = *((int*)nullptr); // cause exception
	}
	catch (...) {
	    auto ex = std::current_exception();  // ex will be nullptr
	}

Catch2 is doing the catch(...) and then uses the nullptr returned from current_exception() in the filtering code, causing a second exception (if I remember correctly).

**Comment by horenmar** [comment]
I got around experimenting with this and, at least for SEH, `std::current_exception() == nullptr` will evaluate to false when SEH exception was caught inside `catch (...)` block. Even the rethrow mostly works\*, but the Console reporter goes crazy afterwards.

**Comment by davidaue** [comment]
You are right. I was fooled by how the debugger displays std::exception_ptr. It's good we found another case though! I attached an example project to show CLR exceptions caught in native code, which really do evaluate == nullptr.

[CatchSEH.zip](https://github.com/catchorg/Catch2/files/1647309/CatchSEH.zip)

**Comment by horenmar** [comment]
> I was fooled by how the debugger displays std::exception_ptr.

Yep, spent some time there as well.
