### ISSUE TITLE
TEST_CASE should warn if it doesn't contain a REQUIRE or CHECK

### ISSUE THREAD

**Issue by faheel** [catchorg/Catch2#1139]
It would be very helpful if a `TEST_CASE` in Catch (v2) reported a warning in case it didn't have any kind of `REQUIRE` or `CHECK` statement in it.

**Comment by horenmar** [comment]
[It is not on by default, by try passing `-w NoAssertions` to the resulting executable.](https://github.com/catchorg/Catch2/blob/master/docs/command-line.md#warnings)

Note that it isn't quite the same thing, as this will warn on any leaf-section that does not have an assertion in it, ie this will warn:
```cpp
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

TEST_CASE("foo") {
    SECTION("bar") {
    }
    REQUIRE(true);
}
```

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warnings.bin is a Catch v2.0.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
foo
  bar
-------------------------------------------------------------------------------
warnings.cpp:5
...............................................................................


No assertions in section 'bar'

===============================================================================
test cases: 1 | 1 failed
assertions: 2 | 1 passed | 1 failed
```

**Comment by nabijaczleweli** [comment]
Also consider: a test case for just (not) throwing exceptions is a legit use case.

**Comment by faheel** [comment]
@horenmar This is exactly what I was looking for. Though can I ask why is it not on by default?

**Comment by horenmar** [comment]
@faheel It also warns on code that is perfectly OK. Consider this

```cpp
TEST_CASE("foo") {
    int a = 1;
    SECTION("bar") {
        a = 2;
    }
    int b = calculate_new(a);
    REQUIRE(b == 3);
}
```

This is a poor man's emulation of generators and a fairly legitimate use case for `SECTION`s without assertions, but it would be flagged by `-w NoAssertions`.

**Comment by faheel** [comment]
I see. Thanks for the explanation @horenmar.
