### ISSUE TITLE
Space-delimited test case names as cmd line args not recognized at all

### ISSUE THREAD

**Issue by tamboril** [catchorg/Catch2#1140]
## Description
Command-line arguments separated by spaces as described are not recognized.

### Steps to reproduce
Make three `TEST_CASE` blocks "a", "b", and "c".
Try to run them all with `test a b c` as documented.
You get "No tests ran"
Try again with `test a,b,c`, and it runs all three.
The documentation shows test cases separated by spaces and doesn't mention at all that commas work.

### Extra information
* Catch version: **v2.0.1**
* Operating System: **CentOS 7**
* Compiler+version: **gcc 7.3**

**Comment by philsquared** [comment]
By "as documented" I presume you mean here: https://github.com/catchorg/Catch2/blob/master/docs/command-line.md#specifying-which-tests-to-run
?
If so, I agree it's not very clear (that could do with a bit of rewriting and/ or augmenting), but it does say, of tags at least (with an implication it applies to names/ patterns), "A series of tags form an AND expression wheras a comma-separated sequence forms an OR expression"

So you `a b c` is an AND expression, meaning a test case must match `a` AND `b` AND `c` - which is impossible.
`a,b,c` is an OR expression, so a test case must match `a` OR `b` OR `c`, and so should therefore select all of them.

What's probably confusing matters is that example given of `a* ~ab* abc` - which looks wrong to me (or rather I would expect that to only match ABC). I'll take a look at that, but I think it's a doc error.

Does that explain it, or am I looking in the wrong place?

**Comment by tamboril** [comment]
Yes.  The operation is OK, but the doc is unclear.  If a test name is an example of a `test-spec`, then
`test-spec ...` makes me think I can put several test names separated by spaces and have them all
run.

It's a little weird for what seems to me to be the most common case (running specific tests) to have to be given as an `OR` expression.

**Comment by philsquared** [comment]
Yeah - definitely agree it's not very clear Also agree it might mot seem intuitive at first when you consider *just* that case - but considering the whole picture (allowing you apply filtering expressions, and also tags) it seemed the most consistent way at the time.
