### ISSUE TITLE
Using assertions outside of tests

### ISSUE THREAD

**Issue by ArekPiekarz** [catchorg/Catch2#1141]
## Description
Currently in my project I use BOOST_ASSERT_MSG in a few places outside of tests to check if some conditions are met.
The problem with it is I have to write by hand the message containing what values were passed in the first argument of the macro.

Catch2 solves this issue by using decomposers, so it would be incredibly convenient to replace the hand-written messages with automatically generated ones.

As an absolutely minimal example I tried to use REQUIRE macro in main().
It needs at least `#define CATCH_CONFIG_RUNNER` to compile and then it crashes in runtime because it wants to access `getCurrentContext().getResultCapture()->assertionStarting( m_assertionInfo )` in `AssertionHandler` constructor. It happens even when I run Catch session, because the check is made before that.
Note that I don't think I can run the Catch session like this, because I want to start an event loop using QApplication (Qt library).

Am I doing something wrong or is there currently no way to use these macros outside of tests?

### Steps to reproduce
```
// main.cpp
#define CATCH_CONFIG_RUNNER
#include <catch.hpp>
#include <QtWidgets/QApplication>

int main(int argc, char* argv[])
{
    REQUIRE(argc == 2);  // crashes here
    // return Catch::Session().run( argc, argv );  // can't do that?
    QApplication app{argc, argv};
    return app.exec();
}

// CMakeLists.txt
cmake_minimum_required(VERSION 3.9)
project(catch-assert-outside-of-tests)
include_directories(external/Catch2/single_include)
find_package(Qt5 REQUIRED COMPONENTS Widgets)
add_executable(${PROJECT_NAME} "main.cpp")
target_link_libraries(${PROJECT_NAME} Qt5::Widgets)
```

### Extra information
* Catch version: **f580591bf873c842df037e5e984bd263b927c7dc (Mon Dec 25 19:38:51 2017 +0100)**
* Operating System: **Windows 10 x64**
* Compiler+version: **GCC 7.2 x64**

**Comment by horenmar** [comment]
There is currently no way for Catch macros to be used outside and there are no plans to enable this use case.


However, I wouldn't be surprised if there was interest in a new library that provided Catch-like stringification for plain old assertions and our licence allows reasonably free reuse of the code.
