### ISSUE TITLE
Non-Single-Include catch.hpp does not define Catch::Session

### ISSUE THREAD

**Issue by hostilefork** [catchorg/Catch2#1142]
## Description

Ordinary include of `catch.hpp` with CATCH_CONFIG_RUNNER defined does not include `include/internal/catch_session.h`.

### Steps to reproduce

Try the code in the example [supplying your own main()](https://github.com/catchorg/Catch2/blob/master/docs/own-main.md#top).  Receive error that Session is not a member of namespace Catch.

### Extra information

Adding a conditional include in catch.hpp makes the example work, e.g.

     #ifdef CATCH_CONFIG_RUNNER
     #include "internal/catch_session.h"
     #endif

The single include variant seems to define Session.

* Catch version: **[c3a1143d23b9b868543fcfad7baab273aedddaab](https://github.com/catchorg/Catch2/commit/c3a1143d23b9b868543fcfad7baab273aedddaab)**
* Operating System: **Kubuntu 17.10**
* Compiler+version: **gcc (Ubuntu 7.2.0-8ubuntu3) 7.2.0**

**Comment by martinmoene** [comment]
With the non-single include, define ` CATCH_CONFIG_EXTERNAL_INTERFACES`, see [docs](https://github.com/catchorg/Catch2/blob/master/docs/configuration.md#reporter--listener-interfaces).

**Comment by hostilefork** [comment]
Cool...actually I'm okay using a single include, now that I've found out about it (!)  But even the existence of the single include should probably be added to the [breaking changes](https://github.com/catchorg/Catch2/releases/tag/v2.0.1), if it's a new thing (is it?)

(Really, I'm not familiar with Catch's installation process, because I'm trying to get something working with the upgrade that someone else set up.  So the first thing I got was just Catch::Session not defined, and I followed through to the include/catch.hpp to look for an inclusion of catch_session.h, and didn't find it...)

Maybe a line in the breaking changes there could be an "if you get Catch::Session not defined, here's what to do"...where that's either switch to a single include, or something else?  Because the code I was looking at looked more or less just like the example, and it worked before.

**Comment by horenmar** [comment]
> Cool...actually I'm okay using a single include, now that I've found out about it (!) But even the existence of the single include should probably be added to the breaking changes, if it's a new thing (is it?)

No. Single include has been around since basically the first release.

**Comment by philsquared** [comment]
It was very early on, yes (long before 1.0) - but it's more recent that the emphasis has shifted to the single include being the primary, supported, way of working.

**Comment by hostilefork** [comment]
Well, if it helps diagnose anything, this was the way Catch was being pulled down via CMake in the project:

https://github.com/metaeducation/ren-cpp/blob/ce80c6deffb1052d3b83b3c4d16da382d94aa6e5/external/catch/CMakeLists.txt#L22

I changed it to Catch2, then got the error.  But rather than use my patch (which then came up with link errors, anyway) I changed:

    ${SOURCE_DIR}/include CACHE INTERNAL

...to

    ${SOURCE_DIR}/single_include CACHE INTERNAL

Now all seems to be well again.

**Comment by philsquared** [comment]
Should be good.
Note that one of the big advantages of the single include is you can just commit it directly in with your own sources - rather than have the external dependencies (although either way is fine).

Also I see that your main test file (main.cpp) is supplying a custom main that doesn't do anything different from the one that Catch itself provides (although from the comment it looks like that might have been because some time ago Catch was using `char* const` in its declaration of `main` - that has now been fixed). So you might want to replace that whole file with just:

```c++
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
```

... but, again, it will work just as well either way - just less boilerplate code to worry about :-)

**Comment by hostilefork** [comment]
Ok, thanks!  Well I'll close this since things are back working again...but like I say, it might be good to put some note (maybe a link to this issue?) in the breaking changes for anyone else who upgrades to get a "no Catch::Session" error popping up...

I'll also mention in passing that there's mixed tabs and spaces in the single include, as it's one of those things that are against my religion.  :-)

**Comment by davidaue** [comment]
I'm having this same issue with version 2.13.9. Your previous solution of using CATCH_CONFIG_EXTERNAL_INTERFACES no longer works. From looking at the source it seems the only way to get internal/catch_session.h is to use CATCH_CONFIG_MAIN.
