### ISSUE TITLE
gsl::byte is printed as {?} (question mark)

### ISSUE THREAD

**Issue by djleach-belcan** [catchorg/Catch2#1144]
## Description
My code makes use of the [C++ Guidelines Support Library](https://github.com/Microsoft/GSL); specifically gsl::byte. There's not much special about this type but I'm unable to see it printed in Catch2 CHECK statements when using the appropriate string conversion mechanisms. It prints as "{?}".

### Steps to reproduce

1. Overload the stream operator for gsl::byte:
```
namespace gsl
{
inline std::ostream& operator << ( std::ostream& os, byte const& value ) {
	os << fmt::format("{:#x}", gsl::to_integer<int>(value));
	return os;
}
}
```
2. And/or specialize `Catch::StringMaker`:
````
namespace Catch
{
template<>
struct StringMaker<gsl::byte>
{
	static std::string convert(gsl::byte const& value)
	{
		return fmt::format("{:#x}", gsl::to_integer<int>(value));
	}
};
}
````
3. Print using INFO:
````
INFO(gsl::to_byte<0x42>());
````
Prints "with messages:
  0x42"
4. Print using CHECK:
````
CHECK(gsl::to_byte<0x00>() == gsl::to_byte<0x42>());
````
Prints "with expansion:
  {?} == {?}"

### Extra information
So INFO works as expected but CHECK does not. See also: https://github.com/catchorg/Catch2/issues/531

**Comment by horenmar** [comment]
Is this with v2.0.1 or v2.1.0?

**Comment by djleach-belcan** [comment]
This is with 2.0.1.

**Comment by horenmar** [comment]
What is your build env? I tried to reproduce the issue using VS 15.5.3 and the 2.0.1 version of single include header and I ran into something different:

```cpp
// testfile
#include <gsl/gsl_byte>
#include "catch.hpp"

namespace Catch {
template<>
struct StringMaker<gsl::byte> {
    static std::string convert(gsl::byte const&) {
        return "stringmaker byte!";
    }
};
}

TEST_CASE("Foo") {
    gsl::byte b{ 0x20 };
    REQUIRE(b != b);
}
```

with
```
 REQUIRE( b != b )
with expansion:
  stringmaker byte! != stringmaker byte
```
as the output.


Interestingly, with 2.1.0 the `gsl::byte` is stringified as a char, because it is implemented as an enum and 2.1.0 stringifies enums according to the underlying type and value.

For 2.0.1 `INFO` doesn't compile even when providing a `operator<<` overload:
```cpp
#include <gsl/gsl_byte>
#include <iostream>

namespace gsl {
std::ostream& operator<<(std::ostream& out, gsl::byte const&) {
    out << "operator<< byte!";
    return out;
}
}

#include "catch.hpp"

TEST_CASE("Foo") {
    gsl::byte b{ 0x20 };
    //INFO(b);  //<-- compilation error if uncommented
    REQUIRE(b != b);
}
```

**Comment by Bu11etmagnet** [comment]
The last sentence sounds like a problem with `gsl`.

**Comment by horenmar** [comment]
It is a problem with ADL and aliases in general, but yeah. The proper fix is to use `StringMaker` specialization which will be found either way (does not matter if it is provided using the alias or not).
