### ISSUE TITLE
Migrating from Catch v1 to v2

### ISSUE THREAD

**Issue by mwpowellhtx** [catchorg/Catch2#1156]
Hello,

So, I am migrating from Catch v1 to v2 today. I didn't expect it to go entirely without a hitch, but there are a couple of issues I am discovering with a simple replacement:

* *CATCH_OVERRIDE* was defined under v1, but is now apparently missing, or the name changed. I could simply use the **override** keyword, I suppose, but I wonder if there is a CATCH-based migration there.

At the moment that appears to be the only issue.

**Comment by philsquared** [comment]
Hi,
`CATCH_OVERRIDE` was a transitional helper macro that allowed Catch to compile with pre C++11 compilers, while giving the greater protection of `override` where supported.
Now Catch2 assumes C++11 there was no need to the macro.
It was only ever intended for internal use (so should, really, have been named `CATCH_INTERNAL_OVERRIDE` - my bad). If you've been using it yourself you should either: replace with `override` if all your code is C++11 on - or if you also need to support older compilers replace with your own macro (feel free to borrow the logic from Catch1.x).

**Comment by mwpowellhtx** [comment]
Great! I like the idea of dropping otherwise superfluous (C++11 and better) definitions. Thank you.

Also, using my ``Catch::Tags(...)``, which returns ``std::string``, no longer necessary to convert to ``std::string::c_str()``. The conversion will work seamlessly, but is unnecessary since *v2* supports *std::string*.

**Comment by philsquared** [comment]
oh yeah - I think we had that conversation elsewhere :-)
Glad it's working out well for you.
Ok to close this?

**Comment by mwpowellhtx** [comment]
Cheers! :+1:

**Comment by mwpowellhtx** [comment]
May have spoken too soon. I'll just append here as necessary.

* I was using ``Catch::Matchers::Not(...)``, in particular *Not(Contains(...))*. I could hazard a guess that *!Contains(...)* would work?

**Comment by horenmar** [comment]
From release notes:
> * Removed deprecated matcher utility functions Not, AllOf and AnyOf.
>   * They are superseded by operators !, && and ||,

That is a yes.
