### ISSUE TITLE
Change directory layout to make Catch trivially bundleable

### ISSUE THREAD

**Issue by SoapGentoo** [catchorg/Catch2#1164]
Hi @horenmar and @philsquared 
would it be possible to change the `single_include/` structure to make bundling and unbundling of others packages a lot easier for distributions? The reason is the following:

In general, given how your pkg-config file points to `/usr/include` as includedir, the expectation is that users use Catch by doing `#include <catch/catch.hpp>`. If people wish to bundle Catch, they will pull it in as a submodule, and will often do things like `#include "single_include/catch.hpp"`. This makes unbundling Catch from these libraries for distributions a massive pain and requires us to hack buildsystems constantly. Here is my suggestion:

1. rename `single_include/` -> `catch/`
2. `ln -s catch single_include`

With 1. you can just change include paths between a system pkg-config found Catch2 (because the catch prefix is the same now), and 2. keeps compatibility for users of current semantics.

Would you be willing to accept a PR for this?

**Comment by djrollins** [comment]
I hit a similar problem when creating a 'linkable' CMake target in my PR (#1170), so I'd appreciate this change as well.

**Comment by esemeniuc** [comment]
same here :+1:

**Comment by horenmar** [comment]
This should be solved since IIRC 2.3.0
