### ISSUE TITLE
CMake Automatic test registration does not skip tests with [!hide] tag

### ISSUE THREAD

**Issue by gegles** [catchorg/Catch2#1166]
## Description

When using one of the tags to skip a test ([.] or [!hide]), the CMake Automatic test registration still enables this test to run in ctest.

### Steps to reproduce

Create any test with a "[!hide]" tag.

Run it directly, catch does not run this test.

Run using ctest ... the test still runs.

### Extra information

* Catch version: **v2.1.0**
* Operating System: **Any (CentOS Linux)**

**Comment by horenmar** [comment]
Which one of the two registration scripts?

Neither of them should, but `ParseAndAddCatchTests.cmake` needs to have `PARSE_CATCH_TESTS_NO_HIDDEN_TESTS` set to exclude hidden tests.

**Comment by gegles** [comment]
Yep, that did it! Thx. Sorry I missed that (I think I was on an old revision...)
