### ISSUE TITLE
Approx does not work as expected when value is zero

### ISSUE THREAD

**Issue by allanleal** [catchorg/Catch2#1174]
## Description

When comparing zero with a very small number (i.e., epsilon) using `Approx`, the comparison results in false.

Both assertions below will fail.

~~~
#include <catch/catch.hpp>

TEST_CASE("0 == Approx(0) fails")
{
    const auto epsilon = std::numeric_limits<double>::epsilon();
    REQUIRE(epsilon == Approx(0.0));
    REQUIRE(Approx(epsilon) == 0.0);
}
~~~

By changing how `m_scale` is initialized in `Approx` as follows:

~~~
    Approx::Approx ( double value )
    :   m_epsilon( std::numeric_limits<float>::epsilon()*100 ),
        m_margin( 0.0 ),
        m_scale( std::fabs(value) < m_epsilon ? 1.0 : 0.0 ),
        m_value( value )
    {}
~~~

the previous assertions now pass.

### Extra information

* Catch version: **v2.1.1**

**Comment by horenmar** [comment]
This is actually working mostly as expected, but float comparisons are hard. `std::numeric_limits<double>::epsilon()` is about 4e18 values apart from 0, so it should not match by default.

The reason why it matches with the proposed solution is that the resulting interval of matched numbers 
contains about 9e18 doubles.

**Comment by sfinkens** [comment]
What about a combination of both relative and absolute tolerance like in [numpy.isclose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.isclose.html)?

**Comment by horenmar** [comment]
@sfinkens That would be Approx::margin.

Anyway, since there hasn't been any followup on the original issue, I am going to close this.

**Comment by adaptiverisk** [comment]
I just updated from version 1 of Catch and now tons of my tests fail because of this issue. Previously 
`REQUIRE(epsilon == Approx(0.0))` would pass, but now it doesn't.
