### ISSUE TITLE
list tests shows hidden

### ISSUE THREAD

**Issue by dvirtz** [catchorg/Catch2#1175]
## Description

Currently --list-tests and --list-test-names-only options list hidden tests as well. I think that the default behavior should be to list the tests that will run when you give the same test spec. 
This is specifically problematic when using the catch_discover_tests CMake command as it uses --list-test-names-only to discover which tests to run and so runs hidden tests as well.

### Steps to reproduce

see above

### Extra information

* Catch version: **v2.0.1**
* Operating System: **Windows 10**
* Compiler+version: **VS 15.6.0**

**Comment by horenmar** [comment]
This makes sense I guess
