### ISSUE TITLE
catch2 is_range pass-by-value breaks MSVC for aligned-types larger than 8bytes

### ISSUE THREAD

**Issue by bdb** [catchorg/Catch2#1183]
This is a weird one, luckily it's all open source:

https://github.com/ProsoftEngineering/core/tree/catch2

https://ci.appveyor.com/project/bdb/core/build/1.0.152

` C:\projects\core\prosoft\core\tests\catch.hpp(1053): error C2718: 'prosoft::filesystem::v1::directory_entry': actual parameter with requested alignment of 8 won't be aligned (compiling source file C:\projects\core\prosoft\core\tests\src\filesystem_tests.cpp) [C:\projects\core\prosoft\core\tests\build_MSVC_VisualStudio14_Debug\coretests.vcxproj]
  C:\projects\core\prosoft\core\tests\catch.hpp(1054): error C2718: 'prosoft::filesystem::v1::directory_entry': actual parameter with requested alignment of 8 won't be aligned (compiling source file C:\projects\core\prosoft\core\tests\src\filesystem_tests.`

https://github.com/ProsoftEngineering/core/blob/catch2/prosoft/core/modules/filesystem/filesystem_iterator.hpp

I'm not sure what the exact issue is, but it looks to be due to the is_range SFINAE test using pass-by-value for all types, including structs and classes that may be quite large. This for some reason breaks MSVC as above. The only relevant info I could find was this:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/8fac034b-6ba4-478d-9130-8f6a56de368f/why-does-msvc-inhibit-the-use-of-aligned-types-as-function-parameters?forum=vclanguage

Note, the class in question is not explicitly aligned. But it does have std::atomic<> members which do use alignment.

This all worked with catch 1.x

Edit: Xcode 7, 8, and 9 and GCC 4.8, 4.9, 5 and 6 all build/pass without issue.

* Catch version: 2.1.2
* Operating System: Windows Server 2012 (AppVeyor)
* Compiler+version: VS 2015 and 2017

**Comment by horenmar** [comment]
`is_range` is a new addition in v2.1.0.

Also, this seems to be a VS 2015 bug, as far as I can tell 2017 properly keeps the context unevaluated -- both the AppVeyor logs and my local installation show 2017 passing compilation properly.

(Btw, you might want to split up your builds, ATM you build with both 2015 and 2017 at both AppVeyor images)

**Comment by horenmar** [comment]
I got 2015 working locally and here is a workaround:

```diff
--- a/prosoft/core/tests/src/filesystem_iterator_tests.cpp
+++ b/prosoft/core/tests/src/filesystem_iterator_tests.cpp
@@ -27,6 +27,13 @@
 
 #include "catch.hpp"
 
+namespace Catch {
+template <>
+struct is_range<prosoft::filesystem::v1::directory_entry> {
+    static const bool value = false;
+};
+}
+
 using namespace prosoft;
 using namespace prosoft::filesystem;

                     e = *i++;
                     CHECK(i == end(i));
                 }
-                
+
                 AND_WHEN("include apple double and skip hidden are enabled") {
                     constexpr auto opts = recursive_directory_iterator::default_options()|directory_options::include_apple_double_files|directory_options::skip_hidden_descendants;
                     recursive_directory_iterator i{root, opts};
--- a/prosoft/core/tests/src/filesystem_tests.cpp
+++ b/prosoft/core/tests/src/filesystem_tests.cpp
@@ -35,6 +35,14 @@
 
 #include "catch.hpp"
 
+
+namespace Catch {
+template <>
+struct is_range<prosoft::filesystem::v1::directory_entry> {
+    static const bool value = false;
+};
+}
+
 using namespace prosoft;
 using namespace prosoft::filesystem;
   
```

Basically the idea is to explicitly specialize `Catch::is_range`, so that the MSVC 2015 `declval` bug isn't invoked.

**Comment by bdb** [comment]
I kind of thought that might be the fix. Thanks. And thanks for the AppVeyor image tip. I did not know the 2017 image included 2015 as well. Should be able to close this now.
