### ISSUE TITLE
Don't run hidden tests if they only match exclusions

### ISSUE THREAD

**Issue by jalfd** [catchorg/Catch2#1184]
## Description
We have a handful of tags we use mainly for excluding tests (tests that shouldn't run on certain platforms, or tests which require some external component like a database or access to a GPU, for example), which means we often run our test executables with one or more tags excluded, and the `[.]` tag does not play well with this.

If I exclude tests that shouldn't run on Windows, all hidden tests suddenly spring to life, meaning that just by excluding a tag, I actually add *more* tests to be run, which is counter-intuitive, and makes the `[.]` tag useless in many cases.

As an example, say you have the following tests:

```
TEST_CASE("A", "[.][foo]");
TEST_CASE("B", "[.][bar]");

```
- Running the test executable with no arguments will run zero tests.
- Running it with `[foo]` will run test A
- Running it with `~[foo]` will run test B (even though it was hidden, and all we're doing is excluding tests to stop them being run)
- Running with `~[baz]` causes both tests to be run (as above, all we did was exclude a tag, and suddenly we're running more tests than we got when we excluded nothing)

To fix this, I'd like to propose one of two things:

- strengthen the semantics of `[.]` so that a hidden test is now only run if one of its tags are positively included (so if a test is tagged `[.foo],`  then `~[bar]` will no longer match it.
- alternatively, add a new "strong hide" instruction tag (perhaps `[:]`), with the above semantics, but without changing the behavior of `[.]`

The first solution is obviously the simpler one (and I feel, makes `[.]` behave in a much more intuitive manner), but it is a change in behavior, so perhaps the second option would be preferable?

Thoughts?

I'd be happy to submit a pull request, but I'm not sure which solution (if any) you'd prefer.

**Comment by horenmar** [comment]
I am going to have to think about this -- changing existing semantics in non-backward compatible way is always likely to break people, but introducing new tag feel weird.

**Comment by philsquared** [comment]
FTR you *can* get the behaviour you want now. You just need to exclude the hidden tests explicitly:

`~[.]~[baz]`

I agree it's not as nice or convenient. I also agree that, usually, when you use an exclusion like `~[baz]` you still don't want the hidden tests. Only adding hidden tests in when they match a positively filtered spec sounds like a reasonable approach - but what about when you mix negative and positive filters together? Not saying that it can't be specified in a reasonable way - just that it needs some thought.

I suspect that changing the behaviour is the way to go - but that would have to be on the next major version. I doubt it would break many, if anyone, but we do want to follow semver more strictly.

Would the approach I mentioned at the start keep you going until then?

**Comment by jalfd** [comment]
> Would the approach I mentioned at the start keep you going until then?

Yes, we can do that for now.

> what about when you mix negative and positive filters together? Not saying that it can't be specified in a reasonable way - just that it needs some thought.

The behavior I would intuitively expect would basically be that if the filter contains at least one positive pattern, then the hide flag is ignored (since the filter will only match if the positive pattern part of it also matches, and so we can bring the test out of hiding). In other words:

- `[x]~[y]`: include tests if they have `[x]` and do not have `[y]`, regardless of whether they're hidden (because they're pulled in by the inclusion of the `[x]` tag)
- `[x],~[y]`: include tests if they have the `[x]` tag, regardless of whether they're hidden. Also include tests that do not have `[y]`, but only if they are not hidden.

That could be implemented just by making exclusion patterns only ever match if the test case is not hidden, like so:

```
diff --git a/include/internal/catch_test_spec.cpp b/include/internal/catch_test_spec.cpp
index d9c149d5..afa61693 100644
--- a/include/internal/catch_test_spec.cpp
+++ b/include/internal/catch_test_spec.cpp
@@ -35,7 +35,9 @@ namespace Catch {
     }
 
     TestSpec::ExcludedPattern::ExcludedPattern( PatternPtr const& underlyingPattern ) : m_underlyingPattern( underlyingPattern ) {}
-    bool TestSpec::ExcludedPattern::matches( TestCaseInfo const& testCase ) const { return !m_underlyingPattern->matches( testCase ); }
+    bool TestSpec::ExcludedPattern::matches( TestCaseInfo const& testCase ) const {
+        return !(testCase.isHidden() || m_underlyingPattern->matches( testCase ));
+    }
 
     bool TestSpec::Filter::matches( TestCaseInfo const& testCase ) const {
         // All patterns in a filter must match for the filter to be a match
```

But I agree that changing this outside of a major version upgrade would probably be a bad idea.
