### ISSUE TITLE
INFO logs get cleared on new nested SECTION

### ISSUE THREAD

**Issue by rcdailey** [catchorg/Catch2#1188]
Is it expected behavior that when I have this:

```cpp
TEST_CASE("foo")
{
    INFO("test1");

    SECTION("bar")
    {
        INFO("test2");
        CHECK(false);
    }
}
```

that the log "test1" does not show up when the nested SECTION assertion fails?

**Comment by horenmar** [comment]
That shouldn't happen.

**Comment by rcdailey** [comment]
Ok I'm going to make you a MCVE

**Comment by rcdailey** [comment]
Got an MCVE, ran to test, wasn't able to reproduce. I realized it was some bad logic in a custom reporter I had implemented. Closing as there is no real issue.

**Comment by philsquared** [comment]
Thanks for getting back
