### ISSUE TITLE
GCC 4.8.0 on AIX: catch.hpp:3404:51: error: requested alignment is not an integer constant

### ISSUE THREAD

**Issue by rusq** [catchorg/Catch2#1191]
## Description
Error when trying to compile the test with GCC 4.8.0 on AIX machine:
```
g++ -std=c++11 -I.. -I../../catch2 -I../../Utils -I/usr/local/zlib/include  -pthread -g3 -O0 -pthread   simple_test.cpp  /usr/local/zlib/lib/libz.a /opt/freeware/lib/pthread/libstdc++.a /opt/freeware/lib/libatomic.a -o simple_test
In file included from simple_test.cpp:3:0:
../../catch2/catch.hpp:3404:51: error: requested alignment is not an integer constant
         alignas(alignof(T)) char storage[sizeof(T)];
                                                   ^
gmake: *** [simple_test] Error 1
```

### Steps to reproduce
1. Compile test file:
```
g++ -std=c++11 -I.. -I../../catch2 -I../../Utils -I/usr/local/zlib/include  -pthread -g3 -O0 -pthread   simple_test.cpp  /usr/local/zlib/lib/libz.a /opt/freeware/lib/pthread/libstdc++.a /opt/freeware/lib/libatomic.a -o simple_test
```

##### simple_test.cpp
```cpp
#define CATCH_CONFIG_MAIN

#include "catch.hpp"

TEST_CASE("simple","simple") {
        REQUIRE(1==1);
}
```

### Extra information

* Catch version: **v2.1.2**
* Operating System: **AIX 5.3**
* Compiler+version: **gcc version 4.8.0 (GCC)**
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/home/oracle/freeware/bin/../libexec/gcc/powerpc-ibm-aix5.3.0.0/4.8.0/lto-wrapper
Target: powerpc-ibm-aix5.3.0.0
Configured with: ../gcc-4.8.0/configure --with-as=/usr/bin/as --with-ld=/usr/bin/ld --enable-languages=c,c++,fortran --prefix=/opt/freeware --mandir=/opt/freeware/man --infodir=/opt/freeware/info --enable-version-specific-runtime-libs --disable-nls --enable-decimal-float=dpd --host=powerpc-ibm-aix5.3.0.0
Thread model: aix
gcc version 4.8.0 (GCC) 
```

I was unable to locate the minimum supported gcc version in the docs, apologies, if I missed it.

**Comment by horenmar** [comment]
GCC 4.8 is supported, but not neccessarily 4.8.0. Are newer point updates available to you?

What you are seeing is a compiler bug, where for some ungodly reason `alignof(T)` does not evaluate as compilation constant. You could probably monkey-patch around the problem by replacing it with `8` and hope nothing breaks (if it does, provide larger alignment values until it stops :-) ).

Btw, what broke with VS 2017?

**Comment by rusq** [comment]
Hi @horenmar, thanks for your reply.

Unfortunately it is not possible for me to update the GCC on that AIX machine.

To workaround these to misfortunes I resorted the following construct:
```cpp
#ifdef _AIX
#include "catch1x.hpp"
#else
#include "catch.hpp"
#endif
```

Re windows - it is possible that I messed up command line parameters, but this does work with Catch2 2.1.2, but with Catch2 1.12 it generates the list of errors which can be observed below.

The Windows compiler is this:
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.12.25831 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

I use batch file to compile:
```
set ZLIB=C:\zlib
set INCLUDE=%ZLIB%\include;..;..\..\Utils;..\..\catch2;%INCLUDE%
set LIB=%LIB%;%ZLIB%\lib
cl Logger_catch2_test.cpp /EHsc /Zi /DEBUG /link /MACHINE:X64
```

Please see the output attached.

**Comment by horenmar** [comment]
Are you including `windows.h`? Alternatively, I think the MFC headers do this as well -- the problem is that if you include them without special define (`NOMINMAX`), they define a `min` and `max` macro. As you would imagine, this can break everything quickly.

Try [changing these lines](https://github.com/catchorg/Catch2/blob/b97e9a2f8b3547ff0434aa97103c68faede6edbe/single_include/catch.hpp#L7295) so that all mentions of `min` and `max` are wrapped in extra parentheses, like so
```cpp
        static constexpr result_type (min)() { return 0; }
        static constexpr result_type (max)() { return 1000000; }
        result_type operator()() const { return std::rand() % (max)(); }
```
