### ISSUE TITLE
Problem compiling in Windows

### ISSUE THREAD

**Issue by jjangulo** [catchorg/Catch2#1197]
## Description
Hello guys. I am trying to compile the most basic of tests using Catch2 in Windows (VS 2015) and I'm having some compiling problems. 

I have only one source file:

```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
```

When I try to compile it I get:

- Error C2039 'OutputDebugStringA': is not a member of '`global namespace''
- Error C2065 'CP_UTF8' : undeclared identifier
- Error C3861 'WideCharToMultiByte': identifier not found

If I try to include Windows.h, then I get clashes with the min/max functions defined in catch.hpp. Has anyone else ran into this? Any advice on how to solve it?

Thanks very much!

### Extras:
Catch version: v2.0.0-develop.4

**Comment by jjangulo** [comment]
Sorry guys, scratch this. I just realised I can use the NOMINMAX macro to signal the window.h header not to define those. Including the header and the macro seems to work

**Comment by horenmar** [comment]
That... shouldn't happen.

Judging by what errors out, are you building a UNICODE binary? I took a look and it seems that we have a regression in how we stitch-in `windows.h`, so that could cause it.

**Comment by JoeyGrajciar** [comment]
Can be closed?

**Comment by horenmar** [comment]
@JoeyGrajciar Since there has been no followup in 8+ months, yeah.
