### ISSUE TITLE
Cannot compile Catch v2.1.2 with clang 6.0

### ISSUE THREAD

**Issue by mgr-inz-rafal** [catchorg/Catch2#1201]
## Description
While compiling my program that uses Catch v2.1.2 (single header) with clang 6.0 I get the following error:

```
/home/***/tests/src/../../external/catch/catch.hpp:10715:16: error: no member named 'uncaught_exceptions'
      in namespace 'std'; did you mean simply 'uncaught_exceptions'?
        return std::uncaught_exceptions() > 0;
               ^~~~~
/home/***/tests/src/../../external/catch/catch.hpp:10713:10: note: 'uncaught_exceptions' declared here
    bool uncaught_exceptions() {
         ^
1 error generated.
```

Code compiles fine on Visual Studio 2017 and g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609.

The exact version of clang:
```
clang version 6.0.0-svn325932-1~exp1 (branches/release_60)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

### Extra information
* Catch version: **v2.1.2**
* Operating System: "Linux Mint 18.3 Sylvia"
* Compiler+version: as mentioned above

**Comment by horenmar** [comment]
What version of stdlib is your Clang installation using? It seems that you have C++17 enabled, but `std::uncaught_exceptions` is not provided by the stdlib.

**Comment by mgr-inz-rafal** [comment]
Yes, that's a very good point. I didn't use LLVM's libc++ for compilation.

I close this issue even though I cannot fully verify it right now, since I have huge mess with compiler/libraries on my development machine after saturday night and actually nothing works correctly right now :)

**Comment by horenmar** [comment]
You can also force use of `std::uncaught_exception` instead, by defining `CATCH_INTERNAL_CONFIG_NO_CPP17_UNCAUGHT_EXCEPTIONS`. However note that next release will change this to `CATCH_CONFIG_NO_CPP17_UNCAUGHT_EXCEPTIONS`, to keep it inline with the other configuration macros.
