### ISSUE TITLE
Too slow link in MinGW-w64

### ISSUE THREAD

**Issue by xylosper** [catchorg/Catch2#1205]
## Description

I'm suffer from too slow link in MinGW-w64 environment.

### Steps to reproduce
I used very simple main.cpp:

```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
```

And, here's the result:

![image](https://user-images.githubusercontent.com/4363181/36866702-63de46c6-1dd6-11e8-9bcf-72ddf68a12c6.png)

Well, it takes about 8 seconds to compile the file here, which is totally acceptable considering big header file.

The problem is that it takes another approximately 9 seconds again to create executable with already compiled object file.
As you can see, the link time is even longer than compile time.
This is very annoying because I have to wait 9 seconds at least whenever building executable even though the object file is not changed.
In fact, my actual test project requires me to wait about 1 minute to be linked.

How can I improve link performance, here?
Any suggestion would be nice.

Thank you.

### Extra information
* Catch version: **v2.1.2**
* Operating System: **Widows 10, MinGW-w64, 64bit**
* Compiler+version: **GCC 7.3.0**

**Comment by alexander-titov** [comment]
Hi,

I have similar problem. I am using Catch under Clion on Windows.

For a simple project (50 lines, 1 test) linking time w/ Catch is about 2 minutes!
W/o Catch everything is linked for less than a second.

Such a huge linking time makes Catch useless.

Regards,
Alexander

**Comment by horenmar** [comment]
We have had some issue with link times before, but that was caused by LTO builds.

For non-lto builds, there is not much we can do except concluding that MinGW link times are awful.

**Comment by xylosper** [comment]
OK. Thanks a lot.

**Comment by iphorde** [comment]
mingw-w64 in version 7.2 and 7.3 LTO is completely broken.  Also, the link times are horrible without LTO, to the point of it not being usable. I have to wait 4 minutes for it to link, compared to under MSVC++ the same projects links in less than 20 seconds.

**Comment by snahmad** [comment]
Any resolution on this issue?

**Comment by iphorde** [comment]
Not that I am aware of. Hopefully soon, as we're about to move back to Visual Studio.

**Comment by maobaoqi** [comment]
I have same problem on MSYS2.

**Comment by maobaoqi** [comment]
> The only reasonable for me to use mingw and catch2 is to create a shared library and compile the whole subtree from here https://github.com/catchorg/Catch2/tree/master/include (not a single header file because it's awfully slow). Tests compile and run within milisecond

@nano-bot Hi, How to compile catch2 shared library?

**Comment by shreyasbharath** [comment]
@nano-bot How'd you go about compiling your shared library?

On a side-note, can we push that shared library to `Conan`? It'll make consumption a whole lot easier rather than having to build it ourselves.

**Comment by dlshcbmuipmam** [comment]
I am a random guy who was searching for a solution to improve the horrible link time in Mingw. I successfully improve it vastly by using the lld linker `-fuse-ld=lld` in my own project. I know nothing about this project so it may or may not work.

**Comment by ylliu** [comment]
where to  set 

> -fuse-ld=lld

?

**Comment by dortamiguel** [comment]
@Adriankhl where do you set the `-fuse-ld=lld` ?

**Comment by Adriankhl** [comment]
@ellipticaldoor It is a compiler flag for `gcc`: https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html
Therefore, it depends on how your project is built. For plane `gcc`, here is an example (https://stackoverflow.com/questions/29361801/is-the-lld-linker-a-drop-in-replacement-for-ld-and-gold). Mostly likely, you are working with a build system like `cmake`, then you have to figure it out how to specify the flag for the system.
