### ISSUE TITLE
[Feature] Single header download for Catch1.x Branch

### ISSUE THREAD

**Issue by andriscewo** [catchorg/Catch2#1213]
I hope I didn't just overlook the download, but I could only find the v.2.2 version. It would be nice to have a download for the Catch1.x branch. If it should already exist, maybe consider placing the link at a more prominent place.

**Comment by horenmar** [comment]
If you switch to the Catch1.x branch, the link in readme will go to the latest version from there.

**Comment by andriscewo** [comment]
I feel stupid now. I switched to the branch but looked in the tutorial. Sorry for the inconvenience and thanks for the answer.
