### ISSUE TITLE
Clang 5.0 with C++17 build fails with CLARA_CONFIG_OPTIONAL_TYPE

### ISSUE THREAD

**Issue by chronoxor** [catchorg/Catch2#1214]
-- The C compiler identification is Clang 5.0.0
-- The CXX compiler identification is Clang 5.0.1
-- Check for working C compiler: /usr/local/clang-5.0.0/bin/clang-5.0
-- Check for working C compiler: /usr/local/clang-5.0.0/bin/clang-5.0 -- works
-- Check for working CXX compiler: /usr/bin/clang++-5.0
-- Check for working CXX compiler: /usr/bin/clang++-5.0 -- works

/home/travis/build/chronoxor/CppBenchmark/modules/Catch2/single_include/catch.hpp:5787:62: error: no template named 'optional' in namespace 'std'
inline auto convertInto( std::string const &source, std::optional& target ) -> ParserResult {

Perhaps forget to #include \<optional\>

**Comment by horenmar** [comment]
Yeah, Clara does not include `<optional>` when enabling support and the bug got hidden because libstdc++ includes it transitively in `<map>`, `<set>` and others.

Already fixed it in Clara, going to update the version in Catch2 and make a patch release either late Sunday or Monday.

**Comment by chronoxor** [comment]
Build still fails. I also tried with clang 6.0 result is the same:

-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/clang-6.0
-- Check for working C compiler: /usr/bin/clang-6.0 -- works
-- Check for working CXX compiler: /usr/bin/clang++-6.0
-- Check for working CXX compiler: /usr/bin/clang++-6.0 -- works

/home/travis/build/chronoxor/CppServer/modules/Catch2/single_include/catch.hpp:5787:62: error: no template named 'optional' in namespace 'std'
    inline auto convertInto( std::string const &source, std::optional<T>& target ) -> ParserResult {
                                                        ~~~~~^

**Comment by chronoxor** [comment]
Travis config to reproduce the issue:

sudo: required
dist: trusty

sources:
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty-6.0

packages:
  - clang-6.0
  - libc++-dev
  - libc++abi-dev

# Scripts that run before install
before_install:
  - export CC="clang-${CLANG_VERSION}" CXX="clang++-${CLANG_VERSION}"
  - pushd .
  - git clone --depth=1 https://github.com/llvm-mirror/llvm.git llvm-source
  - git clone --depth=1 https://github.com/llvm-mirror/libcxx.git llvm-source/projects/libcxx
  - git clone --depth=1 https://github.com/llvm-mirror/libcxxabi.git llvm-source/projects/libcxxabi
  - mkdir llvm-build && cd llvm-build
  - cmake -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_INSTALL_PREFIX=/usr ../llvm-source
  - make cxx -j2
  - sudo make install-cxxabi install-cxx
  - popd

**Comment by horenmar** [comment]
[v2.2.1 is out](https://github.com/catchorg/Catch2/releases/tag/v2.2.1)
