### ISSUE TITLE
Issues with Catch 2.2.0 on macos 10.11.6 and clang 5.0.1

### ISSUE THREAD

**Issue by aacirino** [catchorg/Catch2#1218]
I hadn't updated my local Catch2 repo for a while and when I saw that v2.2.0 was available I pulled it, but then run into trouble. A test as simple as this

```cpp
#define CATCH_CONFIG_MAIN
#include "catch2/catch.hpp"

TEST_CASE("Test issue") {
  auto test = true;
  REQUIRE(test == true);
}
```

gives the following errors:

```bash
/usr/local/include/catch2/catch.hpp:5787:62: error: no template named 'optional' in namespace 'std'
    inline auto convertInto( std::string const &source, std::optional<T>& target ) -> ParserResult {
                                                        ~~~~~^
/usr/local/include/catch2/catch.hpp:10770:21: error: 'uncaught_exceptions' is unavailable: introduced in macOS 10.12
        return std::uncaught_exceptions() > 0;
                    ^
/usr/local/Cellar/llvm/5.0.1/include/c++/v1/exception:130:63: note: 'uncaught_exceptions' has been explicitly marked unavailable here
_LIBCPP_FUNC_VIS _LIBCPP_AVAILABILITY_UNCAUGHT_EXCEPTIONS int uncaught_exceptions() _NOEXCEPT;
```

I had to revert to a commit in January to be able to keep using Catch 2. I tried several commits and stopped at 1ab6be30a28b56c9d9d8782f63ab1f3fdd1630be as the working one.

**Comment by chronoxor** [comment]
Looks like the same - https://github.com/catchorg/Catch2/issues/1214

**Comment by chronoxor** [comment]
Travis config to reproduce the issue:

```
sudo: required
dist: trusty

os: linux
compiler: clang
env: OS=linux COMPILER=clang CLANG_VERSION=5.0

sources:
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty-5.0

packages:
  - clang-5.0
  - libc++-dev
  - libc++abi-dev

before_install:
  - export CC="clang-${CLANG_VERSION}" CXX="clang++-${CLANG_VERSION}"
  - pushd .
  - git clone --depth=1 https://github.com/llvm-mirror/llvm.git llvm-source
  - git clone --depth=1 https://github.com/llvm-mirror/libcxx.git llvm-source/projects/libcxx
  - git clone --depth=1 https://github.com/llvm-mirror/libcxxabi.git llvm-source/projects/libcxxabi
  - mkdir llvm-build && cd llvm-build
  - cmake -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_INSTALL_PREFIX=/usr ../llvm-source
  - make cxx -j2
  - sudo make install-cxxabi install-cxx
  - popd
```

**Comment by horenmar** [comment]
There are 2 bugs in this, one is already fixed as part of #1214, the second one is that OSX 10.11's Clang claims to support C++17 but does not provide [`std::uncaught_exceptions`](http://en.cppreference.com/w/cpp/error/uncaught_exception).


Quick google says that 10.12 has been released September 2016, may I suggest an update?

**Comment by aacirino** [comment]
Better said then done. My MacBook is OK, but my desktop is too old to upgrade to 10.12 and it is my main development computer. I updated LLVM to 6.0 and got rid of the first issue (` error: no template named 'optional' in namespace 'std'`) but the `uncaught_exceptions` remains. It is weird, since I am not using Apple's stock LLVM installation and I am relying on LLVM installed by homebrew, that I thought would bring in the solution to this issue with its libc++.

**Comment by horenmar** [comment]
>Better said then done. 

Fair enough. If I find someone who can tell me how to detect OS X versions properly, I can fix it, but that will have to wait a bit.

**Comment by aacirino** [comment]
By inspecting LLVM's libraries it indeed seems that the only solution to be able to use C++17, Catch2 and macos is to upgrade to macos 10.12. For the moment I will fork Catch2 and change Catch's `uncaught_exceptions` to use the pre-C++17 version. I will also look for a way to detect macos version and circumvent the issue.

**Comment by chronoxor** [comment]
Maybe this workaround will help you

#ifdef __clang__
#define CATCH_CONFIG_NO_CPP17_UNCAUGHT_EXCEPTIONS
#endif

**Comment by aacirino** [comment]
I've put `#define CATCH_CONFIG_NO_CPP17_UNCAUGHT_EXCEPTIONS` in my pre-compiled header and it worked fine with no need to change Catch2. I still haven't found a way to detect the macos version at compile time.

Thanx guys for your help.

**Comment by martinmoene** [comment]
Perhaps of interest: 

Pre-2017 MSVC, GCC and Clang implementation of `uncaught_exceptions()` in [PR 126](https://github.com/martinmoene/gsl-lite/pull/126) of *gsl lite*.

PR 126: Fix final_action_return and final_action_error during stack unwinding

**Comment by horenmar** [comment]
The check was changed to use std feature macro, and allow user to override it.
