### ISSUE TITLE
compact.sw approval test fails in 2.2.1

### ISSUE THREAD

**Issue by chissg** [catchorg/Catch2#1222]
## Description
As a supplemental to issue #1200, we are trying to build and test Catch 2.2.1, and in addition to the path-related issues with the XML tests, we are getting complaints with the compact.sw test. In contrast to issue #1200 we appear to get the same problems with an in-source build.

### Steps to reproduce

CXX=g++ CC=gcc cmake -DCMAKE_INSTALL_PREFIX=<path> -DUSE_CPP14:BOOL=ON .
make -j<#>
ctest -j<#> --output-on-failure

### Extra information

* Catch version: **v2.2.1**
* Operating System: **Scientific Linux 7**
* Compiler+version: **GCC 7.3.0, C++14**
* CMake version: **CMake 3.10.1**

[fail.log](https://github.com/catchorg/Catch2/files/1803237/fail.log)

**Comment by horenmar** [comment]
After some investigation, both of these have the same underlying reason: the machinery for normalizing the output to be comparable between different computers is a bit creaky and fails to work on your PC properly.

ATM there are ~3 issues where the machinery fails, so I will have to work on that soon.
