### ISSUE TITLE
-# works in debug build but not release for junit reporter

### ISSUE THREAD

**Issue by jdmairs** [catchorg/Catch2#1224]
## Description
In debug build I get 

`<testcase classname="CatchTests.exe.rdbcollectortests" name =blah blah>`

but in release build

`<testcase classname="CatchTests.exe.global" name=blah blah>`

### Steps to reproduce
run my unit tests from command line: CatchTests.exe -r junit -#

### Extra information
* Catch version: **v2.2.1**
* Operating System: **Windows 10**
* Compiler+version: **VS2017 15.4.2**

**Comment by horenmar** [comment]
Can't reproduce this with current `devel` branch.
