### ISSUE TITLE
Why not built Catch2 as a static library and header files ?

### ISSUE THREAD

**Issue by bluealert** [catchorg/Catch2#1232]
Build Catch2 as a static library can reduce the build time much when build Test ? The same as Google Test?

**Comment by chronoxor** [comment]
It can be easily made with a following CMakeLists.txt 

``
cmake_minimum_required(VERSION 3.1)

project(Catch2 LANGUAGES CXX VERSION 2.2.1)

set_property(GLOBAL PROPERTY USE_FOLDERS ON)

# define some folders
set(CATCH_DIR ${CMAKE_CURRENT_SOURCE_DIR})
set(HEADER_DIR ${CATCH_DIR}/include)

# library
file(GLOB_RECURSE SOURCE_FILES "${HEADER_DIR}/*.cpp")
add_library(catch ${SOURCE_FILES})
target_include_directories(catch PUBLIC ${HEADER_DIR})
set_target_properties(catch PROPERTIES FOLDER static)
``

**Comment by janisozaur** [comment]
Take a look at https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html too
