### ISSUE TITLE
Compiler error when building PyTorch on Windows

### ISSUE THREAD

**Issue by devinbostIL** [catchorg/Catch2#1233]
## Description
This problem was reported here: https://github.com/pytorch/pytorch/issues/494#issuecomment-322096506
(See the messages starting with my message on March 21st, 2018.)

The log error is here: https://github.com/pytorch/pytorch/files/1838695/pytorch_source_console_output.txt

### Steps to reproduce

Clone the code from: https://github.com/peterjc123/pytorch-scripts
and make sure `MAGMA_HOME` is set to the location of the unpacked MAGMA files downloaded via: `curl -k https://s3.amazonaws.com/ossci-windows/magma_cuda90_release.7z -o magma_cuda90_release.7z`
(if you need cURL, you can get the version: curl-7.57.0-win64-mingw or later and add to the PATH)
and activate Minconda3 by running this script: 
`https://gist.github.com/yf225/1e82a779257914503980eb589044d1c7`
as mentioned here: https://discuss.pytorch.org/t/pytorch-windows-magma-build-from-jenkins/13766/2

Then activate that environment, such as by running the following command (or referencing wherever your environment and code was downloaded to from the previous instructions):
`call C:\src\magma_cuda90\pytorch\Miniconda3\Scripts\activate C:\src\magma_cuda90\pytorch\Miniconda3`

Then, after ensuring that MKL 2018 is installed, run: 
`"C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.1.156\windows\mkl\bin\mklvars.bat" intel64` to set all of the required environment variables from MKL.

And finally, run `cuda90.bat` . 

### Extra information
* Catch2 version: **No idea.**
* PyTorch version: **Current source code from above repositories referenced.**
* Operating System: **Windows 10 (latest)**
* MKL: **2018**
* MAGMA: **referenced above in link**
* Catch version: **v42.42.42**
* cURL version: **curl-7.59.0**
* Compiler+version: **Visual Studio 2017 Professional or Community, x64 Native  v15.0.26430.14**
* CMake: **3.10.3**
* Ninja: **1.7.2**

**Comment by devinbostIL** [comment]
I got the version of catch by running cd to the master branch of PyTorch (_pulled from the repo and method cited above_):
/c/src/pytorch_source/pytorch-scripts/pytorch (master)
and then running:
`$ git submodule status aten/src/ATen/utils/catch`

which returned:

**0a34cc201ef28bf25c88b0062f331369596cb7b7 aten/src/ATen/utils/catch (v2.0.1-233-g0a34cc2)**

**Comment by JoeyGrajciar** [comment]
@devinbostIL 
Looking at the log there is only this error multiple times:
```
C:\src\pytorch_source\pytorch-scripts\pytorch\aten\src\ATen\utils\catch\single_include\catch.hpp(760): error C2872: 'std': ambiguous symbol
```
How exactly is Catch2 header included?
Is this still happening even with latest version?
Is there something named `std`?

**Comment by horenmar** [comment]
Closing due to staleness + no followup
