### ISSUE TITLE
Event listener testRunStarting starting position in junit reporter

### ISSUE THREAD

**Issue by mrbrnk** [catchorg/Catch2#1234]
## Description

I want to add my own XML tag with general information in the junit report and I am using the event listener testRunStarting, since I couldn't figure out how to print "<" with std::cout without being converted to "\&lt;".

### Steps to reproduce

I am using this custom event listener

	virtual void testRunStarting(Catch::TestRunInfo const& testRunInfo) override {
		std::cout << "<info></info>";
	}

which results in this output

	<?xml version="1.0" encoding="UTF-8"?>
	<testsuites<info></info>>
	  <testsuite name="[...]

I think the output should start after `<testsuite>` and not in it.

### Extra information

* Catch version: **v2.2.1**

**Comment by horenmar** [comment]
I am not quite sure where you want the `<info>` element to be, but in the process of looking at this I found out that we have a bug in our support for event listeners. We promise that they will be called _before_ reporters, but right now they are called _after_ reporters.

Anyway

**Comment by mrbrnk** [comment]
This is not what I intended, but I found another way to add my own XML by writing a reporter.

Your output wouldn't be a valid XML file. I wanted something like this
    <?xml version="1.0" encoding="UTF-8"?>
    <testsuites>
      <info></info>
      <testsuite name="TestProject.exe" errors="0" failures="0" tests="1" hostname="tbd" time="0.000326" timestamp="2018-04-06T10:34:12Z">
        <system-out/>
        <system-err/>
      </testsuite>
    </testsuites>

It is also possible to add attributes to `<testsuite>`, but that seems to be the bug.

However, with an own reporter it doesn't matter where the output starts.

**Comment by philsquared** [comment]
Yes, to change the format of the report you'd have to write your own reporter. In this case deriving from the existing one and just overriding the point you need to inject something is probably the way to go (hey, sometimes OOP re-use actual works!).
To write tags you need to use the `XmlWriter` class. It closes tags lazily, so it needs to know the next thing you're writing is a new tag (you can't just start writing the characters `"<info..."`
