### ISSUE TITLE
Regression: `unsigned char` array cannot be stringified in version 2

### ISSUE THREAD

**Issue by netheril96** [catchorg/Catch2#1238]
## Description

In Catch 1 I can stringify an `unsigned char` array just like a `char` array, but it doesn't compile in Catch 2.
### Steps to reproduce

Minimal test file

```c++
#include "catch.hpp"

TEST_CASE("1")
{
    unsigned char array[] = "123";
    CAPTURE(array);
    REQUIRE(1==1);
}
```

### Extra information

* Catch version: **v2.2.1**
* Operating System: **macOS High Serra 10.13.4**
* Compiler+version: **Xcode 9.3**

**Comment by horenmar** [comment]
Nice find. We had an overload for this case ready, but it was missing a cast.

I fixed it and added tests for this and `signed char arr[] = "123";` case.
