### ISSUE TITLE
printf destroys the junit reporter output

### ISSUE THREAD

**Issue by xkbeyer** [catchorg/Catch2#1243]
## Description
Using a printf statement in a TEST_CASE  results in an invalid testsuites XML element. That makes a parser fail.

### Steps to reproduce
Example:
`
TEST_CASE("Single printf Test")
{
	printf("Test with a %s \n", "printf");
}
`
running 
`testcase.exe -r junit > out.txt`
results in:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuitesTest with a printf 
>
  <testsuite name="SingleTestCase.exe" errors="0" failures="0" tests="0" hostname="tbd" time="0" timestamp="2018-04-05T09:00:27Z">
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>
```
Using std::cout works fine and the output lands in the system-out section. 
Running with -o out.txt then the printf output doesn't appear in the file and the XML is ok. The output is only shown on the screen.

### Extra information

* Catch version: v2.1.2
* Operating System: win10
* Compiler+version: gcc 7.3

**Comment by horenmar** [comment]
Yeah, it is completely impossible to capture stdout/stderr in standard C++ and fairly hard to do even with platform specific code (e.g. even Windows binaries have different behaviours dependent on their respective target).

OTOH it _is_ possible to capture things that go through `std::cout`, `std::cerr` and `std::clog`, so these are captured.

**Comment by xkbeyer** [comment]
I see. It is unfortunate that if someone uses printf in their test that a parser can no longer interpret the result.
This means the only way to make a parser work reliably is with `-o` and then parse the file.

**Comment by horenmar** [comment]
> This means the only way to make a parser work reliably is with -o and then parse the file.

This is a good idea in general. The capture is active only during a test case run, so user can break the output with a Listener when a test case is not running.

**Comment by xkbeyer** [comment]
I aggree. Unfortunately it doesn't work with the eclipse test runner. When the plugin is called the file isn't always complete:(

**Comment by frznlogic** [comment]
Why don't you use the -o flag and output the xml logs somewhere else? Then printfs will be on stdout and the xml log will be in a separate file.

**Comment by horenmar** [comment]
Interesting. Is this because the file hasn't been flushed, or because the plugin can be called before the test run is actually finished?

**Comment by xkbeyer** [comment]
The plugin is called with an InputStream, this stream contains the STDOUT of TestExe. What I can see is that the TestExe runs as long as the given InputStream is read.
In case an out file is written, (I assume) it is not flushed at the moment the plugin tries to read it.
That gives me an idea. So far I ignored the InputStream in this scenario. I should read it and see if the TestExe ends earlier and flushs the file.

**Comment by X-Ryl669** [comment]
> Yeah, it is completely impossible to capture stdout/stderr in standard C++ and fairly hard to do even with platform specific code (e.g. even Windows binaries have different behaviours dependent on their respective target).

What about:
```
fclose(stdout);
fclose(stderr);
freopen("/makeyourowntempfilehere", "w", stdout);
freopen("/makeyourowntempfilehere_err", "w", stderr);

[...] 
// Later before leaving program
[...]

fflush(stdout);
fflush(stderr);
FILE * oldOut = fopen("/makeyourowntempfilehere", "r");
// Read from std out here
// etc...
fclose(stdout);
fclose(stderr);
unlink("/makeyourowntempfilehere");
unlink("/makeyourowntempfilehere_err");
```

**Comment by horenmar** [comment]
@X-Ryl669 Actually e.g. `unlink` is POSIX and not a part of standard C. Anyway, master now contains an experimental, opt-in, support for redirecting _all_ output to stdout/stderr.
