### ISSUE TITLE
REQUIRE_THROWS_AS(std::pair<int,int>(1,4),std::invalid_argument) doesn't compile

### ISSUE THREAD

**Issue by Kvaz1r** [catchorg/Catch2#1246]
## Description
When try compile code below(I know that it's wrong test, but it's just short mcve), get this error:

> mcve.cpp:9:68: error: macro "REQUIRE_THROWS_AS" passed 3 arguments, but takes just 2

compile thus:
g++ -static -pedantic -Wall -Wextra  -O3 -std=c++14 -o "mcve" "mcve.cpp"

### Steps to reproduce
```
#define CATCH_CONFIG_MAIN  // This tells Catch to provide a main() - only do this in one cpp file
#include "catch.hpp"

#include <utility>
#include <stdexcept>

TEST_CASE( "test", "[mcve]" )
{
    REQUIRE_THROWS_AS(std::pair<int,int>(1,4),std::invalid_argument);
}
```

### Extra information
* Catch version: **v2.2.2**
* Operating System: **Windows 7**
* Compiler+version: **gcc version 7.1.0**

**Comment by horenmar** [comment]
This is an old problem with macro parsing being different from code parsing. The short version is that by preprocessor rules, there _are_ three arguments there, `std::pair<int`, `int>(1,4)` and `std::invalid_argument`. Some assertions use variadic macros to workaround this, but it can only work in assertions that are in reality single-argument, but can be parsed weird. Assertions with multiple arguments cannot be made variadic and thus are unable to deal with commas inside template argument lists properly.

**Comment by Kvaz1r** [comment]
thanks for the explanation.

**Comment by Bu11etmagnet** [comment]
You can work around this (commas inside template argument list inside macros) by typedef-ing your pair:
```
using two_ints = std::pair<int, int>;
REQUIRE_THROWS_AS(two_ints(1,4),std::invalid_argument);
```

Disclaimer: I didn't actually try this.

**Comment by Kvaz1r** [comment]
this really works, thanks.

**Comment by rpici** [comment]
Another option is to enclose the first argument in parentheses:

    REQUIRE_THROWS_AS(
        (std::pair<int,int>(1,4)),
        std::invalid_argument
    );
