### ISSUE TITLE
single header catch in catch1 branch needs #include <cassert>

### ISSUE THREAD

**Issue by philipcraig** [catchorg/Catch2#1249]
## Description

Compiled the single header catch from catch1 branch with Visual Studio 2015

What I wanted to happen: it builds
What happened: gives an error saying assert isn't defined.

What will fix it: `#include <cassert>` in the single header

### Steps to reproduce

Compile a single header version of catch1 with Visual Studio 2015

### Extra information

Fill in any extra information that might be important for your issue.

If your issue is a bugreport, definitely fill out at least the following.

* Catch version: **v1**
* Operating System: Windows 7
* Compiler+version: Visual Studio 2015 cl.exe

**Comment by horenmar** [comment]
Ok, this should be fixed. But we strongly recommend migrating to Catch2 when you can use VS 2015.

**Comment by horenmar** [comment]
v1.12.2 is out with the fixed includes.
