### ISSUE TITLE
[ the documentation need an update ] Thread safe assertions and catch2

### ISSUE THREAD

**Issue by robinmoussu** [catchorg/Catch2#1252]
Hello,
I was reading the documentation of catch2 before starting to use it, and I found in the documentation of the [limitation](https://github.com/catchorg/Catch2/blob/master/docs/limitations.md#thread-safe-assertions) that catch assertions and macro aren't thread safe

> This limitation is highly unlikely to be lifted before Catch 2 is released.

Since catch2 was released, I think the documentation should be updated either to say that it's no longer a limitation, or that it is still the case even with the release of catch2.

**Comment by capsocrates** [comment]
I would like clarity around this as well. Which macros, if any, are thread-safe, and which are not?

**Comment by horenmar** [comment]
I updated the documentation in ebf89000f19f896fd2fec4755b8135e88d24e318 but missed this issue.

Anyway, no macros are thread-safe.
