### ISSUE TITLE
Attempts to Generate Code Coverage Lead to a Compilation Freeze

### ISSUE THREAD

**Issue by arnavb** [catchorg/Catch2#1253]
## Description

Ok, so this is a problem I have been having for a while, but I have no way to solve. In my repository (arnavb/cpp14-project-template#1), I have been trying to add code coverage so I can see the effectiveness of my tests. To do so, I have been using [this module](https://github.com/bilke/cmake-modules/blob/master/CodeCoverage.cmake). In order to apply code coverage, I added the following CMake code:

```CMake
if (ENABLE_COVERAGE AND NOT CMAKE_CONFIGURATION_TYPES)
    if (NOT BUILD_TESTS)
        message(FATAL_ERROR "Tests must be enabled for code coverage!")
    endif (NOT BUILD_TESTS)
    
    include(CodeCoverage)
    append_coverage_compiler_flags()
    
    set(COVERAGE_EXCLUDES "${CMAKE_SOURCE_DIR}/test/*")
    setup_target_for_coverage(NAME coverage EXECUTABLE ctest DEPENDENCIES coverage)
endif (ENABLE_COVERAGE AND NOT CMAKE_CONFIGURATION_TYPES)
```

Now this does work, I can confirm (without using Catch), as you can see in [arnavb/test-codecov](https://github.com/arnavb/test-codecov) in an older commit. However, when I add Catch tests to the project (it's newest commit), I get a compilation freeze since the Coverage flags are seriously slowing down the Catch code. (I waited a few minutes, and the compilation still hasn't finished). Now I thought: Hey! maybe I can just apply the flags to the library I'm testing! In order to do that, I commented out `append_coverage_compiler_flags()` and added the following to my `src/CMakeLists.txt`:

```CMake
if (ENABLE_COVERAGE) # Uncomment these lines
    target_compile_options(test-codecov-lib PRIVATE "-g;-O0;--coverage;-fprofile-arcs;-ftest-coverage")
endif (ENABLE_COVERAGE)
```

Now this _does_ work, but only partially. Now, when I try to compile, the compilation finishes quickly for the tests. _However_, if there is a function present that is defined _just_ in a header file (such as a template function), it's coverage is completely ignored! I asked a question on SO to try and solve this and got the following response [in a comment](https://stackoverflow.com/questions/49268226/codecoverage-module-for-cmake-does-not-include-functions-defined-in-header-files#comment86703973_49268226):

> So I need to apply flags to the header files? - There is no such thing like "compiler flags for a header file" - compiler flags are applied for the whole source file. It seems exactly the reason of your problem: **your test, which calls the inline function, is compiled without coverage flags. So coverage counters aren't updated for that calls.** When `main.cpp`, compiled with coverage flags, calls the inline function, this updates coverage counters.

So it seems that the test files I'm using DO need the coverage flags, but I can't apply them without a compilation freeze. As such, I'm at a loss for what to do. How can I speed up the compilation of my code?

### Steps to reproduce

If you want an example of the compilation freeze with Catch, then follow the build steps in [arnavb/test-codecov](https://github.com/arnavb/test-codecov).

### Extra information

* Catch version: **v2.2.2**
* Operating System: **Cloud9 IDE Ubuntu 14.04**
* Compiler+version: **GCC 5.4.1**

Thanks for taking the time to read this; I know it's a lot!

**Comment by arnavb** [comment]
**UPDATE:**

Well, this problem no longer exists for _me_, since I switched to doctest which was much faster and could handle the flags.

I'm still leaving this issue open since it isn't resolved yet.

**Comment by JoeyGrajciar** [comment]
Can not reproduce with 2.5.0.
