### ISSUE TITLE
Objc is compilation is broken

### ISSUE THREAD

**Issue by froody** [catchorg/Catch2#1255]
## Description
Using catch in objc files is broken since 
https://github.com/catchorg/Catch2/commit/d2ddb997a74f698e10ac3debbfc48b3722caf3eb
### Steps to reproduce
Foo.mm:
#include "catch.hpp"
TEST_CASE("test") {
REQUIRE(1 == 0);
}

### Extra information
* Catch version: 2.2.2
* Operating System: MacOS X 10.13.4
* Compiler+version: Any clang

**Comment by horenmar** [comment]
I forwarded this one to Phil, because I don't have OS X nor any Obj-C experience. Alternatively you can provide a PR to fix this (ideally while enabling Obj-C CI on Travis).

**Comment by bdb** [comment]
2.2.2 is broken. Obviously you have no Objc++ unit tests or Travis would have caught this.

Xcode 9.3

**Comment by bdb** [comment]
Ok, I must have misunderstood "we don't have the infrastructure" because Catch's .travis.yml file contains Xcode images already. So what's prevent them from running tests?

**Comment by bdb** [comment]
Is this fixed in 2.3?  Release notes say "Fixed Objective-C++ build"

**Comment by bdb** [comment]
Finally got around to testing 2.3 and it does indeed fix this bug. Thanks!

**Comment by JoeyGrajciar** [comment]
Based on previous comment closing this.
