### ISSUE TITLE
Cannot compile library

### ISSUE THREAD

**Issue by Good-Pudge** [catchorg/Catch2#1257]
## Description
I can't compile this library.
![Error](https://i.imgur.com/cAHYGIA.png)

### Steps to reproduce
Just try to compile the library using CMake `GLOB_RECURSE` and compiler which you can see in `Extra information`. If you want to full reproduce, you'll look through [this repo](https://github.com/Good-Pudge/okhttp-fork). Use this script:
```bash
git clone --recursive https://github.com/Good-Pudge/okhttp-fork.git
cd okhttp-fork
mkdir build
cd build
cmake .. -DBUILD_TESTING=ON -G "MinGW Makefiles"
cmake --build . --target ohf_tests -- -j4
```

### <a name="extra"></a> Extra information
* Catch version: **v2.2.2**
* Operating System: **Windows 10 Pro v1709 x64**
* Compiler+version: **MinGW-w64 7.2.0**

**Comment by horenmar** [comment]
Define `CATCH_CONFIG_NO_POSIX_SIGNALS` to fix it for now.

The underlying problem is that MinGW is detected as generic GCC variant, so POSIX signals are expected to work. However, they do not.
