### ISSUE TITLE
Please allow whitespaces in tags or disallow it completely

### ISSUE THREAD

**Issue by quixoticaxis** [catchorg/Catch2#1259]
I have `[.integration tests]`, `[.long running]` and `[won't compile]` tags in my project.

- Hidden tags with whitespaces cannot be invoked by passing `[.long running]` or `[.integration tests]`, they are being run when `[.]` is passed as console parameter though;
- Not hidden tags with whitespaces are listed but can not be run by passing a tag.

It would be great if multi word tags are forbidden completely, otherwise they should act in the same way the single word tags do. I would prefer the later =)

**Comment by philsquared** [comment]
Are you putting the arguments with spaces in quotes?, e.g.

`./MyTests "[.integration tests]"`

**Comment by quixoticaxis** [comment]
@philsquared Yeap, my bad, I was not putting them in quotes.
