### ISSUE TITLE
catch_discover_tests() - cmake's ctest cannot find tests with spaces

### ISSUE THREAD

**Issue by ashaduri** [catchorg/Catch2#1265]
## Description
I'm using catch_discover_tests() with cmake to automatically find catch tests for `make test`.
I'm using `Catch.cmake` and `CatchAddTests.cmake` from "contrib" directory.

My TEST_CASE says:

```
TEST_CASE("port numbers are parsed", "[core]")
{
	REQUIRE(SPar::parseFilenamePorts("") == 0);
}
```

However, when I run `make test`, ctest cannot find any tests. Running `ctest --verbose` reveals the reason - it tries to run the test with `portnumbersareparsed` argument.

### Steps to reproduce
Use ctest with spaces in TEST_CASE.

### Extra information
Catch 2.2.2.

CTest output:
```
$ ctest --verbose
UpdateCTestConfiguration  from :/projects/catch-test-project/0clang-debug/DartConfiguration.tcl
UpdateCTestConfiguration  from :/projects/catch-test-project/0clang-debug/DartConfiguration.tcl
Test project /projects/catch-test-project/0clang-debug
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: portnumbersareparsed

1: Test command: /projects/catch-test-project/0clang-debug/test_core "portnumbersareparsed"
1: Test timeout computed to be: 9.99988e+06
1: ===============================================================================
1: No tests ran
1: 
1/1 Test #1: portnumbersareparsed .............   Passed    0.01 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.02 sec
```

**Comment by mrpilot2** [comment]
I ran into the same issue. I found the offending line:

https://github.com/catchorg/Catch2/blob/8d5d49299be5b8c62ec90be7d6ee4f71cbe89ea0/contrib/CatchAddTests.cmake#L54

I cannot see a reason why the spaces should be stripped, therefore I've created a pull request
