### ISSUE TITLE
Preventing Catch from truncating error output?

### ISSUE THREAD

**Issue by socketbox** [catchorg/Catch2#1274]
## Description

When I run a few tests, they reveal an error in my code, but truncate the full text of the error:

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
foo is a Catch v2.2.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Test1
-------------------------------------------------------------------------------
foo.cpp:55
...............................................................................

foo.cpp:55: FAILED:
due to unexpected exception with message:
  basic_string

===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed

```

I'd like to see more of the `trace`, which reads as follows when run outside of a catch test:

`libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string
Abort trap: 6`

So, I increase verbosity on the command line:

`./testSuite -v high`

But Catch doesn't seem to like that for the console reporter:

`Verbosity level not supported by this reporter`

I then try each reporter (`-r xml,  -r junit, -r compact`) in turn, hoping that one of them will not produce this error. No joy. Each returns the same error. Moreover, `-v quiet` is equally as unsupported.

My question is, how can I prevent Catch from truncating or otherwise redacting error output?

### Steps to reproduce
I suspect that the lack of support for higher levels of verbosity is due to the fact that this feature was never fully implemented in the default set of included reporters that ship with single-file header. But just in case, here are steps to reproduce:

1. Download v2.2.2 release of the single header from https://github.com/catchorg/Catch2/releases/download/v2.2.2/catch.hpp

2. Insert the necessary preprocessor directives at the top of the source code:
```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
```
3. Compile with `g++ -std=c++11 -o foo foo.cpp`

4. Run `./foo -v high`

### Extra information

* Catch version: **v2.2.2**
* Operating System: **macOS 10.12.6**
* Compiler+version: **clang-900.0.39.2**

**Comment by horenmar** [comment]
So, there are two things here to unpack.

1) Reporter verbosity is a vestigial feature, that currently only has impact on the output of `--list-tests` option. The next major version will contain a rework that, among other things, will mean that unsupported verbosities are silently ignored.

2) That you want to see the unexpected exception type in the output. This is not supported (and is currently not planned to be).

It is important to note, that what you see is not a truncated output. It is the entirety of the actual message that was thrown during the test. What `trace` shows extra is the exception type, done via platform-specific demangling machinery.

**Comment by socketbox** [comment]
@horenmar Thank you for your thorough reply.
