### ISSUE TITLE
Use of std::to_string in WithinAbsMatcher

### ISSUE THREAD

**Issue by baldurk** [catchorg/Catch2#1280]
## Description

In `WithinUlpsMatcher::describe` the code calls `std::to_string(m_ulps)`. I'm not even sure if that's actually a bug/unintended, but it feels out of place when all the other values around it call to `::Catch::Detail::stringify`.

### Steps to reproduce

I only noticed this because `std::to_string` is not available on android ( :roll_eyes: ) so it popped up as an error. I just replaced with `::Catch::Detail::stringify` locally, but if this is a WONTFIX then I won't blame you!

### Extra information

* Catch version: **v2.2.2**
* Operating System: **Android 26.0.1**
* Compiler+version: **Android 26 compiler**

**Comment by horenmar** [comment]
Yeah, that is a bug/oversight, probably from prototyping the code outside of Catch at first.

**Comment by baldurk** [comment]
Ah I see, that makes sense then.

I'm not using any special compile flags so it'll be whatever is default for that Android SDK, I'm not really familiar with the setup. Android is very brittle and error-prone though, so I'm happy to leave this as a local change I have for compatibility rather than try and fix it another way on my end and break something else.
