### ISSUE TITLE
Some links in the examples page are broken

### ISSUE THREAD

**Issue by onqtam** [catchorg/Catch2#1282]
see here:
https://github.com/catchorg/Catch2/blob/master/docs/list-of-examples.md

**Comment by horenmar** [comment]
Yeah, some of them do not yet exist. We should probably mark those that are not supposed to work yet, or get them in.

@martinmoene I assume you are still too busy with other stuff?

**Comment by martinmoene** [comment]
@horenmar Indeed still too busy,however also still interested to bring this forward...
Perhaps mark the missing entries with (ToDo) and keep the links.

Related to issue #1037 and PR #1145 (which expands the list)
