### ISSUE TITLE
Reporter output redirection

### ISSUE THREAD

**Issue by AlexeyIgnashin** [catchorg/Catch2#1290]
I want to use Catch on a platform where std::cout cannot be used. 

I do not want to get into Catch implementation details and write my own reporter from scratch. 

I do not want to waste my time investigating how to implement my own std::streambuf to replace the one in std::ostream either.

What I want is to have some kind of a function I can easily override that would allow me to receive everything Catch prints and redirect it wherever I need, i.e.

```
void PrintLine(const std::string& data)
{
    PlatformSpecificOutputFunction(data);
}
```

Is there anything like it?

**Comment by BiCapitalization** [comment]
Take a look at https://github.com/catchorg/Catch2/blob/master/docs/configuration.md#stdout

**Comment by horenmar** [comment]
What @BiCapitalization said. You need to implement your own streams but that isn't that hard.

**Comment by AlexeyIgnashin** [comment]
Can anyone provide a sample where streams are implemented from scratch?

**Comment by horenmar** [comment]
@AlexeyIgnashin 
```cpp
class cout_buff : public std::stringbuf {
public:
    ~cout_buff() { pubsync(); }
    int sync() {
        int ret = 0;
        for (unsigned char c : str()) {
            if (putchar(c) == EOF) {
                ret = -1;
                break;
            }
        }
        // Reset the buffer to avoid printing it multiple times
        str("");
        return ret;
    }
};

namespace Catch {
    std::ostream& cout() {
        static std::ostream ret(new cout_buff);
        return ret;
    }
}
```
