### ISSUE TITLE
Assignment in conditional not standard-compliant

### ISSUE THREAD

**Issue by JubilantJerry** [catchorg/Catch2#1297]
### Description
The expansion of the `SECTION` macro creates non-compliant code, which most compilers will not point out.

The `SECTION` macro expands to `INTERNAL_CATCH_SECTION`, which expands to the form:

``
if (Foo x = Bar(params))
``

In this case, class `Foo` (actually `Catch::Section const &`) wasn't copy or move-constructable. It turns out that even though the compiler elides the second constructor call, it must still exist for the code to be well-defined ([link 1](https://stackoverflow.com/questions/8332285/why-cant-variables-defined-in-a-conditional-be-constructed-with-arguments), [link 2](https://stackoverflow.com/questions/2671532/non-copyable-objects-and-value-initialization-g-vs-msvc)). The semantics of the statement should be:

- Construct an rvalue Bar(params)
- Construct an rvalue Foo(Bar)
- Copy-construct or move-construct the temporary Foo to x (!!!)
- Destroy the temporary Foo / Bar objects

I have occasionally gotten mysterious compiler errors from this, though I haven't found a reliable way to reproduce the error. The error I've gotten was:
``
No viable conversion from 'Catch::SectionInfo' to 'const & Catch::Section'
``

### Proposed solution
On C++11 an initializer list will work, but that solution is not portable. You could define the variable immediately above the conditional statement, like so:

```c++
#ifdef CATCH_CONFIG_VARIADIC_MACROS
    #define INTERNAL_CATCH_SECTION_EXP(sectionId, ... ) \
        Catch::Section const& sectionId((Catch::SectionInfo( CATCH_INTERNAL_LINEINFO, __VA_ARGS__ ))); \
        if( sectionId )
    #define INTERNAL_CATCH_SECTION( ... ) \
        INTERNAL_CATCH_SECTION_EXP(INTERNAL_CATCH_UNIQUE_NAME( catch_internal_Section ), __VA_ARGS__)
#else
    #define INTERNAL_CATCH_SECTION_EXP(sectionId, name, desc ) \
        Catch::Section const& sectionId((Catch::SectionInfo( CATCH_INTERNAL_LINEINFO, name, desc ))); \
        if( sectionId )
    #define INTERNAL_CATCH_SECTION( name, desc ) \
        INTERNAL_CATCH_SECTION_EXP(INTERNAL_CATCH_UNIQUE_NAME( catch_internal_Section ), name, desc)
#endif
```

### Extra information
The error only appeared in the form of error annotations when I was using the EasyClangComplete plugin for Sublime, which uses `libclang` as its backend. Running the compiler manually didn't reveal errors.

**Comment by horenmar** [comment]
No.

While this is correct:
> `if (Foo x = Bar(params))`
> 
> In this case, class `Foo` wasn't copy or move-constructable. It turns out that even though the compiler elides the second constructor call, it must still exist for the code to be well-defined (link 1, link 2). The semantics of the statement should be:
> 
> * Construct an rvalue Bar(params)
> * Construct an rvalue Foo(Bar)
> * Copy-construct or move-construct the temporary Foo to x (!!!)
> * Destroy the temporary Foo / Bar objects

This reasoning does not apply to the actual `SECTION` implementation, because the LHS of the assignment is a `const&`, not value. This means that what actually happens is:

* Temporary `SectionInfo` is constructed
* Temporary `Section` is constructed from the `SectionInfo`
* The temporary above is bound by a **constant reference**.

See this [CE, where func1 represents what is actually happening in `SECTION`s and compiles, but func2 doesn't.](https://godbolt.org/g/34QeZe)
