### ISSUE TITLE
Light Yellow instead of Yellow for Warning Color in Windows (for Catch1)

### ISSUE THREAD

**Issue by M-Fabian** [catchorg/Catch2#1298]
In issue #979, the muddy Yellow in console output was replaced by a bright yellow.

Could you please also add BrightYellow to Catch1? Please consider it for the next release.
It seems that Catch1 is still under active development, which I appreciate since I cannot switch to Catch2 yet (because of the compiler I am bound to use in my current projects),

**Comment by horenmar** [comment]
Catch Classic stopped being actively developed once Catch2 was released. The couple releases were bugfix only (and we hope there won't be more of them).

You should be able to port it to your own local copy easily though.

**Comment by horenmar** [comment]
Since there has been no followup, I am going to close this.
