### ISSUE TITLE
Can not evaluate blocks in CHECK/REQUIRE with Catch 2

### ISSUE THREAD

**Issue by SebDyn** [catchorg/Catch2#1299]
## Description

I switched from Catch 1.35 to Catch 2.2.2.
Now some tests do not compile anymore on some platforms.

### Steps to reproduce

Try the variants of
- REQUIRE, 
- CHECK, 
- REQUIRE_NOTHROW, 
- CHECK_NOTHROW 
- ... 
using C++ blocks inside, for example
- CHECK_NOTHROW( { double A = 0.0; if (true) A = 1.0; } ) 
This leads to a compile error on RHEL-6 using GCC 6.3.1 20170216 (Red Hat 6.3.1-3) 
- error: expected primary-expression before 'if' 
or
- error: expected primary-expression before 'double'

### Extra information
* Catch version: 2.2.2
* Operating System: RHEL6
* Compiler+version: GCC 6.3.1

**Comment by horenmar** [comment]
Thats... definitely an old version of Catch.

This usage was never officially supported, and the interface was tightened to no longer accept arbitrary C++ code in v1.7.0, as it was always meant to only accept an expression. If you need to write a block of code, use C++11 lambda.

**Comment by horenmar** [comment]
Since there has been no followup I am going to close this.
