### ISSUE TITLE
Heap corruption on assertions

### ISSUE THREAD

**Issue by JasonDictos** [catchorg/Catch2#1304]
## Description
Was testing some threading code, and noticed a heap corruption report from the debug heap on windows. This appears to be a simple assert in a thread thats causing the corruption. 

### Steps to reproduce
Don't have one, pretty complex closed source project

### Extra information
Program: <program name unknown>

HEAP CORRUPTION DETECTED: after Normal block (#10736) at 0x000001EA119DC700.
CRT detected that the application wrote to memory after end of heap buffer.

(Press Retry to debug the application)

 	ucrtbased.dll!00007ffc38fa1204()	Unknown
 	ucrtbased.dll!00007ffc38fa4515()	Unknown
>	SWClientTest.exe!operator delete(void * block) Line 38	C++
 	SWClientTest.exe!operator delete(void * block, unsigned __int64 __formal) Line 32	C++
 	SWClientTest.exe!std::_Deallocate<16,0>(void * _Ptr, unsigned __int64 _Bytes) Line 219	C++
 	SWClientTest.exe!std::allocator<char>::deallocate(char * const _Ptr, const unsigned __int64 _Count) Line 1032	C++
 	SWClientTest.exe!std::basic_stringbuf<char,std::char_traits<char>,std::allocator<char> >::overflow(int _Meta) Line 182	C++
 	msvcp140d.dll!00007ffc2b4b1d71()	Unknown
 	msvcp140d.dll!00007ffc2b514bbe()	Unknown
 	SWClientTest.exe!std::operator<<<std::char_traits<char> >(std::basic_ostream<char,std::char_traits<char> > & _Ostr, const char * _Val) Line 806	C++
 	SWClientTest.exe!Catch::ConsoleReporter::lazyPrintRunInfo() Line 12015	C++
 	SWClientTest.exe!Catch::ConsoleReporter::lazyPrintWithoutClosingBenchmarkTable() Line 12006	C++
 	SWClientTest.exe!Catch::ConsoleReporter::lazyPrint() Line 12000	C++
 	SWClientTest.exe!Catch::ConsoleReporter::assertionEnded(const Catch::AssertionStats & _assertionStats) Line 11922	C++
 	SWClientTest.exe!Catch::RunContext::assertionEnded(const Catch::AssertionResult & result) Line 8642	C++
 	SWClientTest.exe!Catch::RunContext::reportExpr(const Catch::AssertionInfo & info, Catch::ResultWas::OfType resultType, const Catch::ITransientExpression * expr, bool negated) Line 8882	C++
 	SWClientTest.exe!Catch::RunContext::handleExpr(const Catch::AssertionInfo & info, const Catch::ITransientExpression & expr, Catch::AssertionReaction & reaction) Line 8867	C++
 	SWClientTest.exe!Catch::AssertionHandler::handleExpr(const Catch::ITransientExpression & expr) Line 5008	C++
 	SWClientTest.exe!Catch::AssertionHandler::handleExpr<bool>(const Catch::ExprLhs<bool> & expr) Line 1561	C++
 	SWClientTest.exe!__writer(ThreadContext & ctx) Line 70	C++
 	[External Code]	

* Catch version: **Catch v2.2.2**
* Operating System: **Windows 10 Pro**
* Compiler+version: **Msvc 2017 15.7.3**

**Comment by horenmar** [comment]
If multiple threads touch Catch's assertion (or sections, or pretty much any other macro), all bets are off as Catch is not internally synchronized.

**Comment by JasonDictos** [comment]
Ok that makes sense, guess I shoulda read the 'ol docs huh ;)
