### ISSUE TITLE
Export Catch2Config.cmake with conan

### ISSUE THREAD

**Issue by Quincunx271** [catchorg/Catch2#1305]
Conan 1.4 recently came out, which added a `cmake_paths` generator, which allows unintrusive use of Conan as a package manager for CMake. When trying to use this, I discovered that it does nothing for libraries which don't install a *FindFoo.cmake* or *FooConfig.cmake,* which includes Catch2.

I'm proposing that the *conanfile.py* be edited to export the *Catch2Config.cmake* file generated by CMake. This would enable users of Catch2 and Conan to easily use Conan in a non-intrusive way.

**Comment by horenmar** [comment]
I don't actually use Conan, but I am willing to accept a PR that improves how Catch is packaged for it.

**Comment by horenmar** [comment]
This is now in master.
