### ISSUE TITLE
Can't build Catch2 on cygwin 32bit

### ISSUE THREAD

**Issue by OmerRosler** [catchorg/Catch2#1311]
I'm trying to build Catch2 on my local machine and it fails.
Setup:
cygwin 32bit on win7 (version 2.10.0)
gcc 7.3
cmake 3.11.3

The problem has to do with ANSI extensions (https://stackoverflow.com/a/32952453/5005049)

The main CMakeLists.txt file explicitly disables the extensions, commenting it out solves the problem and it builds correctly
--------------------------------------------
The output when running `make`:
Scanning dependencies of target SelfTest
[  1%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/TestMain.cpp.o
[  2%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/IntrospectiveTests/CmdLine.tests.cpp.o
[  3%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/IntrospectiveTests/PartTracker.tests.cpp.o
[  4%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/IntrospectiveTests/TagAlias.tests.cpp.o
[  5%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/IntrospectiveTests/String.tests.cpp.o
[  6%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/IntrospectiveTests/Xml.tests.cpp.o
[  7%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/Approx.tests.cpp.o
[  8%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/BDD.tests.cpp.o
[  9%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/Benchmark.tests.cpp.o
[ 10%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/Class.tests.cpp.o
[ 11%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/Compilation.tests.cpp.o
[ 12%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/Condition.tests.cpp.o
[ 13%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/Decomposition.tests.cpp.o
[ 14%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/EnumToString.tests.cpp.o
[ 15%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/Exception.tests.cpp.o
[ 16%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/Message.tests.cpp.o
[ 17%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/Misc.tests.cpp.o
[ 18%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/ToStringChrono.tests.cpp.o
[ 19%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/ToStringGeneral.tests.cpp.o
[ 20%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/ToStringPair.tests.cpp.o
[ 21%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/ToStringTuple.tests.cpp.o
[ 22%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/ToStringVector.tests.cpp.o
[ 23%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/ToStringWhich.tests.cpp.o
[ 24%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/Tricky.tests.cpp.o
[ 25%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/VariadicMacros.tests.cpp.o
[ 26%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/UsageTests/Matchers.tests.cpp.o
[ 27%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_approx.cpp.o
[ 28%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_assertionhandler.cpp.o
[ 29%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_assertionresult.cpp.o
[ 30%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_benchmark.cpp.o
[ 31%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_capture_matchers.cpp.o
[ 32%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_commandline.cpp.o
[ 33%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_common.cpp.o
[ 34%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_config.cpp.o
[ 35%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_console_colour.cpp.o
[ 36%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_context.cpp.o
[ 37%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_debug_console.cpp.o
[ 38%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_debugger.cpp.o
[ 39%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_decomposer.cpp.o
[ 40%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_errno_guard.cpp.o
[ 41%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_exception_translator_registry.cpp.o
[ 42%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_fatal_condition.cpp.o
[ 43%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_interfaces_capture.cpp.o
[ 44%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_interfaces_config.cpp.o
[ 45%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_interfaces_exception.cpp.o
[ 46%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_interfaces_registry_hub.cpp.o
[ 47%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_interfaces_runner.cpp.o
[ 48%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_interfaces_testcase.cpp.o
[ 49%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_list.cpp.o
[ 50%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_leak_detector.cpp.o
[ 51%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_matchers.cpp.o
[ 52%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_matchers_floating.cpp.o
[ 53%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_matchers_generic.cpp.o
[ 54%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_matchers_string.cpp.o
[ 55%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_message.cpp.o
[ 56%] Building CXX object CMakeFiles/SelfTest.dir/include/internal/catch_output_redirect.cpp.o
/home/sharon1/external_libs/Catch2/include/internal/catch_output_redirect.cpp: In constructor ‘Catch::OutputRedirect::OutputRedirect(std::string&, std::string& ’:
/home/sharon1/external_libs/Catch2/include/internal/catch_output_redirect.cpp:105:14: error: ‘fileno’ was not declared in this scope
         dup2(fileno(m_stdoutFile.getFile()), 1);
              ^~~~~~
/home/sharon1/external_libs/Catch2/include/internal/catch_output_redirect.cpp:105:14: note: suggested alternative: ‘fopen’
         dup2(fileno(m_stdoutFile.getFile()), 1);
              ^~~~~~
              fopen
make[2]: *** [CMakeFiles/SelfTest.dir/build.make:778: CMakeFiles/SelfTest.dir/include/internal/catch_output_redirect.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:900: CMakeFiles/SelfTest.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by objectx** [comment]
Current implementation fails compilation when system w/o `dup2`. There is no parameters to configure 😿

**Comment by JoeyGrajciar** [comment]
I guess this one can be closed since it is possible to configure to not use the new capture

**Comment by horenmar** [comment]
Agreed
