### ISSUE TITLE
Feature request: improve conan package

### ISSUE THREAD

**Issue by pleroux0** [catchorg/Catch2#1313]
## Feature request
Feature request: 

Change conan package to use cmake install so that the cmake targets can be used in a cmake package. 

This allows for consumer packages to use modern cmake in their build systems:

```cmake
find_package(Catch2 2.2.2 REQUIRED)
target_link_libraries(my_target PRIVATE Catch2::Catch)
```
instead of

```cmake
target_include_directories(my_target PRIVATE ${CONAN_INCLUDE_DIRS_CATCH})
```
If a consumer uses the `cmake_paths` generator one can even skip the usual

```cmake
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
```

which conan requires with the `cmake` generator. Making the consumer project use of conan transparent.

I would be happy to make a pull request. I see you have a dev-new-cmake (which also changes the conan package). Would you prefer to make the pull request there or on the master branch?

**Comment by horenmar** [comment]
This seems like a duplicate of #1305, so I will repeat myself: I don't actually use Conan, but I would merge a PR that improves its integration.

I would prefer for it to be made against the `dev-new-cmake` branch, to avoid oversights when resolving the merge.

**Comment by horenmar** [comment]
This is now in master.
