### ISSUE TITLE
single include not in sync?

### ISSUE THREAD

**Issue by davnat** [catchorg/Catch2#1315]
I just noticed that the change needed to make #454 work somehow didn't go into the single include header.

The change I'm referring to (included in 788f81230f80cec0551e345cbe42e7d9288fe1f7) is in`include/internal/catch_objc.hpp` at line 96, and if I'm not wrong it should go at line 2965 in `single_include/catch.hpp`.

**Comment by horenmar** [comment]
The single-include versions of headers are only updated when a new release is made.

**Comment by davnat** [comment]
[v2.2.3](https://github.com/catchorg/Catch2/releases/tag/v2.2.3) is a release, and the single-include header was indeed updated, as the version macros are updated.
The change I'm referring to, that appears to be included in [v2.2.3](https://github.com/catchorg/Catch2/releases/tag/v2.2.3) (see https://github.com/catchorg/Catch2/compare/v2.2.3...master), didn't go in the header.

**Comment by horenmar** [comment]
The diff you are viewing are changes _since_ v2.2.3 was released. This means that they will be included in the main header with the next release.

**Comment by davnat** [comment]
Ah, sorry, my bad.
I reached that page from the release page: I didn't read very carefully and it seemed natural to me to see the changes included in that release, not since it happened.
I'm closing this issue, thank you.
