### ISSUE TITLE
CMake: Automatic test registration file output

### ISSUE THREAD

**Issue by fgsalomon** [catchorg/Catch2#1316]
## Description
Is there a way to write the output of the automatic registered tests to multiple files using `ParseAndAddCatchTests`?

### Steps to reproduce
When using this:
~~~
set(AdditionalCatchParameters -o report.xml -s -r junit)
include(ParseAndAddCatchTests)
ParseAndAddCatchTests(${TARGET_NAME})
~~~
The file `report.xml `is always overwritten. I'd like to know if there's a way to parameterize the additional parameters so the output it's redirected to different files.

### Extra information

* Catch version: **v2.2.1**
* Operating System: **Ubuntu 16.04.4**
* Compiler+version: **gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)**

**Comment by Bangjie** [comment]
Hello. I have the same needs and I made some modifications to `ParseAndAddCatchTests.cmake` to redirect report of each `Testcase` to custom dir. I hope it could be helpful. I modify the following lines in `ParseAndAddCatchTests.cmake`

- original:
```camke
add_test(NAME "\"${CTestName}\"" COMMAND ${TestTarget} ${Name} ${AdditionalCatchParameters})
```
- modified

```cmake
# At the head of ParseAndAddCatchTests.cmake
option(REDIRECTDIR "Redirect Catch2 output to specified dir" OFF)
# ...
if (REDIRECTDIR)
    string(REPLACE " " "_" CATCH_OUTPUT_NAME "${Name}")
    add_test(NAME "\"${CTestName}\"" COMMAND ${TestTarget} ${Name} ${AdditionalCatchParameters} -o ${CATCH_OUTPUT_DIR}/${CATCH_OUTPUT_NAME}.catch)
else ()
    add_test(NAME "\"${CTestName}\"" COMMAND ${TestTarget} ${Name} ${AdditionalCatchParameters})
endif ()
```

and then in CMakeLists.txt of my project:
```cmake
...
set(REDIRECTDIR ON)
set(CATCH_OUTPUT_DIR "${PROJECT_SOURCE_DIR}/report") # The output dir.
...
set(AdditionalCatchParameters -r junit -s)
ParseAndAddCatchTests(...)
...
```
and then I use [junit-merger](https://github.com/imsky/junit-merger) to merge all xml junit reports, which is writen in golang.

**Comment by horenmar** [comment]
@fgsalomon There are no ways of doing that at this point, and without a strong support for this feature, I would prefer to avoid adding even more features to the `ParseAndAddCatchTests` script (especially since it is considered somewhat obsolete compared to the other autoregistering script).

@Bangjie's changes look correct, so you should be able to copy them over for your project.

**Comment by fgsalomon** [comment]
Thanks @Bangjie! Your solution works great. 
I understand @horenmar, we'll take a look at `CatchAddTests.cmake` to see if we can use it. Thanks!
