### ISSUE TITLE
CMake Install Helpers for Conan

### ISSUE THREAD

**Issue by Quincunx271** [catchorg/Catch2#1322]
I noticed that the conanfile.py explicitly turns off `CATCH_INSTALL_HELPERS`. I think that this should be turned on, so that users using Catch2 from CMake with Conan can still use the modules inside of contrib. If this isn't desired by default, it's probably a good idea to add this as an option.

**Comment by horenmar** [comment]
I left it out because the documentation was already left out, but re-enabling it isn't much of a problem.
