### ISSUE TITLE
Approx documentation contradicts code

### ISSUE THREAD

**Issue by headsvk** [catchorg/Catch2#1328]
[assertions.md](https://github.com/catchorg/Catch2/blob/master/docs/assertions.md#margin-example) includes this description of Approx margin functionality:

> margin example
> **Margin check is used only if the relative (epsilon and scale based) check fails.**
> 
> Approx target = Approx(100).margin(5);
> 100.0 == target; // Obviously true
> 200.0 == target; // Obviously still false
> 104.0 == target; // True, because we set target to allow absolute error up to 5

While the code looks like this:

```
bool Approx::equalityComparisonImpl(const double other) const {
    // First try with fixed margin, then compute margin based on epsilon, scale and Approx's value
    // Thanks to Richard Harris for his help refining the scaled margin value
    return marginComparison(m_value, other, m_margin) || marginComparison(m_value, other, m_epsilon * (m_scale + std::fabs(m_value)));
}
```

Don't these two descriptions contradict each other? Or am I missing something?

**Comment by horenmar** [comment]
It used to be the case that absolute value check was done later, but there is no functional difference between the two orders of checking.

Anyway, I am gonna fix the documentation so it no longer overspecifies the order of checks.
