### ISSUE TITLE
When failing a test, call abort()

### ISSUE THREAD

**Issue by Leandros** [catchorg/Catch2#1331]
Can I make Catch just call `abort()` (or any other fatal signal / function, I don't care) for any test failure?
This would make it a lot easier for me to provide useful diagnostics.

**Comment by horenmar** [comment]
You can replace `throw Catch::TestFailureException();` at line 5063 with `abort()` if you want, but I am not planning for this to be supported configuration option.

**Comment by onqtam** [comment]
you can also use the [```abort``` command line flag](https://github.com/catchorg/Catch2/blob/master/docs/command-line.md#aborting-after-a-certain-number-of-failures) - but it will end the program in a normal way - not sure if that is what you are looking after.

**Comment by horenmar** [comment]
I am going to close this because using the configuration options for `-fno-exceptions` support, the user can now replace Catch's exceptions handling with a call to a user-provided function.
