### ISSUE TITLE
Custom Exception Type Reporting

### ISSUE THREAD

**Issue by capsocrates** [catchorg/Catch2#1334]
I use a custom exception type that doesn't inherit from `std::exception`. Whenever one of these bubbles up in a test I just get `Unknown exception type` instead of the exception message. Could we please get support for custom exception handling?

**Comment by philsquared** [comment]
https://github.com/catchorg/Catch2/blob/master/docs/tostring.md#exceptions

I admit it's maybe not the most discoverable documentation - but it's there.
Does this do what you want?

**Comment by capsocrates** [comment]
Yes!

**Comment by philsquared** [comment]
Excellent! :-)
