### ISSUE TITLE
Catch 2.2.3: compilation fails on platforms that don't support std::tmpfile()

### ISSUE THREAD

**Issue by fschuh** [catchorg/Catch2#1335]
## Description

Catch 2.2.3 has added a new CATCH_CONFIG_EXPERIMENTAL_REDIRECT feature which introduces a dependency on std::tmpfile() even if CATCH_CONFIG_EXPERIMENTAL_REDIRECT is not defined.
This causes Catch to fail to compile on platforms where std::tmpfile() is not available.

It would be best to remove all references to std::tmpfile() except if CATCH_CONFIG_EXPERIMENTAL_REDIRECT is defined.

### Steps to reproduce

Try to compile under any platform where std::tmpfile() is not available (several game consoles and embedded systems).

### Extra information
* Catch version: **v2.2.3**
* Operating System: **Linux**
* Compiler+version: **Clang**

**Comment by horenmar** [comment]
This should be now implemented.
