### ISSUE TITLE
Add windows commandline argument overload for Catch::Session::applyCommnadLine

### ISSUE THREAD

**Issue by JohnnyHendriks** [catchorg/Catch2#1337]
While working on a Visual Studio Test Adapter for Catch2 I ran into a minor annoyance. To enable a source link to a test case I needed to create a custom test discovery algorithm that outputs in the xml reporter format. As such I have a custom main where I have to call the Session::applyCommandLine method. For the equivalent Session::run method an overload exists for use on windows
 ```int run( int argc, wchar_t* const argv[] );```
a similar overload for the Session::appCommandline
```int applyCommandLine( int argc, wchar_t* const argv[] );```
would be convenient to have as well.

If you're interested you can find my test adapter for Catch2 on GitHub here: [Test Adapter for Catch2](https://github.com/JohnnyHendriks/TestAdapter_Catch2). There you can also find an example for the custom xml test discovery [custom xml test discovery](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/master/Docs/Settings.md#discovercommandline). Note that the example does not make use of the wchar_t commandline argv, as that would unnecessarily complicate the example.

**Comment by horenmar** [comment]
The merged PR should be what you are looking for, at least once the next release is out.
