### ISSUE TITLE
catch2 not detected on Arch Linux build 

### ISSUE THREAD

**Issue by asi14** [catchorg/Catch2#1338]
## Description

I was implementing the Arch Linux version of `Catch2` as part of a C++ project I was doing when the compiler reported that `Catch2`'s header was not found, specifically the error

```
tests.cpp:3:10: fatal error: catch2/catch.hpp: No such file or directory
 #include <catch2/catch.hpp>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

`Catch2` runs when the `catch.hpp` file itself is included, perhaps indicating a problem with the Arch Linux implementation.

### Steps to reproduce
`sudo pacman -Syu`
`sudo pacman -S catch2`
I wrote a basic file `tests.cpp` to test the installation, specifically

```
#define CATCH_CONFIG_MAIN
#include <catch2/catch.hpp>
```

I also followed the instructions indicated [here](https://github.com/catchorg/Catch2/blob/master/docs/tutorial.md#where-to-put-it) indicating how to implement `Catch2` when using it with a package manager (in my case). I finally ran `g++ tests.cpp -o tests` to compile, and ended up with the above error.

### Extra information

* Catch version: **2.2.3-1** (As indicated on the [package listing](https://www.archlinux.org/packages/community/any/catch2/))
* Operating System: **Manjaro Linux v. 17.1.11** (a derivative of Arch)
* Compiler+version: **gcc version 8.1.1 20180531 (GCC)**

**Comment by go2sh** [comment]
I stumbled on the same problem. Arch installs the files in the "catch" subfolder not the "catch2" subfolder in the include folder.

**Comment by horenmar** [comment]
That one is on us. While the `single_include` folder is kept stable between releases, so you can always checkout master and use the latest release, the documentation is updated alongside commits that change things. This means that the current documentation does not match Catch version 2.2.3, but rather 2.?.? (the next released version).

The next release contain reworked CMake and pkg-config support, which includes changes to use `<catch2/catch.hpp>` path, but the last one does not.

**Comment by go2sh** [comment]
Ah I see the problem. I added a symlink, so that i don't have to change every test file in the future.

**Comment by asi14** [comment]
`catch2` now works on Arch, so I'm closing this issue. Thanks!

**Comment by horenmar** [comment]
Good to hear. 👍
