### ISSUE TITLE
How to check for a 'maybe' situation?

### ISSUE THREAD

**Issue by hakkidogusan** [catchorg/Catch2#1340]
Hi,

I'm currently using [!mayfail], but it affects all checks.
Is adding a MAYBE macro considered already?

--
Regards,
Hakki Dogusan

**Comment by hakkidogusan** [comment]
Use CHECK_NOFAIL

**Comment by JoeyGrajciar** [comment]
@hakkidogusan does that mean that this issue can be closed?
