### ISSUE TITLE
Wrong source line number in Catch2 ouput.

### ISSUE THREAD

**Issue by xkbeyer** [catchorg/Catch2#1342]
## Description

The line number of some test checks are wrong. It happens only in debug mode and in certain combinations.
The failures do appear in all reporter.

### Steps to reproduce
The solution has two files:

File 1:
```
//============================================================================
// 
// 
// 
// 
// 
//============================================================================

#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include <iostream>

namespace CatchUnitTest {
TEST_CASE("Simple test case", "[tag]")
{
   REQUIRE(9 == 0);
}

}
```

File 2:
```
#include <cstdlib>
#include <cstdio>
#include "catch.hpp"

namespace CatchUnitTest {

TEST_CASE("Warn", "[Logging]")
{
   CHECK(false); 
}

}
```

The solution is build as Debug x64.

The output looks like:
```
<?xml version="1.0" encoding="UTF-8"?>
<Catch name="CatchUnitTest.exe">
  <Group name="CatchUnitTest.exe">
    <TestCase name="Warn" tags="[Logging]" filename="c:\develop\src\tt\catchunittest\loggingmacros.cpp" line="7">
      <Expression success="false" type="CHECK" filename="c:\develop\src\tt\catchunittest\loggingmacros.cpp" line="9">
        <Original>
          false
        </Original>
        <Expanded>
          false
        </Expanded>
      </Expression>
      <OverallResult success="false"/>
    </TestCase>
    <TestCase name="Simple test case" tags="[tag]" filename="c:\develop\src\tt\catchunittest\testrunnertest.cpp" line="14">
      <Expression success="false" type="REQUIRE" filename="c:\develop\src\tt\catchunittest\testrunnertest.cpp" line="9">
        <Original>
          9 == 0
        </Original>
        <Expanded>
          9 == 0
        </Expanded>
      </Expression>
      <OverallResult success="false"/>
    </TestCase>
    <OverallResults successes="0" failures="2" expectedFailures="0"/>
  </Group>
  <OverallResults successes="0" failures="2" expectedFailures="0"/>
</Catch>
```

The `REQUIRE()` in `TEST_CASE("Simple test case", "[tag]")` is reported as on line 9 but it is on line 16. However the line number of the TEST_CASE itself is correct.

If needed I can upload the whole solution, just let me know.  

### Extra information
* Catch version: **v2.2.3**
* Operating System: **Win10 64 bit**
* Compiler+version: **VS2017**

**Comment by horenmar** [comment]
Sounds like a repeat of #881, which was a 3rd party bug.

The bad news is [that we have already reported it to Microsoft and it was closed as "low priority"](https://developercommunity.visualstudio.com/content/problem/58656/erroneous-line-expansion-in-semi-complex-macroized.html). If you want, you can try to revive the bug report on MS's side.

**Comment by xkbeyer** [comment]
Yeah. that is exactly the same bug. Before opening this issue I searched for a similar. Ok I have to improve my search skills ;)
That is an interesting attitude of MS false information as not so important to regard:(

**Comment by xkbeyer** [comment]
I think it is up to me to close this issue.

**Comment by horenmar** [comment]
We reap resolved issues after a month, but we generally prefer if the original user closes them.
