### ISSUE TITLE
Sharing a variable in two WHEN() scopes

### ISSUE THREAD

**Issue by bradprob** [catchorg/Catch2#1344]
I try to create a shared object for some WHEN-scopes like this:
```
SCENARIO("FOO")
{
   AClass obj();

   GIVEN("Some situation")
   {
      WHEN("change the state obj")
       {
            obj.firstnumber = 5;
            THEN("check it")
             {
                    REQUIRE(obj.firstnumber == 5);
             }
       }

        WHEN("change the state of obj again")
        {
               obj.secondnumber = 5;
               THEN("both changes are visible here")
                {
                     REQUIRE(obj.firstnumber == obj.secondnumber)
                }
        }
   }
}

```
I discovered that Catch2 recreates obj for the second WHEN and the second REQUIRE does never become valid. I tried putting initializing obj in GIVEN scope, but the result is the same. 

How can I share an object between two WHEN scopes?

**Comment by ArekPiekarz** [comment]
I haven't checked it, but try putting the second WHEN in the scope of the first WHEN.

**Comment by horenmar** [comment]
Fundamentally, sections do not work like that. `SECTION`s (and thus also various BDD-macros like `GIVEN`, `WHEN` and `THEN`) are processed inside the test case in a DFS order. What this means is that this `TEST_CASE`

```cpp
TEST_CASE("Foo") {
    std::cout << "1,";
    SECTION("A") {
        std::cout << "A,";
        SECTION("a") {
            std::cout << "a";
        }
        SECTION("b") {
            std::cout << "b";
        }
    }
   SECTION("B") {
        std::cout << "B";
    }
}
```
Will be run 3 times, and it will output "1,A,a", "1,A,b" and "1,B".


For your use case, Arek is right. You can just nest the two `WHEN` macros.
