### ISSUE TITLE
Is it possible to make a TEST_CASE a friend of my class? 

### ISSUE THREAD

**Issue by TrueWodzu** [catchorg/Catch2#1345]
Hello,

So I would like to test my private methods and I've read the discussion [here](https://github.com/catchorg/Catch2/issues/258). However, discussion never answers the question that @cseed asked in the first place. 

His question was: _" I'm happy to use a friend declaration, but I don't see how to refer to the test case."_

So I would like to repeat that question, is it possible to make a TEST_CASE or the whole CATCH a friend of my class?

I would like to avoid discussion whether testing private methods is good or bad. I think enough have been said in this matter already. So please try to refrein from it and just focus on the question itself, thank you:)

**Comment by philsquared** [comment]
You can either add a friend function, put your test code in there, and have your `TEST_CASE` forward on to it, or add friends that forward the values you want to test, so the test case has access via them.

Either way, if you only _implement_ the friend functions in the test project then only the test case has the privileged access.

All my usual warnings (which you've read) about not doing this most of the time apply - but I agree it is sometimes a necessary evil. As with most necessary evils the trick is in containing it as much as possible.

**Comment by TrueWodzu** [comment]
@philsquared Thanks for prompt response and valuable advice.

**Comment by Tyrben** [comment]
> You can either add a friend function, put your test code in there, and have your `TEST_CASE` forward on to it, or add friends that forward the values you want to test, so the test case has access via them.
> 
> Either way, if you only _implement_ the friend functions in the test project then only the test case has the privileged access.
> 
> All my usual warnings (which you've read) about not doing this most of the time apply - but I agree it is sometimes a necessary evil. As with most necessary evils the trick is in containing it as much as possible.

This could be a feature of catch... to implement a `class TEST_FRIEND` that can be mentioned in a friendship wherever I want.

**Comment by TrueWodzu** [comment]
> This could be a feature of catch... to implement a `class TEST_FRIEND` that can be mentioned in a friendship wherever I want.

That is not a bad idea. I think a friend class is a bit better than a friend function anyway, because if I have multiple tests for various private functions I would have to define multiple friend functions, and that is a lot of boiler plate code that the class under test must have. In case of a friend class, this is simpler - it just a one additional line of code in a class declaration.
