### ISSUE TITLE
Allow alternatives/boolean functions in REQUIRE

### ISSUE THREAD

**Issue by Flamefire** [catchorg/Catch2#1349]
I want the following to work:

`REQUIRE(foo == 1 || foo == 2)`

Currently this throws a compilation error like `error: value of type 'const BinaryExpr<const long &, const int &>' is not contextually convertible to 'bool'` or `error: value of type 'ExprLhs<bool>' is not contextually convertible to 'bool'` when putting the equalities into parens.

**Comment by horenmar** [comment]
No.

We intentionally don't support expression decomposition for expressions containing logical AND or OR. The main reason for it is that we cannot emulate the built-in short-circuiting rules, but there are also some secondary ones.

However, you can opt-out of the expression decomposition by placing your expression inside parentheses, like so:

```cpp
REQUIRE( (foo == 1 || foo == 2) );
```

or, in case of logical AND, use multiple assertions:

```cpp
REQUIRE(expr1);
REQUIRE(expr2);
REQUIRE(expr3);
// is equivalent with
REQUIRE( (expr1 && expr2 && expr3) );
```

**Comment by JoeyGrajciar** [comment]
this might be closed since the enforcement is in master?
