### ISSUE TITLE
Does Catch2 require the executable to be passed in the argc/argv?

### ISSUE THREAD

**Issue by dubnde** [catchorg/Catch2#1355]
## Description
The semihosted RISC-V embedded setup I am trying to use Catch2 does not pass the programming executable as the first etnryinto argv. I am seeing Catch2 crash https://github.com/catchorg/Catch2/blob/master/single_include/catch2/catch.hpp#L6670

### Steps to reproduce

- Build single header version for SiFive Eclipse RISC-V project
- Run the simple tutorial on the platform
- Crash at https://github.com/catchorg/Catch2/blob/master/single_include/catch2/catch.hpp#L6670

### Extra information
Trying this on the SiFive FE310-G000 RISC-V development platform for first time.

* Catch version: **v2.3.0**
* Operating System: **[µOS++ IIIe](https://github.com/micro-os-plus/micro-os-plus.github.io)**
* Compiler+version: **riscv-none-embed-g++.exe (GNU MCU Eclipse RISC-V Embedded GCC, 64-bits) 7.2.0**

**Comment by zwcloud** [comment]
You can [use fake `argc` and `argv`](https://github.com/catchorg/Catch2/issues/1352#issue-347247524). And call the fake main entry function from somewhere else.

**Comment by dubnde** [comment]
thanks. will give that a try. 

Does Catch actually use the executable path/name? Does one actually need to pass the executable in `argv[0]`? Would it be a problem if I passed `argc=0` and therefore `argv=NULL`?

**Comment by zwcloud** [comment]
> Does Catch actually use the executable path/name? Does one actually need to pass the executable in argv[0]? Would it be a problem if I passed argc=0 and therefore argv=NULL?

Yes, it needs argv[0]. An error will occur when argv=NULL. That's why I uses a `"whatever"` argument.

**Comment by horenmar** [comment]
Strictly speaking, Catch does not need `argv[0]` to function. The only place where the executable name is used is composing help string for the executable.

**Comment by dubnde** [comment]
okay. so it does need the `rgv[0]` to be valid.
