### ISSUE TITLE
Feature Request: STATIC_REQUIRE macro

### ISSUE THREAD

**Issue by parnmatt** [catchorg/Catch2#1356]
I've just starting using Catch2, and find it very expressive.

There are some tests that can be done at compile time; for example I am writing an adapter library and need to test if two types are implicitly convertible.

I could use `REQUIRE(std::is_convertible_v<A, B>);` which fits in nicely with this test framework.
However the argument is known at compile time. I've found myself doing something like:

    static_assert(std::is_convertible_v<A, B>, "A should be convertible to B");
    SUCCEED("A and B are convertible");

Such that the static test is logged and documented, but done at compile time.

Could there be a macro be included to wrap around that?

    #define STATIC_REQUIRE(expression, message) {  \
        static_assert(expression, message);        \
        SUCCEED(message);                          \
    }

That way it's automatically statically tested, and logged. It would be nice for the expression to be in the output itself; which I guess can be emulated with:

    #define STATIC_REQUIRE(expression, message) {  \
        static_assert(expression, message);        \
        REQUIRE(expression);                       \
    }

which would actually test twice, once at compile time and once at run time; though it should be inexpensive as its likely to have been calculated at compile-time.

**Comment by martinmoene** [comment]
Perhaps you want to be able to also let `STATIC_REQUIRE` behave as the normal `REQUIRE` so that tests may continue where they otherwise would be stopped by a static assertion failure.

Using somewhat like this [here](https://github.com/martinmoene/kalman-estimator/blob/4fb1b74c6d99ab6544a64e87e1a43f12162c5719/test/matrix.t.cpp#L28)

**Comment by parnmatt** [comment]
I wasn't thinking that; however that's a fantastic idea, and simple to implement with a variable as you've shown.

That would be a great addition to this feature request.

**Comment by horenmar** [comment]
I like the idea, so I am open to getting the PR in. (I am gonna post feedback on that there)
