### ISSUE TITLE
Catch Framework

### ISSUE THREAD

**Issue by VidhiRajgor** [catchorg/Catch2#1359]
Description

How to use GENERATORS in Catch Framework?
I am using Catch2 for my project. Can we use GENERATERS for testing multiple inputs ?
Other than GENERATORS is there any other option to run test with multiple inputs ?

* Catch version: Catch2
* Operating System: Linux

**Comment by JoeyGrajciar** [comment]
Generators recently entered final state. Documentation about there usage and with links to examples is [here](https://github.com/catchorg/Catch2/blob/master/docs/generators.md).

> Can we use GENERATERS for testing multiple inputs ?

Yes Generators were designed for that purpose.

> Other than GENERATORS is there any other option to run test with multiple inputs ?

No. Generators are only way how to generate multiple inputs for value parametrized tests.

**Comment by JoeyGrajciar** [comment]
@VidhiRajgor In case you do not have more questions I will close this issue in few days.
