### ISSUE TITLE
Feature Request: Force '--break' if IsDebuggerPresent()

### ISSUE THREAD

**Issue by andrew-gresyk** [catchorg/Catch2#1364]
## Description
For local development, setting '--break' to have Catch break into debugger on assertion failure, is still a bit of a hassle.
E.g. with Visual Studio debug settings are stored in the local *.user file, and with multiple projects ensuring the flag is always set on branch merges is a bit annoying.

Alternatively, if debugger is attached (detection can be achieved with [`IsDebuggerPresent`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680345(v=vs.85).aspx) on Windows or [`some_black_magic()`](https://stackoverflow.com/questions/3596781/how-to-detect-if-the-current-process-is-being-run-by-gdb#24969863) on Linux), '--break' can forced in runtime.

**Comment by horenmar** [comment]
No.

Catch already knows how to detect debugger on Windows/Linux/OS X, but we intentionally don't break into the debugger when it is present, to provide the user with greater control over what happens (e.g. the user might have their own set of breakpoints in their own code to find another issue).

**Comment by andrew-gresyk** [comment]
No problem, I'll do it in my branch.
