### ISSUE TITLE
Delay finding Python interpreter

### ISSUE THREAD

**Issue by Morwenn** [catchorg/Catch2#1374]
## Description
I noticed that the CMake command `find_package(PythonInterp)` is run before checking whether we need to build the self-tests, which on my computer ends up with the following warning since there is no Python interpreter configured (when using Catch2 as a sub-project):

> -- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)

Since I was drowning into other errors I wondered at the time whether this warning affected my issues, then I realized that it only mattered when building the self-tests and not when using Catch2 as a CMake sub-project.

Couldn't the `find_package` be nested into the following condition so that the warning only occurs when trying to build the self-tests?

### Steps to reproduce
I use [DownloadProject](https://github.com/Crascit/DownloadProject) from my testsuite's CMakeLists.txt to fetch the latest version of Catch2, then I call `add_subdirectory` on the resulting directory before declaring `Catch2::Catch2` as library used by my testsuite.

Considering the CMakeLists.txt in the main Catch2 repository, it should happen whenever Catch2 is used as a CMake sub-project anyway.

### Extra information
* Catch version: **v2.3.0**

**Comment by horenmar** [comment]
I wanna say that every programming env should have Python installed, but I agree that there is no good reason to require it.

**Comment by Morwenn** [comment]
Thanks for the fast fix :)
