### ISSUE TITLE
std::queue not changing size after push in test case

### ISSUE THREAD

**Issue by syntactical** [catchorg/Catch2#1378]
## Description
I'm writing a test that involves pushing items to a queue:

```
TEST_CASE( "strings are returned as-is", "[multi-file:2]" ){
    Parser parser;

    LettersGroupToken t("abcdef");

    std::queue<Token*> tokens;
    tokens.push(&t);

    std::vector<std::string> items = parser.parse(tokens);

    REQUIRE( items.size() == 1 );
    REQUIRE(items[0] == "abcdef" );
}
```

My issue is with `tokens.push(&t);`.  It does not change the size of the queue `tokens`.  After the `push` operation the size of `tokens` is zero.  The same behavior happens when using `emplace`.

I've tried using a vector instead of a queue, and `push_back` works as intended, changing the size of the vector.  I need to use a queue though...

Other things I've tried:
* Defining `CATCH_CONFIG_MAIN` in the same file as this test case - still seeing this error
* Defining `CATCH_CONFIG_MAIN` in another file - still seeing this error
* Removing `[multi-file:2]` tag - still seeing this error
* Changing to `std::queue<int>` - still seeing this error

**BUT,** moving this code to a `main` method of the program made the bug go away - the queue behaved as normal.

... really confused! :(

### Extra information

This is the actual error I'm getting in the CLion test runner:

```
/fakepath/test/ParserTest.cpp:14: Failure:
fatal error
Process finished with exit code 132 (interrupted by signal 4: SIGILL)
```

* Catch version: **v2.3.0**
* Operating System: **macOS High Sierra**
* IDE: **CLion 2018.2.2**
* Compiler+version: **Whatever default C++ compiler used by XCode 9.4.1**

**Comment by syntactical** [comment]
Never mind-- this looks like it's a bug in CLion that makes it impossible to inspect certain containers when running tests.

**Comment by horenmar** [comment]
Ok, thanks for reporting back.
