### ISSUE TITLE
What macros should I use with rapidcheck?

### ISSUE THREAD

**Issue by KingDuckZ** [catchorg/Catch2#1382]
Hi, I'm playing around with rapidcheck and I wonder if I'm using it the right way with Catch2. Their readme says that any macro throwing an exception can be used, but I'm not having much luck with CHECK.

As an example, I have:

```
TEST_CASE("my test", "[test]") {
    rc::check(
        "do something",
        [](const std::vector<int>& vec) {
            auto a = vec;
            //a.push_back(10);
            RC_ASSERT(a == vec);
        }
    );
}
```

However if I uncomment the push_back line and make the test fail, the final executable will still report "All tests passed". If I use CHECK instead, then I get tons of failures as rapidcheck doesn't bail out after the first failure. Is there any other macro (from rapidcheck or Catch2) that I'm not aware of? What's the right way to achieve this in Catch2?

**Comment by horenmar** [comment]
`CHECK` family of assertions does not throw, as they are not meant to abort test execution.
`REQUIRE` family of assertions throws, because they are meant to abort the test execution.

If I understand your question correctly, you want to use `REQUIRE` instead of `CHECK`.

**Comment by KingDuckZ** [comment]
horenmar gotcha, no CHECK with rapidcheck :) it should be easy to remember!
