### ISSUE TITLE
Unclear how to install Catch2 system-wide

### ISSUE THREAD

**Issue by danilcha** [catchorg/Catch2#1383]
The documentation says that you can install Catch2 using the OS package manager. It then shows example of how to use such installed Catch2 in CMake by using `find_package`.

However, it never explains how to install it and which OS's have it. For instance, Homebrew in macOS usually has everything, but it does not have Catch2 (nor Catch). Ubuntu 16.04 also hasn't heard of it.

So, how to use `find_package` in CMake to find Catch2?

**Comment by horenmar** [comment]
I am going to answer the question from the title first. If your package manager does not provide Catch2 package (e.g. Ubuntu 16.04 does provide Catch as `catch` but only in version 1.2.0), and you have enough rights to install Catch2 globally, you can do this:

```sh
$ git clone https://github.com/catchorg/Catch2.git
$ cd Catch2
$ cmake -Bbuild -H. -DBUILD_TESTING=OFF
$ sudo cmake --build build/ --target install 
```

If you don't want to install Catch2 globally, you will need to read up on [`CMAKE_INSTALL_PREFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) and [`find_package`](https://cmake.org/cmake/help/latest/command/find_package.html) (specifically the part about `PATHS` argument).

**Comment by danilcha** [comment]
Thank you! This instruction in not in the documentation, or I did not find it?

**Comment by danilcha** [comment]
By the way, what does `-H.` stands for? A [man page](https://cmake.org/cmake/help/v3.5/manual/cmake.1.html) of CMake says it is for displaying the help.

**Comment by horenmar** [comment]
This is not in the documentation because it falls under the umbrella of "basic CMake usage" -- all the commands did was

1) Clone Catch
2) Generate build using CMake
3) Run the `install` step of the build using CMake.

I'll think about whether it is worth adding it to our documentation.

Anyway, `-H.` means "look for CMakeLists in `.`, which means the current folder". Strictly speaking it is an internal flag (along with `-B<dir>`), but it is too useful not to use.

**Comment by danilcha** [comment]
I think it should be in the documentation because the majority of CMake users do not know CMake that well. I was very surprised to find out that Catch2 has the `install` target and that it is something common to every CMake project to the point that it is not even mentioned in the documentation.

Thanks for the explanation!

**Comment by greggwon** [comment]
> I am going to answer the question from the title first. If your package manager does not provide Catch2 package (e.g. Ubuntu 16.04 does provide Catch as `catch` but only in version 1.2.0), and you have enough rights to install Catch2 globally, you can do this:
> 
> ```shell
> $ git clone https://github.com/catchorg/Catch2.git
> $ cd Catch2
> $ cmake -Bbuild -H. -DBUILD_TESTING=OFF
> $ sudo cmake --build build/ --target install 
> ```
> 
> If you don't want to install Catch2 globally, you will need to read up on [`CMAKE_INSTALL_PREFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) and [`find_package`](https://cmake.org/cmake/help/latest/command/find_package.html) (specifically the part about `PATHS` argument).

Installing this way still did not allow me to build cppzmq successfully with the package visible in /usr/local on my Mac.  Is there some way to watch cmake resolve dependencies that would show what directories it's looking in?

**Comment by d7dsem** [comment]
I am try to use in it on Windows

And some steps doesn't have sens to me. 

For example "install on system" (i think its some like add some folder to PATH variable? but what i have to add)

Cloned repositoty on PC.
Build as 
`
cd build/release
cmake ../.. -DCMAKE_BUILD_TYPE=Release
cmake --build .
`

`
cd build/debug
cmake ../.. -DCMAKE_BUILD_TYPE=Debug
cmake --build
`

And what next step?

After that constructioon is not cortrect. 
`#include <catch2/catch_test_macros.hpp>`

There have to be some step whta is clear for experienced user but not for me((
