### ISSUE TITLE
_GLIBCXX_DEBUG causing runtime failure when --order rand

### ISSUE THREAD

**Issue by thomasfanell** [catchorg/Catch2#1384]
## Description

If `_GLIBCXX_DEBUG` is defined during compilation, the following runtime error occur when the test executable is invoked with `--order rand`:
```
/usr/include/c++/7/debug/safe_container.h:83:
Error: attempt to self move assign.

Objects involved in the operation:
    sequence "this" @ 0x0x55d377712c78 {
      type = __gnu_debug::_Safe_container<std::__debug::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_debug::_Safe_sequence, true>;
    }
Aborted (core dumped)
```

### Steps to reproduce

**Code**
```c++
// main.cpp
#define CATCH_CONFIG_RUNNER
#include "catch.hpp"
TEST_CASE("A", "[bug]") { SECTION("a") { REQUIRE(true); } }
TEST_CASE("B", "[bug]") { SECTION("b") { REQUIRE(true); } }
TEST_CASE("C", "[bug]") { SECTION("c") { REQUIRE(true); } }
TEST_CASE("D", "[bug]") { SECTION("d") { REQUIRE(true); } }
TEST_CASE("E", "[bug]") { SECTION("e") { REQUIRE(true); } }
TEST_CASE("F", "[bug]") { SECTION("f") { REQUIRE(true); } }
int main(int argc, char* argv[])
{
    return Catch::Session().run(argc, argv);
}
```
**Compile and run**
- `g++-7 -std=c++14 -g -D_GLIBCXX_DEBUG main.cpp && ./a.out --rng-seed time --order rand`
- `clang++-5.0 -std=c++14 -g -D_GLIBCXX_DEBUG main.cpp && ./a.out --rng-seed time --order rand`

### Extra information

* Catch version: **v2.4.0** (v2.2.2 fails too)
* Operating System: **Ubuntu 18.04 LTS**
* Compiler+version: **g++ 7.3.0**, **clang 5.0.1**

**Comment by horenmar** [comment]
[As far as I can tell, this is a bug in libstdc++](https://stackoverflow.com/questions/22915325/avoiding-self-assignment-in-stdshuffle/23691322). Depending on your PoV, it is either bug in the debug checker, or in its implementation of `std::shuffle`. Either way, I consider this a 3rd party bug that is not worth a workaround.

**Comment by thomasfanell** [comment]
It seems you're right. I must admit I managed to completely miss that SO post. I suppose we'll have to redirect `__glibcxx_check_self_move_assign` for now. Thanks for the link and my apologies for wasting your time.

**Comment by horenmar** [comment]
Not a problem.
