### ISSUE TITLE
Approx::epsilon documentation issue

### ISSUE THREAD

**Issue by mattgodbolt** [catchorg/Catch2#1388]
According to https://github.com/catchorg/Catch2/blob/master/docs/assertions.md "epsilon - epsilon serves to set the percentage by which a result can differ from Approx's"

But in the code:
```
Approx& epsilon( T const& newEpsilon ) {
            double epsilonAsDouble = static_cast<double>(newEpsilon);
            if( epsilonAsDouble < 0 || epsilonAsDouble > 1.0 ) {
                throw std::domain_error
                    (   "Invalid Approx::epsilon: " +
                        Catch::Detail::stringify( epsilonAsDouble ) +
                        ", Approx::epsilon has to be between 0 and 1" );
            }
            m_epsilon = epsilonAsDouble;
            return *this;
        }
```

I've had actual production issues fall out from people disagreeing on the meaning of "percentage" (vs "ratio"). For me it's clear: percentages go from 0 to 100 and ratios are 0 to 1. It _seems_ like catch2 uses a ratio-based epsilon. Rather than just open a PR I'd prefer to discuss to make sure I get the real intent :smile:

**Comment by horenmar** [comment]
The intent is easy enough, setting `epsilon` as `0.5` should provide 50% worth of margin for the comparison. As to the wording, I don't mind changing it, but I think I prefer "coefficient" to either of "percentage" and "ratio".
