### ISSUE TITLE
If the last section fails, the test is re-run once more

### ISSUE THREAD

**Issue by nikola-benes** [catchorg/Catch2#1389]
## Description

It seems that if the last SECTION inside a TEST_CASE fails (i.e. contains a false assertion), the TEST_CASE is run once more, this time bypassing all the sections. Is this expected behaviour?

### Steps to reproduce

```
TEST_CASE("X") {
    // this part is executed twice
    SECTION("A") {
        REQUIRE(false);
    }
    // this part is executed once
}
```

### Extra information

* Catch version: **v2.4.0**
* Operating System: **Arch Linux**
* Compiler+version: **clang-6.0 with libstdc++**

**Comment by philsquared** [comment]
Unfortunately, yes. The reason is that Catch/2 is discovering sections as it runs them. If the last section fails it doesn't know if there are any more after it - so needs to run again to see.

**Comment by horenmar** [comment]
Yeah, this is not really possible to fix.

**Comment by JoeyGrajciar** [comment]
Closing based on last comment
