### ISSUE TITLE
If a specific section is specified, actually two test runs are carried out

### ISSUE THREAD

**Issue by Weeena** [catchorg/Catch2#1394]
## Description
If I like a test in a specific section to be run, I can do this with this command:
`./MyExe Test -c sa`

Surprisingly, this causes two test runs:
1. Test "Test" with section "sa"
2. Test "Test" without any sections

Is there a reason for the second empty test run? In my application where the initialisation for the test case is lengthy this behaviour is inconvenient.

### Steps to reproduce
Put some log output in the test case "Test" outside any sections.

**Comment by horenmar** [comment]
I agree, that shouldn't happen by default.

Is section "sa" failing? (basically, does it run into the same problem #1389 does?)

**Comment by Weeena** [comment]
No, section "sa" is not failing. (I saw issue  #1389 before I opened this new issue and, at first sight, it seemed similar. But because "sa" was not failing I thought this would be something different.)

**Comment by horenmar** [comment]
Then this is a bug, the first run should provide all the information we need to avoid doing a second one.
