### ISSUE TITLE
Exit code goes against Unix conventions - breaks basic assumptions

### ISSUE THREAD

**Issue by jamesfrullo** [catchorg/Catch2#1410]
## Description
When your run your unit test with "-l" or "--list-test-names-only", the exit code of the process is the number of tests. This is quite incorrect behavior on any Unix operating system. A non-zero exit code indicates the program could not perform its intended function. It is reasonable for a tool that runs the program to assume that something went wrong with listing tests, and indeed, I'm using Catch in a framework that assumes exactly that. Furthermore, exit codes above 128 are supposed to have special meaning, and the exit code may not exceed 255. See here, for example:
https://www.tldp.org/LDP/abs/html/exit-status.html

Please fix this to have the test runner exit 0 if there is, in fact, no error.

### Steps to reproduce
Simply build and run any catch unit test with "-l" or "--list-test-names-only".

### Extra information
* Catch version: v2.4.1
* Operating System: Linux
* Compiler+version: GCC 5.4

**Comment by horenmar** [comment]
#1146 

The TL;DR version is that it won't be changed until next major version.

**Comment by hpesoj** [comment]
This is not only a problem when using `-l`, but also when tests fail. I have left a comment on #1146.
