### ISSUE TITLE
EventListener does not support verbosity other than "normal"

### ISSUE THREAD

**Issue by hlindberg** [catchorg/Catch2#1426]
## Description
`TextEventListenerBase` only supports verbosity "normal" and can not be used with a Report Processor that supports other verbosities and using one that is not `-v normal`.

### Steps to reproduce
Define a report processor that accepts verbosities other than "normal" - i.e. this way:
```cpp
 static std::set<Catch::Verbosity> getSupportedVerbosities() {
    return { Catch::Verbosity::Quiet, Catch::Verbosity::Normal, Catch::Verbosity::High};
}
```
This report processor will then accept runs with `-v quiet` and `-v high` (as well as `-v normal`).

When also adding an Event Listener. It no longer works to run with `-v high` or `-v quiet`. The result
is that the message `Verbosity level not supported by this reporter` is printed.

It is not possible to define the `getSupportedVerbosities` in the event listener since the base class
that is required does not support parametrization. 

I tried this:
```cpp
struct GlobalStateGuard : Catch::TestEventListenerBase {

private:
    char* tz_env_before   = NULL;

public:
    using TestEventListenerBase::TestEventListenerBase; // inherit constructor

    // This is called before any tests are executed. Use this method to record
    // any global state that needs to be reset after each test.
    //
    // This implementation manages timezone and TZ environment variable
    //
    void testRunStarting(Catch::TestRunInfo const& testRunInfo) override {
        // remember the TZ in effect
        tz_env_before = getenv("TZ");
        // Cause side effects of setting TZ (timezone and other external variables are set).
        tzset();
    }

    void testCaseEnded( Catch::TestCaseStats const& testCaseStats ) override {
        // Reset timezone and cause side effects (setting external timezone etc) by
        // calling tzset. It is ok if tz_env_before is NULL - that is taken as UTC.
        //
        setenv("TZ", tz_env_before, 1);
        tzset();
    }

    /*  Must state it accepts all verbosities or it will fail with verbosity
     * is something other than "normal"
     */
    static std::set<Catch::Verbosity> getSupportedVerbosities() {
        return { Catch::Verbosity::Quiet, Catch::Verbosity::Normal, Catch::Verbosity::High};
    }

};
CATCH_REGISTER_LISTENER( GlobalStateGuard )
```
And the `getSupportedVerbosities` has no effect since the framework will call the default
version of that method in `StreamingReporterBase<TestEventListenerBase>`

If I patch `StreamingReporterBase<TestEventListenerBase>` and include
the static `getSupportedVerbosities` there - it works using `-v high` and `-v quiet`

### Suggestion
Either make event listeners accept all verbosities (is perhaps the best, since why would it matter?), or make the base class for event listeners templated so it is possible to specify
that it supports different verbosities.

### Extra information
* Catch Version 2.4.1

**Comment by horenmar** [comment]
Yeah, the current verbosities system wasn't well thought through and it will be gone on next breaking release.

For now, I am going to make the base class for event listeners return that it accepts all verbosities, because, as you rightly note, there is no reason event listeners should adhere to reporting verbosities when they aren't supposed to _report_ anything.

**Comment by hlindberg** [comment]
Excellent! Thanks for the quick fix!
