### ISSUE TITLE
Unexpected behaviour of Approx().epsilon(eps)

### ISSUE THREAD

**Issue by zyth0s** [catchorg/Catch2#1427]
## Description

I wrote a very simple unit test to check a floating point number using the 
gamma function. The standard library function `tgamma`, gives an approximate
value that is very close to be exact for small arguments, so I choose `10`.
The value `362879.9999999999` is approximately  `3628800.0`  within a very small error
`< 1e-9`. However, if I test equality with Approx giving a very large epsilon `1e-1` the test
still fails. It is like it were checking the first digit that differs from the correct result. Here
I attach the relevant portion:

```
  REQUIRE(tgamma(10) == Approx(3628800).epsilon(1e-1))
with expansion:
  362879.9999999999 == Approx( 3628800.0 )
```

### Steps to reproduce

The flags selected are the same as for the whole project

`-g -fstandalone-debug -Wall -DNDEBUG  -Ofast`

The whole test is simply 
```
#define CATCH_CONFIG_MAIN
#include "include/catch.hpp"

unsigned int Factorial( unsigned int n ) {
  return n > 1 ? Factorial(n - 1) * n : 1;
}

TEST_CASE( "Factorials are computed", "[factorial]") {
  REQUIRE( Factorial(0)  == 1);
  REQUIRE( Factorial(1)  == 1);
  REQUIRE( Factorial(2)  == 2);
  REQUIRE( Factorial(3)  == 6);
  REQUIRE( Factorial(10) == 3628800);
  REQUIRE( tgamma(10)    == Approx(3628800).epsilon(1e-1) );
}
```
### Extra information

* Catch version: **v2.4.2** Generated: 2018-10-26 21:12:29.223927
* Operating System: Opensuse 42.3 Leap
* Compiler+version: Clang 7.0

**Comment by zyth0s** [comment]
Sorry very much. It is completely my failure. Forgot to change the argument Factorial(i) == tgamma(i+1).

**Comment by horenmar** [comment]
No problem.
