### ISSUE TITLE
Behavior of `catch_discover_tests()` in case of missing dlls

### ISSUE THREAD

**Issue by jdumas** [catchorg/Catch2#1432]
Hi. I think I've hit a limitation of `catch_discover_tests()` on Windows when running some tests on AppVeyor. Due to a missing dll, I had a program that compiles just fine, but returns an error code `ERROR_DLL_NOT_FOUND: 0x00000485` at runtime due to a missing dll (the dll was compiled in a different directory than the `.exe` I was trying to run).

This is a problem since `cach_discover_tests()` seems to run the test program and [assumes](https://github.com/catchorg/Catch2/blob/master/contrib/CatchAddTests.cmake#L37) that a return code < 0 means an error, while > 0 indicates the number of tests that needs to be run. I would suggest to modify this behavior to always return an error code of 0 when successful, and produce a CMake error when the returned code is not 0.

In my particular situation what happened is that the returned code was > 0, but the stdout was empty so no tests were registered into CTest. Then of course, when calling `ctest ...` on AppVeyor no tests where run, but the build is still marked as successful!

**Comment by pantoss** [comment]
This also happens on other platforms too where an error occurs during init. https://github.com/catchorg/Catch2/issues/2268

Sadly I don’t see a simple solution to this either otherwise I would have tried to fix it.

**Comment by horenmar** [comment]
Same as with the linked issue, v3 has fixed this (listing tests no longer returns number of tests) and I don't have a good fix for v2 due to backwards compatibility.
