### ISSUE TITLE
Compile error on Embarcadero XE 10.2 (std::isnan)

### ISSUE THREAD

**Issue by simpleb13** [catchorg/Catch2#1438]
## Description

Embarcadero claims C++11 compatibility in their BCC32C and BCC64 compilers, but setting up a test project throws:

_[bcc64 Error] catch.hpp(11586): no member named 'isnan' in namespace 'std'_

### Steps to reproduce
Fails on build with CLang compiler, all default settings for both 32bit & 64bit apps.

### Extra information

It appears replacing _isnan_ with __isnan_ allows it to compile although I'm not knowledgeable enough yet to understand why.
Found the fix [here](https://forums.embarcadero.com/message.jspa?messageID=845620).

* Catch version: **v2.4.2**
* Operating System: **Windows 10 64bit Pro**
* Compiler+version: **CLang 3.3**

**Comment by horenmar** [comment]
The simple answer is that they did something terrible to their "C++11 compliant" library.

We can provide a polyfill over it, but it will take me at least until the end of the week before I have the time to do so.

**Comment by horenmar** [comment]
This should be fixed now
