### ISSUE TITLE
Catch fails to compile tests using function templates that work outside of Catch

### ISSUE THREAD

**Issue by gnbond** [catchorg/Catch2#1439]
## Description

Catch fails to compile some tests that use function templates that have the same name as templates in `std::`.   The same code works fine when compiled outside of catch.

This appears to be acting as if there was an implicit `using namespace std;` when run under Catch, but I understand the namespace lookups and template arguments can get a bit hairy and I don't profess to be an expert in this.

### Steps to reproduce
Consider the following file (cut down from a much larger problem that's had me scratching my head for a day or so):
``` c++
// same name as a function template in std::
template <typename I>
bool is_heap(I b, I e)
{
    return false;
}

#include <vector>

// a template that gets instantiated in Catch test and calls the above
template <typename T>
bool foo() {
    std::vector<T> a{10};
    return is_heap(a.cbegin(), a.cbegin()); // no std:: -> should be my private version above
}

int main() {
    return foo<int>();
}
```
I can compile and run this just fine.

If I replace the `main()` function with a Catch test:
``` c++
#include "catch.hpp"

TEST_CASE("is_heap") {
    CHECK_FALSE(foo<int>());
}
````

Then this fails to compile. My `is_heap<T>()` template is now ambiguous with `std::is_heap<T>()`.

Same failure occurs regardless of whether `CATCH_CONFIG_MAIN` is defined or not.
```
catch_bug.cpp: In instantiation of ‘bool foo() [with T = int]’:
catch_bug.cpp:31:5:   required from here
catch_bug.cpp:15:19: error: call of overloaded ‘is_heap(std::vector<int>::const_iterator, std::vector<int>::const_iterator)’ is ambiguous
     return is_heap(a.cbegin(), a.cbegin()); // no std:: -> should be my private version above
            ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
catch_bug.cpp:4:6: note: candidate: bool is_heap(I, I) [with I = __gnu_cxx::__normal_iterator<const int*, std::vector<int> >]
 bool is_heap(I b, I e)
      ^~~~~~~
In file included from /home/atlasdev/gcc/linux64/6.3.0/include/c++/6.3.0/bits/stl_algo.h:61:0,
                 from /home/atlasdev/gcc/linux64/6.3.0/include/c++/6.3.0/algorithm:62,
                 from catch.hpp:2739,
                 from catch_bug.cpp:27:
/home/atlasdev/gcc/linux64/6.3.0/include/c++/6.3.0/bits/stl_heap.h:519:5: note: candidate: bool std::is_heap(_RAIter, _RAIter) [with _RAIter = __gnu_cxx::__normal_iterator<const int*, std::vector<int> >]
     is_heap(_RandomAccessIterator __first, _RandomAccessIterator __last)
     ^~~~~~~
```
### Extra information

* Catch version: **v2.4.2**
* Operating System: **RHEL 7.3**
* Compiler+version: **g++ 6.3.0**

**Comment by horenmar** [comment]
The "implicit `using namespace std;` is called ADL. The problem is that the arguments to your unqualified call to `is_heap` are from `std` namespace, which means that it is searched for a matching `is_heap` as well.

The link with Catch is that we bring in `<algorithm>`, where `std::is_heap` lives: https://godbolt.org/z/ZJ8m6P

**Comment by gnbond** [comment]
Cool, thought it might be something like that.

This [Wikipedia article](https://en.wikipedia.org/wiki/Argument-dependent_name_lookup) and the [working paper by Herb Sutter](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2006/n2103.pdf)  linked from there were most helpful, and now I am somewhat less unenlightened.

Thanks!
