### ISSUE TITLE
--list-tests --reporter xml combo would be helpful

### ISSUE THREAD

**Issue by matepek** [catchorg/Catch2#1447]
## Description
It would be nice to have getting the test list in xml format.
The current one is hardly parseable. [Here](https://github.com/matepek/vscode-catch2-test-adapter/issues/21) is an issue which could be easily solved with it.

Especially file names with spaces and dashes are tricky now.

**Comment by horenmar** [comment]
This has already been planned (see branch `dev-m3-list-rework), but for backward compatibility reasons won't happen until the next major release.
