### ISSUE TITLE
Cherrypick BDD AND_GIVEN based macros into Branch Catch1.x

### ISSUE THREAD

**Issue by svdHero** [catchorg/Catch2#1451]
## Description
In #1363 the AND_GIVEN macro was added to the master branch.

This seems to be a small change in code with a great benefit for nested BDD style tests. Could this macro be added/cherrypicked to the Catch1.x branch, too? For those of us who are still stuck with Catch1, e.g. due to Visual Studio 2013. :-/ 

That would be awesome!

**Comment by horenmar** [comment]
Sorry, but Catch v1 is very much EOLed. I might be convinced to review and merge a PR, but I am not planning to do the work cherry-picking the changes by myself.

**Comment by horenmar** [comment]
Since it has been almost 4 weeks, I am going to close the issue until further follow-up
