### ISSUE TITLE
Command line option to log start of tests

### ISSUE THREAD

**Issue by schoetbi** [catchorg/Catch2#1453]
## Description
I have tests that sometimes do crash the pc. Now it is very difficult to find the causing test. If I had a way to write the last started test in a file I would have a way to find that out.

## Implementation

There are several ways to do this:

### Implement a listener in my application

I could to that but it is not avery generic way and others would have to reimplement this feature over and over agein.

### Register a Listener via a command line option

Register a new listener "CaptureTestStart" with a new command line option:

`--TestStartLogFile <filename>`

It is very important that this listener flushes before the actual test starts.

**Comment by Saarg** [comment]
I've used -d yes to display the tests as they are run and find what test is crashing/hanging

**Comment by horenmar** [comment]
> I could to that but it is not avery generic way and others would have to reimplement this feature over and over agein.

I don't think many people have tests that crash their PC...

Anyway, as you said you can implement it yourself, and you can also throw something together via `-r compact -o <filename> --order lex` and looking for the last finished test, if you don't want to do that.
