### ISSUE TITLE
TEMPLATE_TEST_CASE does not support template templates

### ISSUE THREAD

**Issue by porpoises** [catchorg/Catch2#1454]
## Description
TEMPLATE_TEST_CASE only supports substitution of simple types, and not template templates.

### Steps to reproduce

```cpp
template <template <typename> typename T>
struct Foo { };

TEMPLATE_TEST_CASE("instantiate a template template with int", "", Foo) {
     using T = TestType<int>;  // ... or something
}
```

**Comment by JoeyGrajciar** [comment]
@porpoises in your example you wanted to do probably
```c++
template<typename T>
struct Foo {};
```
in linked PR #1457 i added support for this kind of types. For this kind of tests you will have to use
`TEMPLATE_TEMPLATE_TEST_CASE`.
