### ISSUE TITLE
Promote Conan Package on Conan Center

### ISSUE THREAD

**Issue by uilianries** [catchorg/Catch2#1461]
## Description

Now that we have Catch2 available on Bintray, it can be promoted to the [Conan Center](https://bintray.com/conan/conan-center) repository, where all official packages are available.

https://bintray.com/catchorg/Catch2/Catch2%3Acatchorg

To be promoted on Conan Center 2 steps are required:

1) Update Bintray page with package info:
  - Add project logo (optional)
  - description: "A modern, C++-native, header-only, test framework for unit-tests, TDD and BDD - using C++11, C++14, C++17 and later (or C++03 on the Catch1.x branch)"
  - licenses: BSL-1.0
  - tags: same from github (cpp11, testing, test-framework, tdd)
  - maturity: Official
  - website: https://github.com/catchorg/Catch2
  - Issues tracker: https://github.com/catchorg/Catch2/issues
  - Version control: https://github.com/catchorg/Catch2
  - GitHub repo: catchorg/Catch2

You could take as example the [Bincrafters' Catch2 package](https://bintray.com/bincrafters/public-conan/catch2%3Abincrafters). This package will be deprecated as soon as the official Catch2 be available on Conan Center.

2) Request Conan Center inclusion
  - Click on "Add to Conan Center" button
  ![](https://screenshotscdn.firefoxusercontent.com/images/2a180408-7626-41a8-bbe4-f6057342bddb.png)

Regards!

/cc @danimtb

**Comment by horenmar** [comment]
Interesting, I would expect e.g. the logo to be used from the `catchorg/Catch2` repo already

**Comment by uilianries** [comment]
sure, you can use the same :smile_cat:

**Comment by horenmar** [comment]
Should be done.

**Comment by uilianries** [comment]
Great!

@danimtb Could you review on Bintray, please?

**Comment by horenmar** [comment]
As far as I can tell, this is done.

**Comment by uilianries** [comment]
Yes! Thank you!
