### ISSUE TITLE
With CATCH_CONFIG_DISABLE_EXCEPTIONS the single-header still references exception handling functionality

### ISSUE THREAD

**Issue by nagisa** [catchorg/Catch2#1462]
## Description

When Catch2 (v2.5.0 tag) is used with `CATCH_CONFIG_DISABLE_EXCEPTIONS` define set, the single-file header will still refer to exception-handling specific functionality from the standard library.

Namely, in the `ExceptionTranslatorRegistrar` it directly references `std::rethrow_exception` and `std::current_exception()` which will make the library fail to compile when exceptions are disabled.

### Steps to reproduce

1. Use v.2.5.0 library with exceptions disabled and `CATCH_CONFIG_DISABLE_EXCEPTIONS` define set.

### Extra information

* Catch version: **v2.5.0**
* Operating System: **none** (bare-metal)
* Compiler+version: **IAR 8.11.3**

**Comment by horenmar** [comment]
Interesting, all of our test builds on TravisCI passed (the ones with `EXTRAS=1` build without exceptions and `CATCH_CONFIG_DISABLE_EXCEPTIONS` enabled, e.g. [this one](https://travis-ci.org/catchorg/Catch2/jobs/459919751))

**Comment by horenmar** [comment]
Ok, I am going to merge it to master and you can reopen the issue if it still comes up.
