### ISSUE TITLE
GENERATE based on variables?

### ISSUE THREAD

**Issue by johvik** [catchorg/Catch2#1465]
Should it be allowed to base generated values on variables?
I've tested to add an implicit capture to the lambda in the GENERATE macro and it seems to work.
```cpp
// Note that this is just a minimal example.
TEST_CASE("Test") {
    auto i = 1;
    auto j = GENERATE(i*2);
    REQUIRE(j == 2);
}
```

**Comment by johvik** [comment]
Turns out there are some issues with this, for example when capturing pointers that might differ

**Comment by horenmar** [comment]
For safety reasons I decided against providing a macro for this, but [we show how to use variables in generators with an example](https://github.com/catchorg/Catch2/blob/master/examples/310-Gen-VariablesInGenerators.cpp).
