### ISSUE TITLE
Visual Studio C++17 warning C4005 CATCH_CPP14_OR_GREATER macro redefinition

### ISSUE THREAD

**Issue by aegonzalez** [catchorg/Catch2#1469]
## Description
Compiling the cpp file that includes catch.hpp results in a macro redefinition warning.

### Steps to reproduce
Compile the following cpp file and observe the warning:
//--code start
#define CATCH_CONFIG_MAIN
#include "unittests/incl/catch.hpp"

TEST_CASE("AsyncRequest", "[asyncrequest]") {
    std::string text = "sail";
    REQUIRE(text.size() > 0);
}
//--code end

### Extra information
* Catch version: **v2.5.0**
* Operating System: **Windows 10**
* Compiler+version: **Visual Studio Professional 2017 Version 15.8.2**
* Configuration:  ** Win32 Release or Build **
* Compiler option: ** std:c++latest

**Comment by JoeyGrajciar** [comment]
@aegonzalez are you sure that this define is not used somewhere in project properties? I found this macro only on one place in catch2 codebase.

**Comment by aegonzalez** [comment]
You're right. I found it in the cmake global file. Thank you.
