### ISSUE TITLE
Improvements to custom main and argument handling

### ISSUE THREAD

**Issue by BRevzin** [catchorg/Catch2#1472]
I have a custom `main()` using Catch2. There are some things that I need to run before any of the unit tests start and some things that I need to run after all of the unit tests finish, as well as adding some more command line parameters. 

Initially, I wrote this as

```cpp
int ret = session.applyCommandLine(argc, argv);
if (ret != 0) {
  return ret;
}
// (A) custom startup logic
int failures = session.run();
// (B) custom shutdown logic
return failures;
```

But this isn't _entirely_ right. For instance, I want `./test -h` to just print the help and exit, it shouldn't run my startup/shutdown logic. So I added that:

```cpp
int ret = session.applyCommandLine(argc, argv);
if (ret != 0) {
  return ret;
}

if (session.configData().showHelp) {
  return 0;
}

// (A) custom startup logic
```

But that isn't quite right either, since I don't want `./test -l` or the various other test printers to run my startup logic either. So I added that too:

```cpp
int ret = session.applyCommandLine(argc, argv);
if (ret != 0) {
  return ret;
}

if (session.configData().showHelp) {
  return 0;
}

if (auto listed = Catch::list(session.config())) {
  return *listed;
}

// (A) custom startup logic
```

And at this post, I basically have half of `Session::runInternal()` copied into my `main()`. 

I think this should be made as a first-class option somehow - since I suspect this kind of help/list logic would be really common for those writing a custom main.

**Comment by philsquared** [comment]
Hi Barry,
Would a [Listener](https://github.com/catchorg/Catch2/blob/master/docs/event-listeners.md) be a better match for what you want to do?

**Comment by BRevzin** [comment]
It's... possible.

I need to reference some arguments that I get from the command line. To use a Listener, I'd have to make those static members on the Listener or global somehow. That... works. And it's arguably better than what I have now anyway.

Thanks!

**Comment by JoeyGrajciar** [comment]
@BRevzin do you need some more information or can this be closed?
