### ISSUE TITLE
Add findCatch2.cmake to enable MODULE mode

### ISSUE THREAD

**Issue by ncihnegn** [catchorg/Catch2#1476]
## Description
Right now CMake can only find Catch2 in CONFIG mode.
Please add FindCatch2.cmake to support MODULE mode.
It will be nicer to install cmake files into share/cmake/Modules.

**Comment by NeroBurner** [comment]
I'm against adding a FindCatch2.cmake file, the config file should suffice. IMHO config files created and installed by the project are the better than generic `FindXXX.cmake` files

For package integration Catch2 is already doing the right thing to install the config file as `${CMAKE_INSTALL_PREFIX}/lib/cmake/Catch2/Catch2Config.cmake`. This enables us as users to find it with `find_package(Catch2)` or `find_package(Catch2 CONFIG)` when Catch2 is installed into the system (no other environment variables should be necessary)

Do you have issues with just using `find_package(Catch2)`?

**Comment by ncihnegn** [comment]
No issue with using per se. But to make a package for Homebrew or Arch, it will be nice Catch2 is installed along with other CMake modules under share/cmake/Modules.

**Comment by NeroBurner** [comment]
there is no need for the FindCatch2.cmake module

According to the documentation /usr/lib/cmake/Catch2 is in the search path for `find_package(Catch2 CONFIG)`. Therefore it will be found without any other system modification
https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure

Do you have a pkgbuild script for the AUR? I could test against that

**Comment by ncihnegn** [comment]
Agreed.
