### ISSUE TITLE
MSVC 2017 in Release mode causes my variable to be uninitialized?

### ISSUE THREAD

**Issue by TrueWodzu** [catchorg/Catch2#1477]
Hi,

In one of my projects I have this strange behavior. If I build my test suite in debug mode, everything works. If I build it in release mode, tests fail. It seems that my variable is uninitialized in CHECK(), CHECK_FAILS().

Take a look at this example:

```
TEST_CASE("PlateTracker.Track")
{
  PlatePaths plate_paths;
  PlateTracker p_t(PlateTrackerOptions(10, Milliseconds(1000), Seconds(2)));
  CHECK_FALSE(p_t.Track(DateTimeToTimePoint(2018, 1, 1, 0, 0, 0, 0), Plates(), plate_paths));
  CHECK_FALSE(p_t.Track(DateTimeToTimePoint(2018, 1, 1, 0, 0, 0, 0), Plates({ Rect<int>(0, 0, 10, 10) }), plate_paths));
  CHECK_FALSE(p_t.Track(DateTimeToTimePoint(2018, 1, 1, 0, 0, 0, 1000), Plates(), plate_paths));
  CHECK(p_t.Track(DateTimeToTimePoint(2018, 1, 1, 0, 0, 1, 1), Plates(), plate_paths));
}
```
What is even stranger is that when I add one line at the end of my test:

```
TEST_CASE("PlateTracker.Track")
{
  PlatePaths plate_paths;
  PlateTracker p_t(PlateTrackerOptions(10, Milliseconds(1000), Seconds(2)));
  CHECK_FALSE(p_t.Track(DateTimeToTimePoint(2018, 1, 1, 0, 0, 0, 0), Plates(), plate_paths));
  CHECK_FALSE(p_t.Track(DateTimeToTimePoint(2018, 1, 1, 0, 0, 0, 0), Plates({ Rect<int>(0, 0, 10, 10) }), plate_paths));
  CHECK_FALSE(p_t.Track(DateTimeToTimePoint(2018, 1, 1, 0, 0, 0, 1000), Plates(), plate_paths));
  CHECK(p_t.Track(DateTimeToTimePoint(2018, 1, 1, 0, 0, 1, 1), Plates(), plate_paths));
  std::cout << "Hi!\n"; // This has been added!
}
```

What is going on here? Has someone had similar issues? It happens on different versions of Catch2 and I am lost...

Sorry for not providing an easy to reproduce example, I will provide one if needed, I just wanted to ask beforehand, maybe this is a known issue, although I haven't been able to find any information about it here.

* Catch version: **2.0.1 - 2.5.0**
* Operating System: **Win64**
* Compiler+version: **MSVC2017**

**Comment by TrueWodzu** [comment]
It was my fault, I was catching a reference to object which then get destroyed...

**Comment by horenmar** [comment]
Thanks for reporting back.
