### ISSUE TITLE
Teamcity reporter fails to compile because catch_text.h is not included

### ISSUE THREAD

**Issue by stefansullivan** [catchorg/Catch2#1483]
Checking out version 2.5.0 I noticed that I cannot include reporters/catch_reporter_teamcity.hpp

Looking at the code it seems like there's been a concerted effort to reduce the includes in that file. However, I think through a series of refactors the include for "internal/catch_text.h" has been entirely factored out (possibly in revision 3a37f45a97276b3450f8fb86811f590fc1abf1b7).

My main.cpp starts with the first two lines:

    #include <catch.hpp>
    #include <reporters/catch_reporter_teamcity.hpp>

And I get the error message:

    src/../third_party/Catch2/include/reporters/catch_reporter_teamcity.hpp:199:19: error: use of undeclared identifier 'Column'
                os << Column( _string )
                      ^

* Catch version: **v2.5.0**
* Operating System: **Mac OS X**
* Compiler+version: **CLion 2018.3**

> clang --version
> Apple LLVM version 8.0.0 (clang-800.0.42.1)
> Target: x86_64-apple-darwin16.6.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by JoeyGrajciar** [comment]
@stefansullivan are you using your own main? did you define `CATCH_CONFIG_RUNNER`?

**Comment by JoeyGrajciar** [comment]
the reporter you use is somewhat older? i tried compiling it myself and it compiled.

**Comment by stefansullivan** [comment]
I was trying to move from Catch 1.x to 2.x and this was the only error (so
far) that I encountered. Do I still need this header for the teamcity
reporter in Catch 2.x?

**Comment by JoeyGrajciar** [comment]
in that case you should probably also update `catch_reporter_teamcity.hpp` to the one from master :)

**Comment by JoeyGrajciar** [comment]
it should thats why i am surprised that it does not work for you.
`catch.hpp` is included from where? `single_include/catch2` or `include`?

**Comment by stefansullivan** [comment]
I'm using include/ not single_include/

>

**Comment by horenmar** [comment]
Well, there is your problem. The reporters assume that they are preceded by the single include header, because that is what we package and release for further use.

**Comment by stefansullivan** [comment]
So how do you configure the build to include? Do you use

    -ICatch/single_include -ICatch/reporters

and then include without the reporters path?

    #include <catch.hpp>
    #include <catch_teamcity_reporter.hpp>

Is this the preferred way of doing it?

-Stefan

**Comment by horenmar** [comment]
Reporters are also released in the `single_include` folder, so the answer is to add `-ICatch2/single_include` (or the moral equivalent) to your build flags and include them like this:

```cpp
#define CATCH_CONFIG_RUNNER
#include <catch2/catch.hpp>
#include <catch2/catch_reporter_teamcity>
```

**Comment by stefansullivan** [comment]
Ok, thank you. Sorry stupid upgrade issues. I got it working now that everything is reading from `single_include` and using the actual path in `#include` statements
