### ISSUE TITLE
Single include's define guard should be splitted

### ISSUE THREAD

**Issue by YarikTH** [catchorg/Catch2#1504]
Last release 2.5.0
In header only version parts before and after ifdef CATCH_CONFIG_MAIN should have separate define guards.
I made header only helper for testing of complicated classes that implement some interface. And I included catch2/catch.hpp in it. Then I included that helper header in  tests.cpp. tests.cpp tried to use code from catch2/catch.hpp defined under CATCH_CONFIG_MAIN but it failed. Because catch2/catch.hpp was already included without CATCH_CONFIG_MAIN defined.
Maybe it is not recommended usage of catch2 but it convenient usage. Now I workaround it via removing catch2 include from my helper and requirement to include catch2 in tests.cpp before my helper. But it's ugly workaround. Code for reproduce (it's not my code I'm working on, but just simplified example to illustrate problem):
https://github.com/YarikTH/catch2_problem_example

Listing to check:

> ./build.sh
> -- Configuring done
> -- Generating done
> -- Build files have been written to: .../catch2_problem_example/_build
> [100%] Built target tests
> All tests passed (1 assertion in 1 test case)

> ./build_with_bug.sh
> -- Configuring done
> -- Generating done
> -- Build files have been written to: .../catch2_problem_example/_build_with_bug
> Scanning dependencies of target tests
> [ 50%] Building CXX object CMakeFiles/tests.dir/tests.cpp.o
> [100%] Linking CXX executable tests
> /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
> (.text+0x20): undefined reference to `main'
> CMakeFiles/tests.dir/tests.cpp.o: In function `__static_initialization_and_destruction_0(int, int)':
> tests.cpp:(.text+0xce): undefined reference to `Catch::StringRef::StringRef(char const*)'
> tests.cpp:(.text+0xe1): undefined reference to `Catch::StringRef::StringRef(char const*)'
> tests.cpp:(.text+0xf8): undefined reference to `Catch::NameAndTags::NameAndTags(Catch::StringRef const&, Catch::StringRef const&)'
> tests.cpp:(.text+0x12e): undefined reference to `Catch::makeTestInvoker(void (*)())'
> tests.cpp:(.text+0x158): undefined reference to `Catch::AutoReg::AutoReg(Catch::ITestInvoker*, Catch::SourceLineInfo const&, Catch::StringRef const&, Catch::NameAndTags const&)'
> tests.cpp:(.text+0x1a0): undefined reference to `Catch::AutoReg::~AutoReg()'
> CMakeFiles/tests.dir/tests.cpp.o: In function `Catch::ITransientExpression::ITransientExpression(bool, bool)':
> tests.cpp:(.text._ZN5Catch20ITransientExpressionC2Ebb[_ZN5Catch20ITransientExpressionC5Ebb]+0x17): undefined reference to `vtable for Catch::ITransientExpression'
> CMakeFiles/tests.dir/tests.cpp.o: In function `checkSumCalculatorInterface(ISumCalculator*)':
> tests.cpp:(.text._Z27checkSumCalculatorInterfaceP14ISumCalculator[_Z27checkSumCalculatorInterfaceP14ISumCalculator]+0x34): undefined reference to `Catch::StringRef::StringRef(char const*)'
> tests.cpp:(.text._Z27checkSumCalculatorInterfaceP14ISumCalculator[_Z27checkSumCalculatorInterfaceP14ISumCalculator]+0x91): undefined reference to `Catch::AssertionHandler::AssertionHandler(Catch::StringRef const&, Catch::SourceLineInfo const&, Catch::StringRef, Catch::ResultDisposition::Flags)'
> tests.cpp:(.text._Z27checkSumCalculatorInterfaceP14ISumCalculator[_Z27checkSumCalculatorInterfaceP14ISumCalculator]+0x13c): undefined reference to `Catch::AssertionHandler::handleExpr(Catch::ITransientExpression const&)'
> tests.cpp:(.text._Z27checkSumCalculatorInterfaceP14ISumCalculator[_Z27checkSumCalculatorInterfaceP14ISumCalculator]+0x157): undefined reference to `Catch::AssertionHandler::complete()'
> tests.cpp:(.text._Z27checkSumCalculatorInterfaceP14ISumCalculator[_Z27checkSumCalculatorInterfaceP14ISumCalculator]+0x1d4): undefined reference to `Catch::AssertionHandler::handleUnexpectedInflightException()'
> CMakeFiles/tests.dir/tests.cpp.o: In function `Catch::BinaryExpr<int const&, int const&> const Catch::ExprLhs<int const&>::operator==<int>(int const&)':
> tests.cpp:(.text._ZN5Catch7ExprLhsIRKiEeqIiEEKNS_10BinaryExprIS2_RKT_EES8_[_ZN5Catch7ExprLhsIRKiEeqIiEEKNS_10BinaryExprIS2_RKT_EES8_]+0x55): undefined reference to `Catch::StringRef::StringRef(char const*)'
> CMakeFiles/tests.dir/tests.cpp.o: In function `Catch::BinaryExpr<int const&, int const&>::~BinaryExpr()':
> tests.cpp:(.text._ZN5Catch10BinaryExprIRKiS2_ED2Ev[_ZN5Catch10BinaryExprIRKiS2_ED5Ev]+0x32): undefined reference to `Catch::ITransientExpression::~ITransientExpression()'
> CMakeFiles/tests.dir/tests.cpp.o:(.data.rel.ro._ZTIN5Catch10BinaryExprIRKiS2_EE[_ZTIN5Catch10BinaryExprIRKiS2_EE]+0x10): undefined reference to `typeinfo for Catch::ITransientExpression'
> CMakeFiles/tests.dir/tests.cpp.o: In function `Catch::BinaryExpr<int const&, int const&>::streamReconstructedExpression(std::ostream&) const':
> tests.cpp:(.text._ZNK5Catch10BinaryExprIRKiS2_E29streamReconstructedExpressionERSo[_ZNK5Catch10BinaryExprIRKiS2_E29streamReconstructedExpressionERSo]+0x8e): undefined reference to `Catch::formatReconstructedExpression(std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Catch::StringRef, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> CMakeFiles/tests.dir/tests.cpp.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > Catch::Detail::stringify<int>(int const&)':
> tests.cpp:(.text._ZN5Catch6Detail9stringifyIiEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_[_ZN5Catch6Detail9stringifyIiEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_]+0x2f): undefined reference to `Catch::StringMaker<int, void>::convert[abi:cxx11](int)'
> collect2: error: ld returned 1 exit status
> CMakeFiles/tests.dir/build.make:94: recipe for target 'tests' failed
> make[2]: *** [tests] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tests.dir/all' failed
> make[1]: *** [CMakeFiles/tests.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by NeroBurner** [comment]
see documentation https://github.com/catchorg/Catch2/blob/master/docs/tutorial.md#what-did-we-do-here

do the `#define CATCH_CONFIG_MAIN` exactly once. And it must be before your first inclusion of `catch2.hpp`

I haven't tested it, but in your case the following `test.cpp` should work

```cpp
#define CATCH_CONFIG_MAIN
#include test_helper.h
TEST_CASE( "work with SumCalculator", "[SumCalculator]")
{
    auto i = SumCalculator();
    checkSumCalculatorInterface( &i );
}
```
you also could do one test.cpp file where you do the `#define CATCH_CONFIG_MAIN` and another cpp file which implements the tests (without a `#define`)

**Comment by YarikTH** [comment]
I defined CATCH_CONFIG_MAIN exactly once. But before it I included catch2.hpp without define via another header and it broke my code. If catch2.hpp behaved like stb libraries where header and impl part have separate define guards then any include of catch2.hpp without CATCH_CONFIG_MAIN defined don't break anything.
```
#define CATCH_CONFIG_MAIN
#include "test_helper.h"
```
will work, but it's bad practice. I should know that I included catch2.hpp in test_helper and be aware that I should define CATCH_CONFIG_MAIN right before it instead of using clear two strings code from manual:
```
#define CATCH_CONFIG_MAIN
#include "catch/catch2.hpp"
```
just because any include of catch2.hpp not from cpp will break it.

Current catch2.hpp structure:

> #ifndef TWOBLUECUBES_SINGLE_INCLUDE_CATCH_HPP_INCLUDED
> #define TWOBLUECUBES_SINGLE_INCLUDE_CATCH_HPP_INCLUDED
> // non main content
> #ifdef CATCH_CONFIG_MAIN
> // main content
> #endif // CATCH_CONFIG_MAIN
> #endif // TWOBLUECUBES_SINGLE_INCLUDE_CATCH_HPP_INCLUDED

Desired catch2.hpp structure:

> #ifndef TWOBLUECUBES_SINGLE_INCLUDE_CATCH_HPP_INCLUDED
> #define TWOBLUECUBES_SINGLE_INCLUDE_CATCH_HPP_INCLUDED
> // non main content
> #endif // TWOBLUECUBES_SINGLE_INCLUDE_CATCH_HPP_INCLUDED
> 
> #ifdef CATCH_CONFIG_MAIN
> #ifndef TWOBLUECUBES_SINGLE_INCLUDE_CATCH_HPP_INCLUDED_CONFIG_MAIN
> #define TWOBLUECUBES_SINGLE_INCLUDE_CATCH_HPP_INCLUDED_CONFIG_MAIN
> // main content
> #endif // TWOBLUECUBES_SINGLE_INCLUDE_CATCH_HPP_INCLUDED_CONFIG_MAIN
> #endif // CATCH_CONFIG_MAIN

**Comment by YarikTH** [comment]
Ok I'll try it.

**Comment by horenmar** [comment]
You can probably achieve the same effect via the PCH support, but I am not necessarily against splitting the include guards.

**Comment by YarikTH** [comment]
For now I've just created [https://github.com/YarikTH/Catch2/tree/SeparatedDefineGuard](branch) with tests that fail to compile. According to my investigations to separate CATCH_CONFIG_MAIN part from TWOBLUECUBES_SINGLE_INCLUDE_CATCH_HPP_INCLUDED I have to modify original catch.hpp instead of just patching generateSingleHeader.py.

**Comment by YarikTH** [comment]
I gave up. I'm not so interested in this feature and it's hard to implement without main header reorganisation that will lead to undefined problems. And I moved to use doctest instead anyway.
