### ISSUE TITLE
Different tags cause a clash in test case identification

### ISSUE THREAD

**Issue by ruipacheco** [catchorg/Catch2#1519]
**Describe the bug**
The documentation says that different tags can be used to identify test cases: https://github.com/catchorg/Catch2/blob/master/docs/test-cases-and-sections.md#tags

**Expected behavior**
I have two test cases with the same name but different tags:

`TEST_CASE("Connection", "[mdb]") {...}`
`TEST_CASE("Connection", "[pg]") {...}`

I'd expect to be able to run them independently but running the whole test executable returns the following message:

```
error: TEST_CASE( "Connection" ) already defined.
	First seen at ../tests/integration/mdb.cpp:20
	Redefined at ../tests/integration/pg.cpp:22
```

**Reproduction steps**
Create two test cases with the same name and different tags.

**Platform information:**

 - OS: **Latest macOS**
 - Compiler+version: **Apple LLVM version 10.0.0 (clang-1000.11.45.5)**
 - Catch version: **v2.5.0**

**Comment by JoeyGrajciar** [comment]
Tags are used for grouping of several related test cases.
They can be also used to select which tests to run from command line.

> Test names must be unique within the Catch executable.
This is mentioned just few lines above Tags section of linked doc page.

If your test subjects(`mdb` and `pg`) to those test have similar interface you can use
`TEMPLATE_TEST_CASE` to write one generic test for both :)

**Comment by ruipacheco** [comment]
Thanks!
