### ISSUE TITLE
Info, scoped info and captured info do not show with console reporter

### ISSUE THREAD

**Issue by martinmoene** [catchorg/Catch2#152]
When using the _console reporter_ with CATCH v0.9 b16 (integration), the information recorded via `INFO()`, `SCOPED_INFO()` and `CAPTURE()` does not show when only errors are reported (i.e. option `--success`, or `-s` is not specified).

The output of the _basic reporter_ does contain the (scoped) info and captured info.

Can be demonstrated with the following code.

``` Cpp
/*
 *  issue_scoped_info_reporter_console.cpp
 */
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

TEST_CASE( "fail/info", "" )
{
    INFO( "this is info going with the following failure" );
    FAIL( "failure for above info" );
}

TEST_CASE( "fail/info/unrelated info", "" )
{
    INFO( "this is info unrelated to the following failure" );
}

TEST_CASE( "fail/info/unrelated failure", "" )
{
    FAIL( "failure unrelated to above test case info" );
}

TEST_CASE( "fail/scoped info/unrelated", "" )
{
    {
        SCOPED_INFO( "this is scoped info unrelated to the following failure" );
    }
//    {
        FAIL( "failure unrelated to above scoped info" );
//    }
}

TEST_CASE( "fail/scoped info", "" )
{
    {
        SCOPED_INFO( "this is scoped info unrelated to the following failure" );
    }
//    {
        SCOPED_INFO( "this is scoped info going with the following failure" );
        FAIL( "failure for above scoped info" );
//    }
}

TEST_CASE( "fail/capture", "" )
{
    const double m = 1, c = 299792458;
    CAPTURE( (m * c * c) );
    FAIL( "failure for above capture" );
}

// cl -nologo -W3 -EHsc -GR -MD issue_scoped_info_reporter_console.cpp && issue_scoped_info_reporter_console.exe -r console
// g++ -Wall -o issue_scoped_info_reporter_console.exe issue_scoped_info_reporter_console.cpp && issue_scoped_info_reporter_console.exe -r console
```

**Comment by ghpqans** [comment]
> Yes, WARN will always generate output - and is usually what I use for dev purposes. You can also use std::cout and std::err, although due to the way CATCH logs some things lazily they can sometimes appear a little out of sync - so I find WARN a little easier to follow.
> 
> If you think about it: usually, if your tests pass, you don't want any output from your tests! You might want some extra diagnostics while developing, though.

What a pity! WARN should be reserved for a warning and not for general output. Have you ever heard of a programming language using WARN instead of print?
