### ISSUE TITLE
approvalTests.py cannot find executable because missing -.exe

### ISSUE THREAD

**Issue by hbina** [catchorg/Catch2#1523]
**Describe the bug**
approvalTests.py in Windows fails to find the executable.

**Expected behavior**
It should be able to find the executable and run the unit test

**Reproduction steps**
Run approvalTests.py in CLion in Windows

**Platform information:**

 - OS: **Windows NT**
 - Compiler+version: **gcc version 8.2.0 (MinGW.org GCC-8.2.0-3)**
 - Catch version: **v2.6.0**

**Comment by horenmar** [comment]
Resolved by #1524
