### ISSUE TITLE
Catch 1 JUnit Output not Compatable with Jenkins xUnit

### ISSUE THREAD

**Issue by VirtualTim** [catchorg/Catch2#1535]
At some point JUnit added the required element "testsuites", and this was picked up by xUnit.
xUnit format is available here: https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd
This results in the JUnit output returning the following error when xUnit tries to parse it:
`09:56:25 WARNING: The file 'c:\someTest.output.xml' is an invalid file.
09:56:25 WARNING: At line 2 of file:/c:/someTest.output.xml:cvc-elt.1: Cannot find the declaration of element 'testsuites'.
09:56:25 WARNING: The result file 'c:\someTest.output.xml' for the metric 'CppUnit' is not valid. The result file has been skipped.`

I don't know if this has been addressed in Catch 2, but is there any chance of getting this into Catch 1?

**Comment by horenmar** [comment]
If I understand your issue correctly, your XML file is missing a `<testsuites>` root element?

I cannot reproduce this, as this is the output from the JUnit reporter of a trivial test file using Catch v1.12.2:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="a.out" errors="0" failures="2" tests="2" hostname="tbd" time="0.00159" timestamp="2019-04-10T14:17:32Z">
    <testcase classname="INFO surprise" name="without newline" time="0.000415">
      <failure message="false" type="REQUIRE">
Message without newline
at main.cpp:9
      </failure>
    </testcase>
    <testcase classname="INFO surprise" name="with newline" time="0.0003">
      <failure message="false" type="REQUIRE">

Message with newline
at main.cpp:15
      </failure>
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>
```
The root `testsuites` tag is there.


Anyway, Catch 1 is no longer in active development, so if you want to implement some changes, you will need to open up a PR to do it.

**Comment by VirtualTim** [comment]
Huh weird. Anyway we decided to switch the few tests that were using Catch over to Google Test. So since it's not an issue for me, and you can't reproduce it, I'll close this.
