### ISSUE TITLE
Use a single Generators for multiple values (local variables)

### ISSUE THREAD

**Issue by gnatty7** [catchorg/Catch2#1538]
**Description**
While the Cartesian product feature of nesting GENERATE calls is useful in some contexts, the use case I have is more pedestrian.

I'd like to use a generator to generate a number of random values per test case.  I ended up writing something that creates a std::vector, where I extract each element individually for the test case.

NOTE: I'm aware the random generator is not a good implementation. Just used here for illustrative purposes.

```
template<typename Container, size_t NUM_ELEMENTS=1>
class RandomValuesGenerator : public Catch::Generators::IGenerator<Container>
{
public:
	using value_type = typename Container::value_type;
	RandomValuesGenerator()
	{
		_current_value.resize(NUM_ELEMENTS);
		static_cast<void>(next());
	}
	
	Container const& get( ) const override
	{
		return _current_value;
	}
	
	bool next() override
	{
		for (size_t i = 0; i < NUM_ELEMENTS; i++)
		{
			_current_value[i] = value_type ( 1e3 * (drand48() - 0.5) );
		}
		return true;
	}
	
private:
	Container _current_value;
};

// Convenience function for creating a Catch2 generator for producing random numbers
template<typename Container, size_t NUM_ELEMENTS=1>
static Catch::Generators::GeneratorWrapper<Container> randomValues() {
	return Catch::Generators::GeneratorWrapper<Container>(
		std::unique_ptr<Catch::Generators::IGenerator<Container> >(
            new RandomValuesGenerator<Container, NUM_ELEMENTS>()));
}
```

Where I call the code like so:
```
TEST_CASE("someTest") {
    const int numTrials = 10;
    auto values = GENERATE(take(numTrials, randomValues<std::vector<float>, 4>()));
    float a = values[0]; CAPTURE(a);
    float b = values[1]; CAPTURE(b);
    float c = values[2]; CAPTURE(c);
    float d = values[3]; CAPTURE(d);

    SECTION("Section1") {
        SECTION("SubSection 1.1") { ... }
        SECTION("SubSection 1.2") { ... }
    }
}
```

Where it will generate n-tuples of random numbers to be used in the various subsection tests below.
I imagine there should be a better/easier way to do this as I really just want to set up the number of trials I want to do, and have any number of local variables pull digits from the generator.  E.g. I feel like I shouldn't have to tell it to use a std::vector just to extract values from it into separate variables.

E.g. something like
```
TEST_CASE("Ideal") {
    int numTrials = 100;
    int numVars = 4;
    auto generator = GENERATE(take(numTrials*numVars, randomFloats());
    float a = generator.get();
    float b = generator.get();
    ...
```

Is there a way to do this?

**Comment by horenmar** [comment]
I can create a general generator adapter similar to `take` or `map` for this. I was actually thinking about it before releasing 2.6.0, but there is a complication with this kind of adapter:

What do you do, if the user asks for chunks of 3, but the underlying generator does not provide the right number of elements? e.g. if the generator has 10 elements and the user asks for chunks of 3, it can either return 3 chunks of 3 and ignore the last element, or it can return 3 chunks of 3 and then provide one chunk with only 1 element.

**Comment by horenmar** [comment]
I prefer providing only 3 chunks of 3 elements, because that is easier to use on the outside, but whichever I pick will be there for some time.

**Comment by gnatty7** [comment]
I think the some version of the former idea makes sense to me.  For each test case iteration, if there are additional elements in the generator for that iteration left over, they should be discarded, or as you say ignored.
If the API is specific about specifying the chunk size separately from the number of trials, this should be possible. Would it be possible to statically check that the chunks were properly consumed by local variables? It still doesn't mean the generator won't exhaust early (that depends on the implementation of next()) but might help with making sure the intent of the generator is fulfilled.

Another idea is that we want to generate data, of different types, for a single trial.  We could write a 'chunking' generator like the one above, but it returns a std::tuple<> of the various types that are needed.  It might be nice to have this built-in as a generator type where the API lets the programmer specify the types with callbacks/Generator classes to generate those elements.
e.g.
```
int a;
float b;
string c;
Custom d;
int trials = 10;
std::tie<a,b,c,d> = GENERATE(take(trials, ChunkedGenerator<int, float, string, Custom>(MyIntGenerator, MyFloatGenerator, MyStringGenerator, MyCustomGenerator))
```
Where My*Generator are custom generator classes for producing those types that are auto-wrapped by a GeneratorWrapper.  

This would presume that all of those elements are independently generated, while an approach like I've done with std::vector using std::tuple would work where the generator is aware of all of the types and whatever dependencies they might have.

**Comment by horenmar** [comment]
That operation is commonly called `zip` 😃 .

Anyway, master now contains a chunking generator that does what you needed.
