### ISSUE TITLE
Disable Custom Exception in Unit -test

### ISSUE THREAD

**Issue by jambagigirish** [catchorg/Catch2#1543]
**Describe the bug**
I am using custom defined exception handling for my code. When a test verification fails cath2 is calling exception handling of custom function not the catch2 defined one.

**Expected behavior**
catch2 should handle its own exception

**Reproduction steps**
Steps to reproduce the bug.

**Platform information:**
 - OS: Cent os
 - Compiler+version: GCC  4.8.5
 - Catch version: Catch v2.4.2

**Additional context**
How to force catch2 to use its own exception handling

**Comment by jayeshbadwaik** [comment]
Please provide a minimal working example for the same.
