### ISSUE TITLE
deleter for smart pointers called twice

### ISSUE THREAD

**Issue by icegood** [catchorg/Catch2#1547]
Here is my simple test:

```
#include "catch.hpp"
#include <memory>
#include <functional>

static int occur_cnt = 0;

TEST_CASE ("simple") {
  GIVEN ("GIVEN") {
    int magic = 123567;
    std::unique_ptr<int, std::function<void(int*)>> ptr
      (&magic,
       [](int *ptr) {
         assert(occur_cnt == 0);
         occur_cnt++;
         *ptr = 0;
       });
    WHEN ("WHEN") {
      THEN("THEN") {
        REQUIRE(false);
      }
    }
  }
}
```

I wonder why in case when require gets wrong my section in in unique pointer throws. 
Beside of unit testing my units are profiled as well so i'm interested in correct memory usage inside unit tests, that's why i need custom deleters to catch everything whatever happens

**Comment by horenmar** [comment]
The limitation of `SECTION` tracking being done at runtime is that under certain circumstances, a section needs to be run more than one time.

The circumstances are
1) The section hard fails (e.g. with `REQUIRE`, or other thrown exception *AND*
2) It is the _first_ section in its path

**Comment by icegood** [comment]
Ok. Let it be as known issue.
