### ISSUE TITLE
Contents of catch_meta.hpp are in global namespace

### ISSUE THREAD

**Issue by bjude** [catchorg/Catch2#1548]
**Describe the bug**
The types defined in catch_meta.hpp are defined in the global namespace and will conflict with those used in the tested project. In particular, i define a TypeList struct in my project too and this causes the tests to fail unless the fully qualified name is used.

**Expected behavior**
My project's definition of the struct (TypeList in this case) is selected.

**Reproduction steps**
```c++
#include <type_traits>

#include <catch.hpp>

namespace myproject {
template <typename... Ts>
struct TypeList {};
}

using namespace myproject;

TEST_CASE("MyTest") {
    REQUIRE(std::is_same_v<TypeList<int>, TypeList<int>>);
}
```
Compiler Explorer link here: https://godbolt.org/z/mAuZzb

**Platform information:**

 - OS: **Windows 10**
 - Compiler+version: **Clang 8.0 & VS 15.9.5**
 - Catch version: **2.6.0 (Vcpkg)**

**Comment by horenmar** [comment]
Should be fixed in master now.

**Comment by ras0219-msft** [comment]
You can get master via `vcpkg remove catch2` and then `vcpkg install catch2 --head`.
