### ISSUE TITLE
Can't CHECK overloaded comparison operators if the definition is inlined

### ISSUE THREAD

**Issue by jcpaik** [catchorg/Catch2#1549]
**Describe the bug**

If a comparison operator (say, `operator<`) of a class using inline is implented in one file, and the returned expression of operator contains composition of booleans (say, `return (x<other.x && y<other.y);`), and there is a test code in another file that `CHECK`s the comparison operator (say, `CHECK(a < b);`), it is impossible to link the mentioned files to generate the final test executable.

**Reproduction steps**

Let's say we have a simple pair-of-int class with lexicographical ordering in files `pair.hpp` and `pair.cpp`.

* `pair.hpp`
```C++
// class definition
class Pair {
    public:
        int x, y;
        Pair(int x, int y); 
        bool operator<(const Pair &other) const;
};
```

* `pair.cpp`
```C++
#include "pair.hpp"

// class function definitions
Pair::Pair(): x(x), y(y)
{

}

inline bool Pair::operator<(const Pair &other) const
{
    return
        (this->x < other.x) ||
        (this->x == other.x && this->y < other.y);
}

```

We want to test this class in a file called `test_pair.cpp`.
```C++
#include "catch.hpp"

#include "pair.hpp"

TEST_CASE( "Sample Test", "[Pair]" ) {
    Pair x(1, 2), y(3, 4);
    REQUIRE(x < y);
}
```

It is possible to compile the final executable by just compiling and linking all source codes. Here `main.cpp` is the main for Catch2.
```
computer:folder user$ clang++ -std=c++11 main.cpp pair.cpp test_pair.cpp -o main
```
However if one compiles each `.cpp` and try to link the object files, we get the following error.
```
computer:folder user$ clang++ -std=c++11 -c main.cpp
computer:folder user$ clang++ -std=c++11 -c pair.cpp
computer:folder user$ clang++ -std=c++11 -c test_pair.cpp
computer:folder user$ clang++ -std=c++11 main.o pair.o test_pair.o -o main
Undefined symbols for architecture x86_64:
  "Pair::operator<(Pair const&) const", referenced from:
      Catch::BinaryExpr<Pair const&, Pair const&> const Catch::ExprLhs<Pair const&>::operator<<Pair>(Pair const&) in test_pair.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
If one removes `inline` from `pair.cpp`, the same sequence of commands produces `main` without any errors or warnings.

It seems that this happens because one is not allowed to have composition of boolean expressions in `CHECK`s. However, it's also absurd to prevent users from implementing a class operator using inline and test them inlined. 

**Platform information:**

 - OS: **Mac OS X Mojave**
 - Compiler+version: **Apple LLVM clang-1000.11.45.5**
 - Catch version: **v2.5.0**

**Comment by Chukak** [comment]
Hi!
This error occurs because you use the `operator<`, which has no definition. To fix this, delete the `inline` specifier in the definition of `operator<` in the .cpp file or move the definition to the header file.
This error is not a Catch error.

**Comment by jcpaik** [comment]
Chukak,

Thanks for mentioning the right place to look. I did my research and indeed the code had the error ([link](https://isocpp.org/wiki/faq/inline-functions#inline-member-fns)). One should have the definition inside header in general to define a inline function.

**Comment by jcpaik** [comment]
Is putting the issue to close enough to 'undo' it? Since this 'error' is due to my lack of understanding of C++, not Catch, the title seems misleading even for a closed issue.

**Comment by horenmar** [comment]
Yeah, it is okay.
At least if someone finds it, they can fix their problem on their own.
