### ISSUE TITLE
RangeGenerator<T> is absent in v.2.6.1

### ISSUE THREAD

**Issue by dmtkf** [catchorg/Catch2#1557]
Documentation describes Range Data Generator:
https://github.com/catchorg/Catch2/blob/master/docs/generators.md#top

Last version of catch doesn't have it:
https://github.com/catchorg/Catch2/releases/download/v2.6.1/catch.hpp

**Comment by horenmar** [comment]
Documentation for v2.6.1 does not:
https://github.com/catchorg/Catch2/blob/v2.6.1/docs/generators.md

Documentation in master is for master, not for the last release. Anyway, this problem has come up often enough that I wonder if it would be worth a disclaimer of some sort, saying "this documentation is for the state in master, for documentation for the last release go here", or maybe publishing our own ReadTheDocs page.

**Comment by edgrin** [comment]
Oh, now I see that is no issue with documentation, you are right. In my case I got there from the main page: https://github.com/catchorg/Catch2

As you can see all links from "How to use" points to files from master. So may be solution could be to use links to the current release.

**Comment by horenmar** [comment]
> As you can see all links from "How to use" points to files from master. So may be solution could be to use links to the current release.

That's a great idea, thanks.
