### ISSUE TITLE
Cannot find GPG key on any public keyserver

### ISSUE THREAD

**Issue by Minoru** [catchorg/Catch2#1564]
This is not a bug with Catch itself, but rather with its release process.

The releases are signed with GPG key DE48307B8B0D381A, but I couldn't fetch it from e.g. pgp.mit.edu (which is part of a big pool of servers, and should have the key if it was uploaded *somewhere*). The docs don't mention where to fetch the key either.

Since GitHub says the tags are "verified" using the same key, I assume it was only uploaded to GitHub. GitHub doesn't serve the keys, so can you please upload it on a public keyserver somewhere?

**Comment by horenmar** [comment]
I am 99% sure I uploaded it to _a_ public key server and a friend confirmed that he could fetch it, so this is a bit weird. I'll investigate, but in the meantime, the link from the 2.5.0 release where I started signing the releases should work: https://codingnest.com/files/horenmar-publickey.asc

**Comment by Minoru** [comment]
Oh, no need to investigate anymore. Apparently it's pgp.mit.edu fault. I ran `gpg --recv-key DE48307B8B0D381A` again just now and after a minute of waiting, it did fetch the key.

Sorry about the noise.

**Comment by horenmar** [comment]
Yeah that about matches my experiences -- the keyserver infrastructure is creaky and slow.
