### ISSUE TITLE
Can not compile with `random` from GENERATE.

### ISSUE THREAD

**Issue by tnikolla** [catchorg/Catch2#1569]
I am trying to write a trivial `TAST_CASE` that generates random numbers as in:

```
TEST_CASE("Random generator", "[generator]") {
	auto i = GENERATE(take(4, random(0,1)));
	SECTION("foo") {
		CAPTURE(i);
		CHECK(false);
	}
}
```

I get an `error C3861: "random" identifier not found` from visual studio. Am I doing smth wrong?

**Platform information:**

 - OS: **Windows 10**
 - Compiler+version: **Visual C++ 2017**
 - Catch version: **v2.6.1**

**Comment by horenmar** [comment]
Random generators were added in v2.7.0
