### ISSUE TITLE
overloads of match(NSString* ) have wrong type to be overload of the base method, hence it does not compile on ObjectiveC++

### ISSUE THREAD

**Issue by pqnet** [catchorg/Catch2#1571]
Catch does not compile on ObjC++ code (`.mm` files) with default configuration.

The reason is that the template signature of the base class which is overridden specify `const &` qualifier for argument of `match` function, while for `NSString*` the signature is specified as `bool match( NSString* arg) override`.

Replacing the signature on these methods with `bool match( NSString* const& arg) override` fixes the compile error

**Comment by horenmar** [comment]
I don't really have access to ObjC compiler, but can you check that b0ddf1b9b83abfd5 fixes the problem?

Also, you can help prevent this from repeating by opening a PR that adds ObjC CI to Travis 😉

**Comment by pqnet** [comment]
@horenmar it seems like you missed one at line 142, otherwise it is just the same as (the relevant portion) of my local corrected copy. I am not familiar with the codebase nor with Travis, I just downloaded the `catch.hpp` file and discovered the error, I am willing to open a pull request but it might require some time for me to get familiar with travis and create a test case.

**Comment by horenmar** [comment]
Right, I did a search and replace and that signature was missing the `override` specifier. Should be fixed in master now, so I am going to close this and the test discussion can be done via our Discord.
