### ISSUE TITLE
Require non pure functions. How about VOLATILE_REQUIRE?

### ISSUE THREAD

**Issue by architector1324** [catchorg/Catch2#1572]
**Description**
Every time i use REQUIRE i want to reset variables in my test case. Can you provide us with some assertion macro (like in my example)? It's can be useful to test not pure functions (like in this example). May be you implemented it, can you add it to documentation?

**Additional context**
```c++
#define CATCH_CONFIG_MAIN  // This tells Catch to provide a main() - only do this in one cpp file
#include "catch.hpp"

#define VOLATILE_REQUIRE SECTION("") REQUIRE

const int& foo(int& a, int b){
    a += b;
    return a;
}

TEST_CASE("Testing foo()"){
    int a = 4;
    VOLATILE_REQUIRE(foo(a, 1) == 5);
    VOLATILE_REQUIRE(foo(a, 6) == 10);
    VOLATILE_REQUIRE(foo(a, -3) == 1);
}
```

**Comment by xorz57** [comment]
Yeah I would like this feature as well!
