### ISSUE TITLE
Get the number of passed/failed tests in the code

### ISSUE THREAD

**Issue by erelsgl** [catchorg/Catch2#1573]
I would like to use catch2 for automatic grading of homework assignments. For this, I need to get the number of passed tests and the number of failed tests in the code, so that I can write, at the end of the main testing program, something like: "grade = passed*100/(passed + failed)". I do not need to print a report - I only need to insert this grade into a database. Is it possible?

**Comment by JoeyGrajciar** [comment]
I think you want to checkout https://github.com/catchorg/Catch2/blob/master/docs/event-listeners.md

**Comment by erelsgl** [comment]
Looks good. And where is the documentation of the Catch::TestCaseInfo class?

**Comment by JoeyGrajciar** [comment]
You can find example of listener also with some `Catch::TestCaseInfo` example here https://github.com/catchorg/Catch2/blob/master/examples/210-Evt-EventListeners.cpp#L122

Otherwise you can take a look into header file https://github.com/catchorg/Catch2/blob/master/include/internal/catch_test_case_info.h

**Comment by erelsgl** [comment]
This is very helpful, thanks!

**Comment by horenmar** [comment]
As someone who actually uses Catch tests for grading homework, I would recommend a somewhat different approach. Specifically, different tests/assertions are grouped together via tags and the external executor then runs specific tags under the XML reporter to get machine-parseable output and finer grained control over the assessment.
