### ISSUE TITLE
CatchAddTests reports an incorrect warning about number of tests being zero

### ISSUE THREAD

**Issue by XapaJIaMnu** [catchorg/Catch2#1578]
**Describe the bug**
CatchAddTests reports an incorrect warning about number of tests being zero, despite succeeding in adding all tests.

**Expected behavior**
No warning should be given if there is at least one test present (which there is on my system)

**Reproduction steps**
Should be reproducible by any project that tries to add tests using Catch.cmake and CatchAddTests.cmake

**Platform information:**
 - OS: **Arch Linux**
 - Compiler+version: **GCC v8.2.1**
 - Catch version: **v2.7**

I have downloaded the latest one header version of Catch2 and manually added the two extra cmake files (Catch.cmake and CatchAddTests.cmake) in order to have Ctest integration. When compiling I get a warning:

```bash
CMake Warning at myproject/CMake/CatchAddTests.cmake:40 (message):
  Test executable 'myproject/build/tests'
  contains no tests!
```
However all tests are then correctly registered and when I manually run my tests command with `--list-test-names-only` I see a bunch of tests listed.

On inspecting `CatchAddTests.cmake` it has the following code:
```cmake
execute_process(
  COMMAND ${TEST_EXECUTOR} "${TEST_EXECUTABLE}" ${spec} --list-test-names-only
  OUTPUT_VARIABLE output
  RESULT_VARIABLE result
)
```
On my system at least, the variable `result` contains 0 (normal application exit code I assume) and output contains all the test names. Now, `result` is only used in the code section that generates the warning which explains why adding the tests actually works:
```cmake
if(${result} EQUAL 0)
  message(WARNING
    "Test executable '${TEST_EXECUTABLE}' contains no tests!\n"
  )
elseif(${result} LESS 0)
  message(FATAL_ERROR
    "Error running test executable '${TEST_EXECUTABLE}':\n"
    "  Result: ${result}\n"
    "  Output: ${output}\n"
  )
endif()
```

 Is it possible that the behaviour of the generated Catch2 executable has changed as of late and `CatchAddTests.cmake` needs to be updated?

Cheers,

Nick

**Comment by XapaJIaMnu** [comment]
UGH sorry, case of RTFM. I used a custom main and forgot to return from it....................

**Comment by horenmar** [comment]
Thanks for reporting back.
