### ISSUE TITLE
v1.9.7 TEMPLATE_TEST_CASE doesn't compile with nvcc

### ISSUE THREAD

**Issue by HtonS** [catchorg/Catch2#1580]
TEMPLATE_TEST_CASE doesn't compile with nvcc

Expected behavior: it should compile

Steps to reproduce:
Make a single test file:
testmain.cu:
```C++
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
TEMPLATE_TEST_CASE( "template test", "[vector][template]", int, float) {
    REQUIRE(TRUE);
}
```

Compile:
`>> nvcc testmain.cu`
Output:
> nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
> testmain.cu(3): error: this declaration has no storage class or type specifier
> testmain.cu(3): error: a value of type "const char *" cannot be used to initialize an entity of type "int"
> testmain.cu(3): error: expected a ")"
> testmain.cu(3): error: expected a ";"
> At end of source: warning: parsing restarts here after previous syntax error
> 4 errors detected in the compilation of ...

**Platform information:**
 - OS: CentOS Linux release 7.6.1810 (Core) 
 - Compiler+version: nvcc V8.0.61
 - Catch version: v1.9.7

**Comment by horenmar** [comment]
Given that [`TEMPLATE_TEST_CASE` was added in 2.5.0](https://github.com/catchorg/Catch2/releases/tag/v2.5.0) I don't see how it _could_ compile with 1.9.7.
