### ISSUE TITLE
Doc suggestion: put test runner main() in a library

### ISSUE THREAD

**Issue by pwinston** [catchorg/Catch2#1583]
We created a runner.cc with CATCH_CONFIG_RUNNER defined and no tests in there. But we wanted multiple "tests" directories in our code, and didn't want to build the runner in each place since it was slow to compile.

We built runner.cc into a librunner.a. In our tests directories we linked all the test_*cc files with the librunner.a to make a test_runner binary for that directory. This works well, there's just one single runner.cc and the tests compile fast, even if you make clean in the tests directories.

I think this idea might be not intuitive to people for two reasons:
1) You're using a library with a header-only solution.
2) The library contains main(), people might not realize that is allowed.
Works well for us so just passing it on.

**Comment by horenmar** [comment]
I'll need to check if it works on Windows as well, as the default visibility there is different.

Otherwise, sure. We will be providing first class support for being a static library in the next major version anyway.
