### ISSUE TITLE
I already use single_include/catch2/catch.hpp but still have undefined referenceerror when build

### ISSUE THREAD

**Issue by swpuzhang** [catchorg/Catch2#1584]
#include <iostream>
#include <iomanip>
#include <sstream>
#include <string>
#include "catch2/catch.hpp"

std::string format_scale_value(double value)
{
	double percent_value = value * 100;
	std::stringstream sstr;
	sstr << std::fixed << std::setprecision(2) <<  percent_value;
	std::string str_ret = sstr.str();
	size_t pointPos = str_ret.find(".");
	if (pointPos == std::string::npos)
	{
		return str_ret;
	}
	while (true)
	{
		size_t len = str_ret.length();
		if (len == 0)
		{
			break;
		}
		if (str_ret[len - 1] != '0')
		{
			if (str_ret[len - 1] == '.')
			{
				str_ret.pop_back();
			}
			break;
		}
		
		str_ret.pop_back();
	}
	
	return str_ret;
}

TEST_CASE("GameRecordManager_case1", "test_format_scale_value")
{
	CHECK(format_scale_value(123.1012300) ==  "12310.12");
	CHECK(format_scale_value(123.10100)=="12310.1");
	CHECK(format_scale_value(0.001)=="0.1");
	CHECK(format_scale_value(0.00001)=="0");
}

TEST_CASE("GameRecordManager_case2", "test_format_scale_value")
{
	CHECK(format_scale_value(12)=="12");

}

int main()
{
	
	return 0;
}

undefined reference to `Catch::StringRef::StringRef(char const*)'
.....

**Comment by horenmar** [comment]
Does one of your TUs have `#define CATCH_CONFIG_MAIN` or similar before including the Catch's header?

**Comment by swpuzhang** [comment]
I have my own main entry, should I must add "#define CATCH_CONFIG_MAIN"?
or how to use when have my own main entry?  I don't see anything about it on Tutorial 
thank you

**Comment by horenmar** [comment]
[If you have your own main, you still need to define `CATCH_CONFIG_RUNNER` somewhere](https://github.com/catchorg/Catch2/blob/master/docs/own-main.md#top)
