### ISSUE TITLE
Custom Initialize/Cleanup code executed in main() context?

### ISSUE THREAD

**Issue by chronoxor** [catchorg/Catch2#1597]
Is it possible to provide custom Initialize/Cleanup handlers for ALL tests in exe file that will be run from main()?

Currently I tried to create a static test fixture based on static class members, but I get into trouble that when my destruction code is invoked there is no main() context and lots of stuff are missing so I cannot control the time of destruction of the static object.

Or maybe there is a more elegant solution to archive the goal to control lifetime of the static fixture?

**Comment by chronoxor** [comment]
Having something like this would be nice:

```
class MyGlobalFixture
{
public:
    MyGlobalFixture() { ... }
    ~MyGlobalFixture() { .. }   
};

TEST_GLOBAL_FIXTURE(MyGlobalFixture)
```

And the lifetime of MyGlobalFixture instance should not be outside of Catch2 main() function.

**Comment by horenmar** [comment]
Would an event listener for "test run started" and "test run ended" work?

You can also provide your own main and do some extra stuff there.

**Comment by chronoxor** [comment]
Yes something like "test run started" and "test run ended" event listener would be nice!

Thanks for suggestion with own main() I'll try to experiment with it.

**Comment by horenmar** [comment]
[Those already exist.](https://github.com/catchorg/Catch2/blob/master/docs/event-listeners.md)

**Comment by chronoxor** [comment]
That's what I need! Thanks a lot!
