### ISSUE TITLE
Junit report generated by Catch2 can't be parsed by Jenkins

### ISSUE THREAD

**Issue by wallybb000** [catchorg/Catch2#1598]
**Describe the bug**
After merging #1585, Jenkins failed to parse the junit report genrated by catch2.
According to [Junit ANT schema](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd),  \<properties> should be childrend node of \<testsuite>  rather than \<testsuites>.

**Expected behavior**
 \<properties> should be childrend node of \<testsuite> rather than \<testsuites>.
 For example:
 ```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite ....>
      <testcase ..../>
      <system-out/>
      <system-err/>
      <properties>
         <property name="filters" value="Scenario:*"/>
      </properties>
    </testsuite>
</testsuites>
 ```

 
**Platform information:**
 - OS: Windows 
 - Compiler+version: Visual C++ 2017
 - Catch version: v2.7.1

**Comment by horenmar** [comment]
The linked .xsd seems pretty low quality (e.g. it disallows skipped tests, which are usually supported), but [this one from the official junit repo](https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/resources/jenkins-junit.xsd) supports you in that `properties` should be part of the `testsuite` tag.

**Comment by wallybb000** [comment]
Thank you for your information. Sorry for incorrect description about this issue.  
Currently in junit report generated by v2.7.1 Catch2, \<testsuite> are child nodes of \<properties> :
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <properties>
    <property name="filters" value="Scenario: tests"/>
    <testsuite ...">
      <testcase ...>  
      <system-out/>
      <system-err/>
    </testsuite>
  </properties>
</testsuites>
```
To make Jenkins parses the generated report correctly, \<testsuite> should become child node of \<testsuites> rather than \<properties> . 
For example:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <properties>
    <property name="filters" value="Scenario: tests"/>
  </properties>
  <testsuite ...">
    <testcase ...>  
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>
```
