### ISSUE TITLE
JUnit reporter not working when EventListener is registered

### ISSUE THREAD

**Issue by bna080** [catchorg/Catch2#1618]
**Describe the bug**
An assert is raised in catch.hpp when I am using EventListener and call the test executable with JUnit reporter parameter (-r junit).

**Expected behavior**
The JUnit report should be created.

**Reproduction steps**
Since I have added the EventListener to invoke handlers for test case starting and test case ending, if I also want to have the JUnit report created, the testing fails with the following message:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuitesAssertion failed: !m_sectionStack.empty(), file c:\svn\someprojectpath\catch.hpp, line 5291
```

This is the source code in catch.hpp which debugger takes me to:
```
bool assertionEnded(AssertionStats const& assertionStats) override {
            assert(!m_sectionStack.empty());
```

**Platform information:**
Windows 10
Visual Studio 2017
Catch 2.7.2

**Additional context**
This works normally if no reporter or any other reporter than JUnit is used. 
Is this a known issue, something new, or may I be doing something wrong?

**Comment by bna080** [comment]
Is there a chance anyone might be looking into this issue (at least to confirm whether it is a bug or not) in the near future?

**Comment by horenmar** [comment]
Can you provide a minimal reproducer? 
When I try with the current single header version and this
```cpp
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

struct MyListener : Catch::TestEventListenerBase {

    using TestEventListenerBase::TestEventListenerBase; // inherit constructor

    void testCaseStarting(Catch::TestCaseInfo const&) override {}
    void testCaseEnded(Catch::TestCaseStats const&) override {}
};
CATCH_REGISTER_LISTENER(MyListener)

TEST_CASE("1A") {
    REQUIRE(true);
    SECTION("2") {
        REQUIRE(false);
    }
}

TEST_CASE("2A") {
    REQUIRE(true);
    SECTION("2") {
        REQUIRE(false);
    }
}
```

it works as expected:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="tests.exe" errors="0" failures="2" tests="6" hostname="tbd" time="0.003386" timestamp="2019-05-23T12:10:54Z">
    <testcase classname="tests.exe.global" name="1A" time="0.000071"/>
    <testcase classname="tests.exe.global" name="1A/2" time="0.001329">
      <failure message="false" type="REQUIRE">
at C:\ubuntu\temp\tests-main.cpp(16)
      </failure>
    </testcase>
    <testcase classname="tests.exe.global" name="2A" time="0.000069"/>
    <testcase classname="tests.exe.global" name="2A/2" time="0.000996">
      <failure message="false" type="REQUIRE">
at C:\ubuntu\temp\tests-main.cpp(23)
      </failure>
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>
```

**Comment by horenmar** [comment]
Assertions inside listeners (and reporters) are not supported. Consider a case where a listener's `assertionStarting` method contains another assertion -- it will cause an infinite recursion.

The reason why only the JUnit reporter causes a hard error is that it is the only bundled reporter that uses the _CumulativeReporter_ concept, that is, it is the only reporter that requires all assertions in all test cases to be finished before it can write out the output. Combined with the fact that listeners are given events _before_ reporters, what happens is that the JUnit reporter is told "hey, an assertion started" before it is told "hey, a test case started". For obvious reasons, this does not make sense and the assert happens.


```
```

**Comment by bna080** [comment]
I have removed all the assertions from the listeners and all works well now. Thank you.
