### ISSUE TITLE
Setup() / TearDown()

### ISSUE THREAD

**Issue by jpan127** [catchorg/Catch2#1620]
**Description**
I have been using GoogleTest at work for awhile now but for my small and quick personal project I wanted something a little more lightweight: Catch2.  One of the paradigms of GTest is creating fixtures (classes) that have an explicit `Setup()` in which objects and state are initialized, and `TearDown()` in which objects are deinitialized if there is logic outside destructors.  This is extremely useful for code reuse as N tests can belong to the same fixture and have the same start and end logic.

Is there something similar for Catch2?  I have read #851 but it seems to be a global registration, not a fixture-based registration.  For example, I would want 5 test fixtures, with their own start and end logic, modifying instance-based member variables of the fixture.

**Additional context**
```c++
class Fixture {
  public:
    void SetUp() {
        object_ = std::make_unique<SomeObject>();
    }

    void TearDown() {
        object_->do_something();
    }

  private:
    std::unique_ptr<SomeObject> object_;
};

TEST_CASE_METHOD(Fixture, "", "") {
    /// SetUp() implicitly called here
    object_->do_work();
    /// TearDown() implicitly called here
}
```

**Comment by slurps-mad-rips** [comment]
Why not place your setup in the Fixture's constructor and the teardown in its destructor?

**Comment by jpan127** [comment]
@slurps-mad-rips Is a fixture constructed / destructed for each test case method?

**Comment by slurps-mad-rips** [comment]
Have you read the documentation?

**Comment by horenmar** [comment]
1) Use constructors and destructors, each `TEST_CASE_METHOD` has its own completely separate instance of the underlying object.
2) It is generally recommended to use `SECTION`s if possible:

```cpp
TEST_CASE(...) {
    std::cout << 'A';
    SECTION(...) {
        std::cout << 'A';
    }
    SECTION(...) {
        std::cout << 'B';
    }
    SECTION(...) {
        std::cout << 'C';
    }
    std::cout << '\n';
}
```

will print out
```
AA
AB
AC
```

**Comment by jpan127** [comment]
I was thinking the information would be in https://github.com/catchorg/Catch2/blob/master/docs/test-fixtures.md, but I guess it is in some other file.

Thanks @horenmar for confirming!
