### ISSUE TITLE
Sections: "grouping" / non-nested sections / run multiple sections

### ISSUE THREAD

**Issue by meastp** [catchorg/Catch2#1625]
**Description**
I have looked at and am intrigued by the sections feature of Catch2 (I'm currently using googletest). I'm not sure if my use case is covered while avoiding duplication of code.

I want to be able to use `TEST_CASE` and `TEMPLATE_TEST_CASE` with multiple inputs. In googletest this is not possible, and requires quite a lot of boilerplate code.

According to the documentation:

> One leaf section is executed on each run through a `TEST_CASE`. The other sections are skipped. Next time through the next section is executed, and so on until no new sections are encountered.

What I want to be able to do is the following, using `MULTIPLIER` as a placeholder: 

```
TEST_CASE( "vectors can be sized and resized", "[vector]" ) {

    std::vector<int> v;

    MULTIPLIER( "input_testdata", { v = {1, 2, 3}; }, { v = {4, 5, 6}; }, { v = {7, 8, 9}; })
    
    SECTION( "reserving bigger changes capacity but not size" ) {
        v.reserve( 10 );

        REQUIRE( v.size() == 5 );
        REQUIRE( v.capacity() >= 10 );

        SECTION( "reserving smaller again does not change capacity" ) {
            v.reserve( 7 );

            REQUIRE( v.capacity() >= 10 );
        }
    }
}
```

This example would run 3 * <number of times test_case would run without `MULTIPLIER`>:
- first, with v = {1, 2, 3}
- then, with v = {4, 5, 6}
- then, with v = {7, 8, 9}

**Comment by meastp** [comment]
My use case is running a test case with multiple different databases (PostGIS, Oracle, SQL Server...) and multiple input datasets.

An alternative is to expand the TEMPLATE_TEST_CASE to also take a range/array of values/input datasets.

**Comment by horenmar** [comment]
Sounds like you want to read the documentation for Generators.

**Comment by meastp** [comment]
Wow, that's it. Thanks :)
