### ISSUE TITLE
TEMPLATE_TEST_CASE: "duplicate type detected" should not be an error (allow duplicate types)

### ISSUE THREAD

**Issue by VioletGiraffe** [catchorg/Catch2#1628]
"Duplicate type" is a very inconvenient error as it will make some simple test cases require a lot of boilerplate code to circumvent this compile-time check. The thing is that certain types may or may not be synonymous depending on the current platform, and when writing cross-platform code, one may just want to list all imaginable types. Sure, the test case may run twice for the same actual type, but so what? 

Example: `size_t` may be a synonym for `unsigned long` - then `size_t` is incompatible with `unsigned long long`, or it could be vice versa. I wanted to simply list all three (`size_t, unsigned long, unsigned long long`) and I got this compilation error.

**Comment by horenmar** [comment]
That is a good point we did not consider.
