### ISSUE TITLE
Compile very slow on MSYS2 using multi files compile method but fast on Linux

### ISSUE THREAD

**Issue by maobaoqi** [catchorg/Catch2#1637]
**Describe the bug**
Hi, I try to use Catch2 on Linux and it's great! Using multi files compile method introduced by docs description, it's fast when recompile test cases. However, it's very slow on MSYS2 platform using same compile method.

Is there platform checking in single header file? I do not know. So, may be it's not a big question, thanks!

**Comment by guru-florida** [comment]
I can confirm this as well. It's not as much the compilation but the linking step that I've measured takes 35 seconds. I have just 2 files (main + 1 tests file) and a few small tests. It was pretty much instant before migrating to Catch2 (from my own simple tester). Not sure why linking a Catch2 binary would take so long...seems like the hard work is done at that point.

I really like Catch2 though. I have it integrated with CLion and TeamCity. Using regular TEST_CASE and SCENARIOs. I love it!...beside the 35sec recompile time. :)

**Comment by guru-florida** [comment]
This SO thread might help: (looks like a bug in MSYS forking implementation)
https://stackoverflow.com/questions/929495/why-is-mingw-very-slow

**Comment by guru-florida** [comment]
FYI  I tried Cygwin as well. Worse at 40sec link time.

**Comment by maobaoqi** [comment]
@guru-florida thanks for your reply.
