### ISSUE TITLE
Add WORKING_DIRECTORY support to CatchAddTests execute_process

### ISSUE THREAD

**Issue by creffett** [catchorg/Catch2#1640]
**Description**
It would be helpful to support passing a working directory to the command that runs (test executable) --list-tests; in my case my test executable needs access to external DLLs and fails if those DLLs aren't available. I solve this in the tests by passing WORKING_DIRECTORY to catch_discover_tests, but the discovery itself fails because it's not running in the right directory. I've solved this locally by adding ` WORKING_DIRECTORY "${TEST_WORKING_DIR}"` to execute_process, but I'm not sure if that will work correctly in the general case.

**Comment by philbucher** [comment]
I had the same problem and it was solved by #2039 
Hence I think this issue can be closed
