### ISSUE TITLE
[Feature Request] Check for standard library concepts

### ISSUE THREAD

**Issue by MBalszun** [catchorg/Catch2#1641]
**Description**
When implementing a custom container, one often wants to make sure it is compatible with the interface of standard library containers (has all the member aliases like value_type, size_type, iterator .., has the correct member functions (begin, end, size, data) and in particular that the iterators satisfy the standard library requirements for random_access / bidriectional ... iterators. 

It would be great if catch2 could provide tests for this out of the box e.g. either concept style `static_assert(satisfies_random_access_iterator_concept<my_container::iterator>())` or just plain `satisfies_random_access_iterator_concept<my_container::iterator>();` that fails to compile if my iterator doesn't satisfy that concepts (The latter might be better in terms of compile time).

**Comment by Quincunx271** [comment]
When we get concepts as a language feature, this will be doable as just `static_assert(std::RandomAccessIterator<my_container::iterator>)` (or using `STATIC_REQUIRE`, as that uses a `static_assert` under the hood).

For the moment, the [Boost Concept Checking library](https://www.boost.org/doc/libs/1_70_0/libs/concept_check/reference.htm) has concepts for [iterators](https://www.boost.org/doc/libs/1_70_0/libs/concept_check/reference.htm#iterator-concepts) and the like, which may be a reasonable way to work around this.

**Comment by horenmar** [comment]
Using `STATIC_REQUIRE` with the concepts proper is the correct answer.

**Comment by MBalszun** [comment]
@horenmar : Correct me if I'm wrong, but there don't exist any standard library concepts for containers or for c++17 style named requirements in general.

What I've been asking for is for Catch to provide such concepts.

**Comment by horenmar** [comment]
Okay, but I am not interested in providing them as part of Catch2, for multiple reasons. The two big ones are:

* Concepts themselves are orthogonal with testing. A distinct library can provide these for any unit testing library.
* Providing the checks is a lot of work for relatively niche feature.

**Comment by MBalszun** [comment]
Fair enough
