### ISSUE TITLE
catch_discover_tests breaks when test description is long (wraps with --list-tests)

### ISSUE THREAD

**Issue by Quincunx271** [catchorg/Catch2#1645]
**Describe the bug**

Long test descriptions are mis-parsed by CatchAddTests.cmake and are parsed as multiple tests (of which neither is actually a test).

This is because `--list-tests`` wraps long test descriptions, and CatchAddTests.cmake assumes each test description is on a single line.

**Expected behavior**

Either `--list-tests` should have a way to forbid wrapping of test descriptions, or CatchAddTests.cmake needs more work

**Reproduction steps**

Running the test executable with `--list-tests` wraps the test description if the string is long enough:

https://github.com/catchorg/Catch2/blob/00347f1e79260e76d5072cca5b3636868397dda5/include/internal/catch_list.cpp#L45

However, CatchAddTests.cmake assumes the tests are newline delimited:

https://github.com/catchorg/Catch2/blob/00347f1e79260e76d5072cca5b3636868397dda5/contrib/CatchAddTests.cmake#L82

This means that a test case with a long enough name is parsed as two test cases.

**Platform information:**

 - Catch version: **v2.8.0**

**Comment by horenmar** [comment]
I think that in the future `CatchAddTests` should add them with the `-w NoTests` flag, so that similar breakage is an error.

Anyway, because I don't do CMake scripting unless it is absolutely critical, this issue will have to go into the "help needed" heap for now.

**Comment by Quincunx271** [comment]
On further reflection, I don't think this is solvable entirely inside CMake. If the line wraps when there are multiple spaces, the `Column( ... )` mechanism strips the whitespace in between:

```
TEST_CASE("Some      Test")
```

If it wraps after `Some`, `Test` is indented, but the exact amount of spaces between `Some` and `Test` is lost, as far as I can tell. This test name cannot be reproduced.

------------

One idea I have is to make the column width effectively infinite, by setting it to a very large number such as `std::numeric_limits<size_t>::max()`. This could be controlled by a flag.

Another idea I have is to have a flag to spit out a machine-readable list of test cases, rather than a human-readable list.

Another workable, but not ideal idea is to run the tests with `-s` early instead of discovering the tests, parsing the output, and having the CTest tests simply spit out the output. This sucks as a solution, because the tests are a lie and don't actually run the tests, and because it's noisy.

**Comment by Quincunx271** [comment]
Actually, I just discovered `--list-test-names-only`, which doesn't wrap the names. I'll look into updating the CMake script to work mainly off of this flag.

**Comment by horenmar** [comment]
> Another idea I have is to have a flag to spit out a machine-readable list of test cases, rather than a human-readable list.

This will happen in v3, because all the output will be routed through the Reporters, so e.g. XMLReporter can write out the list of all tests as a valid XML.

**Comment by Quincunx271** [comment]
Prior to https://github.com/catchorg/Catch2/commit/d4eec016a9df54a560d82e5ee12aef42822525e7 , this problem didn't occur, because CatchAddTests.cmake used `--list-test-names-only`. This commit splits out the tags and adds them as CTest labels.

Reverting this commit would be the easy solution, but I can see wanting the tags as labels. The wip I have tries to add back in tags as labels, but CatchAddTests.cmake breaks the rules of `add_test` because the test names aren't valid CMake identifiers, so my fix doesn't work.

We should probably go to upstream CMake to see if we can allow arbitrary strings as `add_test` names or at least a way to control the name that CTest outputs even if internally we have to mangle the name.

**Comment by Quincunx271** [comment]
Upstream CMake issue: https://gitlab.kitware.com/cmake/cmake/issues/19391
