### ISSUE TITLE
how to add catch2 to existing code base

### ISSUE THREAD

**Issue by laoshaw** [catchorg/Catch2#1647]
This is really a newbie question, assuming I have an existing c++ code base and want to add unit testing into it.

CATCH_CONFIG_MAIN provides main() but my code of course always has its own main(), how will this work?

Is there a way to turn off catch2 in production builds?

**Comment by acgetchell** [comment]
Put Catch’s main in a test directory along with your tests and tell CMake to build your test executable. Here’s an example in production code: https://github.com/acgetchell/CDT-plusplus/tree/develop/tests

**Comment by laoshaw** [comment]
This separates test totally from production code, which is clean but could get out of sync over time. Is it possible to put unit-tests directly in production code(this way when I update a method, I can update the test function directly instead of tracking an external file), and catch2 has a way to find all those unit test functions and compile/run them via its own main()?

**Comment by acgetchell** [comment]
If you follow TDD orthodoxy, anytime you’re adding a feature you should be writing a test for non-existent code and getting a fail. Then writing just enough code to get it to pass. Then refactor as appropriate. Red-green-refactor. 

That way, your tests don’t get out of sync, they’re inherent documentation. 

(I also use Doxygen to mark up my functions and data and auto generate documentation per Literate Programming, but that’s another topic.)

Also, when I find bugs, I write a test to replicate the bug and then fix it.

One could also change `CMakeLists.txt` to just detect all *.cpp files in the test directory, but that is not considered to be good CMake practice.

**Comment by laoshaw** [comment]
Thanks. time to learn TDD then. I used to just add a few unit-test inside the code, a trade-off between no unit-tests at all and a full-blown TDD, maybe it's time to upgrade to TDD.
