### ISSUE TITLE
Using Catch2 with GCC on MacOS and sanitizer causes extremely large number of linker warnings

### ISSUE THREAD

**Issue by eferri** [catchorg/Catch2#1657]
**Describe the bug**
Trying to compile a simple catch2 program on MacOS using Homebrew GCC 8 or GCC 9 causes an extremely large number of linker warnings when the undefined behaviour sanitizer is used. Example of the warnings from a simple test program are attached.

`ld: warning: direct access in function 'std::__lg(long)' from file '/var/folders/k8/v9d4qphj23z402_dr2qrkqy40000gn/T//ccJVhtlZ.o' to global weak symbol 'std::__cxx11::regex_traits<char>::lookup_collatename<char const*>(char const*, char c
onst*) const::__collatenames' from file '/var/folders/k8/v9d4qphj23z402_dr2qrkqy40000gn/T//ccJVhtlZ.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with differ
ent visibility settings.`

**Expected behavior**
No linker errors. 

**Reproduction steps**
Steps to reproduce the bug.

1. Create the following program

```
[Uploading log.txt…]()
#define CATCH_CONFIG_MAIN

#include "catch.hpp"

TEST_CASE("Basic Member Test", "[interval]") {
  REQUIRE(true);
}
```
2. Compile with

`g++-8 test.cpp -fsanitize=undefined -o test`

**Platform information:**
 - OS: **MacOS 10.14.5**
 - Compiler+version: **GCC v8.3.0 from Homebrew**
 - Catch version: **v2.8.0**

**Additional context**
I have tried with Homebrew Catch2 as well as a pre-built header file from this repository, and the issue occurs in both versions. This issue does not happen with Apple Clang.

[log.zip](https://github.com/catchorg/Catch2/files/3287709/log.zip)

**Comment by horenmar** [comment]
As far as I can tell, this is because of mismatched visibility settings between the way the stdlib was built and what you compile with. Try using `-fvisibility=default` or `fvisibility=hidden`.

**Comment by eferri** [comment]
This still seems to happen with both `-fvisibility=default` and `-fvisibility=hidden`. It doesn't happen with the address sanitizer though, so maybe this is unrelated to catch2? Not entirely sure as I am not able to reproduce with other libraries.

**Comment by eferri** [comment]
Saw this issue with another library. Closing as its likely not related to catch2.

**Comment by horenmar** [comment]
Thanks for letting us know.
