### ISSUE TITLE
Add mocking support

### ISSUE THREAD

**Issue by Viatorus** [catchorg/Catch2#1659]
**Description**
If you want to mock an interface in C++, there are two well known frameworks, which are:

* [GMock](https://github.com/google/googlemock/tree/master/googlemock) feature-rich but with an old school API and no seamless integration with Catch (GMock throws exceptions on mocking failure)
* [FakeIt](https://github.com/eranpeer/FakeIt) with a nice API, but sadly, by using some compiler internal vtable modification. It does not support all kinds of mocking (no virtual inheritance, no multiple inheritance, optimization limitation).

I have the strong opinion, that we can create a better API than GMock (by supporting only newer CPP standards) but overcome the limitation of FakeIt.

**Additional context**
I would love to support this feature with planning and PRs.

Guys, should we give it a try?

**Comment by Viatorus** [comment]
There is https://github.com/rollbear/trompeloeil. 

I think it is a good alternative to all.

**Comment by ChooseYourPlan** [comment]
So no further development in this?

**Comment by matepek** [comment]
This is might interesting for someone: [https://github.com/matepek/catch2-with-gmock](https://github.com/matepek/catch2-with-gmock)

**Comment by sinojelly** [comment]
Maybe someone is interested in this :  https://github.com/sinojelly/catch2-with-mockcpp

More information can be found here : https://github.com/sinojelly/mockcpp
