### ISSUE TITLE
GENERATE(as<int>{}) with MSVC does not compile

### ISSUE THREAD

**Issue by kaidokert** [catchorg/Catch2#1664]
**Describe the bug**
Using GENERATE with `as<int>{}` does not compile, and neither do things like GENERATE_COPY with `as<function pointer type>`. GENERATE with other type casts seems to work fine.

Error:
`Catch.hpp(3820): error C2535: 'Catch::Generators::SingleValueGenerator<T>::SingleValueGenerator(T)': member function already defined or declared` ( see godbolt or [catch_err.txt](https://github.com/catchorg/Catch2/files/3317427/catch_err.txt) for full context )

**Expected behavior**
The code should compile as it does with Clang and GCC
**Reproduction steps**

```
#include <catch.hpp>
TEST_CASE("a","b") {
  auto a = GENERATE(as<int>{},1); // error
  auto b = GENERATE(as<char>{},1); //works fine
  auto c = GENERATE(as<long>{},1); //works fine
}
```

Longer sample: https://godbolt.org/z/7vLGWz

**Platform information:**
- OS: Windows
- Compiler+version: MSVC v19.20, Visual Studio 2017, Visual Studio 2019
- Catch version: trunk ( as of 2.9.1 ) 

**Additional context**
I found this when trying to use GENERATE_COPY with function pointers, testing my own code against reference implementation, i.e. `auto func = GENERATE_COPY(as<FuncPtr>{}, func1, func2)`. This works fine on GCC/Clang. 

Oddly, `int` is the only integral type where it fails, others seem fine.

**Comment by horenmar** [comment]
Interesting, I'll take a look at it.

**Comment by kaidokert** [comment]
Did you have a chance to investigate this ? I just had another look and the godbolt still fails with updated msvc 19.22, too.

**Comment by horenmar** [comment]
I don't have a workaround for this in Catch, but MSVC can compile the code if you specify `/permissive-`, which I'd recommend you to use anyway.
