### ISSUE TITLE
CMake build fails if compiler/toolchain's default C++ standard is not C++11 or newer

### ISSUE THREAD

**Issue by jenisys** [catchorg/Catch2#1665]
CATCH2-VERSION: 2.9.1 (was OK in: 2.8.0 AFAIK)

**Describe the bug**
The CMake build fails with the latest version of Catch2, if the compiler has a default C++ standard less than C++11. You are better off, if the "CMakeLists.txt" file specifies the minimum STD-C++ version that should be used while building. Otherwise, you rely on the compiler/toolchain which is out of your control.

The following FIX solves the problem:
```cmake
# -- FILE: CMakeLists.txt (in root-directory)
...
project(Catch2 LANGUAGES CXX VERSION 2.9.1)

# -- NEEDS: To ensure that compiler uses -std=c++11 or newer (at least).
set(CMAKE_CXX_STANDARD 11)  # Enable C++11 standard (or newer)
...
```

**Expected behavior**
* CMake build should not fail while building objects.
* If the compiler's default STD-C++ version is not greater or equal C++11, then the CMake file should enforce that CXX_STANDARD=11 (or better) is used.

**Reproduction steps**
Use a compiler version that still uses -std=c++98 as default C++ standard if none is specified. Then run cmake

```sh
$ cmake --build .
Scanning dependencies of target SelfTest
[  0%] Building CXX object projects/CMakeFiles/SelfTest.dir/SelfTest/TestMain.cpp.o
In file included from /Users/jens/se/_EXPLORE/cxx.test_frameworks/third_party/Catch2/projects/SelfTest/TestMain.cpp:10:
In file included from /.../Catch2/include/catch.hpp:52:
In file included from /.../Catch2/include/internal/catch_tag_alias_autoregistrar.h:10:
/.../Catch2/include/internal/catch_common.h:50:63: error: 
      expected ';' at end of declaration list
        SourceLineInfo( char const* _file, std::size_t _line ) noexcept
...  
# -- HINT: noexcept C++ keyword is causing the problem.       
```

**Platform information:**
 - OS: **macOS 10.14.x**
 - Compiler+version: **Apple LLVM version 10.0.0 (clang-1000.11.45.5)**
 - Catch version: **v2.9.1** (was OK in: v2.8.0)

**Additional context**

Problem was probably introduced in the following commit (just by reading the commit-message):

```
commit b87caafd9117bf7004af13fe2c806cdb5957d87c
Author: Jayesh Badwaik <public@jayeshbadwaik.in>
Date:   Sun May 5 00:23:53 2019 +0200
 
  Remove explicit setting of CXX_STANDARD for SelfTest target 
```

**Comment by horenmar** [comment]
Use either a toolchain file, or tell CMake to enable C++11 with `-DCMAKE_CXX_STANDARD=11`.

The point of the change is to make Catch's build respect the standard ways of setting up C++ standard in CMake.

**Comment by jenisys** [comment]
Sorry, I disagree.
Catch2 has the assumption / requirement that at least C++11 is used.
Therefore, CMakeLists.txt should check that this assumption is fulfilled.

And you should at least mention the suggested approach in the docs, like:
[cmake-integration.md](https://github.com/catchorg/Catch2/blob/master/docs/cmake-integration.md)

**Comment by janisozaur** [comment]
I second the request.

Additionally, the `cpp98` tag of this repository should be removed.

**Comment by horenmar** [comment]
@janisozaur The C++98 supporting version is still kept in a branch and can be used by people stuck there, so I am not sure if it really should be removed (but if more people speak up, I don't have trouble with the idea).

@jenisys Okay, I'll make the project default to C++11 if no standard is specified.
