### ISSUE TITLE
Is it possible to remove all of the extra targets when doing CTest integration?

### ISSUE THREAD

**Issue by dbak-invn** [catchorg/Catch2#1669]
Because I have to do `include(Catch)` to do `catch_discover_tests`, I get a ton of extra targets that I do not need:

```
C:\Users\dbak\Projects\testing\cmake-build-debug>cmake --build . --target help
The following are some of the valid targets for this Makefile:
... all (the default if no target is provided)
... clean
... depend
... NightlyMemoryCheck
... Experimental
... ContinuousSubmit
... ContinuousConfigure
... NightlyTest
... NightlyStart
... NightlyBuild
... NightlySubmit
... NightlyConfigure
... ContinuousTest
... Continuous
... Nightly
... NightlyUpdate
... NightlyCoverage
... NightlyMemCheck
... ExperimentalStart
... ExperimentalUpdate
... ExperimentalConfigure
... ExperimentalBuild
... ExperimentalTest
... ExperimentalCoverage
... ExperimentalMemCheck
... ExperimentalSubmit
... ContinuousBuild
... ContinuousStart
... ContinuousUpdate
... ContinuousCoverage
... ContinuousMemCheck
```

Is it possible to avoid adding all of these unnecessary targets?

Also, it is not clear to me where these are even coming from. None of these targets are mentioned in catch.hpp, nor are they mentioned in Catch.cmake or CatchAddTests.cmake

**Comment by horenmar** [comment]
Those are CTest targets. If you are doing `include(CTest)`, you might be able to get away with just `enable_testing()` instead.

**Comment by rummanwaqar** [comment]
From [Stackoverflow](https://stackoverflow.com/questions/56089330/cmake-creates-lots-of-targets-i-didnt-specify/59493613#59493613
)

You can disable the CTest targets in your project
set_property(GLOBAL PROPERTY CTEST_TARGETS_ADDED 1)
