### ISSUE TITLE
WIN32 not defined yet

### ISSUE THREAD

**Issue by matt77hias** [catchorg/Catch2#1676]
Hey, I have some possible (as I manually configure MSBuild) compilation on Windows 10 (VS2019).

**internal\catch_session.h**

```c++
#if defined(CATCH_CONFIG_WCHAR) && defined(WIN32) && defined(UNICODE)
        int applyCommandLine( int argc, wchar_t const * const * argv );
#endif
```
`WIN32` is not defined (yet).

**internal\catch_session.cpp**

```c++
#if defined(CATCH_CONFIG_WCHAR) && defined(WIN32) && defined(UNICODE)
    int Session::applyCommandLine( int argc, wchar_t const * const * argv ) {
...
    }
#endif
```
`WIN32` is defined.

**Solution**: move `#include "catch_windows_h_proxy.h"` before `"#include "catch_session.h"`.

I am running the trunk version.

**Comment by horenmar** [comment]
Upon closer inspection, the macro used should `_WIN32`, but given the other issues you've opened, it seems that your build is fundamentally broken.

**Comment by JoeyGrajciar** [comment]
Are you including header from `single_include/catch2` folder? or from `include` folder?

**Comment by matt77hias** [comment]
I will provide a minimal example containing the VS2019 solution later
today. Basically, I just build a static lib (so not the header-only
version) and link against that for my test executable. The latter
originally used doctest, but I replaced that with all the corresponding
Catch2 includes and macros. Building the lib and exe succeeds.
