### ISSUE TITLE
No available reporters

### ISSUE THREAD

**Issue by matt77hias** [catchorg/Catch2#1678]
msvc++ (C++17) on Windows 10:

#define CATCH_CONFIG_RUNNER
#include <catch2/catch.hpp>

```c++
int main(int argc, char** argv)
{
	// MAGE setup.
	mage::Initialize();

	// Catch setup.
	Catch::Session session;

	const int result = session.applyCommandLine(argc, argv);
	if (result != 0)
	{
		return result;
	}

	return session.run();
}
```

Running my .exe with `--list-reporters`, no reporters are enumerated.

Running my .exe with no arguments: `No reporter registered with name: 'console'`

If I use the default main implementation from Catch2, the problem remains.

**Comment by horenmar** [comment]
Can you provide a [small and compilable example](http://sscce.org/)?

**Comment by matt77hias** [comment]
VS2019 solution: https://www.dropbox.com/s/vyephg8dhyn75ka/Widget.rar?dl=0

**Changes** (to make it compile):

- Added a "internal/catch_session.h" include to "catch.hpp":
```
#ifdef CATCH_CONFIG_RUNNER
#include "internal/catch_session.h"
#endif
```
- Made the "catch_windows_h_proxy.h" include the first include in "catch_session.cpp" (it should be included before "catch_session.h" as `WIN32` was not defined in that header yet.

**Minor changes:**

- Prefixed some includes (e.g., "catch_interfaces_runner.cpp") with "../"  as I only added `Code/External/catch2` to the include directories.
- Replaced "external/clara.hpp" with the trunk of Clara in the `Code/External/clara` directory instead of the `Code/External/catch2` directory.

**Comment by horenmar** [comment]
So yeah, you are running into a linker problem, because you are compiling catch as a static library.

To register a reporter, Catch creates a global object whose constructor registers the reporter with the reporter factory. The problem is that when you compile a static library with MSVC, the linker will not link the constructors of global objects into the resulting binary, unless the objects are further referenced -- however, because their only use is the construction side effect, they are not further referenced and will not be part of the final binary.

**Comment by matt77hias** [comment]
@horenmar thank you very much for explaining the problem! (This also explains why CMake results in a working solution as the `SelfTest` project compiles both the Catch library and the tests without relying on a lib.)

So I just added:

```
#include <catch2/reporters/catch_reporter_console.h>
namespace Catch
{
	CATCH_REGISTER_REPORTER("console", ConsoleReporter)
}
```
to the .exe project which makes it work like a charm.

**Comment by horenmar** [comment]
You can also use the [`/wholearchive` linker flag](https://docs.microsoft.com/en-us/cpp/build/reference/wholearchive-include-all-library-object-files?view=vs-2019).
