### ISSUE TITLE
Ability to mock malloc/free functions without breaking Catch2

### ISSUE THREAD

**Issue by RonAmihai** [catchorg/Catch2#1681]
I'm working on a C library which is intended to work in memory constrained environments (with an emphasis on Embedded RTOS/frameworks like [Zephyr](https://github.com/zephyrproject-rtos/zephyr) and [ESP-IDF](https://github.com/espressif/esp-idf) ). 

Some parts of this library are depend on dynamic memory allocation, ie stdlib's malloc/free functions. 

As part of the library development, I'm trying to write unit tests using Catch2 and [FFF (Fake Function Framework)](https://github.com/meekrosoft/fff) as function-mocking framework.

In order to fully unit-testing the library's functionally, **I need to mock malloc/free functions in some of my tests** in order to test behavior in critical memory situations (which aren't rare in embedded environments)

**This actually can't be done using Catch2 because "registerTestMethods" function in catch.hpp is using malloc/free.** 

(I Know I can just wrap calls to malloc/free in my library with my own custom macros, and manipulate them for testing, but I'm really not excited to take this approach for such trivial methods...)

I think we should think of an "side feature" to enable "registerTestMethods" to not rely on malloc/free functions - in order to enable proper unit-testing of global (plain C) methods which are using dynamic memory allocation.

**Comment by horenmar** [comment]
Catch2 uses dynamic allocations and there are no plans to change that.

**Comment by JoeyGrajciar** [comment]
Closing based on previous comment.
