### ISSUE TITLE
-w NoTests should give non-zero status

### ISSUE THREAD

**Issue by sd-x** [catchorg/Catch2#1683]
docs/command-line.md says "NoTests        // Return non-zero exit code when no test cases were run" but I see a status of zero being returned instead of non-zero

my_bug.cpp:
```#define CATCH_CONFIG_MAIN
#include "catch2/catch.hpp"

TEST_CASE("my case", "[foo]") {
  SECTION("my section") {
    CHECK(1);
  }
}
```
```
> g++ -o my_bug my_bug.cpp -I ...
> ./my_bug -w NoTests '[x]'
Filters: [x]
No test cases matched '[x]'
===============================================================================
No tests ran

status=0
```

I expected a non-zero status.

**Platform information:**
 - OS: **Linux CentOS 6**
 - Compiler+version: **GCC v7.3.0**
 - Catch version: **v2.9.1**

**Comment by sfranzen** [comment]
This was also reported in issue #1449 I happened to be working on, so there is a pull request underway to fix it and make it part of the self-testing suite.

**Comment by sd-x** [comment]
Ah, thanks; I missed that issue when I searched, sorry.  I'll close this issue.

**Comment by sfranzen** [comment]
No problem! The other issue is different but related, another user reported the missing exit code in a reply.
