### ISSUE TITLE
Clang *crashes* with SIGILL for REQUIRE() with C++17 and OpenMP.

### ISSUE THREAD

**Issue by ldalessa** [catchorg/Catch2#1687]
**Describe the bug**
[I reported this as a bug to the clang team](https://bugs.llvm.org/show_bug.cgi?id=42586), but I'm adding this report so that you are aware of this.

Using a simple `REQUIRE` macro causes clang to abort with a `SIGILL` during compilation when `C++17` and `-fopenmp`.

**Expected behavior**
Well... anything other than clang crashing with `SIGILL`.

**Reproduction steps**

Compile the following with `$ clang++ -Xclang -fopenmp -std=c++17 -o test.o -c test.cpp`.

```C++
#include <catch.hpp>

TEST_CASE ("Test", "") {
  auto t0 = std::make_tuple();
  REQUIRE (std::tuple_size_v<decltype(t0)> == 0);
}
```

```bash
Lukes-MacBook:test ldalessa$ clang++ --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Lukes-MacBook:test ldalessa$ cat test.cpp 
#include <catch.hpp>

TEST_CASE ("Test", "") {
  auto t0 = std::make_tuple();
  REQUIRE (std::tuple_size_v<decltype(t0)> == 0);
}

Lukes-MacBook:test ldalessa$ clang++ -Xclang -fopenmp -std=c++17 -save-temps -o test.o -c test.cpp
clang: error: unable to execute command: Illegal instruction: 4
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/nm/j3bknc2n2t7f8llmt1m8j4680000gn/T/test-36c4ea.cpp
clang: note: diagnostic msg: /var/folders/nm/j3bknc2n2t7f8llmt1m8j4680000gn/T/test-36c4ea.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /Users/ldalessa/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg: 

********************
```

**Platform information:**

 - OS: **Mac OS X**
 - Compiler+version: **Apple LLVM version 10.0.1 (clang-1001.0.46.4)**
 - Catch version: **HEAD**

**Additional context**
I'm sure this isn't a Catch2 problem but maybe someone else will find this and they'll be able to track the clang issue.

**Comment by horenmar** [comment]
Yeeeeah, that is a compiler bug. Also I am not sure that the LLVM issue tracker is the right place to report bugs in the Apple-specific version.

**Comment by ldalessa** [comment]
For sure. I don't have access to my normal Linux development box at the moment so I couldn't really figure out a good way to see if this is impacting normal clang, and the Apple bug reporting site is actually so confusing that I gave up. I'm hoping that this hits all of clang or that someone at Apple trolls llvm bugs for Apple stuff.
