### ISSUE TITLE
constexpr GENERATE

### ISSUE THREAD

**Issue by ldalessa** [catchorg/Catch2#1702]
**Description**
I have a template header library for HPC that is parameterized by a `size_t` that indicates dimensionality of the underlying space. I have unit tests for `N=1,2,3` and sometimes higher dimensions. I am currently handling this through the use of either test duplication or indirection through a template function.

It would be great if it were possible within `catch2` to manifest a `constexpr` `GENERATOR`. I'm not familiar with the underlying mechanism that `catch2` is using to deal with enumerating generated parameters. I generally use `index_sequence` to deal with this in our code base.

**Additional context**
```
TEST_CASE ("Test", "[]")
{
  constexpr auto N = GENERATE(1u, 2u, 3u);
  Foo<N> foo;
  ...
}
```

**Comment by horenmar** [comment]
Sounds like you want template test cases, [the NTTP variant in particular](https://github.com/catchorg/Catch2/blob/master/docs/test-cases-and-sections.md#signature-based-parametrised-test-cases).

**Comment by ldalessa** [comment]
You're probably right, however I can't make heads or tails of what this section actually means. If I have a single parametric `size_t` and I'd like to instantiate the test case for `1, 2, 3`, is that simple?

**Comment by horenmar** [comment]
```cpp
TEMPLATE_TEST_CASE_SIG("Foo", "[tag]", ((int Num), Num), 1, 2, 3) {
        std::cerr << Num << '\n';
}```

Will run 3 test cases, one with each of the three numbers.

**Comment by ldalessa** [comment]
Got it, thanks.
