### ISSUE TITLE
Could you add my project to Open Source projects using Catch list?

### ISSUE THREAD

**Issue by Czapa10** [catchorg/Catch2#1705]
Currently I work on this project: https://github.com/SPC-Some-Polish-Coders/PopHead/
We use Catch2 so it would be nice if you added our project to list of open source projects using catch.

**Comment by horenmar** [comment]
We prefer when project authors/maintainers open up a PR themselves, as it shows that they want to be associated with the project.

If that is problematic for some reason, I can do it later.

**Comment by Czapa10** [comment]
Oh Sorry. I just added the Pull request.
