### ISSUE TITLE
undefined reference to `__android_log_print'

### ISSUE THREAD

**Issue by gegles** [catchorg/Catch2#1720]
Compile issue on Android with latest v.2.9.2 checkin

```console
tests_main.cpp.o: In function `Catch::writeToDebugConsole(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)':
/.../catch2/single_include/catch2/catch.hpp:9995: undefined reference to `__android_log_print'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by horenmar** [comment]
Are you linking in the `log` library? (IIRC it is `LOCAL_LDLIBS    := -llog` for the Android make)

**Comment by gegles** [comment]
Ah, thank you, yes that it is. Things were compiling fine before the update, so when I got the error, I did not dig deep into before filing the bug.

I still think this dependency should come automatically when linking with the Catch2 target on Android. I simply use `add_subdirectory(catch2)` to add the whole git repo to my build tree.

Could you had the following to the top-level CMakeLists.txt?

```cmake
if (CMAKE_SYSTEM_NAME MATCHES "Android")
  target_link_libraries(Catch2 INTERFACE log)
endif ()
``` 

I can also submit a MR if you prefer.

Thanks.

**Comment by horenmar** [comment]
Yeah that makes sense -- I was under the impression that CMake + Android is still bit of a horror, so I did not bother making it part of the library interface.

It should work with current master now.

**Comment by gegles** [comment]
Cool, it works, thanks!

**Comment by Domain** [comment]
I have the same error in termux

**Comment by SergeyJames** [comment]
-DCMAKE_CXX_FLAGS="-llog" helps me
