### ISSUE TITLE
undefined reference to `__android_log_write'

### ISSUE THREAD

**Issue by Domain** [catchorg/Catch2#1725]
building master in termux:

Linking CXX executable SelfTest
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: CMakeFiles/SelfTest.dir/__/include/internal/catch_debug_console.cpp.o: in function `Catch::writeToDebugConsole(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)':
catch_debug_console.cpp:(.text+0x40): undefined reference to `__android_log_write'
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [projects/CMakeFiles/SelfTest.dir/build.make:1749: projects/SelfTest] Error 1
make[1]: *** [CMakeFiles/Makefile2:987: projects/CMakeFiles/SelfTest.dir/all] Error 2
make: *** [Makefile:165: all] Error 2

**Comment by horenmar** [comment]
Are you linking in the `log` system library?

**Comment by Domain** [comment]
I though the last commit is solving this problem?

**Comment by horenmar** [comment]
Only if your system is detected by CMake as Android. Yours isn't.
