### ISSUE TITLE
Multiple random generators generate the same values

### ISSUE THREAD

**Issue by Hedanito** [catchorg/Catch2#1734]
**Describe the bug**
When using multiple random generators, they use the same seed and thus generate the same values.

**Expected behavior**
Each random generator uses its own seed and produces different numbers

**Reproduction steps**
```
uint8_t a = GENERATE(take(10, random(0, 255)));
uint8_t b = GENERATE(take(10, random(0, 255)));
```
`a` and `b` will always have the same value

**Platform information:**
 - Catch version: **v2.9.2**

**Comment by amitherman95** [comment]
I tried to reproduce the bug:
Platform: Windows 10
Compiler: MinGW32
Catch version: 2.9.2

Code:
```
TEST_CASE("bugTest","[generators]"){
uint8_t a = GENERATE(take(5, random(0, 255)));
uint8_t b = GENERATE(take(5, random(0, 255)));
std::cout << "a=" <<(int)a <<" b="<<(int)b<<std::endl;
}
```

Output:
```
a=0 b=0
a=0 b=21
a=0 b=153
a=0 b=228
a=0 b=247
a=21 b=0
a=21 b=21
a=21 b=153
a=21 b=228
a=21 b=247
a=153 b=0
a=153 b=21
a=153 b=153
a=153 b=228
a=153 b=247
a=228 b=0
a=228 b=21
a=228 b=153
a=228 b=228
a=228 b=247
a=247 b=0
a=247 b=21
a=247 b=153
a=247 b=228
a=247 b=247
```

random() uses the same set over and over
I'll look into that

**Comment by horenmar** [comment]
Yeah, this is in many ways an intended behaviour -- the idea was to guarantee reproducible results given seed, so that the user can rerun failing test and examine what happened in greater detail.

I see that the linked PR centralizes handling of random generators, I'll have to think about it a bit.

**Comment by amitherman95** [comment]
Martin, the numbers are still reproducible, but the random generator(m_rand) is kept somewhere else, to avoid reinitialization when a GeneratorTracker decided to clear its child tracker.
