### ISSUE TITLE
Escaping special characters in test name no longer works in v2.9.2

### ISSUE THREAD

**Issue by JohnnyHendriks** [catchorg/Catch2#1737]
**Describe the bug**
When calling a test via the command line by its full name, and this name contains a special character such as `,`, `[`, `\` or `"`, it used to be possible to escape these characters and run the specific test. This no longer seems to work as of v2.9.2 of Catch2. Works just fine in all previous Catch2 versions. The [Test Adapter for Catch2](https://github.com/JohnnyHendriks/TestAdapter_Catch2) extension for Visual Studio relies on this functionality to call individual tests.

**Expected behavior**
It should be possible to call specific tests with special characters in their name via the command line by escaping the special characters, as was the case in all versions of Catch2 prior to v2.9.2.

**Reproduction steps**
Create a test with a name that contains a special character, _e.g._ "Test, special". Call the test by its full name via the commandline. Make sure you make use of Catch2 v2.9.2

```
Test.exe "Test\, special"
```
This will result in an `invalid string position` error.

The same test with any of the previous version of Catch2 are able to run the test this way.

**Platform information:**
 - OS: Windows 10
 - Compiler+version: Visual Studio 2019
 - Catch version: v2.9.2

**Comment by amitherman95** [comment]
I'm looking into it

**Comment by horenmar** [comment]
This should now work

**Comment by JoeyGrajciar** [comment]
@JohnnyHendriks was the issue resolved for you?
I am going to close this for now. If it is not resolved please reopen it.

**Comment by JohnnyHendriks** [comment]
Thank you. I checked and it looks like the issue is indeed resolved.
