### ISSUE TITLE
Add UX3D to commercial users

### ISSUE THREAD

**Issue by UX3D-schmithuesen** [catchorg/Catch2#1740]
[UX3D](https://ux3d.io) ([GitHub page](https://github.com/ux3d)) is a startup from Munich focused on GPU software and rendering related things. We use Catch2 to test our C++ applications and would enjoy being listed the [Commercial Users](https://github.com/catchorg/Catch2/blob/master/docs/commercial-users.md) page :+1: 

Apart from our closed source projects like our upcoming [glTF Scene Editor](https://www.ux3d.io/products/scene-editor), we are usually involved in several of the open source projects at [KhronosGroup](https://github.com/KhronosGroup), but there, we haven't used Catch so far.

**Comment by horenmar** [comment]
Thanks, but can you open up the PR yourself? We prefer additions to the list of users to be done by people related to the project.
