### ISSUE TITLE
Catch2 v2.9.2 will SEGFAULT if test case tag contains space

### ISSUE THREAD

**Issue by Shmoopty** [catchorg/Catch2#1741]
**Describe the bug**
Catch2 will SEGFAULT during initialization if the "tags" string contains spaces

**Reproduction steps**

Build and run the following complete program:

    #define CATCH_CONFIG_MAIN
    #include <catch2/catch.hpp>
    TEST_CASE("Settings", "[ Settings ]")
    {
        CHECK(true);
    }

The resulting program will crash with following backtrace:

    #0  Catch::(anonymous namespace)::PosixColourImpl::setColour (this=0xca6e68 <Catch::(anonymous namespace)::PosixColourImpl::instance()::s_instance>, _escapeCode=0x98e87f "[0;31m")
    at catch2/catch.hpp:8236
    #1  Catch::(anonymous namespace)::PosixColourImpl::use (this=0xca6e68 <Catch::(anonymous namespace)::PosixColourImpl::instance()::s_instance>, _colourCode=Catch::Colour::Red)
    at catch2/catch.hpp:8212
    #2  Catch::Colour::use (_colourCode=Catch::Colour::Red) at catch2/catch.hpp:8298
    #3  Catch::Colour::Colour (this=0x7fffffffe07f, _colourCode=Catch::Colour::Red) at catch2/catch.hpp:8283
    #4  Catch::Session::Session (this=0x7fffffffe220) at catch2/catch.hpp:10962
    #5  in main (argc=1, argv=0x7fffffffe488)

**Platform information:**

 - OS: **Linux**
 - Compiler+version: **GCC v9.1** (Also confirmed on v4.8.5)
 - Catch version: **v2.9.2**  (Also confirmed on v2.7.0)

**Comment by horenmar** [comment]
ugh, this bug keeps popping up and up.

The problem is that Catch tries to tell you spaces in tags are not supported, but the Posix colour subsystem is not yet initialized, so when we attempt to report the message using a red-coloured text, we access a null-pointer.

**Comment by JoeyGrajciar** [comment]
This should not happen as we are initializing the colour subsystem just before going to report startup exceptions.

**Comment by horenmar** [comment]
I can't reproduce this with an up to date versions, and the issue is positively ancient.
