### ISSUE TITLE
Data generator for pairs of values?

### ISSUE THREAD

**Issue by rcdailey** [catchorg/Catch2#1742]
I'm using data generators to exercise a function that is implemented like so:

```
constexpr bool IsStatusSuccess(Status status)
{
   auto statusValue = static_cast<unsigned>(status);
   return statusValue >= 200 && statusValue < 300;
}
```

My first thought was that it would be nice to have a data generator for pairs. That way I can map the expected result (`true` or `false`) to the respective input. However, looking through the documentation, I don't see a mechanism to do this. So this is what I have right now:

```
TEST_CASE("Verify behavior of IsStatusSuccess()")
{
   using namespace Net::HTTP;
   auto statusCode = GENERATE(199, 200, 299, 300);
   auto const isSuccess = statusCode >= 200 && statusCode < 300;
   CHECK(isSuccess == IsStatusSuccess(static_cast<Status>(statusCode)));
}
```

This functions but I don't really like "duplicating" the implementation of the method in the test case just to deduce the expected return value. It would be better to more explicitly designate which inputs should result in "false" and those that should result in "true". Another alternative is this:

```
TEST_CASE("Verify behavior of IsStatusSuccess()")
{
   using namespace Net::HTTP;

   SECTION("Success status codes")
   {
      auto statusCode = GENERATE(200, 250, 299);
      CHECK(IsStatusSuccess(static_cast<Status>(statusCode)));
   }

   SECTION("Failure status codes")
   {
      auto statusCode = GENERATE(199, 300);
      CHECK(!IsStatusSuccess(static_cast<Status>(statusCode)));
   }
}
```

But this feels too structurally verbose and there is some code duplication (the `CHECK` could be shared, like in the first example).

As a pseudocode, this is more or less what I would *like* to see:

```
TEST_CASE("Verify behavior of IsStatusSuccess()")
{
   using namespace Net::HTTP;
   auto statusCode = GENERATE(
      {199, false},
      {200, true},
      {299, true},
      {300, false});
   CHECK(statusCode.second == IsStatusSuccess(static_cast<Status>(statusCode.first)));
}
```

Is there a mechanism to do this (or something close to it) in Catch 2.9? If not, what is the most recommended solution?

**Comment by horenmar** [comment]
Do you mean [like this](https://github.com/catchorg/Catch2/blob/ce42deb72fab2be85a862f559984580c24cb76c4/projects/SelfTest/UsageTests/Generators.tests.cpp#L199)?

**Comment by rcdailey** [comment]
Yeah, now that I'm seeing this, the answer was pretty obvious all along. All `GENERATE()` does is repeat some arbitrary expression, so I can make the type whatever I want. Thanks for the eye-opener.
