### ISSUE TITLE
Catch 2.9.2 enforces requirement libandroid

### ISSUE THREAD

**Issue by fredcadete** [catchorg/Catch2#1743]
**Describe the bug**
Due to #1710, catch2 now requires linking to libandroid.

**Expected behavior**
Expected to have the same linkage requirements as before (STL only).
Or, expected a compile-time option to not have this requirement.

**Reproduction steps**
- Build 2.9.1 for Android, without linking to libandroid - OK
- Build 2.9.2 for Android, without linking to libandroid - linkage fails. Cannot find __android_log_print , from writeToDebugConsole

**Platform information:**

 - OS: **Ubuntu 18.04**
 - Compiler+version: **Clang 8.0.0**
 - Catch version: **2.9.2**

**Additional context**
In some cases it is desirable build for an Android target without expecting a requirement on the Android FW - libandroid included.

It's a nice feature btw, just would be good to opt out in some cases.
If this level of granularity in the compile-time options is not desirable by the project, I could live with patching my checkout of catch or undef'ing __ANDROID__ at the inclusion point.

**Comment by horenmar** [comment]
This should be doable in master now, can you test it out?

**Comment by fredcadete** [comment]
:ok_hand: 

With master, defining "CATCH_CONFIG_NO_ANDROID_LOGWRITE" avoids the link to libandroid.
