### ISSUE TITLE
Catch2 benchmark not working

### ISSUE THREAD

**Issue by emmettwu** [catchorg/Catch2#1745]
compile https://github.com/catchorg/Catch2/blob/master/projects/SelfTest/UsageTests/Benchmark.tests.cpp
in archlinux

output is

====================
No tests ran

compiler: g++ 9.1 in archlinux
version: catch2 2.9.2-1 installed by pacman

**Comment by horenmar** [comment]
Have you compiled it with `CATCH_CONFIG_ENABLE_BENCHMARKING`?

**Comment by emmettwu** [comment]
yes
I have added
#define CATCH_CONFIG_MAIN
#define CATCH_CONFIG_ENABLE_BENCHMARKING
to Benchmark.tests.cpp

**Comment by emmettwu** [comment]
I have recompiled, it works.

**Comment by biodranik** [comment]
@emmettwu Then you can close the issue.
