### ISSUE TITLE
Compilation error C2664 when compiling with /CLR using VS2015

### ISSUE THREAD

**Issue by jspahn80134** [catchorg/Catch2#1749]
**Describe the bug**
Compiling Catch2 produces the following error:
Error	C2664	'std::shared_ptr<Catch::TestCaseTracking::SectionTracker> std::make_shared<Catch::TestCaseTracking::SectionTracker,Catch::TestCaseTracking::NameAndLocation,Catch::TestCaseTracking::TrackerContext&,nullptr>(Catch::TestCaseTracking::NameAndLocation &&,Catch::TestCaseTracking::TrackerContext &,nullptr &&)': cannot convert argument 3 from 'nullptr' to 'nullptr &&'	

**Expected behavior**
A clean compile

**Reproduction steps**
Steps to reproduce the bug.
Create an Empty CLR project in Visual C++ (VS2015)
Include catch.hpp
Compile

**Platform information:**

 - OS: Windows 10
 - Compiler+version: VS2015 - 
Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.8.03752
Visual C++ 2015   00322-40000-00000-AA139
Microsoft Visual C++ 2015

 - Catch version: 2.9.2

**Additional context**
This does not occur for a console project that is not CLR, i.e. no STL included in the VS project. I was able to get a good Catch2 compile by creating a Win32 Console app but when I include /clr it no longer compiles. I need this for a CLR project

**Comment by horenmar** [comment]
Does this also happen with a newer visual studio?
