### ISSUE TITLE
Expose Catch::clara::Parser and co without CATCH_CONFIG_RUNNER

### ISSUE THREAD

**Issue by NightNord** [catchorg/Catch2#1756]
I have a common library that includes catch and implements special main that initialize all the codebase (memory manager, log manager, stuff like that), finalize it after the test, etc - basically performs a global setup and teardown. This library is implemented with `CATCH_CONFIG_RUNNER` and is linked with cpp's with actual tests by each library's UT.

Now I want to let actual tests also define cli flags (on per-library basis), for ease of debugging. To do so, I've made a static registry that keeps list of `Catch::clara::Parser (const Catch::clara::Parser&)` callbacks. In my main, after creating `Catch::Session` I run all those callbacks in chain, passing them `session.cli()`. Result is pushed back into `session.cli`.

It works with small exception - to actually use `Catch::clara::Parser` in my unit test files, I need to include `catch.hpp` with `CATCH_CONFIG_RUNNER`, which obviously leads to symbol redefinition and all the bad stuff

It would be nice to have some sort of `CATCH_OTHERWISE_NORMAL_BUT_WITH_THAT_CLARA_PARSER_DEFINITION_PLEASE` macro to define. I can, of course, just use external clara, but then there is non-zero probability of ODR-violation, which I would rather avoid.

**Comment by javorszkymazsi** [comment]
I have a similar issue which relates to the Catch::Clara parser. I wanted to add extra command line arguments to Catch::Session to parse for my test application to run. This works fine if I'm in one file but if I create a handler class for processing my custom arguments properly and it's in a separate file it can't be done.

**Comment by horenmar** [comment]
In v2 this was a major mess (essentially it required classifying interfaces as "internal" vs "external" vs "always-on" and then plumbing that decision around behind some preprocessor defines), and will not change.

In v3 this works without any further changes.
