### ISSUE TITLE
Approx(inf) == everything

### ISSUE THREAD

**Issue by paulfloyd** [catchorg/Catch2#1763]
**Describe the bug**
Approx(inf) with a non-zero margin is equal to any non-nan value.

**Expected behavior**
I would expect that only inf should be equal to inf.

**Reproduction steps**
This will fail

    double inf = std::numeric_limits<double>::infinity();
    REQUIRE(Approx(inf) != 1.0);

but this succeeds

     REQUIRE(Approx(inf) == 1.0);

**Platform information:**

 - OS: **Linux**
 - Compiler+version: **GCC v6.2.0**
 - Catch version: **v2.9.2**

**Additional context**
The issue arises because 

`marginComparison(m_value, other, m_epsilon * (m_scale + std::fabs(m_value)));`

With the default m_scale of 0.0 and m_epsilon of about 1e-5 (though this would apply to any non-zero value) then these arguments become

`marginComparison(inf, other, inf)`

which evaluates to

`return (lhs + margin >= rhs) && (rhs + margin >= lhs);`

or `inf + inf >= other && other + inf >= inf`

which is always true since ` inf > other && inf == inf`

**Comment by horenmar** [comment]
Ouch. The code should properly handle `nan`s, but I forgot about `inf`s.

**Comment by amitherman95** [comment]
I'm on it

**Comment by horenmar** [comment]
Should be fixed by 02ee130bd0191b084821ccfa2dfd7eba9df197aa.

**Comment by amitherman95** [comment]
Oh well
