### ISSUE TITLE
Only enforce build dir when not used as  a subproject

### ISSUE THREAD

**Issue by kinnarr** [catchorg/Catch2#1773]
**Description**
Allow in-source build when Catch2 is used as a subproject.

**Additional context**
Add ```NOT_SUBPROJECT``` to the if-statement
```
if (CMAKE_BINARY_DIR STREQUAL CMAKE_SOURCE_DIR)
    message(FATAL_ERROR "Building in-source is not supported! Create a build dir and remove ${CMAKE_SOURCE_DIR}/CMakeCache.txt")
endif()
```

**Comment by horenmar** [comment]
You should not be doing in-tree build anyway, but since the reason we check is that in-tree build leads to weird errors that should not be present when Catch2 is a subdirectory, I am willing to modify the check.
