### ISSUE TITLE
Storing match expressions in a variable causes runtime crashes

### ISSUE THREAD

**Issue by imMute** [catchorg/Catch2#1781]
If a match expression is built up and stored in a variable, which is then passed to `REQUIRE_THAT`, the test will crash.

```
TEST_CASE("Bug Demo", "[Bug]"){
    std::string str = "Bugs as a service";
    REQUIRE_THAT( str,
        Catch::EndsWith( "as a service" ) ||
        (Catch::StartsWith( "Big data" ) && !Catch::Contains( "web scale" ) ) );
    
    auto match_expression = Catch::EndsWith( "as a service" ) ||
        (Catch::StartsWith( "Big data" ) && !Catch::Contains( "web scale" ) );
    REQUIRE_THAT(str, match_expression);
}
```

The first `REQUIRE_THAT` is straight from the documentation.  The second example uses the exact same match expression, it just stores it in a variable first.  This code compiles, but crashes when running.

I've seen it crash with a message like
```
{Unknown expression after the reported line}
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal
```
but the repro above crashes with
```
pure virtual method called
...
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal
````
My test case uses custom Matcher subclasses, so that might be the reason why I get two different kinds of crashes.  I can try to replicate the SIGSEGV case in a minimal test case, but that might take a while.

**Platform information:**
 - OS: Debian 8 ("Jessie")
 - Compiler+version: Clang++ 3.5.0-10 (using libstdc+6 4.9.2-10).
  - Repro sample compiled with `-std=c++14` and `-O2`
 - Catch version: v2.10.0

**Additional context**
If the match expression is instead "stored" in a macro, it works correctly (which should be obvious).
The reason I'm storing the match expression in a variable is that I'm doing repeated tests on different pieces of data, but the pass/fail criteria is the same for all of them.

**Comment by horenmar** [comment]
The problem is that the logical operators do not take ownership of the matchers, so when you write

```cpp
auto match_expression = Catch::EndsWith( "as a service" ) ||
        (Catch::StartsWith( "Big data" ) && !Catch::Contains( "web scale" ) );
```
`match_expression` stores pointers to invalid objects after this line. The solution is to ensure that the matchers outlive the expression, e.g. by also storing them on stack.
