### ISSUE TITLE
TEMPLATE_PRODUCT_TEST_CASE not work in VS2017 and VS2019

### ISSUE THREAD

**Issue by Domain** [catchorg/Catch2#1786]
```
TEMPLATE_PRODUCT_TEST_CASE("template product","[template]",
			   (std::tuple, std::pair, std::map),
			   ((int,float),(char,double),(int,char)))
{
}
```
VS2017 15.9.8: 

> 6>C:\workspaces\test.cpp(31): error C2672: “create”: 未找到匹配的重载函数
6>C:\workspaces\test.cpp(31): error C2893: 未能使函数模板“unknown-type `anonymous-namespace'::ns_____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____6::create(`anonymous-namespace'::ns_____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____6::TypeList<Types...>) noexcept”专用化
6>C:\workspaces\tes.cpp(31): note: 用下列模板参数:
6>C:\workspaces\test.cpp(31): note: “Final=`anonymous-namespace'::ns_____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____6::____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____6”
6>C:\workspaces\test.cpp(31): note: “Containers={std::map}”
6>C:\workspaces\test.cpp(31): note: “Types={`anonymous-namespace'::ns_____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____6::TypeList<int,int>}”

VS2019 16.3.6:

> 1>test.cpp(31): error C2059: 语法错误:“)”
1>test.cpp(31): error C2143: 语法错误: 缺少“;”(在“{”的前面)

**Comment by JoeyGrajciar** [comment]
What version of Catch2?
What is exactly in the errors?

**Comment by JoeyGrajciar** [comment]
VS2017 issue looks similar to #1748 
VS2019 says something about syntax error `)` and missing `;` before `{`

Also the error says something about `int,int` and only `std::map` as container being passed to `create` helper.

Either way try 2.10.1 since this part got reworked there to support issues like #1748 .

**Comment by Domain** [comment]
@JoeyGrajciar I update to 2.10.1, and VS2017 works. But nothing changed in VS2019.

**Comment by Domain** [comment]
Oh, std::pair is not working in VS2017. std::map and std::multimap works.

**Comment by JoeyGrajciar** [comment]
Tried the code in latest VS2017 and VS2019 and I can tell that both compile without problems. VS2019 has only some Intellisense errors but that is probably due to heavy macro machinery in the code.

Do you have some specific compilation flags set?

**Comment by Domain** [comment]
@JoeyGrajciar I use this in VS2019:
```
cl.exe -c -FS -Zi -FdC:\\Git\\test\\test.pdb -W3 -WX -Od -std:c++17 -Iinc -DWIN32 /EHsc -nologo -FoC:\\Git\\test\\obj\\test.cpp.obj test.cpp
```

**Comment by Domain** [comment]
Sorry, I mistake. It works well now.
