### ISSUE TITLE
there is no warning number '4800' in VS2017

### ISSUE THREAD

**Issue by Domain** [catchorg/Catch2#1787]
catch2 2.10.0 and 2.10.1
VS2017 15.9.8
error C4619: #pragma warning: there is no warning number '4800'

**Comment by JoeyGrajciar** [comment]
Seems like MS removed this warning in some update of VS2017
https://developercommunity.visualstudio.com/content/problem/78259/visual-studio-2017-no-longer-generates-a-c4800-war.html
, but it is back in VS2019.

**Comment by horenmar** [comment]
This seems to be problem only with a very specific version of VS2017, so I am going to close this as won't fix. Detecting the exact version of VS2017 where this happens is cumbersome, and current VS does not have the same problem.
