### ISSUE TITLE
storage_for missing from single include

### ISSUE THREAD

**Issue by Tridacnid** [catchorg/Catch2#1800]
**Describe the bug**
single_include/catch2/catch.hpp appears to be missing some benchmarking symbols that appear in the [docs](https://github.com/catchorg/Catch2/blob/master/docs/benchmarks.md#constructors-and-destructors). Others may also be missing.

**Expected behavior**
Compiling the example code should work:
```
TEST_CASE("BLAH")
{
    BENCHMARK_ADVANCED("construct")(Catch::Benchmark::Chronometer meter)
    {
        std::vector<Catch::Benchmark::storage_for<std::string>> storage(meter.runs());
        meter.measure([&](int i) { storage[i].construct("thing"); });
   }
}
```

**Observed behavior**
`error: storage_for is not a  member of Catch::Benchmark`

**Reproduction steps**
Compile the following:
```
#define CATCH_CONFIG_MAIN
#define CATCH_CONFIG_ENABLE_BENCHMARKING

#include <catch2/catch.hpp>

#include <vector>
#include <string>

TEST_CASE("BLAH")
{
    BENCHMARK_ADVANCED("construct")(Catch::Benchmark::Chronometer meter)
    {
        std::vector<Catch::Benchmark::storage_for<std::string>> storage(meter.runs());
        meter.measure([&](int i) { storage[i].construct("thing"); });
   }
}
```

**Platform information:**
 - Catch version: **v2.10.2**

**Comment by Tridacnid** [comment]
Looks like include/internal/benchmark/catch_constructor.hpp isn't ever referenced in the source code, so the generateSingleHeader.py script doesn't include it in the final product. I'm going to try to submit a patch for both the missing inclusion as well as add a warning to the script so that in the future this sort of problem will be more visible to the developer.

**Comment by horenmar** [comment]
Yeah, this sort of missing functionality has happened couple of times before.

Improvements to the stitching script are always welcome, but for the benchmarking specifically I would suggest creating file named something like `catch_benchmarking_all.hpp` inside the benchmarking folder, and including that for stitching. I suspect that our users will want such a header for the v3 version where we intend to provide Catch2 as a regular library made from multiple headers/TUs.

**Comment by Tridacnid** [comment]
Thanks! I'll try to put together a patch to warn about this sort of thing when running the script. Is it intentional that SelfTest/UsageTests/Benchmark.test.cpp doesn't always compile with CATCH_CONFIG_ENABLE_BENCHMARKING?
