### ISSUE TITLE
Custom generator which accepts other generator

### ISSUE THREAD

**Issue by TysonRayJones** [catchorg/Catch2#1803]
> Note the code snippets below have been simplified from featuring `Catch::Generators::IGenerator` to `IGenerator` (simiarly for `GeneratorWrapper`) for visual clarity

Let's say I have some custom generator, which (boringly) just returns the square of integers in a given vector.

```C++
class SquareGenerator : public IGenerator<int> {
    vector<int> list;
    int current_index;
    int current_square;
public:
    SquareGenerator(vector<int> elems) {
        list(elems);
        current_index = 0;
        current_square = pow(list[current_index++], 2) ;
    }
    int const& get() const {
        return current_square;
    }
    bool next() override {
        if (current_index < list.size()) {
            current_square = pow(list[current_index++], 2) ;
            return true;
        }
        return false;
    }
```
and we have the helper function...
```C++
GeneratorWrapper<int> square(vector<int> elems) {
    return GeneratorWrapper<int>(
        std::unique_ptr<IGenerator<int>>(
            new SquareGenerator(elems)));
}
```
so that we can invoke the generator with `GENERATE`, like so:
```C++
int elem = GENERATE( square(vector<int>{0, 1, 2, 3, 4}) );
```

How can one write a custom generator which _accepts_, in its constructor, _another_ generator? E.g so that the above snippet could instead be expressed as
```C++
int elem = GENERATE( square(range(0,4)) );
```

The obvious approach seems to be to modify the custom `SquareGenerator` constructor to accept a `GeneratorWrapper<T>` 
```C++
public:
    SquareGenerator(GeneratorWrapper<int> gen) {
        do {
            list.push_back(gen.get());
        } while (gen.next());
        current_index = 0;
        current_square = pow(list[current_index++], 2) ;
    }
```
and update the helper function
```C++
GeneratorWrapper<int> square(GeneratorWrapper<int> gen) {
    return GeneratorWrapper<int>(
        std::unique_ptr<IGenerator<int>>(
            new SquareGenerator(gen)));
```
but this results in a compilation error
```bash
In function 'GeneratorWrapper<int> square(GeneratorWrapper<int>)':
error: use of deleted function 'GeneratorWrapper<int>::GeneratorWrapper(const GeneratorWrapper<int>&)'
             new SquareGenerator(gen)));

In file included from ...:
catch.hpp:3915:11: note: 'GeneratorWrapper<int>::GeneratorWrapper(const GeneratorWrapper<int>&)' is implicitly deleted because the default definition would be ill-formed:
     class GeneratorWrapper final {
```

Admittedly I'm not sufficiently familar with C++ to understand the nature of the error myself. However, the general idea (custom generators accepting other generators) seems reasonable enough, since some standard generators (e.g. `take` and `filter`) already do this.
While I can snoop `catch.hpp` to probably figure out working code, it'd be nice to have some doc elaborating on custom generators, and to avoid any unnecessary boilerplate.

**Comment by TysonRayJones** [comment]
Ah yep a quick peek at `catch.hpp` showed this was indeed trivial.

``C++
public:
    SquareGenerator(GeneratorWrapper<int>&& gen) {
        do {
            list.push_back(gen.get());
        } while (gen.next());
        current_index = 0;
        current_square = pow(list[current_index++], 2) ;
    }
```
```C++
GeneratorWrapper<int> square(GeneratorWrapper<int>&& gen) {
    return GeneratorWrapper<int>(
        std::unique_ptr<IGenerator<int>>(
            new SquareGenerator(std::move(gen))));
```

**Comment by horenmar** [comment]
Yeah, `GeneratorWrapper<T>` is a plain move-only type, so you have to move it along.
