### ISSUE TITLE
Rerun session

### ISSUE THREAD

**Issue by Dainin** [catchorg/Catch2#1804]
**Description**
Looks like there is no possible to run tests multiple times in one session. It will be useful in embedded to run tests multiple times without rebooting the device.
Basically are rerun successfully, but if I run the session with arguments like -l or -h, next runs will only print list/help information.
Or maybe I miss something?

**Additional context**
Here is a code how I run the session:

```
#define CATCH_CONFIG_NOSTDOUT
#define CATCH_CONFIG_COLOUR_NONE
#define CATCH_CONFIG_RUNNER
#define CATCH_CONFIG_DISABLE_EXCEPTIONS
#define CATCH_INTERNAL_CONFIG_NO_POSIX_SIGNALS
#include "catch.hpp"

void TestCatchTask(void *task_arg) {
   Catch::Session session;

    while(true)
    {
        if(getNextCommand())
            session.run(arguments.size() - 1, arguments.data());
    }
}
```

**Comment by maxklint** [comment]
Rerunning a session is possible. Try the session.useConfigData method. For example, you can write something like this:

```
int main(void)
{
	Catch::Session session;

	for (int i = 1; i <= 3; i++) {
		Catch::ConfigData cd;
		cd.processName = std::string("my_test") + std::to_string(i);
		// any other config
		session.useConfigData(cd);

		session.run();
	}
}
```

The only thing you need to make sure is that you only instantiate the Catch::Session object once.

**Comment by Dainin** [comment]
@maxklint thank you for advise, but this method is not resolve my problem. I need to implement full support of command line arguments. Is there a method to parse command line arguments to Catch::ConfigData? I think it's not right to parse it by myself because they can change with updates.

**Comment by Dainin** [comment]
Looks like I should just reset ConfigData. This code resolve my issue:
```
    Catch::Session session;

    while(true) {
        if(getNextCommand()) {
            Catch::ConfigData cd = {0};
            session.useConfigData(cd);
            session.run(arguments.size() - 1, arguments.data());
        }
    }
```
