### ISSUE TITLE
Add documentation to add Catch2 into CTest when using add_subdirectory

### ISSUE THREAD

**Issue by TheButlah** [catchorg/Catch2#1805]
**Description**
I tried to follow the instructions for getting Catch2's tests to register with CMake's CTest framework, but when attempting to run `cmake ..`, I got an error indicating that the `include(Catch)` command couldn't find the `Catch.cmake` file. After some googling, I found out about the `CMAKE_MODULE_PATH` variable, and added 
`list(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/third_party/catch2/contrib")` in my top level `CMakeLists.txt` after the `add_subdirectory(third_party/catch2)` command.

After this process, I can now run `cmake ..` as expected. It would be good to add this documentation into the part of the docs that describes integration with CMake. I would submit a PR myself, but I'm new to C++ and CMake and not confident that this wasn't a self-inflicted error, or I did something else wrong.

**Additional context**
Using Ubuntu 18.04, g++-8, c++17

**Comment by L117** [comment]
Yep, this helped. But I believe, there's a better way. So, I'm bumping this issue.
