### ISSUE TITLE
SonarQube reporter missing in Catch 2.11.0 release

### ISSUE THREAD

**Issue by torfinnberset** [catchorg/Catch2#1807]
**Describe the bug**
When running a test executable linked with Catch2, the new SonarQube test reporter is not available for use. It does not show up in the list of reporters.

**Expected behavior**
Passing `-r sonarqube` to the test executable should generate a SonarQube compatible xml output.

**Reproduction steps**
1) Check version
```
./test -h

Catch v2.11.0
usage:
  test [<test name|pattern|tags> ... ] options
```

2) Run with SonarQube test reporter:
```
./test -r sonarqube

Error(s) in input:
  Unrecognized reporter, 'sonarqube'. Check available with --list-reporters

Run with -? for usage
```

3) Check list of reporters:

```
./test --list-reporters 
Available reporters:
  compact:  Reports test results on a single line, suitable for IDEs
  console:  Reports test results as plain lines of text
  junit:    Reports test results in an XML format that looks like Ant's
              junitreport target
  xml:      Reports test results as an XML document
```

**Platform information:**
 - OS: macOS Catalina
 - Compiler+version: LLVM Clang 9.0.0
 - Catch version: 2.11.0

**Additional context**
From what I can gather, the new SonarQube test reporter is not included in catch.hpp in the main branch of this repository. I'm assuming something is going wrong in the build process, as I can see the code for the sonarqube reporter is in the repo.

And finally, thanks for Catch2 and the SonarQube plugin (@sp-dani-garcia)!

**Comment by horenmar** [comment]
[Did you include it manually?](https://github.com/catchorg/Catch2/blob/master/docs/ci-and-misc.md#other-reporters)

**Comment by torfinnberset** [comment]
Ah no I did not know that was required. Thanks for pointing that out. It might be useful to put these notices in the Release Notes for the lazy ones like me :)
