### ISSUE TITLE
Uninitialized boolean values always pass

### ISSUE THREAD

**Issue by stevenbitner** [catchorg/Catch2#1812]
**Describe the bug**
Uninitialized booleans always pass assertions.

**Expected behavior**
Uninitialized booleans should either evaluate to true or false, but not both. It is confusing and can lead to a programmer thinking they are "done" when they aren't.

**Reproduction steps**
```cpp
TEST_CASE("Uninitialized heap bool")
 {
     bool* foo = new bool[10];
     REQUIRE(foo[0]); // passes
     REQUIRE(!foo[0]); // passes
     REQUIRE(!!foo[0]); // passes
     REQUIRE_FALSE(foo[0]); // passes
  }
```

**Platform information:**

 - OS: **Cent OS** and **Ubuntu**
 - Compiler+version: **GCC v4.8.5**
 - Catch version: **v2.5.0**

**Comment by cor3ntin** [comment]
This is undefined behavior https://en.cppreference.com/w/c/language/behavior 

What you consider "expected" behavior is in fact not expected, and not something catch could enforce, even if it wanted to. Initialize your variables.

**Comment by horenmar** [comment]
FYI, you can catch these problems using Valgrind/Sanitizers
