### ISSUE TITLE
TEMPLATE_LIST_TEST_CASE_METHOD does not work as expected on some compilers

### ISSUE THREAD

**Issue by rick-de-water** [catchorg/Catch2#1814]
**Describe the bug**
The following code compiles when using Visual Studio 2019:
```
template <typename TestType>
struct MyFixture
{
	using MyType = TestType;
};

using MyTypes = std::tuple<int, float, double>;

TEMPLATE_LIST_TEST_CASE_METHOD(MyFixture, "MyName", "[MyTag]", MyTypes)
{
	MyType foo;
}
```
But when compiling with GCC 7.4.0 I get the following error:

```
myfile.cpp: In member function ‘void ____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____F_U_N_C____0<TestType>::test()’:
myfile.cpp:19:2: error: ‘MyType’ was not declared in this scope
  MyType foo;
  ^~~~~~
```

**Expected behavior**
I expect `MyType` to be defined in the test case.

**Platform information:**
 - OS: **Windows 10** & **WSL**
 - Compiler+version: **Visual Studio 2019** & **GCC 7.4.0**
 - Catch version: **v2.11.0**

**Comment by Resurr3ction** [comment]
`MyType` is wrong, in Catch2 it is `TestType`.

**Comment by rick-de-water** [comment]
`MyType` is a typedef of `TestType` in the fixture.

**Comment by Resurr3ction** [comment]
On MSVC this compiles. However with Clang and GCC it does not as you observe. And clang-tidy with MSVC gives a direct reason why: `use of identifier 'MyType' found via unqualified lookup into dependent bases of class templates is a Microsoft extension` Nothing to do with Catch2.

**Comment by rick-de-water** [comment]
That indeed seems to be the issue. This makes using fixtures in template tests quite a bit more frustrating
