### ISSUE TITLE
v3.0.0 preview available through conan?

### ISSUE THREAD

**Issue by offa** [catchorg/Catch2#1823]
Will the v3.0.0 preview version become available through conan?

**Comment by horenmar** [comment]
I intend to make v3 available through conan, but from the tasks in backlog it has a very low priority, similarly to providing single header version.

If you have experience with conan, you can contribute the required changes to speed it up.

**Comment by offa** [comment]
What's still open respectively where can I help? I'm not an expert but a casual Conan user, maybe I can give you a hand.

**Comment by horenmar** [comment]
I think there are 2 things that need work for v3 to show up on Conan:

1) Catch's Conan recipe likely needs to be updated to properly use the static library build in v3
2) The Conan publishing script needs to be updated to publish to `testing` (or whatever the usual non-stable name is) under some circumstances (currently it only publishes to `stable` when a stable tag is made).

**Comment by horenmar** [comment]
Catch2 is also included in Conan-center by the Conan folks, so you might also try asking them to provide a recipe for v3.

**Comment by offa** [comment]
I'm currently working on this.

**Comment by offa** [comment]
Conan center ships only stable releases, so I have updated the conanfile for v3.

**Comment by horenmar** [comment]
Bintray should now have v3.0.0 preview uploaded
https://bintray.com/catchorg/Catch2/catch2%3Acatchorg

**Comment by gegles** [comment]
Now that bintray is gone, could we get it through another conan remote?

Much appreciated!

**Comment by horenmar** [comment]
@gegles Yes, if someone takes care of it.

I don't use Conan anymore, nor have an idea what is a good free remote. However, if someone sets up something like existed for bintray in a GitHub action, I am fine with merging it again.
