### ISSUE TITLE
Running with `exclude:` causes benchmarks to run

### ISSUE THREAD

**Issue by TysonRayJones** [catchorg/Catch2#1829]
**Describe the bug**
My Catch2 tests include some benchmarks (tests with tag `[!benchmark]`). These are (correctly) not run when I invoke my executable `./test` which instead runs all my other non-benchmark tests.
However, when I include the `exclude:` command-line arg, e.g..
```bash
./test exclude:sometest
```
then all tests except `sometest` are correctly run, but the benchmarks are *also* incorrectly run.

**Expected behavior**
Since the benchmarks are not run when `./test` is run, they should also not be run when `./test exclude:sometest` is run.

**Reproduction steps**
A MWE (`test.cpp`):

```C++
#define CATCH_CONFIG_ENABLE_BENCHMARKING
#include "catch.hpp"

TEST_CASE( "a", "[mytests]") {
    REQUIRE( true );
}

TEST_CASE( b", "[mytests]") {
    REQUIRE( true );
}

TEST_CASE( c", "[!benchmark]") {
    
    BENCHMARK( "mybenchmark" ) {

        int s=0;
        for (int i=0; i<10; i++)
            s++;
    };
}
```
Compile with 
```bash
g++ -std=c++14 -c test.cpp -o test
```

When `./test` is run, only tests `a` and `b` run (correct behaviour).
When `./test except:a` is run, `b` runs (correctly), but `c` incorrectly also runs.

**Platform information:**
 - OS: Ubuntu 18
 - Compiler+version: **GCC v8.3.0**
 - Catch version: **v2.10.0**

**Comment by horenmar** [comment]
At a quick glance, this seems to be the same problem as #1184. If that is indeed the case, it is already fixed in v3 branch, but because it is a backwards incompatible change, it has to wait for the next major release.

**Comment by TysonRayJones** [comment]
Hi Martin,
You might be right, thanks very much for the update!
