### ISSUE TITLE
v3.0.0 Link order

### ISSUE THREAD

**Issue by offa** [catchorg/Catch2#1830]
**Describe the bug**
Does the link order of _Catch2_ / _Catch2Main_ matter? Linking `Catch2Main Catch2` works, but using the opposite order results in undefined references:

```
[…]/lib/libCatch2Main.a(catch_main.cpp.o): in function `main':
catch_main.cpp:(.text.startup+0x34): undefined reference to `Catch::Session::Session()'
/usr/bin/ld: catch_main.cpp:(.text.startup+0x46): undefined reference to `Catch::Session::~Session()'
/usr/bin/ld: catch_main.cpp:(.text.startup+0x79): undefined reference to `Catch::Session::applyCommandLine(int, char const* const*)'
/usr/bin/ld: catch_main.cpp:(.text.startup+0x88): undefined reference to `Catch::Session::run()'
```

**Expected behavior**
Either _(a)_ this is intentional or _(b)_ a should be fixed (both are OK to me).

**Reproduction steps**

1. Build _v3.0.0-preview1_ as a static library (eg. using CMake)
1. Compile minimal program (see below) and change order of Catch2 / Catch2Main

```cpp
// minimal program
#define CATCH_CONFIG_MAIN
#include <catch2/catch.hpp>
```

```sh
# Fails (undefined references):
$ g++ 000-CatchMain.cpp -I[…]/include -L[…]/lib -lCatch2 -lCatch2Main

# Ok
$ g++ 000-CatchMain.cpp -I[…]/include -L[…]/lib -lCatch2Main -lCatch2
```

**Platform information:**

 - OS: **Linux**
 - Compiler+version: **GCC v9.2.0**
 - Catch version: **v3.0.0-preview1**

**Additional context**
#1823

**Comment by maybug** [comment]
I met this

**Comment by horenmar** [comment]
Right, I forgot about people who don't use CMake. If you use the CMake targets, linking just `Catch2Main` should work, because it declares dependency on `Catch2`.

I'll have to think about whether I want the two libraries to be link-order dependent, or whether they should both include all the required symbols.

**Comment by horenmar** [comment]
I am going to go with the option of keeping the libraries as they are, and documenting that if you don't use CMake-provided integration, you have to link them both, and in the correct order (`Catch2Main` and then `Catch2`).

**Comment by offa** [comment]
Thanks!
