### ISSUE TITLE
Calling destructor in unit test

### ISSUE THREAD

**Issue by acse-fk4517** [catchorg/Catch2#1836]
Hi, 

Is there a way to call a delete / destructors after allocating an object on the heap inside the test?

For example, suppose I create  matrix, run some test on it, and want to then delete it. Is this possible regardless of whether the test fails? The test can be either REQUIRE or CHECK based:

```
TEST_CASE("Row major matrix; matrix multiplication; square matrix")
{
    int rows = 2;
    int cols = 3;

    // create a dense matrix
    auto *dense_mat = new Matrix(rows, cols);

    // test some aspect of the matrix. Assume it has failed for illustration purposes
    REQUIRE(false);
    
    // How can I get this to run? 
    delete dense_mat;
}
```

Any guidance would be helpful as the document does not make it clear how I can do this after a test passes or fails.

**Comment by PureAbstract** [comment]
Have you considered putting it in a std::unique_ptr?

**Comment by acse-fk4517** [comment]
thanks, I have not considered using that - how would I go about using that to avoid leaving memory allocated on the heap? I am somewhat new to c++ and don't know some of these techniques.

That said I read [this](https://github.com/catchorg/Catch2/blob/master/docs/test-fixtures.md). This seems like a good way to do it - but is this the recommended way to do it in Catch2?

**Comment by horenmar** [comment]
This sounds like you need a good C++ book and not issue tracker at this moment.

The technique you are looking for is called RAII, and the idea is to use automatic storage destruction rules, that is a variable is destroyed when it goes out of scope, to manage your resources automatically. Your snippet specifically would look like this

```cpp
TEST_CASE("Row major matrix; matrix multiplication; square matrix") {
    int rows = 2;
    int cols = 3;

    // unique_ptr calls `delete`* on your allocation when it goes out of scope, such as if the unit test fails
    auto dense_mat = std::make_unique<Matrix>(rows, cols);

    // test some aspect of the matrix. Assume it has failed for illustration purposes
    REQUIRE(false);
}
```

* _This is not 100% true, but it details would only serve to confuse the matter right now._

But unless you have an actual need for heap allocation, you should just keep the `Matrix` instance itself on the stack:
```cpp
TEST_CASE("Row major matrix; matrix multiplication; square matrix") {
    int rows = 2;
    int cols = 3;

    // unique_ptr calls `delete`* on your allocation when it goes out of scope, such as if the unit test fails
    Matrix dense_mat(rows, cols);

    // test some aspect of the matrix. Assume it has failed for illustration purposes
    REQUIRE(false);
}
```

**Comment by acse-fk4517** [comment]
Ah thank you - I do indeed need a good c++ book. Thank you for the comprehensive reply - I will look into this as I really like this library.

Cheerio!
