### ISSUE TITLE
Unable to add tagged test specs programatically

### ISSUE THREAD

**Issue by philsquared** [catchorg/Catch2#184]
Ross Bencina raised the following issue in the forums:

[from https://groups.google.com/forum/?fromgroups#!topic/catch-forum/OK4sorOfznA]

///
config.addTestSpec( "X/level0/_" );
config.addTestSpec( "X/level1/_" );
config.addTestSpec( "X/level2/*" );

config.addTestSpec( "~[fuzz]" ); // don't run fuzz tests
//

My intention was to run the X/level{0,1,2}/\* tests excluding those tests tagged with [fuzz]. However in the case above "~[fuzz]" adds tests that do not match X/level{0,1,2}/\* (eg. it has caused tests "Y/Z/etcetc" to run).

So I tried this:

///
config.addTestSpec( "X/level0/\* ~[fuzz]" );
config.addTestSpec( "X/level1/\* ~[fuzz]" );
config.addTestSpec( "X/level2/\* ~[fuzz]" );
////

Which results in:

No test cases matched 'X/level0/\* ~[fuzz]'
No test cases matched 'X/level1/\* ~[fuzz]'
No test cases matched 'X/level2/\* ~[fuzz]'
No tests ran

Is that a bug, or am I doing something wrong?

Note that the following is working as expected:
///
config.addTestSpec( "X/level0/_" )
config.addTestSpec( "X/level1/_" );
config.addTestSpec( "X/level2/*" );
///

I'm using the latest Catch 1.0 merged header

**Comment by philsquared** [comment]
Looks like I never followed up on this to see if it is still an issue.
@RossBencina do you recall if this ever got sorted for you. I appreciate it was a long time ago.

**Comment by horenmar** [comment]
This has been fixed by making so that a test spec exclusion does not include everything else.
