### ISSUE TITLE
Is it possible to force CHECK to behave like REQUIRES?

### ISSUE THREAD

**Issue by dbak-invn** [catchorg/Catch2#1841]
Is there some compiler flag I can set to force CHECK to behave like REQUIRES?

**Comment by horenmar** [comment]
There is not, `CHECK` is always `CHECK` and `REQUIRE` is always `REQUIRE`. However, for specific use cases you can use the `-x 1` command line flag.

**Comment by onqtam** [comment]
```c++
#undef REQUIRE
#define CHECK REQUIRE
```
