### ISSUE TITLE
Assertion failed: !m_sectionStack.empty(), file catch.hpp line 5882

### ISSUE THREAD

**Issue by schoetbi** [catchorg/Catch2#1845]
**Describe the bug**
While running the tests I got this assertion failure

`Assertion failed: !m_sectionStack.empty(), file D:\GitlabRunner\builds\yz6XsHQZ\0\s\catch\catch.hpp, line 5882`

**Reproduction steps**
I start my console application under Windows with the following command line:
`bin\Debug\RtLib.Test.exe -s -r junit -o test_debug.xml ~OpDeadlockPreventionPattern`

I can only reproduce this on the buildserver, it did not happen on my dev machine yet. On the buildserver the tests runs within powershell (started by gitlab ci pipeline). But when I start this test through powershell on my dev machine the error did not occour.

**Platform information:**
 - Compiler+version: **MSVC v140**
 - Catch version: **Catch v2.10.2 2019-10-24 17:49:11.459934**

**Comment by schoetbi** [comment]
It was a segmentation fault in a test.

**Comment by horenmar** [comment]
Interestingly, we get these fairly regularly -- I wonder what it is about JUnit reporter that triggers this so often.
