### ISSUE TITLE
ParseAndAddCatchTests.cmake silently ignores test that contains right parenthesis

### ISSUE THREAD

**Issue by apartridge** [catchorg/Catch2#1848]
**Describe the bug**
The https://github.com/catchorg/Catch2/blob/master/contrib/ParseAndAddCatchTests.cmake script
does not handle when a test name contains a right parenthesis. For example

> TEST_CASE("Test ) abc")
> {
> }

This is silently ignored and the test is never run. 

**Expected behavior**
Expected that the test is run. An alternative is that the script returns with an error signalling that the test name was invalid.

**Platform information:**
OS Ubuntu 18.04
Cmake version 3.15.5
Tested on newest master 2d172dc688ffab0867a94928159e93384475a870

**Comment by knzivid** [comment]
Minimal test case for the regex

https://regex101.com/r/RhkeDO/3
