### ISSUE TITLE
'wmain' is only used if 'WIN32' is defined

### ISSUE THREAD

**Issue by glebov-andrey** [catchorg/Catch2#1849]
Hi!
There appears to be a leftover `WIN32` macro check after #193 and #1676.
https://github.com/catchorg/Catch2/blob/2d172dc688ffab0867a94928159e93384475a870/include/internal/catch_default_main.hpp#L15-L17
Because of this one has to resort to manually defining `WIN32` (if `_WIN32` is defined) before including `catch.hpp` in `main.cpp`.
Presumably the correct thing would be to check `CATCH_PLATFORM_WINDOWS` instead.
As far as I can tell this is the only remaining use of `WIN32` in Catch2.

**Comment by horenmar** [comment]
Thanks
