### ISSUE TITLE
Ubuntu apt install catch - CMake cannot find Catch2Config.cmake

### ISSUE THREAD

**Issue by olimexsmart** [catchorg/Catch2#1850]
**Describe the bug**
After installing Catch2 on Kubuntu 18.04 using:
```
sudo apt install catch
```
CMake is not able to find `Catch2Config.cmake`

**Expected behavior**
CMake should be able to find the package using:
```
find_package(Catch2 REQUIRED)
```

**Platform information:**

 - OS: Kubuntu 18.04.3
- CMake Version 3.10

**Additional context**
Other libraries like `libeigen3-dev` work fine

Thank you

**Comment by horenmar** [comment]
Last I checked, the `catch` package in Ubuntu installed an amazingly outdated (v1.10.0) version. However, I have nothing to do with Ubuntu's packaging, so ask them to rectify it.
