### ISSUE TITLE
Confirm: you can only instantiate the Catch::Session in file with #define CATCH_CONFIG_RUNNER

### ISSUE THREAD

**Issue by dtgriscom** [catchorg/Catch2#1851]
**Description**
The documentation describes two useful techniques:

1. [Putting the bulk of the `catch.hpp` compilation into its own file](https://github.com/catchorg/Catch2/blob/master/docs/slow-compiles.md)

2. [Supplying your own `main()`](https://github.com/catchorg/Catch2/blob/master/docs/own-main.md#top)

The obvious extension is to do both of these: to put `#define CATCH_CONFIG_RUNNER`/`#include "catch.hpp"` into its own two-line file, and then have your `main.cpp`'s `main()` function run the tests. But, this doesn't work: 

````
main.cpp:161:21: error: ‘Session’ is not a member of ‘Catch’
     result = Catch::Session().run();
````

After much investigation, I believe that the (one and only one) use of Catch::Session() **must** be in the one file with `#define CATCH_CONFIG_RUNNER`/`#include "catch.hpp"`.

Is this true? If so, it really should be mentioned in one or both of the technique pages above. I'd be happy to submit a doc PR, especially if you suggest where to put the info.

**Comment by claremacrae** [comment]
What you’ve described agrees with this documentation: https://github.com/catchorg/Catch2/blob/master/docs/configuration.md

I went through the same process as you a year or so ago, trying to work out how to make Session work, based on the docs for supplying my own main. 

So your suggestion of mentioning this in the two locations you mention - perhaps linking to the existing docs - sounds like a good idea to me.

**Comment by torarnv** [comment]
Just hit this myself. It would be really nice if the two were decoupled, so you could build the bulk of catch once, while still allowing a separate main per translation unit. How about splitting it up into `CATCH_CONFIG_RUNNER_IMPL` and `CATCH_CONFIG_RUNNER_API`, leaving `CATCH_CONFIG_RUNNER` as defining both for compatibility?

**Comment by horenmar** [comment]
@dtgriscom You are correct. The reason is that `CATCH_CONFIG_RUNNER` hides a lot of the header away to keep compilation times reasonable for the test TUs. I updated the docs to reflect this.

@torarnv For v3 the implementation is compiled into a static library, so that is happening implicitly. I have no intention to make changes to the split for v2.
