### ISSUE TITLE
How to implement a custom matcher to check for object equality in Catch2

### ISSUE THREAD

**Issue by minicatsCB** [catchorg/Catch2#1859]
I'm new to unit testing in C++ with [Catch2][1]. Lastly, I was trying to implement a [custom Matcher][2] to test if the fields of a given object match the ones I provide. The object in question good be like:

```c++
class Book {
private:
	int chapters;
	int pages;

public:
	int GetChapters();
	int GetPages();
};
```
My matcher would be used like this in a test case:
```c++
TEST_CASE("Books info is correct")
{
    Book myBook;
    CHECK_THAT(myBook, IsCorrect(5, 150));
    CHECK_THAT(myBook, IsCorrect(10, 325));
}
```
Following the example in the documentation, my intent has been:
```c++
// The matcher class
class BookCheck : public Catch::MatcherBase<Book> {
	Book book;
	int chapters = -1;
	int pages = -1;

public:
	BookCheck(int chapters, int pages) : chapters(chapters), pages(pages) {}

    // Performs the test for this matcher
    bool match( Book& b ) const override {
        return b.GetChapters() == chapters && b.GetPages() == pages;
    }

    virtual std::string describe() const override {
        ostringstream ss;
        ss << "chapters is " << chapters << " and pages is " << pages;
        return ss.str();
    }
};

// The builder function
inline BookCheck IsCorrect(int chapters, int pages) {
    return BookCheck(chapters, pages);
}
```
When I compile this code, I get this errors:
*error: ‘bool BookCheck::match(Book&) const’ marked ‘override’, but does not override*

*error: invalid abstract return type ‘BookCheck’*

*error: invalid abstract return type for function ‘BookCheck
   IsCorrect(int, int)’*

*error: invalid cast to abstract class type
   ‘BookCheck’*

Could you point me what am I doing wrong here?

  [1]: https://github.com/catchorg/Catch2
  [2]: https://github.com/catchorg/Catch2/blob/master/docs/matchers.md#custom-matchers

**Comment by horenmar** [comment]
> error: ‘bool BookCheck::match(Book&) const’ marked ‘override’, but does not override

The signature should be `bool BookCheck::(Book const&) const`. This will also require some changes to `Book` to make it const correct.

**Comment by minicatsCB** [comment]
Thanks!

Just (I hope) a quickly question:
When I test:
```c++
TEST_CASE("Books info is correct")
{
    Book myBook;
    CHECK_THAT(myBook, IsCorrect(10, 325));
}
```

and `match()` returns false, I get this output:
```plaintext
../test/test-sections.cpp:238: FAILED:
  CHECK_THAT( myBook, IsCorrect(10, 325) )
with expansion:
  {?} chapters is 10 and pages is 325
```

Is it possible to avoid the "{?}" thing and display `myBook` values?

**Comment by horenmar** [comment]
https://github.com/catchorg/Catch2/blob/master/docs/tostring.md#top
