### ISSUE TITLE
IOS Debugger Break code not compiling under armv7s

### ISSUE THREAD

**Issue by andywyatte17** [catchorg/Catch2#1862]
I am compiling catch2.11.1 source for IOS. I see that a change has been made in this version around the debugger-break code - #define CATCH_TRAP... etc.

This code doesn't compile for me when using the command such as clang -x c++ -target armv7s-apple-ios9.3 ..., ie when targetting IOS armv7s platform. The error I get compiling in Xcode is:

> Cannot determine Thumb instructino size, use inst.n/inst.w instead

The code needs a tweak around the area...

**(old code)**

```
#elif defined(CATCH_PLATFORM_IPHONE)
    // use inline assembler
    ...
    #elif defined(__arm__)
        #define CATCH_TRAP() __asm__(".inst 0xe7f001f0")
```

**(new code)**

```
#elif defined(CATCH_PLATFORM_IPHONE)
    // use inline assembler
    ...
    #elif defined(__arm__) && !defined(__thumb__)
      #define CATCH_TRAP() __asm__(".inst 0xe7f001f0")
    #elif defined(__arm__) && defined(__thumb__)
      #define CATCH_TRAP() __asm__(".inst 0xde01")
```

My choice of code for the second case (.inst 0xde01) was inspired by code at https://github.com/scottt/debugbreak/blob/master/debugbreak.h... however I don't have an easy way to verify this is good (although it does compile).

**Comment by horenmar** [comment]
I don't have any iOS device to test this on, but the change seems reasonable enough.

**Comment by kaihowl** [comment]
I still found this compilation error when trying to update Catch to 2.11.3 in Hunter.
https://travis-ci.com/github/kaihowl/hunter/jobs/300418739
