### ISSUE TITLE
Unicode in source file causes compilation warning C4819 with MSVC

### ISSUE THREAD

**Issue by nfrechette** [catchorg/Catch2#1869]
**Describe the bug**
In a few places in the catch header, unicode characters are used but the header does not contain a BOM UTF-8 marker. Most compilers will assume that source files are using UTF-8 but this is not always the case, especially on Windows. If your locale is set to Japanese, the unicode characters will be interpreteted as SHIFT-JS characters and cause compilation to fail with a warning similar to this:

`...\catch2\single_include\catch2\catch.hpp(3243): warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss (compiling source file ...)`

Here are a few examples that explain the issue:
https://stackoverflow.com/questions/47690822/possible-to-force-cmake-msvc-to-use-utf-8-encoding-for-source-files-without-a-bo
https://github.com/libretro/RetroArch/issues/6404
https://stackoverflow.com/questions/10501634/warning-c4819-how-to-find-the-character-that-has-to-be-saved-in-unicode
https://github.com/nfrechette/acl/issues/260

In order to avoid the issue, a fix similar to [this](https://github.com/nfrechette/acl/commit/4e08dbb2533fb55db22b84077def38a26b90854b) is required which is unfortunate.

**Expected behavior**
Catch2 should work regardless of the host compiler locale without requiring special compilation switches to force source code encoding.

**Reproduction steps**
Set the windows locale to Japanese and compile a project that uses Catch2.

**Platform information:**
 - OS: **Windows 10**
 - Compiler+version: **MSVC**
 - Catch version: **v2.5.0**

**Additional context**
I'm not sure whether it is possible to include the BOM in the generated header. The easiest solution would be to remove all usage of unicode characters. There are a few that add no value as part of comments (such as the famous shrug ¯\_(ツ)_/¯ ) and [one minor instance](https://github.com/catchorg/Catch2/blob/6ccd467094973824d89efb16cbc553e279f79823/single_include/catch2/catch.hpp#L13006) (the 'micro' character) that could probably be omitted.

**Comment by horenmar** [comment]
Apart from UTF-8 BOM being a Windows-only abominations, v2.5.0 is well over year old.

**Comment by nfrechette** [comment]
Specifically, the issue is a duplicate of #1542 which describes the same issue with wording that doesn't mention Unicode which is why I haven't found it earlier. I will update to a newer version, thanks!
