### ISSUE TITLE
C++ lambda functions in TEST_CASE problems with Intel C++ compiler

### ISSUE THREAD

**Issue by drdummel** [catchorg/Catch2#1871]
Please have a look at the example below:

f1.cxx
/////////////////////////////////////////////////////////////////////////
`#include<functional>`
`#include<catch.hpp>`

`static bool output(const std::function<bool(void)> &f) {`
`    return f();`
`}`

`TEST_CASE("func1", "[test]")`
`{`
`    auto fun = []() -> bool {return true;};`
`    REQUIRE(output(fun) == true);`
`}`

f2.cxx
/////////////////////////////////////////////////////////////////////////
`#include<functional>`
`#include<catch.hpp>`

`static bool output(const std::function<bool(void)> &f) {`
`    return f();`
`}`

`TEST_CASE("func2", "[test]")`
`{`
`    auto fun = []() -> bool {return false;};`
`    REQUIRE(output(fun) == false);`
`}`

main.cxx
/////////////////////////////////////////////////////////////////////////
`#define CATCH_CONFIG_RUNNER`
`#include<catch.hpp>`

`int main(int argc, char* argv[]) {`
`    const int result = Catch::Session().run(argc, argv);`
`    return 0;`
`}`

build:
icl -Qvc14.2 -Icatch/2.11.1/include -c -EHsc -Z7 -Od f1.cxx
icl -Qvc14.2 -Icatch/2.11.1/include -c -EHsc -Z7 -Od f2.cxx
icl -Icatch/2.11.1/include -c -EHsc -Z7 -Od main.cxx

link:
icl main.obj f1.obj f2.obj -o mainicl.exe

execute:
./mainicl.exe

f2.cxx(11): FAILED:
  REQUIRE( output(fun) == false )
with expansion:
  true == false

link (order reversed):
icl main.obj f2.obj f1.obj -o mainiclrev.exe

execute:
./mainiclrev.exe

f1.cxx(11): FAILED:
  REQUIRE( output(fun) == true )
with expansion:
  false == true

We get different errors!

To see what happens:
dumpbin -disasm f1.obj > f1iclobj.txt
dumpbin -disasm f2.obj > f2iclobj.txt

Compare the text files, you see that the lambda functions have exactly the same name mangling!
So it depends on the link order which lambda will be linked. (Microsoft compiler decorates the lambda with some kind of checksum and it worked correctly, also on Linux icc works correctly)

Used configuration:
Windows 10 64bit
Visual Studio 2019 (16.4.5)
Intel C++ 2020 (19.1.0.166 Build 20191121)
Catch 2.11.1

Thank you!

**Comment by drdummel** [comment]
When we change 
TEST_CASE("func1", "[test]")
to
void func1() 
and
TEST_CASE("func2", "[test]")
to
void func2() 

and call
func1();
func2();
in main, the lambdas gets correct mangling from function scopes.

**Comment by horenmar** [comment]
Yeah, I do not think I can fix your compiler for you.

**Comment by drdummel** [comment]
The preprocessor output for f1.cxx is

static void ____C_A_T_C_H____T_E_S_T____0(); __pragma( warning(push) ) namespace{ Catch::AutoReg autoRegistrar1( Catch::makeTestInvoker( &____C_A_T_C_H____T_E_S_T____0 ), ::Catch::SourceLineInfo( "f1.cxx", static_cast<std::size_t>( 8 ) ), Catch::StringRef(), Catch::NameAndTags{ "func1", "[test]" } ); } __pragma( warning(pop) ) static void ____C_A_T_C_H____T_E_S_T____0()
{
	auto fun = []() -> bool {return true;};
	do { Catch::AssertionHandler catchAssertionHandler( "REQUIRE"_catch_sr, ::Catch::SourceLineInfo( "f1.cxx", static_cast<std::size_t>( 11 ) ), "output(fun) == true", Catch::ResultDisposition::Normal ); { __pragma( warning(push) ) catchAssertionHandler.handleExpr( Catch::Decomposer() <= output(fun) == true ); __pragma( warning(pop) ) } catchAssertionHandler.complete(); } while( (void)0, (false) && static_cast<bool>( !!(output(fun) == true) ) );
}

and for f2.cxx

static void ____C_A_T_C_H____T_E_S_T____0(); __pragma( warning(push) ) namespace{ Catch::AutoReg autoRegistrar1( Catch::makeTestInvoker( &____C_A_T_C_H____T_E_S_T____0 ), ::Catch::SourceLineInfo( "f2.cxx", static_cast<std::size_t>( 8 ) ), Catch::StringRef(), Catch::NameAndTags{ "func2", "[test]" } ); } __pragma( warning(pop) ) static void ____C_A_T_C_H____T_E_S_T____0()
{
	auto fun = []() -> bool {return false;};
	do { Catch::AssertionHandler catchAssertionHandler( "REQUIRE"_catch_sr, ::Catch::SourceLineInfo( "f2.cxx", static_cast<std::size_t>( 11 ) ), "output(fun) == false", Catch::ResultDisposition::Normal ); { __pragma( warning(push) ) catchAssertionHandler.handleExpr( Catch::Decomposer() <= output(fun) == false ); __pragma( warning(pop) ) } catchAssertionHandler.complete(); } while( (void)0, (false) && static_cast<bool>( !!(output(fun) == false) ) );
}

In older Catch 1.2.1 the function name
____C_A_T_C_H____T_E_S_T____0
was for example
____C_A_T_C_H____T_E_S_T____#lineno

If you create a unique name depending on line no., compile unit name, path etc.
this will fix the problem.

For some reason Intel C++ compiler creates in f1.cxx
??R<lambda_0>@?1??____C_A_T_C_H____T_E_S_T____0@@YAXXZ@QEBA_NXZ (public: bool __cdecl `void __cdecl ____C_A_T_C_H____T_E_S_T____0(void)'::`2'::<lambda_0>::operator()(void)const ):
and the same in f2.cxx
??R<lambda_0>@?1??____C_A_T_C_H____T_E_S_T____0@@YAXXZ@QEBA_NXZ (public: bool __cdecl `void __cdecl ____C_A_T_C_H____T_E_S_T____0(void)'::`2'::<lambda_0>::operator()(void)const ):
so that the linker get ambiguities!

**Comment by drdummel** [comment]
plz have a look at the raw input, because editor shows not all : /
