### ISSUE TITLE
--list-tests / --list-test-names-only does not respect --out/-o

### ISSUE THREAD

**Issue by schoetbi** [catchorg/Catch2#1878]
**Description**
If I use -l and -o together the output is printed to stdout not to the file declared in -o. I use Catch under a operating system with no pipes so I can not pipe stdout to another file.

**Expected behavior**
Write test list to the file after -o not to stdout.

**Platform information:**
 - OS: **Intervalzero RTX**
 - Catch version: **Catch v2.10.2**

**Comment by horenmar** [comment]
Yeah, for v2 the `--list-*` family of command line flags is kinda weird -- it does not respect `-o`, it does not respect `-r` and it also has non-zero exit code on success.

For backwards compatibility reasons I won't change this in v2, but in v3 the `--list-*` flags are piped through reporters, which respects `-o` naturally.
