### ISSUE TITLE
"benchmark name" has overly wide column width

### ISSUE THREAD

**Issue by uckelman-sf** [catchorg/Catch2#1885]
**Describe the bug**
The "benchmark name" column is too wide for the default `CATCH_CONFIG_CONSOLE_WIDTH` in full analysis mode, which prevents output from appearing as intended on a single line in a terminal which is 80 columns wide.

Example of current output:
```benchmark name                                  samples       iterations    estimated
                                                mean          low mean      high mean
                                                std dev       low std dev   high std dev
-------------------------------------------------------------------------------
to_hex_old 0                                              100            17     2.0876 ms 
                                                     1.188 us      1.177 us      1.215 us 
                                                        84 ns         36 ns        152 ns 
```

**Expected behavior**

```benchmark name                        samples       iterations    estimated
                                      mean          low mean      high mean
                                      std dev       low std dev   high std dev
-------------------------------------------------------------------------------
to_hex_old 0                                    100            17       2.04 ms 
                                           1.112 us      1.103 us      1.132 us 
                                              64 ns         34 ns        121 ns 
```

**Reproduction steps**
Use `BENCHMARK` in a test. See the output.

**Additional context**
The problem is caused by setting the "benchmark name" column width to `CATCH_CONFIG_CONSOLE_WIDTH - 32` in `ConsoleReporter::ConsoleReporter()`, when the other three columns are each 14 characters wide. (14*3 = 42 > 32).

**Comment by drazen911** [comment]
The problem is caused by setting the "benchmark name" column width to CATCH_CONFIG_CONSOLE_WIDTH - 32 in ConsoleReporter::ConsoleReporter(), when the other three columns are each 14 characters wide. (14*3 = 42 > 32).
