### ISSUE TITLE
All tests passed (166 assertions in 1 test case)  free(): invalid pointer

### ISSUE THREAD

**Issue by Linshiqi** [catchorg/Catch2#1887]
Its seems like all tests passed, but something wrong in catch2 clean up.

Catch v2.11.1

1: ===============================================================================
1: All tests passed (166 assertions in 1 test case)
1: 
1: free(): invalid pointer
1/1 Test #1: catch_test .......................Child aborted***Exception:   0.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.01 sec

The following tests FAILED:
          1 - catch_test (Child aborted)
Errors while running CTest

**Comment by drazen911** [comment]
That's true

**Comment by horenmar** [comment]
Try running your tests under Valgrind.

**Comment by VioletGiraffe** [comment]
This is not a bug in Catch2, it's a bug in your code that you're testing.
