### ISSUE TITLE
multiple tests as argument acts weirdly 

### ISSUE THREAD

**Issue by matepek** [catchorg/Catch2#1905]
**Describe the bug**
suite5.cpp
```cpp
#define CATCH_CONFIG_MAIN
#include "catch2/catch.hpp"
TEST_CASE("spec , char") {}
TEST_CASE("spec . char") {}
```

Running: 
```bash
./suite5.exe '"spec . char","spec \, char"'
```
result output: ❌
```bash
basic_string
```

The other way around works: ✅
```bash
./suite5.exe '"spec \, char","spec . char"'
Filters: "spec \, char","spec . char"
===============================================================================
test cases: 2 | 2 passed
assertions: - none -
```

I also tried this: ❌
```bash
./out/cpp/suite5.exe "\"spec . char\",\"spec \\, char\""
basic_string
```

**Platform information:**

 - OS: macOS 10.15.3
 - Compiler+version: Apple clang version 11.0.0 (clang-1100.0.33.17)
 - Catch version: v2.11.1
 - Command line: zsh 5.8 (x86_64-apple-darwin19.3.0)
    Same result with GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

**Additional context**

**Comment by horenmar** [comment]
Found the bug, the problem was that the test spec parser did not properly clear state between ORed test specs. I did a hotfix that shouldn't break anything, but the relevant part of the code is a giant mess that badly needs rewrite in the future.

**Comment by horenmar** [comment]
Also, as to the linked issue, I would recommend trying a much simpler approach, which is to run tests in parallel based on their file of origin. Add `-# [#file_name]` to the command line to invoke all tests within `file_name.xxx`.
