### ISSUE TITLE
multiple tests as argument with `\` acts weirdly

### ISSUE THREAD

**Issue by matepek** [catchorg/Catch2#1912]
**Describe the bug**
suite5.cpp
```cpp
#define CATCH_CONFIG_MAIN
#include "catch2/catch.hpp"
TEST_CASE("spec , char") {}
TEST_CASE("spec \\ char") {}
TEST_CASE("spec [a] char") {}
TEST_CASE("spec {a} char") {}
```

Running: 
```bash
./suite5.exe "spec ' char,spec \\ char"
```
result output: ❌
```bash
basic_string
```

Also escaping `[` doesn't work either.
```bash
./suite5.exe "spec {a} char,spec \\[a] char" 
```
result output: ❌
```bash
basic_string
```

**Platform information:**

 - OS: macOS 10.15.3
 - Compiler+version: Apple clang version 11.0.0 (clang-1100.0.33.17)
 - Catch version: commit `5d32ce2`
 - Command line: zsh 5.8 (x86_64-apple-darwin19.3.0)
    Same result with GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

**Additional context**
Probably relates to #1905

**Comment by horenmar** [comment]
Did you regenerate the single header? Because if I do so, and fix escaping, the second works for me:

```
$ ./a.out 'spec {a} char,spec \[a] char' --list-tests
Matching test cases:
  spec [a] char
  spec {a} char
2 matching test cases
```

Notice just one `\` as the escape.

The first does not quite work, but it no longer crashes, but for some weird reason the literal `\` is not matched...

```
$ ./a.out "spec ' char,spec \\ char" --list-tests
Matching test cases:
0 matching test cases
```

**Comment by horenmar** [comment]
So, the second one works as well, but you have to avoid bash interpolation:

```
$ echo "\\"
\
$ echo '\\'
\\
```
If you have to get a `\\` to Catch2 through Bash or similar, you will have to use `\\\\`, or forbid it from interpolating the strings. 🤷

**Comment by matepek** [comment]
I'm starting the process from nodejs.
I forget to regenerate the singe header file.
Thanks for the support ^^
Any idea when will your suer get a release version which contains the bugfix?

**Comment by horenmar** [comment]
I intend to make a release during the weekend/Monday.
