### ISSUE TITLE
Warnings reported by clang-tidy due to use of `var_arg`

### ISSUE THREAD

**Issue by avitase** [catchorg/Catch2#1921]
**Description**
Using `REQUIRE` [triggers clang-tidy](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-type-vararg.html) to warn about the usage of `var_arg`. Using `NOLINT` at each and every call to `REQUIRE` resolves this issue but is very tedious... Maybe there is way to avoid the usage of `var_arg` (as suggested by core guidelines [F.55](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f55-dont-use-va_arg-arguments)) or maybe add `NOLINT` to the definition of the macro?

**Comment by horenmar** [comment]
Which version are you using?

**Comment by avitase** [comment]
`catch2/2.11.0` via conan

**Comment by horenmar** [comment]
That's quite a bit behind. Have you tried updating?

**Comment by avitase** [comment]
sorry, my mistake. I mixed up the versions. The "error" occurs since `catch2/2.11.3` (i.e. including `catch2/2.12.1`). Version `catch2/2.11.1` is the last that is not "affected". (`2.11.2` is not available via conan.)

**Comment by horenmar** [comment]
Interesting, that [warning should already be suppressed](https://github.com/catchorg/Catch2/blob/master/include/internal/catch_compiler_capabilities.h) since v2.12.0. Can you check why the `NOLINT` is not obeyed in your configuration?

**Comment by avitase** [comment]
I am not quite sure how. But maybe this error log helps? This is from version `catch2/2.12.0` but it is the very same for `catch2/2.12.1` (including the line numbers). You are right, obviously there is the `/* NOLINT(cppcoreguidelines-pro-type-vararg) */` comment and I don't know why it is skipped. I cannot test it right now, but just two things that pop up to my mind: I always use `NOLINT` with `//` instead of a `/*` ... `*/` or maybe this issue is related to my old clang-tidy version [`7.0.1`](https://releases.llvm.org/7.0.0/tools/clang/tools/extra/docs/clang-tidy/index.html) ...

```
[...] tests.cpp:10:3: error: do not call c-style vararg functions [hicpp-vararg,-warnings-as-errors]
  REQUIRE(Factorial(1) == 1);
  ^
[...] catch2/catch.hpp:17394:24: note: expanded from macro 'REQUIRE'
#define REQUIRE( ... ) INTERNAL_CATCH_TEST( "REQUIRE", Catch::ResultDisposition::Normal, __VA_ARGS__  )
                       ^
[...] catch2/catch.hpp:2698:9: note: expanded from macro 'INTERNAL_CATCH_TEST'
        CATCH_INTERNAL_IGNORE_BUT_WARN(__VA_ARGS__); \
        ^
[...] catch2/catch.hpp:166:55: note: expanded from macro 'CATCH_INTERNAL_IGNORE_BUT_WARN'
#    define CATCH_INTERNAL_IGNORE_BUT_WARN(...) (void)__builtin_constant_p(__VA_ARGS__) /* NOLINT(cppcoreguidelines-pro-type-vararg) */
                                                      ^
```

**Comment by horenmar** [comment]
@moha-gh Hey, can you confirm what clang-tidy version are you running?

**Comment by moha-gh** [comment]
@horenmar: We are using v9. I think the issue here is that for @avitase `hicpp-vararg` triggers, while the `NOLINT` is limited to `cppcoreguidelines-pro-type-vararg`. However, the `hicpp` warning [is an alias](https://releases.llvm.org/7.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/hicpp-vararg.html) for the `cppcoreguidelines` one. clang-tidy doesn't seem to take this into account when processing the NOLINT - even on v9: If I also enable `hicpp-vararg` in our config, I get the same warning locally. So I guess the solution would be to either extend the existing NOLINT

```
/* NOLINT(cppcoreguidelines-pro-type-vararg, hicpp-vararg) */
```

(works for me and my preference) or make it suppress every finding:

```
/* NOLINT */
```

**Comment by horenmar** [comment]
Ok, I will suppress the warning in both variants, and open up an issue with clang-tidy upstream.

**Comment by avitase** [comment]
thanks for your help

**Comment by horenmar** [comment]
Okay, this is now fixed in master.

I also opened two bugs in clang-tidy's bugzilla,
* [one for silencing via aliases](https://bugs.llvm.org/show_bug.cgi?id=45859)
* [one for `__builtin_constant_p`](https://bugs.llvm.org/show_bug.cgi?id=45860)
