### ISSUE TITLE
Cannot compile with REQUIRE_THROWS_MATCHES

### ISSUE THREAD

**Issue by whatsthecraic** [catchorg/Catch2#1926]
Hey there,

consider the following snippet of code:
```
REQUIRE_THROWS_AS( ... , LogicalError ) ; // okay
REQUIRE_THROWS_WITH( ... , Contains("blah") ); // okay
REQUIRE_THROWS_MATCHES( ... , LogicalError, Contains("blah") ); // build error
```
Where ... is the same in all the above three cases. I'm able to compile the first two statements, but not the third one:
```
../tests/catch.hpp: In instantiation of ‘Catch::MatchExpr<ArgT, MatcherT>::MatchExpr(const ArgT&, const MatcherT&, const Catch::StringRef&) [with ArgT = LogicalError; MatcherT = Catch::Matchers::StdString::ContainsMatcher]’:
../tests/catch.hpp:3755:16:   required from ‘Catch::MatchExpr<ArgT, MatcherT> Catch::makeMatchExpr(const ArgT&, const MatcherT&, const Catch::StringRef&) [with ArgT = LogicalError; MatcherT = Catch::Matchers::StdString::ContainsMatcher]’
../tests/test_iterator.cpp:531:5:   required from here
../tests/catch.hpp:3736:44: error: cannot convert ‘const LogicalError’ to ‘const string&’ {aka ‘const std::__cxx11::basic_string<char>&’}
 3736 |             m_matcherString( matcherString )
      |                                            ^
In file included from ../tests/test_iterator.cpp:18:
../tests/catch.hpp:3517:44: note:   initializing argument 1 of ‘virtual bool Catch::Matchers::StdString::ContainsMatcher::match(const string&) const’
 3517 |             bool match( std::string const& source ) const override;
      |                         ~~~~~~~~~~~~~~~~~~~^~~~~~
In file included from ../tests/test_iterator.cpp:18:
../tests/catch.hpp:3736:44: error: no matching function for call to ‘Catch::ITransientExpression::ITransientExpression(<brace-enclosed initializer list>)’
 3736 |             m_matcherString( matcherString )
      |                                            ^
In file included from ../tests/test_iterator.cpp:18:
../tests/catch.hpp:2180:9: note: candidate: ‘Catch::ITransientExpression::ITransientExpression(bool, bool)’
 2180 |         ITransientExpression( bool isBinaryExpression, bool result )
      |         ^~~~~~~~~~~~~~~~~~~~
../tests/catch.hpp:2180:9: note:   conversion of argument 2 would be ill-formed:
../tests/catch.hpp:2175:12: note: candidate: ‘constexpr Catch::ITransientExpression::ITransientExpression(const Catch::ITransientExpression&)’
 2175 |     struct ITransientExpression {
      |            ^~~~~~~~~~~~~~~~~~~~
../tests/catch.hpp:2175:12: note:   candidate expects 1 argument, 2 provided
```

 LogicalError is a descendant of std::runtime_error. What are the requirements for the API of REQUIRE_THROWS_MATCHES to work?

GCC 9.3.0, linux, catch v.2.11.1

**Comment by horenmar** [comment]
Right, the difference between `REQUIRE_THROWS_WITH` and `REQUIRE_THROWS_MATCHES` is that the former is specialized to use string matcher on the exception message*, while the latter is a fully generic Matcher macro. This means that the matcher's argument type has to match the exception type, which it does not in your case -- the argument type of `Contains` is `std::string`, while you are passing it `LogicalError`.


* As long as Catch2 understands how to turn that exception into a string.

**Comment by whatsthecraic** [comment]
Hi @horenmar,
thanks for the quick reply and the explanation.

**Comment by nrwahl2** [comment]
> the argument type of `Contains` is `std::string`, while you are passing it `LogicalError`.

What is a valid argument of `Contains` supposed to look like? OP was passing it a `std::string`, not a `LogicalError`. `"blah"` is a string.

**Comment by horenmar** [comment]
@nrwahl2 The construction `Contains("blah")` is fine. The problem is that you get a String matcher, whose `match` method expects `std::string` as an argument. If you use `REQUIRE_THROWS_MATCHES(expr, ExceptionType, Matcher)`, the constructed matcher must accept `ExceptionType` as the argument to its `match` method.

**Comment by PiCake314** [comment]
For future reference, the proper way to use `REQUIRES_THROWS_MATCHES` with a specific message is as follows:

```
REQUIRE_THROWS_MATCHES(expr, ExceptionType, Catch::Matchers::MessageMatches(Catch::Matchers::ContainsSubstring("blah")));
```
