### ISSUE TITLE
Using std::memset in getLineOfChars is UB

### ISSUE THREAD

**Issue by sheerluck** [catchorg/Catch2#1927]
**Describe the bug**
Using std::memset in getLineOfChars is UB

**Expected behavior**
Implement getLineOfChars without std::memset

**Reproduction steps**
I can not :(

**Platform information:**
in all platforms

**Additional context**
https://github.com/catchorg/Catch2/blob/master/include/reporters/catch_reporter_bases.hpp#L264

**Comment by horenmar** [comment]
Why is it UB?

**Comment by sheerluck** [comment]
instead of
```
    template<char C>
    char const* getLineOfChars() {
        static char line[CATCH_CONFIG_CONSOLE_WIDTH] = {0};
        if( !*line ) {
            std::memset( line, C, CATCH_CONFIG_CONSOLE_WIDTH-1 );
            line[CATCH_CONFIG_CONSOLE_WIDTH-1] = 0;
        }
        return line;
    }
```
we can use
```
    template<char C>
    char const* getLineOfChars() {
        static std::array<char, CATCH_CONFIG_CONSOLE_WIDTH> line = {0};
        if( 0 == line[0] ) {
            line.fill(C);
            line[CATCH_CONFIG_CONSOLE_WIDTH-1] = 0;
        }
        return line.data();
    }
```
because both `std::memset( line ... )` and `line.fill(C);` are
```
        mov edx, line
        mov ecx, CATCH_CONFIG_CONSOLE_WIDTH-1
        mov eax, <char C>
        rep stosb
```
so maybe in this particular case std::memset don't cause UB.
I guess I just prefer  `line.fill(C);`

**Comment by horenmar** [comment]
Right. If it is not UB, there is no reason to change it.
