### ISSUE TITLE
3.0 RC Release notes got a typo

### ISSUE THREAD

**Issue by NeroBurner** [catchorg/Catch2#1932]
**Describe the bug**
A word is missing (or a `for` is to much) in the `Other changes` section of https://github.com/catchorg/Catch2/releases/tag/v3.0.0-preview2

![Screenshot_20200515_080636](https://user-images.githubusercontent.com/9076163/82017350-3f978c00-9683-11ea-8196-7df5fa9e0f3c.png)

I think it should either be:

> `StringMaker` specializations for `chrono` are always provided

or

> `StringMaker` specializations are always provided

**Comment by horenmar** [comment]
Thanks.

The markdown contains the `<chrono>` header without backticks, so it is interpreted as a tag. I actually noticed it yesterday, but didn't realize it will break the output so I didn't bother fixing it.

**Comment by NeroBurner** [comment]
You're welcome. And thanks to the dedication to this awesome test framework!
