### ISSUE TITLE
Compilation failures with the latest MSVC v142 toolchain (Visual Studio 16.6.0)

### ISSUE THREAD

**Issue by VioletGiraffe** [catchorg/Catch2#1934]
~~Must be due to this change shipped in [16.6](https://github.com/microsoft/STL/wiki/Changelog#shipped-in-vs-2019-166)~~

I was wrong, it must be this one: "Removing C++17-Deprecated Features In C++20". You will need `/std:c++latest` to reproduce the error, which is caused by `std::result_of` not being available anymore.

**Comment by VioletGiraffe** [comment]
Workaround: define macro `_HAS_DEPRECATED_RESULT_OF=1`

**Comment by horenmar** [comment]
Oh, nevermind, that doesn't actually fix it, master just doesn't properly test benchmarking.
