### ISSUE TITLE
Problems compiling to Embarcadero Tokyo C++ Free Compiler 

### ISSUE THREAD

**Issue by Tomatin** [catchorg/Catch2#1937]
Hi !

When I try to compile doc test with this compiler, these errors appear:

\third_party\catch\catch.hpp:11429:18: error: no member named 'nextafterf' in the global namespace
        return ::nextafterf(x, y);
               ~~^

Someone could help me ?

Thanks in advance !

**Comment by horenmar** [comment]
Try [`CATCH_CONFIG_NO_GLOBAL_NEXTAFTER`](https://github.com/catchorg/Catch2/blob/master/docs/configuration.md#other-toggles), and hope that your stdlib provides `std::nextafter`.

**Comment by pmcgee69** [comment]
Embarcadero 10.3.3 (Community Edition) Clang 5.0.0 64 bit - compiled and ran with the addition of 
"#define _GLIBCXX_USE_C99_MATH_TR1"

Is this an acceptable solution, and can I test that it is not creating a silent error somewhere?

**Comment by horenmar** [comment]
It should be fine. That define tells glibc to provide C99 math facilities.

**Comment by pmcgee69** [comment]
In fact, before I remembered to come back here, I did #define CATCH_CONFIG_NO_GLOBAL_NEXTAFTER as it says above, and that also compiled and ran.
(BTW the 32 bit clang compiler, on the other hand, totally died, and I have communicated that to the company)

**Comment by horenmar** [comment]
Right.

What it boils down to is that Catch2 tries to use C's stdlib `::nextafterf` and `::nextafter`, which are parts of C99. If you define `CATCH_CONFIG_NO_GLOBAL_NEXTAFTER`, it instead uses `std::nextafter`, which is C++11 feature. IIRC the reason that the default is using C99's math library is that it was more commonly present on a platform than `std::nextafter`.
