### ISSUE TITLE
INTERNAL_CATCH_UNIQUE_NAME should be more specific

### ISSUE THREAD

**Issue by jimon** [catchorg/Catch2#1940]
**Description**
When debugging crashes on a machine without debugger, callstack looks something like that:
```
18: foo - 0x7FF7F735F8E0
17: ____C_A_T_C_H____T_E_S_T____98 - 0x7FF7F6DC7900
16: Catch::TestInvokerAsFunction::invoke - 0x7FF7F72D7BC0
15: Catch::TestCase::invoke - 0x7FF7F72CB2E0
```
It's kinda hard to pin point which test fails from this name :) Would be nice if it was a bit more specific.

**Comment by horenmar** [comment]
Is there a reason you cannot have debug info enabled?

**Comment by jimon** [comment]
It's a build with partial debug info (given function names in callstack), but I don't have debugger.
One way would be to remap pointer to source file, but that is usually tricky in stacktrace crash handler printers

**Comment by horenmar** [comment]
Well, you could define `CATCH_CONFIG_NO_COUNTER` and the number after the name will be the line no.

However, there is a problem with this: it affects all unique names Catch2 constructs, so you cannot have two of the same macro on a line.
