### ISSUE TITLE
Includes & Usage: v3 docs/

### ISSUE THREAD

**Issue by ax3l** [catchorg/Catch2#1944]
**Description**
It looks like the docs and tutorials in `docs/` do not even use the "new" `catch2/catch.hpp` include, introduced in v2.3.0+, yet.

With respect to v3, the same files as well as the tutorial should be reworked. A table with all public includes and their usage would be good in there a well.

**Additional context**
I am trying to use v3 preview 2 :-) but the shipped docs are outdated and I am left confused.

**Comment by horenmar** [comment]
To quote from the preview release notes

>Note that documentation has not yet been updated to account for the
new design.

🤷

**Comment by ax3l** [comment]
Ups, overlooked. Sorry for that!

**Comment by horenmar** [comment]
No problem. I recognize that updated documentation is needed before final release, but the header splits aren't even final yet, and it also has lower priority than other changes.
