### ISSUE TITLE
Generate JUnit report using catch_discover_tests

### ISSUE THREAD

**Issue by jheaff1** [catchorg/Catch2#1946]
**Description**
When using the catch2_discover_tests CMake function, it is currently not possible to generate a JUnit report for each test (i think). 

My project CMakeLists.txt file contains the following

```
catch_discover_tests(
${PROJECT_NAME}_tests
EXTRA_ARGS -r junit -o report.xml
)
```

This will generate "report.xml" for each test scenario and overwrite the previous "report.xml"

Is there a way to generate a JUnit report for all tests when using catch_discover_tests?

**Comment by globberwops** [comment]
CMake's own [GoogleTest module](https://cmake.org/cmake/help/latest/module/GoogleTest.html) suffered from the same issue.
That's why **XML_OUTPUT_DIR** was introduced in version 3.18.

> XML_OUTPUT_DIR dir
> If specified, the parameter is passed along with --gtest_output=xml: to test executable. The actual file name is the same as > the test target, including prefix and suffix. This should be used instead of EXTRA_ARGS --gtest_output=xml to avoid race > conditions writing the XML result output when using parallel test execution.

**Comment by globberwops** [comment]
Here's a working implementation of `XML_OUTPUT_DIR` arg to `catch_discover_tests` based on CMake's `GoogleTest` module.

https://github.com/globberwops/Catch2/commit/b0dcfbc4bb5eb21da5fa28edb097587bffe87b99
