### ISSUE TITLE
stringification in CAPTURE(...) doesn't work for a type, but INFO(...) is fine

### ISSUE THREAD

**Issue by jwdevel** [catchorg/Catch2#1949]
**Describe the bug**
I am using the [glm](https://github.com/g-truc/glm) library in some tests. When using types such as `glm::vec4`, they are output as `{?}` by Catch2.
I can get them to output correctly in INFO(...) statements, but not in CAPTURE(...) or REQUIRE(...).

**Expected behavior**
Stringification of a type should behave consistently across INFO, CAPTURE, REQUIRE, etc.

**Reproduction steps**
I have several permutations of my test below, each trying a different technique to provide custom string representations.
They each fail in some way, which I have noted in the comments.

If there are other variations I should try, please let me know.

Not providing any custom stringification:

``` cpp
#include <glm/vec4.hpp>

#include <catch2/catch.hpp>

TEST_CASE("no custom tostring") {
	glm::vec4 x(1,2,3,4);
	// This fails to compile, due to the below line. Error is:
	// catch2/single_include/catch2/catch.hpp(1431 col 20) error: no match for ‘operator<<’ (operand types are ‘std::ostream’ {aka ‘std::basic_ostream<char>’} and ‘const glm::vec<4, float, (glm::qualifier)0>’)
	// If I comment out the INFO line, I still see "{?}" in the other output.
	INFO("value is: " << x);
	CAPTURE(x);
	REQUIRE(x == glm::vec4(4,5,6,7));
}
```

Providing `operator<<` at global scope (per [documentation](https://github.com/catchorg/Catch2/blob/master/docs/tostring.md#operator--overload-for-stdostream)):

``` cpp
#include <glm/vec4.hpp>

#include <iostream>

std::ostream& operator<<(std::ostream& os, const glm::vec4& v) {
	return os << "vec4(" << v.x << "," << v.y << "," << v.z << "," << v.w << ")";
}

#include <catch2/catch.hpp>

TEST_CASE("global operator<<") {
	glm::vec4 x(1,2,3,4);
	INFO("value is: " << x);
	CAPTURE(x);
	REQUIRE(x == glm::vec4(4,5,6,7));

	// Compiles, and test fails with output:
	//     tests/main.cpp(17) FAILED:
	//       REQUIRE( x == glm::vec4(4,5,6,7) )
	//     with expansion:
	//       {?} == {?}
	//     with messages:
	//       value is: vec4(1,2,3,4)
	//       x := {?}
	
	// PROBLEM: notice the {?} for the expansion and the CAPTURE value.
	// However, the INFO output is correct.
}
```

Providing `operator<<` in `glm` namespace (per [documentation](https://github.com/catchorg/Catch2/blob/master/docs/tostring.md#operator--overload-for-stdostream)):

``` cpp
#include <glm/vec4.hpp>

#include <iostream>

namespace glm {
std::ostream& operator<<(std::ostream& os, const glm::vec4& v) {
	return os << "vec4(" << v.x << "," << v.y << "," << v.z << "," << v.w << ")";
}
}

#include <catch2/catch.hpp>

TEST_CASE("glm::operator<<") {
	glm::vec4 x(1,2,3,4);
	INFO("value is: " << x);
	CAPTURE(x);
	REQUIRE(x == glm::vec4(4,5,6,7));

	// Identical result to "global operator<<" case.
}
```

Providing `Catch::toString` (per [old comment](https://github.com/catchorg/Catch2/issues/405#issuecomment-94865552)):

``` cpp
#include <glm/vec4.hpp>

#include <iostream>

namespace Catch {
std::string toString(const glm::vec4 &) {
    return std::string("vec4(some data here)");
}
}

#include <catch2/catch.hpp>

TEST_CASE("Catch::toString") {
	glm::vec4 x(1,2,3,4);
	// This fails to compile, due to the below line.
	// Same error message as in the "no custom tostring" test case.
	// If I comment out the INFO line, I still see "{?}" in the other output.
	INFO("value is: " << x);
	CAPTURE(x);
	REQUIRE(x == glm::vec4(4,5,6,7));

}
```

Providing specialization of `Catch::StringMaker` (per [documentation](https://github.com/catchorg/Catch2/blob/master/docs/tostring.md#catchstringmaker-specialisation)):

``` cpp
#include <glm/vec4.hpp>

#include <catch2/catch.hpp>

namespace Catch {
    template<>
    struct StringMaker<glm::vec4> {
        static std::string convert(const glm::vec4 &) {
    		return std::string("vec4(some data here)");
        }
    };
}

TEST_CASE("Catch::StringMaker") {
	glm::vec4 x(1,2,3,4);
	// This fails to compile, due to the below line.
	// Same error message as in the "no custom tostring" test case.
	// If I comment out the INFO line, I still see "{?}" in the other output.
	INFO("value is: " << x);
	CAPTURE(x);
	REQUIRE(x == glm::vec4(4,5,6,7));

}
```

**Other Info**

I don't know what is special about the `glm::` types. Otherwise, Catch2 is generally working for me. I can do custom stringification for my own types, for instance.

**Comment by horenmar** [comment]
Some quick notes:
* `toString` only existed in v1, v2 no longer uses it.
* `INFO("..." << x)` only works with types that have the `operator<<`, providing `StringMaker` specialization will not help

The fact that neither `operator<<` nor `StringMaker` specialization work is weird -- under some circumstances, `operator<<` is unreliable because of ADL, but if neither works, then there is something suspicious about the type.

**Comment by jwdevel** [comment]
> which compiler did you test?

gcc (Debian 8.3.0-6) 8.3.0

One thing of note about the `glm` stuff is there are a lot of implicit constructors. For instance, you can make a `glm::vec4` via `vec4(vec2(a,b), vec2(c,d)), or via `vec4(a,b,c,d)`, or via `vec4(vec3(a,b,c),d)`, etc. I don't know if that's relevant, but it is one difference with my own types that I've tried (with success).

**Comment by horenmar** [comment]
So, I tried to repro this, and cannot:

```
$ cat repro.cpp
#include <glm/vec4.hpp>

#include <ostream>

std::ostream& operator<<(std::ostream& out, glm::vec4 const& vec) {
    out << "op<<(vec)";
    return out;
}

#include "catch.hpp"


TEST_CASE("no custom tostring") {
	glm::vec4 x(1,2,3,4);
	INFO("value is: " << x);
	CAPTURE(x);
	REQUIRE(x == glm::vec4(4,5,6,7));
}

$ make && ./repro -s

[100%] Built target repro

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
repro is a Catch v2.12.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
no custom tostring
-------------------------------------------------------------------------------
/mnt/c/ubuntu/catch-1949/repro.cpp:13
...............................................................................

/mnt/c/ubuntu/catch-1949/repro.cpp:20: FAILED:
  REQUIRE( x == glm::vec4(4,5,6,7) )
with expansion:
  op<<(vec) == op<<(vec)
with messages:
  value is: op<<(vec)
  x := op<<(vec)

===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed
```

**Comment by horenmar** [comment]
Putting `op<<` into `glm` namespace also works as expected, same goes for specializing StringMaker. This is using Clang 10.0.1.

**Comment by jwdevel** [comment]
Some additional strangeness:

Given your last commanet, I was going to try testing on various compilers.
So, I dumped everything to a preprocessed single file (so I could #include it in [godbolt](https://godbolt.org/), I was hoping).

However, when I compiled and ran that locally, everything worked.

The only change I made was adding `#define CATCH_CONFIG_MAIN`, since I had been using `CATCH_CONFIG_RUNNER` in my real code.

So, that's weird to me.

One other difference, of course, is all the stuff I'm not linking against with a single CPP file, versus my real project.
Will try to narrow it down as I have time.

If you have it set up already, could you try doing your test again, but with `#define CATCH_CONFIG_RUNNER`, just to rule that out?

If so, I imagine it's an issue on my own setup somehow (though still a mystery to me).

**Comment by horenmar** [comment]
Nope, still cannot reproduce.

**Comment by alessiocali** [comment]
Resurrecting this thread because I think I stumbled upon the same issue. I think the reason the @jwdevel 's issue could not be reproduced is due to template caching. 

If @jwdevel had other tests where `gml/vec4.hpp` was being `CHECK`ed , then the compiler would have already specialized the generic `Catch::StringMaker<glm::vec4>`. It doesn't matter if the type trait changed later, when re-specializing the template the compiler might have decided to reuse the generic, cached specialization. Which means the pretty printing would go ignored.

**Comment by jwdevel** [comment]
Thanks for that info @alessiocali — how did you end up solving it?

I guess if that's the culprit, one solution would be to rigorously make sure all tests that might use that template have the appropriate stringification defined too (perhaps via some  `#include <my_vec4.h>` wrapper header) ?

Also, if that caching issue is the culprit, is that a compiler bug? Or is that one of the fuzzy areas of C++ standard?

**Comment by alessiocali** [comment]
I'm not sure how compliant it is with the standard, in my case the operator was defined in a different header, sometimes included sometimes not. I will just move the operator to the class' header. In your case, as you said, you are probably better off wrapping the dependency and using your header instead.

**Comment by ruifig** [comment]
Resurrecting this because I think I might have spotted the problem (in my case).
Using VS 2022 (latest version) and Catch 3.4.

I'm using precompiled headers, and Catch2 headers are of course included there.
Seems like the StringMaker specializations need to be also in the precompiled header.

Don't think I ever encountered this problem before.

**Comment by alessiocali** [comment]
While investigating this issue again, I stumbled in this blog post which I think explains it perfectly
https://brevzin.github.io/c++/2023/01/19/debug-fmt-catch/#the-one-definition-rule

Long story short, due to ODR the compiler might see two definitions for the StringMaker in different files (the default one, and the specialization), and arbitrarily pick one or the other. I had funky cases where `CAPTURE(x)` worked but `REQUIRE(x != x)` didn't because CAPTURE was invoked in just one file that included the specialization, and REQUIRE was used somewhere else.

There aren't many solutions to this but one possible is to include the stringmaker specialization along with the custom type header, possibly with an opt-in.

**Comment by felixcrazzolara** [comment]
I just noticed that the stringification doesn't work if the type lives in another namespace.
Edit: I had to move the definition of the << operator overload for ostream into the same namespace as the class for which it's overloaded.
