### ISSUE TITLE
Inconsistency in licensing

### ISSUE THREAD

**Issue by rtshilston** [catchorg/Catch2#1952]
**Describe the bug**
Catch2 is described as being MIT license, but includes GPL3 code.

**Expected behavior**
No other licenses to be in use.

**Reproduction steps**
Review header of scripts/updateDocumentToC.py which says GPL3

**Platform information:**
N/A

**Additional context**
N/A

**Comment by horenmar** [comment]
I have absolutely no idea how you came up with MIT licence. The library source code is BSD, development support tooling depends.

**Comment by rtshilston** [comment]
@horenmar - Please accept my apologies.  I must have been tired when I wrote the bug.  Yes, Catch2 is BSL.  However, the rest of the bug is accurate.  The code base includes a script which contains a GPL3 header.

**Comment by horenmar** [comment]
I still do not see the problem. All of the source code is BSL.
