### ISSUE TITLE
Approx Usage & Constructors (margin & epsilon)

### ISSUE THREAD

**Issue by phil-zxx** [catchorg/Catch2#1962]
Hi,

I often have to deal with floating point values and hence use the `Approx` class. But I've never completely understood the the use of `epsilon`, `scale` and `margin`.

Lets look at this example:
```cpp
const double testValue = 0.98765;
const double trueValue = 0.98766;
CHECK(Approx(testValue).margin(1.e-14) == trueValue);  // this gives CHECK(true)
```
Here `CHECK` will pass, even though the true absolute difference is `0.00001 = 1e-05` and the margin is set to `1.e-14`. To truly ensure `CHECK` only passes for differences less than `1.e-14` we would need to add `epsilon(0)` and write
```cpp
CHECK(Approx(testValue).margin(1.e-14).epsilon(0) == trueValue);  // now we get CHECK(false)
```

---

Questions:

1. What purpose does `epsilon > 0` serve? And why does it default to `std::numeric_limits<float>::epsilon()*100`, as opposed to `std::numeric_limits<double>::epsilon()*100`. I am asking since all comparisons are based on `double` values, and not `float` values.<br>

2. Writing `Approx(testValue).margin(1.e-14).epsilon(0)` seems very verbose to me. Why not have an additional constructor like `Approx(double value, double margin, double epsilon)`  so that we can simplify the expression to `Approx(testValue, 1.e-14, 0)`.<br>
In fact, in my local version I have added `Approx(double value, double margin)` with `epsilon` defaulting to 0, as this results in the strictest default behavior.

**Comment by jwdevel** [comment]
Perhaps this document helps you: https://github.com/catchorg/Catch2/blob/devel/docs/comparing-floating-point-numbers.md#top

Specifically, the section on [`Approx`](https://github.com/catchorg/Catch2/blob/devel/docs/comparing-floating-point-numbers.md#approx) says:

> The downside to Approx is that it has a couple of issues that we cannot fix without breaking backwards compatibility. Because Catch2 also provides complete set of matchers that implement different floating point comparison methods, Approx is left as-is, is considered deprecated, and should not be used in new code.

I think some of those issues are related to what you are seeing. Not the verbosity, though (:
