### ISSUE TITLE
GitHub action for Catch2 tests

### ISSUE THREAD

**Issue by pozemka** [catchorg/Catch2#1964]
**Description**
It would be nice to have GitHub action to integrate Catch2 **tests** into GitHub workflows. So it will run tests on commit and if something goes wrong it can mark workflow as failed. 

**Additional context**
I found Catch2 **benchmark** action [here](https://github.com/marketplace/actions/continuous-benchmark) but it is not exactly what i wanted.

**Comment by TysonRayJones** [comment]
Hi there,
This is already possible, and probably a common use of Catch2. Just have your GithubAction compile and run your Catch2 tests. [Here's](https://github.com/QuEST-Kit/QuEST/blob/develop/.github/workflows/macos-unit.yml) an example using CMake.

**Comment by pozemka** [comment]
Thank you @TysonRayJones for good example!
I'm still new to CMake, so I didn't know about this kind of thing. With some trial and error I managed to integrate tests. It is actually very easy!

I am closing the issue.
