### ISSUE TITLE
Min/Max problem in Visual Studio 

### ISSUE THREAD

**Issue by jeffin143** [catchorg/Catch2#1970]
**Describe the bug**

##[warning]tests\catch.hpp(8074,0): Warning C4003: not enough arguments for function-like macro invocation 'min' 

The min/max problem in C++ and Windows -> http://www.suodenjoki.dk/us/archive/2010/min-max.htm

**Expected behavior**
It should compile 

**Reproduction steps**
Import it in a project and build using visual studio 

I haven't used windows for quite a long time -> but this is what I get https://dev.azure.com/mlpack/84320e87-76e3-4b6e-8b6e-3adaf6b36eed/_apis/build/builds/2927/logs/26

**Platform information:**

 - Catch version: **v1.2.3**

 CI workflow : https://github.com/mlpack/mlboard/pull/9
- job: WindowsVS15
  timeoutInMinutes: 360
  displayName: Windows VS15
  pool:
    vmImage: vs2017-win2016

  strategy:
    matrix:
      Plain:
          CMakeArgs-mlpack: '-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_TESTS=OFF'
          CMakeGenerator: '-G "Visual Studio 15 2017 Win64"'
          MSBuildVersion: '15.0'

**Additional context**
May be a work around :- https://github.com/mlpack/mlboard/pull/9/commits/8a115f73964acb99a95b7c9847a0c6482422a92f

If need i can give a quick fix upstream

**Comment by horenmar** [comment]
That's, uh, _ancient_ version of Catch2. Please update.

**Comment by jeffin143** [comment]
Sorry about that , Thanks 
I will go ahead and close it :)
