### ISSUE TITLE
nan == Approx(nan) fails

### ISSUE THREAD

**Issue by fschoenm** [catchorg/Catch2#1974]
**Describe the bug**

The following test case fails:

    REQUIRE(std::numeric_limits<float>::quiet_NaN() == Approx(std::numeric_limits<float>::quiet_NaN()));

with the error message:

      REQUIRE(std::numeric_limits<float>::quiet_NaN() == Approx(std::numeric_limits<float>::quiet_NaN()))
    with expansion:
      nanf == Approx( nan )

**Reproduction steps**
Complete code:

	#define CATCH_CONFIG_MAIN
	#include "catch.hpp"

	#include <limits>

	TEST_CASE("nan") {
	    REQUIRE(std::numeric_limits<float>::quiet_NaN() == Approx(std::numeric_limits<float>::quiet_NaN()));
	}

**Platform information:**

 - OS: **Ubuntu 20.04**
 - Compiler+version: **GCC v9.3.0**
 - Catch version: **v2.12.3**

**Comment by horenmar** [comment]
Given that `NaN != NaN`, why would you expect this to pass?

**Comment by fschoenm** [comment]
@horenmar Oh, I wasn't aware that that's the case. Unfortunately, that makes it a little bit more complicated to check my test results but never mind.
