### ISSUE TITLE
non-const operator overloads not invoked

### ISSUE THREAD

**Issue by philsquared** [catchorg/Catch2#20]
If a class provides an operator overload, typically ==, as a _non-const_ method this will not be used by Catch if the operator is relied on in the assertion comparison. e.g.:

```
struct Test
{
  Test( unsigned int v ) : m_value(v) {}

  bool operator==( const Test&rhs )
  { 
    return (m_value == rhs.m_value);
  }
  unsigned int m_value;
};

TEST_CASE("example/non-const==", "Demonstrate that a non-const == is not used")
{
    Test t( 1 );

    bool ok = (t == 1); // (1)
    REQUIRE(ok);    
    REQUIRE( t == 1 );  // (2)
}
```

In (2) the == operator is not found at all (yet it is in (1)) - leading to a compiler error. Alternative problems are that both const and non-const overloads are provided but the const overload is selected for a non-const object - possibly resulting in different behaviour (although it's hard to think of a case where that this would be justified). Also, if the method takes it's argument by non-const ref, or, again, provides overloads.

This is because the operands are being conveyed through several layers as const-ref arguments.
This could be fixed by providing non-const overloads, but this would involve 3-4x as much code.

It is debatable whether non-const operator methods are good practice, although it is understood that the user may not always have the choice (if they don't own the code in question, for example).

I'm leaning towards const-casting the references when invoking the operators. This has two potential issues, AFAICS:
1. We might still select the wrong overload if both are provided (for either operand) - but this is no worse than the current case, and it's debatable whether this should matter.
2. This is perhaps the same issue, really. If const and non-const overloads are provided and the non-const overload modifies itself or its operand (as applicable), but the test actually passed a const object down, this could result in incorrect side-effects. Again I'm struggling to think of a case where this would really be done, but nonetheless the issue is there.

Comments or criticisms welcome.

**Comment by joe-sonrichard** [comment]
Reading through the comments, I'm having a hard time tracking exactly what is and isn't supported. 

I believe these are the four options - which ones are supported? I'm trying to figure out if my current experience is the expected behavior or not.

```cpp
MyClass {
  public:
   bool operator==(MyClass &rhs); /* supported ? */
   bool operator==(const MyClass &rhs); /* supported ? */
   bool operator==(MyClass &rhs) const; /* supported ? */
   bool operator==(const MyClass &rhs) const; /* supported ? */
};

```

**Comment by horenmar** [comment]
Only the last one is.
