### ISSUE TITLE
BDD-style does not pretty print test cases

### ISSUE THREAD

**Issue by diegopaiva1** [catchorg/Catch2#2000]
**Describe the bug**
I wrote some BDD-style test structure and the test passed as expected. However I did not get the "pretty" output. Same thing happened when I tried the tutorial's example. Therefore the problem is not with my actual code and I will use the tutorial code as demonstration. As I'm new to Catch, I'm not sure whether this is a bug or something I am missing.

**Expected behavior**
```
Scenario: vectors can be sized and resized
     Given: A vector with some items
      When: more capacity is reserved
      Then: the capacity changes but not the size
```

**Reproduction steps**
```cpp
SCENARIO( "vectors can be sized and resized", "[vector]" ) {

    GIVEN( "A vector with some items" ) {
        std::vector<int> v( 5 );

        REQUIRE( v.size() == 5 );
        REQUIRE( v.capacity() >= 5 );

        WHEN( "the size is increased" ) {
            v.resize( 10 );

            THEN( "the size and capacity change" ) {
                REQUIRE( v.size() == 10 );
                REQUIRE( v.capacity() >= 10 );
            }
        }
        WHEN( "the size is reduced" ) {
            v.resize( 0 );

            THEN( "the size changes but not capacity" ) {
                REQUIRE( v.size() == 0 );
                REQUIRE( v.capacity() >= 5 );
            }
        }
        WHEN( "more capacity is reserved" ) {
            v.reserve( 10 );

            THEN( "the capacity changes but not the size" ) {
                REQUIRE( v.size() == 5 );
                REQUIRE( v.capacity() >= 10 );
            }
        }
        WHEN( "less capacity is reserved" ) {
            v.reserve( 0 );

            THEN( "neither size nor capacity are changed" ) {
                REQUIRE( v.size() == 5 );
                REQUIRE( v.capacity() >= 5 );
            }
        }
    }
}
```

**Platform information:**

 - OS: **Ubuntu 18.04.4  LTS**
 - Compiler+version: **GCC v7.5.0**
 - Catch version: **v2.13.0**

**Additional context**
According to this [section](https://github.com/catchorg/Catch2/blob/master/docs/test-cases-and-sections.md#bdd-style-test-cases):

*When any of these macros are used the console reporter recognises them and formats the test case header such that the Givens, Whens and Thens are aligned to aid readability.*

I also tried running Catch v2.10.0 and v1.9.6 but same behavior persisted. This gives the feeling that the documentation is a little confusing. Not sure what I am missing.

**Comment by actinium** [comment]
Catch only prints failing tests and all the tests in your code are successful.
If you want to include successful tests in your output add a `-s` or `--success` when your run your test program.

**Comment by diegopaiva1** [comment]
> Catch only prints failing tests and all the tests in your code are successful.
> If you want to include successful tests in your output add a `-s` or `--success` when your run your test program.

Thank you, that was not clear at all for me.
