### ISSUE TITLE
Format test name in xml-document

### ISSUE THREAD

**Issue by cbrnd** [catchorg/Catch2#2001]
**Description**
I would like to format the test name in the xml-file without changing the catch.hpp file.

I generated a xml file using the JunitReporter and this is the result:
![withoutSpace](https://user-images.githubusercontent.com/69455517/89765757-39387500-daf7-11ea-96f4-424a03ca9965.PNG)
The test name is the combination of the TestCase and the Section, seperated by a slash. I would like to insert a space before and after the slash. I made a small change in the catch.hpp file and got this result:
![withSpace](https://user-images.githubusercontent.com/69455517/89765995-b1069f80-daf7-11ea-8b78-818706d34953.PNG)

Is it possible to somehow insert these whitespaces **without** changing the header file? I tried adding a whitespace at the end of the TestCase-name and at the beginning of the Section-name, but that didn't work.

**Comment by horenmar** [comment]
You could derive from the reporter and then override the specific function that writes these out. Not sure that is easier though. 😃
