### ISSUE TITLE
What macros must be enabled for the correct linkage of catch?

### ISSUE THREAD

**Issue by juandent** [catchorg/Catch2#2009]
I get unresolved external symbols when I try to link a Visual Studio C++ project with one file which has:

```
#include <catch2/catch.hpp>
```

**Expected behavior**
**Being catch a header only library I expect the linking to have no missing external symbols!**

**Reproduction steps**

Steps to reproduce the bug. Create a .cpp file containing:
```
#include <catch2/catch.hpp>

TEST_CASE("Learning Catch")
{
	REQUIRE(1 == 1);
	REQUIRE(1 == 2);
}
```

**Platform information:**
 - OS: Windows 10 Pro
 - Compiler+version: **Visual Studio 2019 16.6.5**
 - Catch version: **v1.2.3**

**Additional context**
The big question here is WHAT I need to #define in order for the missing externals are included. I have #defined the following macros in the project:

CATCH_CONFIG_MAIN;_DEBUG;_CONSOLE

and with this, the error goes away ... but I have code that does not #define CATCH_CONFIG_MAIN and still compiles correctly so I don't understand when this macro needs to be #defined

**Comment by horenmar** [comment]
https://github.com/catchorg/Catch2/blob/9e09d79946b0c4afd815341684c7c4dc4f40c20b/docs/configuration.md#main-implementation

https://github.com/catchorg/Catch2/blob/9e09d79946b0c4afd815341684c7c4dc4f40c20b/docs/own-main.md#supplying-main-yourself

https://github.com/catchorg/Catch2/blob/9e09d79946b0c4afd815341684c7c4dc4f40c20b/docs/slow-compiles.md#practical-example
