### ISSUE TITLE
GENERATE() changes compile time length of arrays

### ISSUE THREAD

**Issue by SmorkalovG** [catchorg/Catch2#2012]
**Description**
GENERATE macro takes type of first argument and cast all other args to it. It is ok for most cases but for string literals it is bad. It takes length of first literal and force it for all.
`TEST_CASE("t", "[t]") {
    auto& str = GENERATE("123", "1");
    WARN(typeid(str).name());
}`
Output
`warning:
  A4_c`
Usually you don't see it. If you use std::string to store the result of GENERATE then everything works fine, all lengths are correct. But some string implementations use length from type of array. E.g., https://stackoverflow.com/questions/2384107/magic-arguments-in-function-templates
This template magic works wrong with GENERATE. I cann't say this is a bug, because I have no idea how to fix it. May be detect arrays and generate compilation error if lengths are different?

It is very bad rule in C++ that references to arrays with different lengths can be cast to each other.

**Comment by horenmar** [comment]
Right, so, there are two parts to this.

1) single `GENERATE` "call" can have only one return type. (even though for e.g. `TEMPLATE_TEST_CASE`, the type can differ across different input types...)
2) deducing string literals as char arrays with specific size _can_ be a problem.

I cannot change 1), and fixing 2) by forcing a pointer decay would break people who already use it with all literals having the same size.

I will have to think about whether there is an use case for having different size string literals deduce as the same size, and if not, `static_assert` that they share length is indeed the best option.


In the meantime, if you have this issue in your code, consider passing `as<char const*>{}` as the first element in `GENERATE`. Doing so forces the type to be deduced as `char const*`.

**Comment by SmorkalovG** [comment]
Thank you for answer.
Yes, casting to string is how I solved this problem in my case.

For general case there is the only solution - detect reference to array. It is a question what to do with it. One option is static assert for length, but it is code breakage. If somebody used `std::string a = GENERATE("a", "ab");` it worked well and, imho, should continue working. But static_assert breaks it. 
Another option is cast to `const char*`. Correct code with std::string continues to compile and incorrect depends on situation. If it could not work without length then it wouldn't compile. And it is good because it was wrong code that worked with wrong length. If it can work with `const char*` instead of `char&[N]` then everything is OK like std::string.

Detection itself can be implemented with function overload, e.g., `template<typename T,size_t N> 
 void generate(T (&a)[N])`

**Comment by horenmar** [comment]
Update: I've decided that for v3 I am going to make arrays decay. Not sure if I will port this to v2 as well.
