### ISSUE TITLE
Compiling with -fsanitize=cfi-unrelated-cast generates an "illegal instruction"

### ISSUE THREAD

**Issue by cjdb** [catchorg/Catch2#2014]
**Describe the bug**
I enable the [control flow integrity][1] sanitiser when building with Clang and ThinLTO. I've deduced that Catch2 continues to work when the compiler is fed `-fsanitize=cfi -fno-sanitize=cfi-unrelated-cast`, but it'll crash with an illegal instruction without `-fno-sanitize=cfi-unrelated-cast` . This leads me to believe that there are some [bad casts][2] happening somewhere.

**Expected behavior**
Catch2 runs without crashing due to bad cast checks.

**Reproduction steps**

```bash
$ export CXX=/usr/bin/clang++-11
$ export CXXFLAGS='-O3 -fvisibility=hidden -fsanitize=cfi -flto=thin'
$ export LDFLAGS='-fuse-ld=lld'
$ cmake -GNinja .. -DCMAKE_BUILD_TYPE=Release
$ ninja
$ ctest --output-on-failure # bring popcorn
```

**Platform information:**

 - OS: Ubuntu 20.04
 - Compiler+version: Clang 11
 - Catch version: HEAD

**Additional context**
No additional context.

[1]: https://clang.llvm.org/docs/ControlFlowIntegrity.html
[2]: https://clang.llvm.org/docs/ControlFlowIntegrity.html#bad-cast-checking

**Comment by horenmar** [comment]
I am gonna go with false positive/stdlib bug, amongst other reason because I can reproduce this in a trivial .cpp file:

```cpp
#include <memory>

struct IReporterFactory {
    virtual ~IReporterFactory() = default;
};

class ReporterFactory : public IReporterFactory {};

void register_reporter(std::shared_ptr<IReporterFactory> ptr) {}

int main() {
    register_reporter(std::make_shared<ReporterFactory>());
}
```

```
$ clang++ -std=c++14 -flto -fvisibility=hidden -g -fsanitize=cfi 2014.cpp && ./a.out
Illegal instruction
```

When you look at the callstack, the failure happens deep in `shared_ptr` internals.

**Comment by cjdb** [comment]
Thanks @horenmar! I'll forward this on to libstdc++ in that case.
