### ISSUE TITLE
ctest registration scripts aren't in a standard cmake search path 

### ISSUE THREAD

**Issue by jrhemstad** [catchorg/Catch2#2026]
**Describe the bug**
The CTest registration scripts located in the `contrib/` directory are not in a standard [cmake search path](https://cmake.org/cmake/help/v3.18/command/find_package.html#search-procedure). 

This means when using `add_subdirectory` you cannot simply do `include(Catch)` as the scripts are not found. For reference, this means that these scripts are not found when using [CMake Package Manager (CPM)](https://github.com/TheLartians/CPM.cmake).

**Expected behavior**

`include(Catch)` should work when using `add_subdirectory` for Catch2. 

**Reproduction steps**

Assuming use of CPM:
```
cmake_minimum_required(VERSION 3.18 FATAL_ERROR)
include(CPM)
CPMAddPackage(
  NAME Catch2
  GITHUB_REPOSITORY catchorg/Catch2
  VERSION 2.13.1
)

include(Catch) # this fails

# work around is to specify the full path
# include(${Catch2_SOURCE_DIR}/contrib/Catch.cmake)
```

**Platform information:**

 - OS: Ubuntu 16.04
 - Compiler+version: gcc5.4
 - Catch version: 2.13.1

**Additional Context**

This is similar to https://github.com/catchorg/Catch2/issues/1805, but instead of adding documentation, these scripts should be made available so that they can just be found as expected when using `add_subdirectory`.

**Comment by ghost** [comment]
The include would add a bunch of targets that belong to Catch2:
- ContinuousTest
- ExperimentalMemCheck
- NightlyConfigure/
- ...
Found solution: https://github.com/catchorg/Catch2/issues/1669
