### ISSUE TITLE
Approx bug

### ISSUE THREAD

**Issue by mipac** [catchorg/Catch2#2035]
**Describe the bug**
Test if a float is "zero" fail

**Expected behavior**
test zero at epsilon

**Reproduction steps**
Test if a float is "zero" failed

CHECK(6.1817e-08 == Approx(0.f)) //FAIL
CHECK( 6.1817e-08f == Approx(0.f).epsilon(numeric_limits<float>::epsilon() * 1000) ) //FAIL
CHECK(0.f == Approx(0.f) ) //PASS

**Platform information:**

 - OS: **debian 10**
 - Compiler+version: **GCC v8.3.0**
 - Catch version: **v2.10.2**

**Additional context**
no

**Comment by horenmar** [comment]
epsilon is relative comparion, margin is absolute.

**Comment by mipac** [comment]
thank you
yes with margin set manually to float epsilon is ok
