### ISSUE TITLE
Catch v3.0.0-preview3 link error on std::string_view

### ISSUE THREAD

**Issue by michaelvlach** [catchorg/Catch2#2046]
**Describe the bug**
Building and linking with CMake against Catch2 v3.0.0.-preview3 and using C++17 `std::string_view` results in undefined symbols for stringifying `std::string_view`.

**Expected behavior**
Test code using C++17 `std::string_view` links against Catch2.

**Reproduction steps**
1. Use `add_subdirectory(projects/Catch2)`
2. Link against it using `target_link_libraries(MyTest Catch2::Catch2WithMain)` (or just Catch2)
3. Use `std::string_view` in a test so that it needs to be stringified (e.g. in a `REQUIRE`):

```
REQUIRE(std::string_view{"Hello"} == std::string_view{"World"});
```

**Platform information:**

 - OS: **Windows NT**
 - Compiler+version: **MSVC 16.7.5**
 - Catch version: **v3.0.0-preview3**

**Additional context**
A workaround is to directly enable the C++17 target feature after adding the Catch2 subdir:

```
add_subdirectory(projects/Catch2)
target_compile_features(Catch2 PUBLIC cxx_std_17)
```

**Comment by horenmar** [comment]
Right, this happens because you compile the static library with C++14, but the header included from your project sees C++17 and makes `string_view` overloads declared (but not defined, because the definition would be in the static library).

The workaround is also the correct fix: make sure that your project is compiled with consistent C++ version.


-----

I guess I could make the headers resilient to that by having the definitions be inline, but that would introduce compilation overhead.

**Comment by michaelvlach** [comment]
I understand the overhead is undesirable and I don't think it is a good idea either.

I have explicitly set C++17 on all my targets and used the as per documentation `add_subdirectory(Catch2)` and then link against that. For some reason the Catch2 is the project that defaults to C++14 (or 11 maybe?) so when it links against C++17 stuff (therefore using the Catch2 headers with enabled C++17 features) it fails to link because the static libs are compiled with C++11/14.

The reason I don't like the "fix" is that it means I am modifying the private Catch2 target directly from outside of its CMake stuff. Using the public ALIAS `Catch2::Catch2` does not work (says CMake) which would be slightly better imho.

I think the real fix would be twofold:
1. Catch2 should default to C++17
2. There is a property that can be set prior to `add_subdirectory` that could modify this and that would internally set different standard to all the targets. Something like:

```
set(CATCH2_CXX_STD 14)
add_subdirectory(src/Catch2)
```

Would something like that make sense?

Why it default to C++14 is beyond me, probably it is CMake's default or  something. I certainly don't set it anywhere and I can't see it in Catch2's CMake either.

**Comment by horenmar** [comment]
Catch2 v3 defaults to C++14 because that is the minimal version it supports.

As for your project, C++ standard, and whether you want to allow language extensions is something that should be set globally, because CMake only propagates compile options "down" from libraries to their consumers, but not vice versa.

**Comment by michaelvlach** [comment]
Ok, thanks. I was under the impression that setting global stuff like this is not "modern" CMake but it makes sense actually if there are third party dependencies like this.

**Comment by horenmar** [comment]
C++ standard is one of the exceptions. 🤷

**Comment by dimztimz** [comment]
Hello Martin. I got hit by this same bug and I think I have found the real solution.

First let me explain why is this a bug and why the issue should be reopened. If you consume Catch2 by source code via `add_subdirectory()` then there are various workaround like the one OP mentioned. All boil down to telling CMake to build the target Catch2WithMain in C++17 mode. But If you consume preinstalled Catch2 with package manager (apt, yum, vcpkg) via `find_pacakge(Catch2)` then you can not control how the package manager invokes CMake, and in that case there is no workaround to this bug.

The proper fix is to build `Catch2WithMain` in C++17 mode **privately** on systems that already support C++17, and build in C++14 on systems that only support C++14. By privately I mean use C++17 only for building the library but not for using. Adding the following code in Cmake should fix things:

```cmake
if ("cxx_std_17" IN_LIST CMAKE_CXX_COMPILE_FEATURES)
  target_compile_features(Catch2 PRIVATE cxx_std_17)
  target_compile_features(Catch2WithMain PRIVATE cxx_std_17)
endif()
```

See more about this solution in the docs for [cmake-compile-features](https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html).

> The CMAKE_C_KNOWN_FEATURES, CMAKE_CUDA_KNOWN_FEATURES, and CMAKE_CXX_KNOWN_FEATURES global properties contain all the features known to CMake, regardless of compiler support for the feature. The CMAKE_C_COMPILE_FEATURES, CMAKE_CUDA_COMPILE_FEATURES , and **CMAKE_CXX_COMPILE_FEATURES variables contain all features CMake knows are known to the compiler**, regardless of language standard or compile flags needed to use them.
