### ISSUE TITLE
Using Clang on Wndows warns about microsoft-cast being used (v3.0.0-preview3)

### ISSUE THREAD

**Issue by michaelvlach** [catchorg/Catch2#2048]
**Describe the bug**
As per the title.

**Expected behavior**
No warning regarding casts being only available as Microsoft extension.

**Reproduction steps**
1. Compile using any Catch2 (v3.0.0-preview3) header on Windows with Clang forcing stringification of anything.

**Platform information:**
 - OS: **Windows NT**
 - Compiler+version: **Clang 10**
 - Catch version: **v3.0.0-preview3**

**Additional context**
The warning: https://clang.llvm.org/docs/DiagnosticsReference.html#wmicrosoft-cast
Coming from: `src\catch2\..\catch2/catch_tostring.hpp(45,56)` and few other places in this header. The offending code seems to be:
```
std::declval<U>()
```
Not sure what exactly is going on there. But probably if `U` is an object pointer the `operator<<` overload used from somewhere takes function pointer as argument? Hence the warning probably. I haven't digged too deep into Catch's stringification internals.

The workaround is to disable the warning as I don't see any obvious code fix for this:

```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-microsoft-cast")
```

**Comment by horenmar** [comment]
Does this happen when building your project, or just Catch's tests?

**Comment by horenmar** [comment]
I am going to close this due to no follow up.
