### ISSUE TITLE
not able to reproduce --list-test-names-only exactly in v3

### ISSUE THREAD

**Issue by bowie7070** [catchorg/Catch2#2051]
In catch2 v2 we have --list-test-names-only which prints the test names matching a filter.

According to the notes for v3

--list-test-names-only has been removed (#1190)
You should use verbosity-modifiers for --list-tests instead

However -l --verbosity quiet does not produce the same output. It also includes before the first test case:

All available test cases:

And after the last test case:

x test cases

I would like -l --verbosity quiet to only  print the test names. That is reproduce the behaviour of --list-test-names-only.

The motivation for this is similar to the comment on the issue relating to the removal of the flag. I want to be able to get a list of only test case names consumable by -f or passable as a command line argument as in xargs.

https://github.com/catchorg/Catch2/issues/1190#issuecomment-400223778

Please note that the blank line is also problematic. To be specific I have a script for running tests in parallel and it does:

$exe --list-test-names-only --order rand --rng-seed time "$@" |
    parallel --bar --halt now,fail=1 -j 20 $exe "{}" ">" "tmp$$/{}.out"

Parallel reads lines from stdin and executes the catch program ($exe) with the given lines. When it hits the blank line it tries to run all tests again.

**Comment by horenmar** [comment]
Okay, should be fixed.

**Comment by bowie7070** [comment]
I can confirm it is fixed when I build and link against the static library.
It doesn't seem to be fixed if I used the amalgamated cpp file but I can
live with that. Thanks.

**Comment by horenmar** [comment]
Yeah, the checked-in amalgamated file should behave just like single header used to, that is, it is only updated upon release. You can update it with `tools/scripts/generateAmalgamatedFiles.py`.
