### ISSUE TITLE
assertion fails but the condition is correct

### ISSUE THREAD

**Issue by stkw0** [catchorg/Catch2#2054]
When executing the test case of the this gist (https://gist.github.com/stkw0/67a2d0ad2c7fe345ceaec5fa6861fcc7) it fails:

> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> misc_test is a Catch v2.13.2 host application.
> Run with -? for options
> 
> -------------------------------------------------------------------------------
> Heartbeat test
>   a
> -------------------------------------------------------------------------------
> /tmp/heartbeat/heartbeat_test.cpp:9
> ...............................................................................
> 
> /tmp/heartbeat/heartbeat_test.cpp:11: FAILED:
>   REQUIRE( hb.counter == 1 )
> with expansion:
>   1 == 1
> 
> terminate called without an active exception
> /tmp/heartbeat/heartbeat_test.cpp:11: FAILED:
>   {Unknown expression after the reported line}
> due to a fatal error condition:
>   SIGABRT - Abort (abnormal termination) signal
> 
> ===============================================================================
> test cases: 1 | 1 failed
> assertions: 2 | 2 failed
> 
> zsh: abort      sudo ./misc_test

but as can be seen the condition is correct (1 equals 1) and should not fail.

**Expected behavior**
Tests passes.

**Platform information:**
Linux-5.9.0
gcc-10.2.0, cmake-3.18.4
catch-2.13.2 (it also fails with version 2.9.1 at least)

**Comment by horenmar** [comment]
Data race 101.

What happens is that Catch2 captures a _reference_ to `hb.counter`, and when it checks whether `hb.counter == 1` holds, the counter is still 0, because the thread to set it has not set it yet).  When the check fails, it has to read the reference again, but this time it is at 1, because the second thread has set it in the meantime.

**Comment by stkw0** [comment]
Thanks, the original code is more complex and have a mutex and so, I tried to reduce it too much it seems xd. But will check it again, probably I missed something. btw I thought that the value was copied or something to avoid having this kind of situations

**Comment by horenmar** [comment]
Copying would not support non-copyable types, and also could have significant performance penalty. 🤷

**Comment by stkw0** [comment]
well, fundamental types shouldn't have a big performance penalty. But anyway,  thanks. I will close this issue then.
