### ISSUE TITLE
Single header link is not working

### ISSUE THREAD

**Issue by ThudPoland** [catchorg/Catch2#2063]
**Describe the bug**
When trying to reach address:
https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp
I get 404 error.

**Expected behaviour**
Link: https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp is working
OR
Documentation is updated with new link.

**Reproduction steps**
Just try to open this link:
https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp

**Comment by ThudPoland** [comment]
Is version from branch v2.x stable and ready for use?
https://raw.githubusercontent.com/catchorg/Catch2/v2.x/single_include/catch2/catch.hpp

**Comment by horenmar** [comment]
Right, I knew a bunch of stuff will break when I finally delete the branch, didn't expect this one.

Yes, `v2.x` is basically renamed master.

**Comment by horenmar** [comment]
I _think_ that all links to `master` for v2 should be fixed. `devel` no longer has a single header version and I'll have to rewrite the docs more later.
