### ISSUE TITLE
Catch2 application header not always displayed

### ISSUE THREAD

**Issue by loximann** [catchorg/Catch2#2065]
**Description**
The application header (including relevant info such as Catch2 version and random seed) is only printed when some tests fail or when forcing the inclusion of successful tests in the output.

**Expected behavior**
The application header, ie
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a.out is a Catch v2.11.0 host application.
Run with -? for options
```
should always be shown, regardless of the results of the tests. Ideally, the application header would be shown immediately after starting the application. 

**Reproduction steps**
Consider the following test file `foo.cpp`:
```
#define CATCH_CONFIG_MAIN

#include <catch2/catch.hpp>

TEST_CASE("LOL")
{
    CHECK(1==1);
}

TEST_CASE("LAL")
{
    CHECK(1==1);
}
```

The application header is shown only when tests fail or when using `-s`:

```
$ g++ foo.cpp
$ ./a.out 
===============================================================================
All tests passed (2 assertions in 2 test cases)

$ ./a.out -s

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a.out is a Catch v2.11.0 host application.
Run with -? for options

-------------------------------------------------------------------------------
LOL
-------------------------------------------------------------------------------
foo.cpp:5
...............................................................................

foo.cpp:7: PASSED:
  CHECK( 1==1 )
with expansion:
  1 == 1

-------------------------------------------------------------------------------
LAL
-------------------------------------------------------------------------------
foo.cpp:10
...............................................................................

foo.cpp:12: PASSED:
  CHECK( 1==1 )
with expansion:
  1 == 1

===============================================================================
All tests passed (2 assertions in 2 test cases)

```

**Comment by horenmar** [comment]
I don't see a reason to print the header every time. However I just noticed that the console reporter does not report RNG seed in any case (`-s`, test failure, no test failure), which is bug, or at least bug adjacent.

**Comment by loximann** [comment]
Hmmm, I beg to disagree, I think that the information contained in the header (Catch2 version, help hint, random seed) is something that should be shown or not independently of the test results and how they are reported. I for one want to have that info always, while not needing the successful test results (eg I may want to re-run with a successful seed on a different system).

As far as I can tell, the --rng-seed must be explicitly given so that the seed is shown.

**Comment by horenmar** [comment]
> As far as I can tell, the --rng-seed must be explicitly given so that the seed is shown.

This is not entirely true, but close enough for most cases. For reporters that support it, the actual rule is that the seed has to be different from 0 (because 0 is the default value).

See

```
xarn@DESKTOP-TJBO4PG:~/builds/Catch2/debug-v3-all$ ./tests/SelfTest -r xml --rng-seed 0 [matchers][approvals]~[failing] | head -n 5
<?xml version="1.0" encoding="UTF-8"?>
<Catch name="SelfTest" filters="[matchers][approvals]~[failing]">
  <Group name="SelfTest">
    <TestCase name="Regex string matcher -- libstdc++-4.8 workaround" tags="[approvals][matchers]" filename="/mnt/c/ubuntu/Catch2/tests/SelfTest/UsageTests/Matchers.tests.cpp" line="155">
      <OverallResult success="true"/>
```
vs
```
xarn@DESKTOP-TJBO4PG:~/builds/Catch2/debug-v3-all$ ./tests/SelfTest -r xml --rng-seed 1 [matchers][approvals]~[failing] | head -n 5
<?xml version="1.0" encoding="UTF-8"?>
<Catch name="SelfTest" filters="[matchers][approvals]~[failing]">
  <Randomness seed="1"/>
  <Group name="SelfTest">
    <TestCase name="Regex string matcher -- libstdc++-4.8 workaround" tags="[approvals][matchers]" filename="/mnt/c/ubuntu/Catch2/tests/SelfTest/UsageTests/Matchers.tests.cpp" line="155">
```


The problem with the console reporter is that it doesn't report seed either way

```
$ ./tests/SelfTest --rng-seed 1 [matchers][approvals]~[failing]
Filters: [matchers][approvals]~[failing]
===============================================================================
All tests passed (19 assertions in 5 test cases)
```
This means that if the user is using `--rng-seed time` together with the console (and after a quick test, also the compact reporter) the run is unrepeatable.


-----------------------

As for what information should be displayed by default, I prefer the linuxish approach of not having too much output to stdout by default -- consider a tool like a compiler, would you want it to print out

```
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
use -h or --help for more options
Copyright (C) 2019 Free Software Foundation, Inc.
```

after each compiled file? 😃

**Comment by loximann** [comment]
I am not sure if I am running the same selfTests, but I get

```
$ ./projects/SelfTest --rng-seed 1

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SelfTest is a Catch v2.11.0 host application.
Run with -? for options

Randomness seeded to: 1
[...]
```

And well, I agree with your gcc example, but Catch2 binaries are a different thing. There are many examples of console programs that always show their version and other information by default (valgrind comes to mind). In any case, whatever the default behavior of Catch2 binaries is, in my opinion it should be consistent: either show the header or not, but do not make that depend on the outcome of the tests. I would need to always log things such as versions and random seeds regardless of the success or failure of the tests. If the supported way to obtain this is with -s (which in my opinion is not optimal, since those are two different functions) this should be clarified somehow.

**Comment by horenmar** [comment]
Okay I see. The console reporter only reports the seed in the header... that's definitely not how it should behave.



Also, why are you logging the version of Catch2 running the tests?

**Comment by loximann** [comment]
Well, I guess we are not since it is not always displayed :-D To rephrase, I guess what I meant is "If I needed to always log things such as versions and random seeds, I would want to do that regardless of the success or failure of the tests.".

In any case, I would not be surprised if at some point we end up logging it, since we are quite verbose in our troubleshooting output for both our product and our CI/CD system, and we log the versions of all kinds of dependencies.

**Comment by horenmar** [comment]
Right. The reason I am asking is that I am not fundamentally against showing the version as well, but I don't see the need for it yet, so I am asking if you have a reason that would convince me.

The reason I do not see a need to log the version by default is that any CI run should be obviously linked to a specific commit/revision, and a specific commit/revision should be linked to specific Catch2 version. This is unlike random seed, which is (hopefully :smiley:) different between each run of the same binary, and thus cannot be reconstructed without being reported.

-----------

Also if you are doing postprocessing on the output, I strongly recommend using a different reporter, e.g. XML, or a custom one.

**Comment by hardsetting** [comment]
@horenmar
> I just noticed that the console reporter does not report RNG seed in any case

I noticed this too while trying to set up my project for reproducibility. I was wondering if there was any plan to fix it.
Should I open a new issue about it?

EDIT:
for now I'm providing a custom main as workaround:
```cpp
#define CATCH_CONFIG_RUNNER
#include <catch2/catch.hpp>

int main(const int argc, const char* const argv[]) {
    Catch::Session session;
    session.applyCommandLine(argc, argv);
    if (session.config().rngSeed() != 0) {
        printf("RNG seed: %d\n", session.config().rngSeed());
    }
    return session.run();
}
```
