### ISSUE TITLE
Test case names are not printed if they include no assertions with the console reporter

### ISSUE THREAD

**Issue by loximann** [catchorg/Catch2#2066]
**Description**
If a test case has no assertions, its name will not be printed by the console reporter, even when running with `-s`.

**Expected behavior**
The name of all test cases should be shown.

**Reproduction steps**
Consider the following test file:
```
#define CATCH_CONFIG_MAIN

#include <catch2/catch.hpp>


TEST_CASE("quiet")
{
    sleep(5);
}
TEST_CASE("test")
{
    CHECK(1==1);
}
```

The output when running with the `-s` option:

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a.out is a Catch v2.12.4 host application.
Run with -? for options

-------------------------------------------------------------------------------
test
-------------------------------------------------------------------------------
foo.cpp:10
...............................................................................

foo.cpp:12: PASSED:
  CHECK( 1==1 )
with expansion:
  1 == 1

===============================================================================
All tests passed (1 assertion in 2 test cases)


```

See related issue
https://github.com/catchorg/Catch2/issues/2065

**Comment by horenmar** [comment]
Why should the name of all test cases be shown?

**Comment by loximann** [comment]
For one, this arose when looking at the shuffling pull request: Even though a test does not assert anything, it is relevant to know the order in which it was run.
It can also be frustrating to have no way to know which assertion-less tests where run when using filters. Suppose the result is only "test cases : 12, assertions: -none-": You would need to resort to another reporter which lists all tests to figure out what happened.

**Comment by horenmar** [comment]
I am going to close this with "use custom reporter/the proper warning flag", because I don't want to change the default output and I don't think a flag that provides this is not worth the maintenance overhead.
