### ISSUE TITLE
Will be v3 rebranded as Catch3 or Catch 3.0.0 or Catch2 3.0.0 ?

### ISSUE THREAD

**Issue by mnesarco** [catchorg/Catch2#2068]
**Description**
There are Catch, Catch2 and now Catch2 has version 3 and I can see mayor breaking changes in v3. It looks like V2 and V3 are very different in philosophy, one of the most beloved features was the sinlgle header philosophy but in v3 it is different. It makes a lot of sense to rebrand it as Catch3 or just rebrand back to Catch and just use semantic versioning.

**Comment by horenmar** [comment]
Catch2 v3.x.x

The rebranding to Catch2 happened to make the project more searchable.
