### ISSUE TITLE
What happened with `master` branch?

### ISSUE THREAD

**Issue by mika314** [catchorg/Catch2#2069]
**Describe the bug**
`master` branch is missing.

**Expected behavior**
`master` branch exists.

**Reproduction steps**
1) Open https://github.com/catchorg/Catch2/
2) try to find `master` branch.

**Platform information:**
 - OS: N/A
 - Compiler+version: N/A
 - Catch version: master

**Additional context**
N/A

**Comment by horenmar** [comment]
Ongoing development is in `devel`, "good" places are marked with tags.
