### ISSUE TITLE
Our CI should check that all files use proper include guards

### ISSUE THREAD

**Issue by horenmar** [catchorg/Catch2#2075]
As part of cleanup efforts in the `devel` branch, I standardized the include guards of all headers to obey simple pattern: `${UPPER_CASE_FILENAME}_INCLUDED`.

To avoid non-standard include guards in the future, we should make this check a part of the automatic per-commit CI. I originally used `checkguard` Python tool for this check, but other tools can also be used.

**Comment by innerout** [comment]
I will be working on this issue.
