### ISSUE TITLE
conan packages do not contain Catch2Config.cmake

### ISSUE THREAD

**Issue by PinkySan** [catchorg/Catch2#2080]
**Describe the bug**
I was unable to use the cmake integration, if catch2 was integrated by conan.
```
[requires]
catch2/2.13.2

[generators]
cmake
```
`find_package(Catch2)` does not work, because the downloaded package do not contain any the requested information

**Expected behavior**
`find_package(Catch2)` should work as expected, when requesting the package from conan.
`Catch2/2.11.1@catchorg/stable` as conan-requirement works!

**Reproduction steps**
Basic project with the provided conanfile.txt and a basic CMakeLists.txt which only contains 
`find_package(Catch2)`

**Platform information:**

 - OS: Windows 10
 - Compiler+version: MSVC
 - Catch version: **2.13.2 (or some older ones**

**Additional context**

**Comment by Minimonium** [comment]
Hi, @PinkySan!
The recipe in the Conan Center Index is maintained externally, not by Catch2 maintainers. CCI has rules about removing native configs and use generated ones instead. To generate a target you can either `cmake_find_package` (for FindXXX file generation) or `cmake_find_package_multi` (for ConfigXXX file generation).

**Comment by PinkySan** [comment]
Pretty bad at all. 
I really liked the simplicity of conan and catch
