### ISSUE TITLE
Catch2 installation not working & no installation guide in this repo...

### ISSUE THREAD

**Issue by PascalMarechal** [catchorg/Catch2#2081]
When I run these two lines it installs catch2.

```bash 
git clone https://github.com/catchorg/Catch2.git
cd Catch2 && mkdir build && cd build && cmake .. -DBUILD_TESTING=OFF && make install
```

But there is not catch.hpp in the catch2 folder.

Am i missing something ?

Thanks

**Comment by PascalMarechal** [comment]
Nevermind I found single_include folder in v2.x branch :)

**Comment by horenmar** [comment]
Sorry, I rewrote the readme to point to old branch, but forgot to commit the changes.

The readme should make that explicit now 😃  I will also throw up some documentation on migrating soon™️
