### ISSUE TITLE
TEMPLATE_TEST_CASE breaks clang-tidy check modernize-avoid-c-arrays

### ISSUE THREAD

**Issue by cjdb** [catchorg/Catch2#2095]
**Describe the bug**
`TEMPLATE_TEST_CASE` uses a C array in its definition, which breaks the clang-tidy check `modernize-avoid-c-arrays`.

**Expected behavior**
clang-tidy shouldn't report anything.

**Reproduction steps**

```cpp
TEMPLATE_TEST_CASE("", "", int) {} // this should be enough
```

**Platform information:**

 - OS: WSL2 Ubuntu 20.04
 - Compiler+version: GCC 10.2, clang-tidy 12
 - Catch version: Head

**Comment by horenmar** [comment]
ugh, that's just clang-tidy being stupid and not understanding the "initialize discarded array to do something over an arg pack" idiom.

I'll suppress it when I get around to it, alternatively PRs are welcome. 😉

**Comment by cjdb** [comment]
Do you want it to be changed to `std::array` or `// NOLINT(modernize-avoid-c-arrays)`?

**Comment by horenmar** [comment]
`NOLINT`, there is no reason to drag in an extra header

**Comment by rutayan** [comment]
I have taken a stab at it.
This is my first time contributing here. I am not sure how to add reviewers.
