### ISSUE TITLE
Catch2 Repeated Generators causes segfault

### ISSUE THREAD

**Issue by NickolasLapp** [catchorg/Catch2#2097]
Not sure if this is an expected error or not, but wanted to get some feedback on it anyway.

I ran into a case where using the same name to capture `GENERATE` output  results in a segfault. See the minimum repeatable example below:

```
TEST_CASE("Test 1")
{
  SECTION("Section 1")
  {
    const auto foo = GENERATE(1, 2, 3, 4);
    REQUIRE(foo > 0);
  }

  const auto foo = GENERATE(1, 2, 3);
  SECTION("Section 2")
  {
    REQUIRE(foo > 0);
  }
}
```

When trying to compile and run this test, I get a segfault without any notable information. Is this a bug? User Error?
I am pretty sure it's due to the repeated use of the name `foo`, probably due to how the SECTIONS are generated from the GENERATE statement, but I'm not familiar enough with the library to know. Can someone help?

**Comment by horenmar** [comment]
What version of Catch2 are you using?
