### ISSUE TITLE
[Cc]atch on conancenter / bintray

### ISSUE THREAD

**Issue by blackliner** [catchorg/Catch2#2100]
Why are there 2 different conancenter / bintray repos for Catch2? And its also mixed for the two repos...

1. Version 1 offers versions up to 2.11.1 and also 3.0 and`FindPackage(Catch2)` compatible conan recipe:
UPPERCASE **C** https://conan.io/center/Catch2
lowercase **c** https://bintray.com/catchorg/Catch2/catch2%3Acatchorg
2. Version 2 offers versions 2.11.2 - 2.13.3, but has the "generic" version of conan recipe that breaks native CMake usage :-(
lowercase **c** https://conan.io/center/catch2
UPPERCASE **C** https://bintray.com/catchorg/Catch2/Catch2%3Acatchorg

My problem is that I need Catch2 2.13.3 with the native CMake compatibility. Is there a way to tell conan install to use this github repo? Because I think the maintained `conanfile.py` from you guys would work perfectly.

Also see:
https://github.com/catchorg/Catch2/issues/2080
https://github.com/conan-io/conan/issues/8050

**Comment by blackliner** [comment]
If I understand https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_paths_generator.html correctly, `cmake_paths` generator is supposed to work with `find_package` only, no conan stuff required in my CMakeLists.txt

**Comment by horenmar** [comment]
Public bintray stopped being a thing, so this has solved itself I guess.
