### ISSUE TITLE
Add "surrogate TUs" for all library headers

### ISSUE THREAD

**Issue by horenmar** [catchorg/Catch2#2106]
Surrogate TUs are TUs that only include one single header, and do nothing else. These TU must still include: if they do not, then a header doesn't stand on its own, and there is likely some include or declaration missing from it.

There are three parts to this
- [x] Add surrogate TUs for all current headers
- [x] Ensure that they are built during testing (probably under "Extra Tests" CMake toggle, to save compilation times for common builds)
- [x] Add CI script that checks whether all headers have their surrogate TU

**Comment by innerout** [comment]
I will be working on this issue. It seems like a good starting point to learn the codebase.
