### ISSUE TITLE
The reporter interface needs new events for test case as a whole

### ISSUE THREAD

**Issue by horenmar** [catchorg/Catch2#2107]
The current `testCaseStarting`  and `testCaseEnding` events can (and usually do) fire multiple times for a single `TEST_CASE`. This is because they fire _every_ time `TEST_CASE` is entered/left, which happens multiple times when there are `SECTION`s inside it. We want to provide reporter member function that is called when a `TEST_CASE` is about to be entered the first time, and when it has exited the last time.

Possible names `testCaseBeginning` and `testCaseFinishing`? Definitely open to better suggestions.

**Comment by sudara** [comment]
Maybe going with the explicit `testCaseFirstEntered` and `testCaseLastExited` would prevent confusion with the existing Starting/Ending events.
