### ISSUE TITLE
Add AllMatch, AnyMatch, NoneMatch generic range matchers

### ISSUE THREAD

**Issue by horenmar** [catchorg/Catch2#2109]
They should take single matcher during construction, and their `match` method should take a generic range, using the new generic matcher support.

Expected usage:
```cpp
REQUIRE_THAT(get_keys(), AllMatch(KeyPattern({1, 2, 3})));
REQUIRE_THAT(get_numbers(), NoneMatch(IsOdd{}));
REQUIRE_THAT(get_strings(), AnyMatch(Contains("webscale") && !Contains("MongoDB")));
```

the matching semantics are hopefully obvious from the names 😃

**Comment by horenmar** [comment]
There might also be interest in simple `All`, `Any`, `None` (or maybe `AllTrue`, etc.) range matchers that are explicitly specialized for ranges of `bool`s, or types convertible to `bool`. While they can be simply emulated by composing `AllMatch` with `IsTrue` generic matcher, having them out of box would likely be convenient for bunch of users.

**Comment by urielgarciarivas** [comment]
@horenmar Hello! I would love to contribute here. Where should I implement those methods? And could you tell me more about the new generic matcher support?

**Comment by horenmar** [comment]
The [new matchers docs are here](https://github.com/catchorg/Catch2/blob/devel/docs/matchers.md#writing-custom-matchers-new-style). There is a very similar functionality in `ContainsElementMatcher`, in `src/catch2/matchers/catch_matchers_contains.hpp`, which takes a Matcher at construction, a generic range* at match time, and returns true if at least one element in the range matches.

This is essentially the `AnyMatch` implementation done already :smiley: The other two should be analoguous.


* Looking at it, I will need to check whether it accepts C++20 ranges, which can have different type returned from `begin` and from `end`. I think it currently doesn't.

**Comment by urielgarciarivas** [comment]
Thank you! I will be working on this. :sunflower:
