### ISSUE TITLE
Cmake finds Catch2 package but 'catch.hpp' file not found in tests cpp file

### ISSUE THREAD

**Issue by itaiSternberg** [catchorg/Catch2#2113]
CMake works as expected, when I want to build my target using a Makefile the catch header isn't found.
<h3>CMakeLists.txt:</h3>

```
find_package(Catch2 REQUIRED)

IF (${Catch2_FOUND})
  MESSAGE(STATUS "Catch2 found")
ELSE (${Catch2_FOUND})
  MESSAGE(STATUS "Catch2 not found")
endif(${Catch2_FOUND})


add_executable(Tests Tests/main.cpp)


target_link_libraries(Tests Catch2::Catch2)

include(CTest)
include(Catch)
catch_discover_tests(Tests)
enable_testing()
```

**Comment by blackliner** [comment]
I think you need `#include <catch2/catch.hpp>` ?

**Comment by blackliner** [comment]
Also
- your `ELSE` path will be never reached, because your `find_package` will abort with an error
- `target_link_libraries(Tests Catch2::Catch2)` --> get used to `target_link_libraries(Tests PRIVATE Catch2::Catch2)`

**Comment by horenmar** [comment]
This was solved on Discord in the meantime. The problem was with using v3, but using the v2 header paths.
