### ISSUE TITLE
Same bug as in the following issue https://github.com/catchorg/Catch2/issues/1921

### ISSUE THREAD

**Issue by VladAdGad** [catchorg/Catch2#2126]
Same problem as in https://github.com/catchorg/Catch2/issues/1921 with Catch2/3.0.0 from conan

**Comment by horenmar** [comment]
Should also [be long fixed](https://github.com/catchorg/Catch2/blob/17a04f88d90d3687bd561e89dab40e4ba6a55b83/src/catch2/internal/catch_compiler_capabilities.hpp#L82).
