### ISSUE TITLE
ERROR: Unable to find 'Catch2/2.13.3@catchorg/stable' in remotes

### ISSUE THREAD

**Issue by VladAdGad** [catchorg/Catch2#2127]
**Describe the bug**
```
conan inspect Catch2/2.13.3@catchorg/stable
Catch2/2.13.3@catchorg/stable: Not found in local cache, looking in remotes...
Catch2/2.13.3@catchorg/stable: Trying with 'conan-center'...
ERROR: Unable to find 'Catch2/2.13.3@catchorg/stable' in remotes
```
```
asig@DESKTOP-Q2UPL37:/mnt/c/Users/asig/Repositories/leetcode-solutions$ conan search Catch2 -r=all
Existing package recipes:

Remote 'conan-center':
Catch2/2.5.0@catchorg/stable
Catch2/2.5.0@catchorg/testing
Catch2/2.6.0@catchorg/stable
Catch2/2.6.1@catchorg/stable
Catch2/2.7.0@catchorg/stable
Catch2/2.7.1@catchorg/stable
Catch2/2.7.2@catchorg/stable
Catch2/2.8.0@catchorg/stable
Catch2/2.9.0@catchorg/stable
Catch2/2.9.1@catchorg/stable
Catch2/2.9.2@catchorg/stable
Catch2/2.10.0@catchorg/stable
Catch2/2.10.1@catchorg/stable
Catch2/2.10.2@catchorg/stable
Catch2/2.11.0@catchorg/stable
Catch2/2.11.1@catchorg/stable
```
I don't see in this **list Catch2/2.13.3@catchorg/stable** but package in my opinion exists https://bintray.com/catchorg/Catch2/Catch2%3Acatchorg/2.13.3%3Astable. And what strange is that exactly this package is "separate" from the others.
![image](https://user-images.githubusercontent.com/15636176/102665301-f1042000-4184-11eb-84ac-ce4784886468.png)

**Expected behavior**
Should work as for others packages

**Reproduction steps**
conan inspect Catch2/2.13.3@catchorg/stable

**Platform information:**

 - OS: **Windows 10**
 - Compiler+version: **MinGW 8.1.0**
 - Catch version: **v2.13.3**

**Comment by Minimonium** [comment]
Hi, Vladyslav!

The `catchorg/stable` format packages are so-called Conan-Community packages. They're on the plan to get discontinued with that advance of the Conan-Center-Index. What happened before - the `conan-center` was linking packages from other remotes, such as the `catchorg` one which you observe. While I don't have exact information on hand - it seems that they no longer link to new Community packages.

What are you options:
* If you depend on the Catch2 being the name of the package that you depend on - you can add the `catchorg` in the list of your remotes (The Set Me Up! blue button contains instructions on how to do it). It'll allow you to pick up further packages produced by previous means.
* Move to the CCI's `catch2` package. BTW, it's suggested to use the official search platform to look for packages - https://conan.io/center/catch2

**Comment by VladAdGad** [comment]
Thanks a lot! When I looked for catch in conan I found only deprecated version. When you mention conan-central I checked again and yes - now I see the latest version. Thank you.
