### ISSUE TITLE
fix unused variable warning

### ISSUE THREAD

**Issue by mizvekov** [catchorg/Catch2#2132]
compiling 3.0.0p2 with clang, I get the following warning:
```
catch2/internal/catch_run_context.cpp:465:31: warning: unused variable '_' [-Wunused-variable]
        FatalConditionHandler _;
                              ^
```

Needs something like [[maybe_unused]] or similar, possibly in a way that handles old standards / compilers.

**Comment by horenmar** [comment]
What compiler+platform are you using?

**Comment by mizvekov** [comment]
clang 11.0, on two profiles, targeting x86_64 mingw32 and also msvc.
