### ISSUE TITLE
v3 - Migration doc requires a section at the beginning of the document "Changes overview"

### ISSUE THREAD

**Issue by robert-andrzejuk** [catchorg/Catch2#2135]
Looking at the migration information in:
https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md#top

It just jumps right into the details of what to do.

As I understand it, it's a step away from single-header.

Would be great to describe this philosophy change at the beginning of this document.

**Expected behavior**
Add a new section at the beginning of the document "Changes overview".

**Comment by horenmar** [comment]
Sure. Care to try writing it up?

**Comment by robert-andrzejuk** [comment]
I'm not following v3.

Anything else, which should be put in this section?
