### ISSUE TITLE
How can I make my own custom reporter?

### ISSUE THREAD

**Issue by mirkocuidado** [catchorg/Catch2#2148]
**Describe the bug**

**Expected behavior**

**Reproduction steps**
Steps to reproduce the bug.

**Platform information:**

 - OS: **Windows NT**
 - Compiler+version: **GCC v2.9.5**
 - Catch version: **v1.2.3**

**Additional context**

**Comment by mirkocuidado** [comment]
I want to run 10'000 tests and to print the failed ones and their errors ONLY after all the tests are checked. Does anybody have an idea on how to do that?

**Comment by horenmar** [comment]
[Writing your own reporter](https://github.com/catchorg/Catch2/blob/devel/docs/reporters.md#writing-your-own-reporter)
