### ISSUE TITLE
true is not true (uninitialized bool)

### ISSUE THREAD

**Issue by matbb** [catchorg/Catch2#2156]
An uninitialized `bool` produces a funny test report.

Test case:
```c++
#include <iostream>

#define CATCH_CONFIG_MAIN
#include "catch.hpp"

TEST_CASE("true is true, sometimes", "[bool]") {
    bool is_true = true;
    REQUIRE(is_true != false);  // pass
    REQUIRE(is_true == true);   // pass
    char& c = (char&)is_true;
    c = 10;
    REQUIRE(is_true != false);  // pass
    REQUIRE(is_true == true);   // fail
}
```
fails with:
```bash
$ g++ -o main.out main.cpp && ./main.out
   
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.out is a Catch v2.13.4 host application.
Run with -? for options

-------------------------------------------------------------------------------
true is true, sometimes
-------------------------------------------------------------------------------
main.cpp:6
...............................................................................

main.cpp:13: FAILED:
  REQUIRE( is_true == true )
with expansion:
  true == true

===============================================================================
test cases: 1 | 1 failed
assertions: 4 | 3 passed | 1 failed
```

I would like to see a boolean that is neither true nor false printed as something else, perhaps with a hex representation next to the usual true/false string.
Originally found when comparing against an uninitialized bool value returned from a function.

**Comment by jayeshbadwaik** [comment]
![image](https://user-images.githubusercontent.com/779964/105275032-6b7cf100-5bc4-11eb-869e-9ecd63b839b1.png)

The [C++ standard](https://en.cppreference.com/w/cpp/language/types) says that the bool can only have either a true or a false value. So, there is no bool that is neither true nor false.

**Comment by matbb** [comment]
The documentation explains that ordinary C++ operators are used for testing,
therefore comparing an uninitialized bool to true (as in a "true bool")
fails as it should. 
This is not a problem.

What is a bit unusual for me is the stringification of the results.

I would expect that a variable of type `bool` that is not actually
a true bool would be stringified in such way that a user would
be able to see the error.

Since the test framework uses ordinary C++ operators for stringification,
I would suggest adding
```
s << std::noboolalpha;
```
before the stringification.

**Comment by horenmar** [comment]
No. Use sanitizers to protect you from undefined behaviour, not your testing framework.
