### ISSUE TITLE
Variables named `last` can shadow C++20 std::chrono::last

### ISSUE THREAD

**Issue by StephanTLavavej** [catchorg/Catch2#2169]
**Describe the bug**
I work on MSVC's STL, and we regularly test open-source projects with in-development builds of the compiler and Standard Library, allowing us to find and fix toolset regressions before shipping to users, and allowing us to provide advance notice of source-breaking changes.

We recently merged a partial implementation of C++20 `<chrono>` and encountered a compiler warning in Catch2. The issue is that C++20 defines `std::chrono::last` (see [N4878](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/n4878.pdf) [time.syn] or online at https://eel.is/c++draft/time.syn defining `inline constexpr last_spec last{};`). If user code:

* Is compiling in C++20 mode (`/std:c++latest`)
* Includes `<chrono>`
* Says `using namespace std::chrono;`
* Then includes Catch2

Then uses of `last` in Catch2 source code can emit the shadow warning [C4459](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4459?view=msvc-160).

We originally found this via ReactiveX/RxCpp using an old version of Catch2, https://github.com/ReactiveX/RxCpp/tree/master/ext , which said:

https://github.com/catchorg/Catch2/blob/9e1bdca4667295fcb16265eae00efa8423f07007/single_include/catch2/catch.hpp#L3091

and the warning emitted was:

```
F:\gitP\Reactive-Extensions\RxCpp\ext\catch\single_include\catch2\catch.hpp(3091): error C2220: the following warning is treated as an error
F:\gitP\Reactive-Extensions\RxCpp\ext\catch\single_include\catch2\catch.hpp(3091): warning C4459: declaration of 'last' hides global declaration
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\chrono(765): note: see declaration of 'std::chrono::last'
F:\gitP\Reactive-Extensions\RxCpp\ext\catch\single_include\catch2\catch.hpp(3091): note: while compiling class template member function 'Catch::Generators::RangeGenerator<T>::RangeGenerator(const T &,const T &)'
        with
        [
            T=int
        ]
```

I observe that this is no longer present in Catch2's current codebase, but in the current `devel` commit I found at least one parameter still named `last` and there are probably more elsewhere:

https://github.com/catchorg/Catch2/blob/2dbe63a6ba949c3f0a2078770f7d12cfe5adc10c/src/catch2/generators/catch_generators_range.hpp#L76

The simplest way to avoid this shadow warning is to rename any variables named `last`, to an identifier that isn't used by the Standard Library. (Alternatively, the specific warning number can be push-disable-popped.)

MSVC's STL can't do anything to avoid this warning, as we are required to define `std::chrono::last` now, and cannot prevent user-programmers from `using namespace std::chrono;`.

**Expected behavior**
Programmer-users should be able to include `<chrono>` and Catch2 in the scenario described above, without encountering shadow warnings from code they don't control.

**Reproduction steps**
Because this requires the very latest changes to MSVC's STL which haven't shipped yet, it's difficult to provide a self-contained test case. I could prepare one if it is absolutely necessary.

**Platform information:**
 - OS: Windows 10
 - Compiler+version: VS 2019 16.10 Preview 1 (in development)
 - Catch version: It appears that RxCpp was using 2.4.1 but I believe that this should also repro with `devel` as explained above.

**Additional context**
None.

**Comment by jayeshbadwaik** [comment]
I'm curious why a bug report against `RxCpp` is not the preferred way to go.

**Comment by StephanTLavavej** [comment]
The specific constructor that RxCpp was invoking has been fixed in the latest version of Catch2 as far as I can tell, but (as cited above) there appear to be more occurrences of this issue in Catch2's current sources that can be encountered by other projects. If there were no occurrences in Catch2's current sources, then I wouldn't have filed this issue, and instead would have asked RxCpp to update their version.

**Comment by jayeshbadwaik** [comment]
No, my question seems to be a little misinterpreted. Why are you not instead opening a bug report against `RxCpp` for having `using namespace std::chrono`? You mention that you cannot prevent the user-programmers from doing `using namespace std::chrono`, but not the rationale for it. Since the bug is obviously in `RxCpp` for having `using namespace std::chrono`.

**Comment by horenmar** [comment]
So, I don't need a minimal repro, I think I understand what happens.

However, I disagree with your core premise of

> Programmer-users should be able to include <chrono> and Catch2 in the scenario described above, without encountering shadow warnings from code they don't control.

Specifically when the user in question also has `using namespace std::chrono;` in their TU. The reason I disagree with this, and especially with the suggested solution of 

> The simplest way to avoid this shadow warning is to rename any variables named last, to an identifier that isn't used by the Standard Library.

is quite simple. The set of names the standard library might use at some point in the future is infinite. To avoid future collisions, I would have to either go back to C "namespaces" (no), or start naming variables with randomly generated GUIDs (hell no). C++ namespaces exist for a reason, and if users opt into merging them, then they have to deal with what that entails.

**Comment by Bronek** [comment]
Any user who does, in this specific order:

```
using namespace foo;
#include <bar>
```

... deserve all the warnings the compiler can throw at them. So I think the shadowing warning is actually reasonable, nothing to do with the content of `<bar>` header and everything to do with the *preceding* `using namespace`.

Just my $0.02

**Comment by Minimonium** [comment]
@Bronek While the shadowing warning is bogus with respect to using namespace, I think it's important to correct the issue to make it more relatable. 
The issue in the mentioned project occurs _not_ because it does `using namespace` in a header or before including other files. 
The issue occurs because of macro expansion in test files, where `using namespace` is used for convenience.

**Comment by StephanTLavavej** [comment]
I have no objections to resolving this as by design. (The library that I work on is required to be maximally resistant to using-directives, macros, argument-dependent lookup, etc. and I forgot that this is quite unusual among libraries :joy_cat:.)

**Comment by horenmar** [comment]
I am indeed going to close this with resolution of "don't bring other namespaces into the global one before including other headers".
