### ISSUE TITLE
Catch2 sometimes prints out XML to the console when debugging in CLion

### ISSUE THREAD

**Issue by BullyWiiPlaza** [catchorg/Catch2#2171]
**Describe the bug**
When I'm debugging a test case in e.g. `CLion` `IDE`, I sometimes get catch specific `XML` output to the console instead of only the output produced by my application. I'm not sure if this happens in other debuggers or `IDE`s.

**Expected behavior**
`Catch2` never prints out any `XML` results when debugging.

**Reproduction steps**
* Define a test case using `CMake` and `CLion`
* Set a breakpoint at the top of the test case and start debugging
* Make a few steps in and out of methods, resume the program
* Observe the console output

**Platform information:**
 - OS: **WSL Ubuntu 20.04.1 LTS**
 - Compiler+version: **gcc (Ubuntu 10.2.0-5ubuntu1~20.04) 10.2.0**
 - Catch version: **v2.13.1**

**Additional context**
This is an example `XML` output you may get on the console:
```
Testing started at 6:26 PM ...
D:\Cpp\MyProject\cmake-build-debug\tests\Tests -r xml -d yes --order lex "Test Catch2 bug"
2021-02-04 18:35:49.322 (   6.688s) [        F7A07B80]    RegressionTests.cpp:325   INFO| My test log...
      <OverallResult success="true" durationInSeconds="104.462"/>
    </TestCase>
    <OverallResults successes="5" failures="0" expectedFailures="0"/>
    <OverallResultsCases successes="1" failures="0" expectedFailures="0"/>
  </Group>
  <OverallResults successes="5" failures="0" expectedFailures="0"/>
  <OverallResultsCases successes="1" failures="0" expectedFailures="0"/>
</Catch>
Process finished with exit code 0
```
Expected output:
```
D:\Cpp\MyProject\cmake-build-debug\tests\Tests -r xml -d yes --order lex "Test Catch2 bug"
2021-02-04 18:35:49.322 (   6.688s) [        F7A07B80]    RegressionTests.cpp:325   INFO| My test log...
Process finished with exit code 0
```
Any ideas how this could happen? It seems like undefined behavior of some sort since the `XML` output is quite random and doesn't always appear in the same way.

**Comment by horenmar** [comment]
CLion asks Catch2 for the XML output behind user's back -- that's how they integrate with it.

No idea why it sometimes ends up in console though... Are we talking about the console emulator in CLion? If so, JetBrains might be the ones to ask.

**Comment by BullyWiiPlaza** [comment]
@horenmar Thank you, it seems like you're right. I've spotted 2 open bug reports for `CLion` somewhat covering this problem:
https://youtrack.jetbrains.com/issue/CPP-20954
https://youtrack.jetbrains.com/issue/CPP-14261

It looks like those hardly get any attention from either the `CLion` users or `JetBrains` themselves which is unfortunate. I still hope that this issue eventually gets resolved by them.
