### ISSUE TITLE
Add option to skip tests with certain tag

### ISSUE THREAD

**Issue by JHagemeister** [catchorg/Catch2#2180]
**Description**
I have a test that I would like to run in a certain environment/mode, only.  I would like to tag the test with e.g. "[workstation]" and then be able to run the test suite in a non-workstation environment with something like ~[workstation].

**Additional context**

**Comment by horenmar** [comment]
I honestly can't tell if this is a real request or not, because this is literally the current behaviour.

Adding `~` before other test selector negates it, so e.g. `[windows]~[workstation]` will run tests that are tagged as `[windows]` but not as `[workstation]`.

**Comment by JHagemeister** [comment]
Thank you, it works indeed - sorry for missing this! Maybe, you like to update the documentation to include this information?
