### ISSUE TITLE
When debugging a test case, the console output is not displayed anywhere until the case ends

### ISSUE THREAD

**Issue by juandent** [catchorg/Catch2#2184]
**Describe the bug**
When debugging a test case, the console output is not displayed anywhere!!! It appears AFTER the test case ends which is of no use to me!

**Expected behavior**
when there is a code  `cout << "Hello" << endl` I would expect to see Hello printed in the console  or some window inside the IDE being used (Visual Studio 2019), but that does not happen.

**Reproduction steps**
Debug this test case: you will not see the output until the test case ends! That is the bug I am reporting!
```C++
TEST_CASE("No output seen")
{
	std::cout << "Hello" << std::endl;
}
```

**Platform information:**

 - OS: **Windows 10 Pro**
 - Compiler+version: **Visual Studio 2019 v 16.9.0**
 - Catch version: **v2.12.1**

**Additional context**
Is there a way to display console output AS IT OCCURS rather than all at once when the test case completes?

**Comment by juandent** [comment]
Looking at the code for RunContext::runTest, I see that cout output is stored in  a  string called redirectedCout... Is this customizable?

**Comment by horenmar** [comment]
This only happens if your IDE integration uses reporter that asks for the machine parseable output, e.g. the XML reporter. You can test this by running the binary outside of the IDE and inserting long sleep right after the print.
