### ISSUE TITLE
Why it takes too much time to link the tests.exe in my cmake project ? Thanks!

### ISSUE THREAD

**Issue by sinojelly** [catchorg/Catch2#2185]
**Describe the bug**
 It takes too much time to link the tests.exe in my cmake project.

**Expected behavior**
I expect it to be very fast to compile and link.

**Reproduction steps**
cmake -BBuild . -G `"MinGW Makefiles`"
cd Build
make

**Platform information:**
 - OS: **Windows 10**
 - Compiler+version: **GNU 8.1.0**
 - Catch version: **v2.13.1**

**Additional context**
I have heared that if I use the single header, it should take much time to compile.
So I tried to use cmake project.
But I can't compile it successfully,  I see the same issue as : https://github.com/catchorg/Catch2/issues/1097
So I changed to include single_include/catch.hpp,

This sample project is at: https://gitee.com/sinojelly/catch2-with-mockcpp/

![catch2-sample-link-too-slow-45s](https://user-images.githubusercontent.com/520711/110654234-ed6abd00-81f8-11eb-8154-7d773b5bc08b.PNG)

**Comment by sisco0** [comment]
Hello, is it the same if you use `MSBuild` (`cl`-based) Windows native solution for the compilation?

**Comment by horenmar** [comment]
This is a common problem with the MinGW linker. It is... not fast, and has problems with algorithmic complexity of some actions, so it ends up needing a lot of time to link Catch2.

If you do not necessarily need MinGW, I recommend setting up with either LLVM or MSVC. If you do need MinGW, you might want to try compiling the implementation files into a static library, and linking that. The current CMake setup provides target for it, `Catch2WithMain`, but it is explicitly provided with no guarantees.

**Comment by tollana** [comment]
I have the same problem with CL compiler. My project is a little bit complicated but the issue is just on release. On debug, everything builds pretty fast.

**Comment by horenmar** [comment]
@tollana Do you have LTO enabled? (It is enabled by default for Release configuration in pure VS projects)

**Comment by yhyu13** [comment]
Ubuntu 20.03 LLVM clang16 links slow as well. Can't cope with slow linking time for every test cases.

Opt to copy some key ideas from Catch2 into my custom test framework built for game engine project : https://github.com/yhyu13/HLVM-Engine/tree/main/Engine/Source/Common/Test
