### ISSUE TITLE
Catch single Header is not working

### ISSUE THREAD

**Issue by Umong51** [catchorg/Catch2#2217]
I was following the tutorial but my g++ compiler could not compile the code. I downloaded the latest version of the single header. The file looked like this.

`#define CATCH_CONFIG_MAIN
#include "catch.hpp"

unsigned int factorial ( unsigned int number ) {
        return number <= 1 ? number : factorial(number - 1) * number;
}

TEST_CASE ("Factorials are computed", "[factorial]") {
        REQUIRE (factorial(1) == 1);
        REQUIRE (factorial(2) == 2);
        REQUIRE (factorial(3) == 6);
        REQUIRE (factorial(10) == 3628800);
}`

After compiling, it was showing the following error.

`In file included from test.cpp:2:
C:\MinGW\include/catch.hpp:10754:5: error: no declaration matches 'int Catch::FatalConditionHandler::engage_platform()'
10754 |     FatalConditionHandler::engage_platform() {}
      |     ^~~~~~~~~~~~~~~~~~~~~
In file included from test.cpp:2:
C:\MinGW\include/catch.hpp:8006:14: note: candidate is: 'void Catch::FatalConditionHandler::engage_platform()'
 8006 |         void engage_platform();
      |              ^~~~~~~~~~~~~~~
C:\MinGW\include/catch.hpp:8000:11: note: 'class Catch::FatalConditionHandler' defined here
 8000 |     class FatalConditionHandler {
      |           ^~~~~~~~~~~~~~~~~~~~~
In file included from test.cpp:2:
C:\MinGW\include/catch.hpp:10755:5: error: no declaration matches 'int Catch::FatalConditionHandler::disengage_platform()'
10755 |     FatalConditionHandler::disengage_platform() {}
      |     ^~~~~~~~~~~~~~~~~~~~~
In file included from test.cpp:2:
C:\MinGW\include/catch.hpp:8007:14: note: candidate is: 'void Catch::FatalConditionHandler::disengage_platform()'
 8007 |         void disengage_platform();
      |              ^~~~~~~~~~~~~~~~~~
C:\MinGW\include/catch.hpp:8000:11: note: 'class Catch::FatalConditionHandler' defined here
 8000 |     class FatalConditionHandler {
      |           ^~~~~~~~~~~~~~~~~~~~~`

 - OS: Windows 10
 - Compiler+version: gcc version 9.2.0 (GCC)
 - Catch version: v2.13.5

**Comment by Umong51** [comment]
Well, I just solved it just by adding the return types.

**Comment by horenmar** [comment]
Duplicate, fixed in today's release.
