### ISSUE TITLE
fatal error: 'catch2/catch.hpp' file not found on macOS Big Sur after install with brew

### ISSUE THREAD

**Issue by waitaria** [catchorg/Catch2#2218]
**Describe the bug**

**Expected behavior**

**Reproduction steps**
Steps to reproduce the bug.

**Platform information:**

 - OS: **Windows NT**
 - Compiler+version: **GCC v2.9.5**
 - Catch version: **v1.2.3**

**Additional context**

**Comment by waitaria** [comment]
I installed Catch2 on my macOS Big Sur, M1 chip, using the command 

``brew install catch2''

Then, when I try to compile using Clang version 12.0.0, I get the error:

``fatal error: 'catch2/catch.hpp' file not found''

Any help would be much appreciated.

**Comment by jangleboom** [comment]
have the same issue

**Comment by horenmar** [comment]
There is about 99.99% chance that the issue is homebrew already installing v3, which uses different headers.

The remaining 0.01% is a bug in the brew package, which I do not maintain.
