### ISSUE TITLE
Junit report is incompatible with Jenkins xUnit plugin

### ISSUE THREAD

**Issue by jmairboeck** [catchorg/Catch2#2221]
**Describe the bug**
The [Jenkins xUnit plugin](https://plugins.jenkins.io/xunit/) can't parse a junit report produced by Catch2. The time (duration) values have the wrong format. The error message is:

```
WARNING: The file '<path>\TestResults-Scintilla.xml' is an invalid file.
WARNING: At line 3 of file:/<path>/TestResults-Scintilla.xml:cvc-pattern-valid: Wert '0.022408' ist nicht Facet-gültig in Bezug auf Muster '(([0-9]{0,3},)*[0-9]{3}|[0-9]{0,3})*(\.[0-9]{0,3})?' für Typ 'SUREFIRE_TIME'.
WARNING: At line 3 of file:/<path>/TestResults-Scintilla.xml:cvc-attribute.3: Wert '0.022408' des Attributs 'time' bei Element 'testsuite' hat keinen gültigen Typ 'SUREFIRE_TIME'.
ERROR: Step ‘Publish xUnit test result report’ failed: The result file '<path>\TestResults-Scintilla.xml' for the metric 'JUnit' is not valid. The result file has been skipped.
```
It seems that it expects time values only with 3 decimal digits, but the generated file contains 6.

**Expected behavior**
Generate a report which is parsed correctly by the xUnit / JUnit plugin.

**Reproduction steps**
In a jenkins build, build and invoke a Catch2 test executable with options `-r junit -o someReportFile.xml`. Configure the job with the xUnit Test publisher and JUnit report source referencing `someReportFile.xml`.

**Platform information:**
 - OS: Windows 10
 - Compiler+version: MSVC 16.28 (Visual Studio 2019)
 - Catch version: 2.0.1 (from https://sourceforge.net/p/scintilla/code/ci/0d68633e33ce996a83a7ff640da74e1c6fd1459b/tree/test/unit/catch.hpp)

**Comment by jmairboeck** [comment]
We use the xUnit plugin instead of JUnit directly because we also have other non-JUnit tests (NUnit) which we want to have reported.

**Comment by mknejp** [comment]
How is this not filed as a bug against said Jenkins plugin instead? It's a valid number. This is ridiculous.

**Comment by jmairboeck** [comment]
I have reported the bug to Jenkins: https://issues.jenkins.io/browse/JENKINS-65438

**Comment by nfalco79** [comment]
by documentation the only supported JUnit schemas are: Ant junit and Maven Surefire
Since JUnit does not define a specific schema we supports the most famous. We can not handle any custom schema cases

**Comment by horenmar** [comment]
Well, I changed the JUnit reporter.

However, I want to go on the record as saying that this is all extremely stupid, JUnit is bad and Maven surefire can go rot in hell.
