### ISSUE TITLE
Why is the folder /extras removed from all releases?

### ISSUE THREAD

**Issue by Fytch** [catchorg/Catch2#2222]
As above. I want to have access to `catch_discover_tests` but it seems like this feature (alongside with everything else in [/extras](https://github.com/catchorg/Catch2/tree/devel/extras)) is removed in every release (e.g. [here](https://github.com/catchorg/Catch2/tree/v2.13.6)). Why?

**Comment by ferdnyc** [comment]
@Fytch `extras/` was only renamed that way for the 3.0 branch; the `.cmake` scripts are/were present in the 2.x branches (and releases) inside the `contrib/` directory.
