### ISSUE TITLE
Are the parameters order of target_link_libraries important?

### ISSUE THREAD

**Issue by albayenes** [catchorg/Catch2#2229]
Hi,
I work on the following example that I found from [here](https://raymii.org/s/tutorials/Cpp_project_setup_with_cmake_and_unit_tests.html). Unlike the example, I use catch v3.

I came accross the following behaviour:
If I use target_link_libraries parameters as following

    target_link_libraries(${BINARY} PUBLIC ${CMAKE_PROJECT_NAME}_lib Catch2::Catch2WithMain)

the command ./tst/ExampleProject_tst runs main function of the program instead of main of test

If I change the order of parameters like that

    target_link_libraries(${BINARY} PUBLIC Catch2::Catch2WithMain ${CMAKE_PROJECT_NAME}_lib)

It runs the tests. Why is there such a difference? Is it a bug or not?

Full of my code:

**CMakeLists.txt**
    
    cmake_minimum_required(VERSION 3.10)
    project(ExampleProject)
    
    set(CMAKE_CXX_STANDARD 14)
    
    include_directories(src)
    
    enable_testing()
    
    add_subdirectory(src)
    add_subdirectory(tst)

**src/main.cpp**

    #include <iostream>
    #include "Formula.h"
    
    int main() {
        std::cout << "Bla: " << Formula::bla(2) << std::endl;
        return 0;
    }

**src/Formula.h**
  
    #ifndef EXAMPLEPROJECT_FORMULA_H
    #define EXAMPLEPROJECT_FORMULA_H
    
    class Formula {
    public:
        static int bla(int arg1);
    };
    
    #endif //EXAMPLEPROJECT_FORMULA_H

**src/Formula.cpp**
    
     #include "Formula.h"
    
    int Formula::bla(int arg1) {
        return arg1 * 2;
    }

**src/CMakeLists.txt**

    set(BINARY ${CMAKE_PROJECT_NAME})
    
    file(GLOB_RECURSE SOURCES LIST_DIRECTORIES true *.h *.cpp)
    
    set(SOURCES ${SOURCES})
    
    add_executable(${BINARY}_run ${SOURCES})
    
    add_library(${BINARY}_lib STATIC ${SOURCES})

**tst/Formula-test.cpp**
    
    #include <catch2/catch_all.hpp>
    
    #include "Formula.h"
    
    TEST_CASE("blaTest", "[ExampleProject_tst]") {
        //arrange
        //act
        //assert
        REQUIRE (Formula::bla (0) ==  0);
        REQUIRE (Formula::bla (10) == 20);
        REQUIRE (Formula::bla (50) == 100);
    }

**tst/CMakeLists.txt**

    set(BINARY ${CMAKE_PROJECT_NAME}_tst)
    
    file(GLOB_RECURSE TEST_SOURCES LIST_DIRECTORIES false *.h *.cpp)
    
    #variable_watch(TEST_SOURCES)
    message(${TEST_SOURCES})
    
    set(SOURCES ${TEST_SOURCES})
    
    find_package(Catch2 REQUIRED)
    
    #add_executable(${BINARY} ../src/Formula.h ../src/Formula.cpp Formula-test.cpp)
    add_executable(${BINARY}  ${TEST_SOURCES})
    
    add_test(NAME ${BINARY} COMMAND ${BINARY})
    
    target_link_libraries(${BINARY} PUBLIC Catch2::Catch2WithMain ${CMAKE_PROJECT_NAME}_lib)
    #target_link_libraries(${BINARY} PUBLIC ${CMAKE_PROJECT_NAME}_lib Catch2::Catch2WithMain)

**Platform information:**

 - OS: Ubuntu 16.04
 - Cmake: version 3.18.2
 - Catch version: v3

**Comment by horenmar** [comment]
Yes.

For every symbol that is needed from a library, the first seen occurrence is linked into the resulting binary. This includes `main`. The libraries are visited in order you list them, so when you list the libraries in order of "Catch2's main, your main", then Catch2's main is seen first and used. If you list them in the other order, then your main is used.

**Comment by horenmar** [comment]
Yes.

For every symbol that is needed from a library, the first seen occurrence is linked into the resulting binary. This includes `main`. The libraries are visited in order you list them, so when you list the libraries in order of "Catch2's main, your main", then Catch2's main is seen first and used. If you list them in the other order, then your main is used.
