### ISSUE TITLE
How to deal with function-static variables

### ISSUE THREAD

**Issue by Gomox11** [catchorg/Catch2#2243]
The code I'm testing contains a static variable at function scope. My test cases all pass if I run them individually. However, if I execute all tests registered to one catch2 main, some of them fail because the static variable is still initialized with the other test's values.

Is there any elegant way to get around this issue? I tried using (different) Fixtures, using Sections and duplicating the initialization code to each individual test case.

**Comment by LinuxDevon** [comment]
I can't think of any elegant solution. To me this is difficult to say if Catch2 should attempt to do anything with static variables. The intent of them is to be `static` throughout the life of the program. 

This more sounds like an API or design issue. Is there a reason you are testing a function that uses a static variable and needs to be a certain state?  In my opinion, the test failing is the correct result. You shouldn't assume you know what the static variable will be in a program anyways. 

If you really need to have a known state then you need to setup some sort of `reset` method to call to get it back to a known state before the `SECTION` / `TEST_CASE` is over. The other option is if it is a class rather then a function you can create a new instance of the class every `TEST_CASE`. See [Test_Fixture](https://github.com/catchorg/Catch2/blob/devel/docs/test-fixtures.md#top). Feel free to drop in the example if you need some help as well.

**Comment by codeinred** [comment]
I feel like this issue is outside the scope of Catch2, especially since a testing framework has no way to "reset" global state that it's entirely unaware of. Should this issue be closed?

**Comment by horenmar** [comment]
Don't have function-static variables if they are not idempotent, and you want to test the function.

If you believe that they are good design for you, and the fact that running different tests in same process causes test failures doesn't convince you otherwise, use something like CTest to run each test in its own process.
