### ISSUE TITLE
CATCH_CONFIG_ENABLE_BENCHMARKING not very safe

### ISSUE THREAD

**Issue by ye-luo** [catchorg/Catch2#2246]
To reduce compilation time, my app creates a customized main. The actual one is more complicated.
```C++
#define CATCH_CONFIG_RUNNER
#include "catch.hpp"

int main(int argc, char* argv[])
{
  Catch::Session session;
  return session.run(argc, argv);;
}
```
complied into catch_main.o
```
g++ -g -fsanitize=address -DCATCH_CONFIG_ENABLE_BENCHMARKING catch_main.cpp  -c
```

Then we have a few tests or benchmark compiled separately.
```C++
#include "catch.hpp"

TEST_CASE("DiracMatrix_identity", "[wavefunction][fermion]")
{
  CHECKED_ELSE(false) { FAIL("ABC");}
}
```
The test is good with `CATCH_CONFIG_ENABLE_BENCHMARKING` enabled.
```
g++ -g -fsanitize=address -DCATCH_CONFIG_ENABLE_BENCHMARKING test_catch.cpp  catch_main.o
./a.out
```

However
```
g++ -g -fsanitize=address test_catch.cpp  catch_main.o
./a.out
```
The run fails. So it seems that I cannot have a single catch_main with  `CATCH_CONFIG_ENABLE_BENCHMARKING` enabled to serve linking tests with and without `CATCH_CONFIG_ENABLE_BENCHMARKING`

Is it possible to make this case work so I don't need to compile one catch_main.o and one catch_benchmark_main.o.

**Comment by horenmar** [comment]
Probably not, and even if it was it wouldn't be worth the time to do so.

The reason why the split is even there is that the single header distribution of v2 causes benchmarking to have significant compilation overhead. IIRC the tests at the time of adding benchmarking showed some 20% in test files, and even more in the implementation file.

The different distribution model of v3 means that benchmarking is always enabled and doesn't cause the compilation slowdown it does for v2.
