### ISSUE TITLE
Errors about redefinition of ____C_A_T_C_H____T_E_S_T____

### ISSUE THREAD

**Issue by acidtonic** [catchorg/Catch2#225]
I have been using catch for awhile now and sometimes find that after breaking a test such that it won't compile I can no longer build the tests that previously were working. Even after fixing the compilation error. It's very "strange".

Originally I was seeing these when trying to check for a nullptr in a REQUIRE() block. But then after removing the check I still get these errors even after clean building. Now I'm back to old code that was previously checked in and working that now has build errors. I can't help but think this is just a bug somewhere in Catch. 

In short it kinda went like this....
1. Tests were working
2. I added new REQUIRE statements to the existing test that checked for a nullptr using ==.
   1. Compilation failed.
   2. Removed that offending line.
   3. Clean build and now I still can't build the tests. What went wrong?

Is there potentially a workaround by just naming the functions instead of using anonymous ones? Seems like a name clash and I've even tried removing any parallel -j options to make thinking maybe that would help.

In file included from [REDACTED].cpp:22:0:
tests/[REDACTED_1].hpp:7:1: error: redefinition of ‘Catch::AutoReg {anonymous}::autoRegistrar7’
tests/[REDACTED_2].hpp:7:1: error: ‘Catch::AutoReg {anonymous}::autoRegistrar7’ previously declared here
tests/[REDACTED_1].hpp: In function ‘void ____C_A_T_C_H____T_E_S_T____7()’:
tests/[REDACTED_1].hpp:7:1: error: redefinition of ‘void ____C_A_T_C_H____T_E_S_T____7()’
tests/[REDACTED_2].hpp:7:1: error: ‘void ____C_A_T_C_H____T_E_S_T____7()’ previously defined here
make: **\* [[REDACTED].o] Error 1

$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/x86_64-pc-linux-gnu/gcc-bin/4.6.3/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/4.6.3/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-4.6.3/work/gcc-4.6.3/configure --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/4.6.3 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/4.6.3/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.6.3 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.6.3/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.6.3/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/4.6.3/include/g++-v4 --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --disable-altivec --disable-fixed-point --without-cloog --without-ppl --disable-lto --enable-nls --without-included-gettext --with-system-zlib --enable-obsolete --disable-werror --enable-secureplt --enable-multilib --enable-libmudflap --disable-libssp --enable-esp --enable-libgomp --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/4.6.3/python --enable-checking=release --disable-libgcj --enable-libstdcxx-time --disable-libquadmath --enable-languages=c,c++ --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-targets=all --with-bugurl=http://bugs.gentoo.org/ --with-pkgversion='Gentoo Hardened 4.6.3 p1.13, pie-0.5.2'
Thread model: posix
gcc version 4.6.3 (Gentoo Hardened 4.6.3 p1.13, pie-0.5.2) 

$ make -v
GNU Make 3.82
Built for x86_64-pc-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by pip010** [comment]
maybe worth mentioning that in docs, I got myself in the same trap, good I dont need to re-factor like 100s files :)

**Comment by horenmar** [comment]
@pip010 IIRC the only case when Catch2 doesn't use `__COUNTER__` is when being parsed by older CLion. Once it is compiled, it should only use `__COUNTER__`, except if the user explicitly defines `CATCH_CONFIG_NO_COUNTER`.
