### ISSUE TITLE
No way to require a "fatal error condition"

### ISSUE THREAD

**Issue by KubaO** [catchorg/Catch2#2254]
I have some tests that by design should fail with a "fatal error condition" - that's the error message that Catch2 currently displays: `FAILED: [...] due to a fatal error condition: [...]`.

What is the `REQUIRE_` incantation needed to make this a success, not a failure? In my case, it is a divide by zero error that is expected and a necessary part of testing.

I'm looking for `REQUIRE_CRASHES` equivalent in the below - I want that test case to succeed on on the fatal error, and fail if no fatal error occurs.

```
int div0() { return 0/0; }

TEST_CASE("should succeed") REQUIRE_CRASHES(div0());
```

This is under MSVC 2019 latest, compiled with `/EHa`, catch 2.13.6.

**Comment by KubaO** [comment]
The following appears to be a workaround under MSVC:

```
#define CATCH_CONFIG_NO_WINDOWS_SEH
[...]
REQUIRE_THROWS(div0());
```

**Comment by horenmar** [comment]
There isn't, because this requires a process level isolation from the test code. This takes a lot of work due to platform specifics and serializing enough state to run the correct assertion.

#853 is the overarching issue for this.
