### ISSUE TITLE
Silent test failure under cmake

### ISSUE THREAD

**Issue by pantoss** [catchorg/Catch2#2268]
**Describe**
If the test executable should abort(SIGABRT) the build and test run under cmake/ctest can be successful.

During the post build step when --list-test-names-only is executed the exit code is used as a count of the number of tests. If the executable should fail for some reason at this stage (e.g. SIGABRT) this exit code is assumed to be a valid count. The ctests configuration will not have been updated and then at the test stage no tests will be executed.

**Expected behavior**
If the list of tests during catch_discover_tests should fail then the build should fail.

**Reproduction steps**

Steps to reproduce the bug:

Add this to any existing catch2 test which is built using cmake and catch_discover_tests
```
#include <stdlib.h>

int abort_test()
{
    std::cerr << "Aborting" << std::endl;
    abort();
}

const int v = abort_test();
```

Build test - You should see "Aborting" is output during the build but the build will not fail.

Run tests - The test executable will not be executed.

**Platform information:**
 - OS: Oracle Linux 7
 - Compiler+version: GCC 9.2.0
 - Catch version: v2.13.1

**Comment by codeinred** [comment]
catch_discover_tests registers tests with CTest, but it doesn't run them. There's no reason why aborting inside a test should cause the build to fail.

Unless I'm misunderstanding something, I think this issue should be closed.

**Comment by pantoss** [comment]
But it does fail to register the tests. Shouldn't that mean it should cause the build to fail, if part of the builds purpose is to register the tests? It has the knock on effect of tests never being run when ctest is executed, which again is contrary to the purpose of catch2 which is to check for failing tests.

**Comment by horenmar** [comment]
I don't see an easy way to fix this for v2, and for v3 it has already been fixed.

You can open up a PR against v2 if you have a nice way to fix it instead.
