### ISSUE TITLE
Devel branch not building on Visual Studio 2019

### ISSUE THREAD

**Issue by tobiashienzsch** [catchorg/Catch2#2275]
**Describe the bug**

In `src/catch2/benchmark/catch_execution_plan.hpp`: MSVC complains about `std::back_inserter` not being defined. It does not compile.

**Expected behavior**

It should compile. 

**Reproduction steps**

Built using CMake and Catch as a submodule.

```
add_subdirectory(3rd_party/Catch2 EXCLUDE_FROM_ALL)
enable_testing()
include(CTest)
list (APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/3rd_party/Catch2/extras)
include(Catch)
```

**Platform information:**

 - OS: **Windows 10**
 - Compiler+version: **Visual Studio 2019**
 - Catch version: **devel branch**

**Additional context**

Can be fixed by `#include <iterator>` in `src/catch2/benchmark/catch_execution_plan.hpp`

**Comment by horenmar** [comment]
Thanks.
