### ISSUE TITLE
it would be nice if the order of the scenarios was alphabetical

### ISSUE THREAD

**Issue by timprepscius** [catchorg/Catch2#2277]
So, ./MyTester -s

runs different scenarios, in what seems to be related to random order of object files linking?  Not sure.

It would be nice if either they were alphabetical, or something not random.

It would be also nice if a priority could be assigned to tests, either 0 being highest or infinity being highest.
So that the higher priority tests are run first.

**Comment by horenmar** [comment]
The default is declaration order within object file, object file order depends on the linker's mood.

[Luckily, the order is customizable](https://github.com/catchorg/Catch2/blob/devel/docs/command-line.md#specify-the-order-test-cases-are-run)
