### ISSUE TITLE
Any special reason why ConsoleReporter is now final? (and other builtin reporters)

### ISSUE THREAD

**Issue by matt-deboer** [catchorg/Catch2#2287]
**Description**
I had a customized class that was inheriting from ConsoleReporter to branch some behavior based on my own test contexts.
It was nice to avoid duplicating all of the useful console-based reporting functionality and just modify a few key behaviors.

Of course, now I can accomplish the same thing by duplicating all of the code in ConsoleReporter, but I'm just wondering the reasoning behind making all of the built-in reporters final....were there issues arising from people extending them?

It seems like extending one of the built-in reporters would be the best way to add new functionality for custom scenarios...or is there a different/recommended way to do this now?

**Comment by horenmar** [comment]
The answer is pretty much what the relevant commit message says. With single exception, the reporters weren't meant to be derived-from, and we do not want to provide any stability guarantees, to allow various future refactoring of the reporters outside of major version.

So yes, the current recommendation is to copy paste the `ConsoleReporter` into your own sources, and hack it up as you need for your use case. This is not exactly DRY, but forcefully isolates you from breaking changes.
