### ISSUE TITLE
Could not find <catch2/catch_test_macros.hpp> header but <catch2/Catch.hpp> works

### ISSUE THREAD

**Issue by tcw165** [catchorg/Catch2#2292]
**Describe the bug**
I'm using vcpkg to install Catch2 and link Catch2 in my CMakeLists.txt file. But I couldn't include the following header.
```
#include <catch2/catch_test_macros.hpp> // Could not be found
```

**Expected behavior**
The `<catch2/Catch.hpp>` could be found so maybe the macros are collected in this file during the release process.
```
#include <catch2/Catch.hpp> // Could be found.
```

**Reproduction steps**
Search `<catch2/catch_test_macros.hpp>` and you'll find the occurrence in sample code and tutorial.md.

**Platform information:**

 - OS: **MacOs Big Sur v11.6**
 - Compiler+version: **Clang v12.0.0**
 - Catch version: **v2.13.1**

**Additional context**
If `<catch2/Catch.hpp>` is the final header that has everything, would you update the sample code and tutorial document?

**Comment by horenmar** [comment]
From the main readme:

> You are on the devel branch, where the next major version, v3, of Catch2 is being developed. As it is a significant rework, you will find that parts of this documentation are likely still stuck on v2.
>
> For stable (and documentation-matching) version of Catch2, go to the v2.x branch.


You have installed a v2.x version, so you need documentation from the v2.x branch.

**Comment by ahadji05** [comment]
Can you share a link to the installation instructions for the latest stable release?

**Comment by 7mare** [comment]
# Add Catch2 include directory
include_directories("/usr/local/include/catch2")
i already install catch2 and add the lines above in cmakelist(pangolin),but when i add dependencies for pangolin, still tells me that cannot locate catch2
