### ISSUE TITLE
Avoid global test setup when running catch_discover_tests

### ISSUE THREAD

**Issue by Time0o** [catchorg/Catch2#2308]
**Description**

I have the following use case: I'm using a custom main function that does some elaborate setup/teardown that might take several seconds to complete:

```c++
int main(int argc, char **argv)
{
  // expensive setup
  
  int ret = Catch::Session().run(argc, argv);
  
  // expensive teardown
  
  return ret
}
```
I would like to avoid going through all of this during the build step when `catch_discover_tests` in invoked. Unless there is already some canonical way to do this (I suppose I could search for the corresponding flag in `argv` but that doesn't seem very clean) it would be nice if one could be added. E.g. by allowing optional `setup` and `teardown` functions to be passed to `run` that are only invoked when actually running the tests.

**Comment by horenmar** [comment]
If set up and tear down is the only thing you want, then it should be enough to hook testRun events in listener.

**Comment by Time0o** [comment]
@horenmar Yes I think that should do it, I wasn't aware of that feature.
