### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by zidingz** [catchorg/Catch2#2323]
Hey there!

I belong to an open source security research community, and a member (@dwisiswant0) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by horenmar** [comment]
For now you can send me an email at martin.horenovsky@gmail.com, I'll take a look at adding a security docs to the repo.

**Comment by horenmar** [comment]
The docs have been there a while.

**Comment by dwisiswant0** [comment]
Thank you, @horenmar!
