### ISSUE TITLE
Custom main when using amalgamated header/cpp

### ISSUE THREAD

**Issue by eugeneko** [catchorg/Catch2#2324]
I want to provide my own main function, and I use amalgamated version of library which has "main" hard-coded.
What can I do except patching my version of Catch locally? I would make a PR, but I don't know what's the expected solution.

Thanks, Eugene.

**Comment by horenmar** [comment]
There currently isn't any way to do this I think.

**Comment by Mercotui** [comment]
For posterity, I was able to do so by setting `#define CATCH_CONFIG_RUNNER` before the catch include

**Comment by horenmar** [comment]
You should be using the `CATCH_AMALGAMATED_CUSTOM_MAIN` toggle from the linked commit though.
