### ISSUE TITLE
Using Catch2 as a submodule / wrong include

### ISSUE THREAD

**Issue by h-2** [catchorg/Catch2#2340]
**Describe the bug**

I followed the instructions in https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md#top
It tells me to use `add_subdirectory(lib/Catch2)` to add a local clone / subdirectory. The top-level cmake that is used in that case exports `$<BUILD_INTERFACE:${CMAKE_CURRENT_LIST_DIR}/single_include>` but there is no header in `single_include`.

If I change the CMake to export the regular include folder, my build works, but linking fails. I assume that the required libraries are not built or linked automatically?

**Expected behavior**

* There should be an easy way to use Catch2 from a subdirectory and "modern cmake" interface linking. 
* The correct paths should be set.
* The library should work as header-only or build the required shared objects when needed.

**Reproduction steps**
Put Catch2 into a subdirectory, use as decribed in the documentation.

**Platform information:**

 - OS: **Linux**
 - Compiler+version: **GCC 10**
 - Catch version: **v2.13.7**

**Additional context**

**Comment by horenmar** [comment]
That sounds like you checked out different version of the repository. If I switch to `v2.x` branch, `single_include/catch2/catch.hpp` is the target single header, and the build target points the include path there: https://github.com/catchorg/Catch2/blob/d71b4617e9935f8589870af211f5b7552d743654/CMakeLists.txt#L95-L99
