### ISSUE TITLE
Add option for disabling trivial ABI attribute on unique_ptr

### ISSUE THREAD

**Issue by psalz** [catchorg/Catch2#2344]
**Description**

As noted in the message of the commit introducing the `[[trivial_abi]]` attribute for `Detail::unique_ptr` (1d79683e), this optimization breaks linking of objects compiled with Clang and GCC. While that has always been a "use at your own risk" feature, in my experience it basically worked in all but the most esoteric scenarios. However, with the aforementioned change, it now consistently produces segfaults for me. I'm wondering whether there would be interest in adding some kind of compile time option for disabling the `[[trivial_abi]]` attribute, restoring the previous works-most-of-the-time behavior.

**Additional context**

I'm in the process of migrating the [Khronos Group SYCL Conformance Test Suite](https://github.com/KhronosGroup/SYCL-CTS/) to Catch2. The SYCL ecosystem is still relatively young and different implementors are using different mechanisms for integrating their implementations with CMake. For example they might set `CMAKE_CXX_COMPILER` on the CLI or inside a `CMakeLists.txt`, use a custom compiler launcher or custom build steps with dedicated device compiler passes. Whatever the method, it currently can (and does) happen that object files compiled with GCC (typically the default compiler on a given system) get linked with object files compiled with some Clang derivative (most SYCL implementations rely on LLVM in some form).

While ultimately this is a problem that implementors will have to figure out how to best deal with, sorting this stuff out takes time. So in the interest of completing the Catch2 migration sooner than later, I'm hoping we can find a workaround here!

**Comment by horenmar** [comment]
Given that this isn't the first time this came up, I am going to remove the attribute.

**Comment by psalz** [comment]
Well then - not quite what I was expecting, but works for me! :) Thanks for the quick action. I'll leave this issue open until it is auto-closed upon merge.

**Comment by horenmar** [comment]
Yeah, the problem is that if I leave it in as an option, I will need to test it.

I don't believe the maintenance effort is worth the relatively minor gains from having trivial-abi, at least compared to investing similar effort to some higher level optimization inside Catch2, so the easiest option for me is to grumble about people not building their projects properly and remove it completely 😃
