### ISSUE TITLE
CATCH_INSTALL_HELPERS still documented but not available anymore (v3.0.0-release4)

### ISSUE THREAD

**Issue by AlexisWilke** [catchorg/Catch2#2347]
**Describe the bug**

When I run cmake with `-DCATCH_INSTALL_HELPERS=on`, I get the following warning:

    $ cmake -DCATCH_BUILD_TESTING=off -DCATCH_INSTALL_HELPERS=on -DCATCH_INSTALL_DOCS=on -DCMAKE_INSTALL_PREFIX=`pwd`/out ../Catch2-3.0.0/
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    CMake Warning:
      Manually-specified variables were not used by the project:

        CATCH_INSTALL_HELPERS

    -- Build files have been written to: /home/snapwebsites/snapcpp/contrib/snapcatch2-3/BUILD

**Expected behavior**

Obviously, to avoid the warning I can simply not add that variable. Done.

However, the fact is it is documented.

**Reproduction steps**

See above. Get latest, run `cmake ...`. See warning about unknown variable.

**Platform information:**

Not relevant, but here it is:

 - OS: Linux (Ubuntu 18.04)
 - Compiler+version: g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
 - Catch version: 3.0.0-release4

**Additional context**

The following two files include that reference:

    $ grep -r CATCH_INSTALL_HELPERS Catch2-3.0.0/
    Catch2-3.0.0/docs/cmake-integration.md:* `CATCH_INSTALL_HELPERS` -- When `ON`, Catch2's extras folder will be
    Catch2-3.0.0/conanfile.py:        cmake.definitions["CATCH_INSTALL_HELPERS"] = "ON"

**A Little Further**

It looks like the variable may have been renamed `CATCH_INSTALL_EXTRAS`, in which case, renaming it in those two places would do better than just deleting those entries.

Also, explaining a bit what those "extras" are would be good for us.

**Comment by horenmar** [comment]
Thanks, I updated the docs and expanded them slightly.
