### ISSUE TITLE
Unable to run tests from dll

### ISSUE THREAD

**Issue by xoorath** [catchorg/Catch2#2356]
Hey,

This isn't a bug in Catch2, but I'm hoping you'll know how to deal with this problem.

In my project on windows using msvc I have dll projects depending on catch2. ~The problem is the static constructor used for auto registering test cases doesn't appear to be getting called when I have test macros in the DLL.~

The tests work fine if I declare them in my exe project.

Is this something you've come across or have a suggested resolution to?

Thanks

**Comment by xoorath** [comment]
I was incorrect saying "The problem is the static constructor used for auto registering test cases doesn't appear to be getting called".

I now think it's because catch2 is statically linked meaning the singletons are separate in the dll and exe projects.

**Comment by xoorath** [comment]
I can work around this issue somewhat painfully by having my dll export a test entry point and calling it from my exe. That seems to work, but I'll add a +1 to others who have requested DLL exports for the project. I _think_ that would resolve this issue.

**Comment by horenmar** [comment]
Wait, so you have a dll project that contains tests? What is the reason you don't compile them into an executable?

**Comment by xoorath** [comment]
Hey, thanks for commenting on the issue @horenmar. 

I have a game project that has dlls for parts of the game engine. The intent was to have a test config (like debug) that would run and build my tests. I was hoping to not compile my code differently (.lib or more exes) just for testing.

Sounds like it might be a pain to setup my library to support both lib and dll, although I haven't done that before.

What I'm doing now (to be clear) is:

I write unit tests in each of my projects inside an `#if CONFIG == CONFIG_TEST` block. Each library has a test header with a function like `namespace blah { int RunTests(int argc, char** argv); }` and in my game project I have an entry point inside a `#if CONFIG == CONFIG_TEST` block and it calls RunTests for each of my libraries. The main difference between what I have and what I want is: I'd like to not need that `blah::RunTests` call and for all tests to be run together. 

If Catch were capable of being dynamically linked then it's singletons would be shared between the projects and registration would work automatically, I think.
