### ISSUE TITLE
Make METHOD_AS_TEST_CASE work with virtual methods of base classes by instantiating the derived class instead of the base class object

### ISSUE THREAD

**Issue by RicardoCapurro** [catchorg/Catch2#2373]
**Describe the bug**

If you use METHOD_AS_TEST_CASE on a virtual NON OVERRIDEN method of a derived class, then an object of the base class is instantiated instead of an object of the derived class, Note that in order to identify the method I use the Derived class name.

**Expected behavior**
The natural and expected behavior is to have the method being invoked on an instance of the Derived class, the one specified on the macro METHOD_AS_TEST_CASE()

**Reproduction steps**

```
class Base {
    virtual void another_vmethod() { thwow std::runtime_exception{"Fail!!!"}; }
    virtual void vmethod() {
        REQUIRE_NOTHROW(another_vmethod());
    }
    virtual ~Base() = default;
};
class Derived : public Base {
    void another_vmethod() override {} 
};
METHOD_AS_TEST_CASE(Derived::vmethod, "Test virtual method on derived class", "[TAG]")

```
This end up instantiating an object of Base class, so we can't use Base a a container for tests fixtures

If we redefine Derivad as

```
class Derived {
    void another_vmethod() override {}
    void vmethod() override { Base::vmethod(); }  // Note this should be unnecessary
};
METHOD_AS_TEST_CASE(Derived::vmethod, "Test virtual method on derived class", "[TAG]")

```
Now it works, but seems ugly and unnecessary

**Platform information:**
 - OS: Windows and Linux
 - Compiler version: Visual Studio 2022 and GCC 11.2.0
 - Catch version: **v2.13.8

**Additional context**
Not needed

**Comment by horenmar** [comment]
Hmmm, I am not sure there is a good way to fix this. The underlying issue is that if `Derived` doesn't override `vmethod`, then passing `&Derived::vmethod` to `makeTestinvoker` as defined below, infers the `C` template parameter as `Base`. This then means that later we construct `Base` for the call, and thus `Base::another_vmethod` ends up being called.

```cpp
template<typename C>
Detail::unique_ptr<ITestInvoker> makeTestInvoker( void (C::*testAsMethod)() ) {
    return Detail::make_unique<TestInvokerAsMethod<C>>( testAsMethod );
}
```

-----

Also a fixed up reproducer to compile:
```cpp
namespace {
    class Base {
    public:
        virtual void another_vmethod() {
            throw std::runtime_error{ "Fail!!!" };
        }
        virtual void vmethod() { REQUIRE_NOTHROW( another_vmethod() ); }
        virtual ~Base() = default;
    };
    class Derived : public Base {
    public:
        void another_vmethod() override {}
    };
} // namespace

METHOD_AS_TEST_CASE( Derived::vmethod,
                     "Test virtual method on derived class",
                     "[TAG]" )
```

**Comment by horenmar** [comment]
I poked around this and there is no way to do this without changing the interface.

Type inference for `Derived::vmethod` if `vmethod` was not overridden in `Derived` ends up with the type `Base::vmethod`. This means that there is no way for Catch2 to get back the `Derived` type inside the test macro.
