### ISSUE TITLE
catch2/catch_user_config.hpp has to be copied from build/generated-includes/catch2 manually

### ISSUE THREAD

**Issue by nandanvasudevan** [catchorg/Catch2#2374]
**Describe the bug**
Project: https://github.com/nandanvasudevan/cpp_scratch_pad/tree/stl
Multiple includes for `#include <catch2/catch_user_config.hpp>` fails because it no in the `./src/catch2` directory where it was all this time.
I am just copying the catch2 folder to where I need it to be included.
I have a feeling that's not how its is supposed to be.
All the tests seem to pass but my code won't even compile. Complains it cannot find `catch2/catch_user_config.hpp` which is because it is not in the src directory.

src/catch2/internal/catch_test_macro_impl.hpp in [4396a9119fa32abf966f189c6f6d9c54698d89c8](https://github.com/catchorg/Catch2/commit/4396a9119fa32abf966f189c6f6d9c54698d89c8) is the change causing issues.

I know I shouldn't use [devel](https://github.com/catchorg/Catch2/tree/devel) unless I know what I am doing, but I also would like to learn why this happens and the right way to do this. 

**Expected behavior**
`catch2/catch_user_config.hpp` in src/catch2

**Reproduction steps**
Steps to reproduce the bug.
Just build using the includes provided in src/catch2.

**Platform information:**

 - OS: **Ubuntu Jammy Jellyfish (development branch)**
 - Compiler+version: **GCC v11.2.0**
 - Catch version: **v3.0.0 Preview 4 [529eec97bb15a8a861986cb782897412f1be4ae2](https://github.com/catchorg/Catch2/commit/529eec97bb15a8a861986cb782897412f1be4ae2)**

**Additional context**

**Comment by horenmar** [comment]
> I am just copying the catch2 folder to where I need it to be included.

What do you mean by this? Do you "install" catch2 by doing `cp /path/to/catch2/src/ my-project/catch2`?

**Comment by correaa** [comment]
I have the same problem. 
I am also looking for a solution.

I have this in my project in the CMakeLists.txt file

```
Include(FetchContent)
FetchContent_Declare(
	Catch2
	GIT_REPOSITORY https://github.com/catchorg/Catch2.git
	GIT_TAG        devel
	)
FetchContent_MakeAvailable(Catch2)
```

This used to work a few weeks back.

**Comment by nandanvasudevan** [comment]
> > I am just copying the catch2 folder to where I need it to be included.
> 
> 
> 
> What do you mean by this? Do you "install" catch2 by doing `cp /path/to/catch2/src/ my-project/catch2`?

Essentially yes.
I guess it's intended to be built as a sub-project? But I am static linking it anyway so I thought why not.
What is the right way to **install** it?

**Comment by nandanvasudevan** [comment]
> I have the same problem, in my project I have this in the CMakeLists.txt file
> 
> ```
> Include(FetchContent)
> FetchContent_Declare(
> 	Catch2
> 	GIT_REPOSITORY https://github.com/catchorg/Catch2.git
> 	GIT_TAG        devel
> 	)
> FetchContent_MakeAvailable(Catch2)
> ```
> 
> This used to work a few weeks back.

@correaa Do you do a `make install` or something similar? Or do you somehow let CMake figure out the includes?

**Comment by nandanvasudevan** [comment]
Sorry! I have used `make install` before it simply did not occur to me to use it here. My bad!

# Resolution
- Make a new directory, say `build` inside Catch2 root.
- Run `cmake ../ cmake ../ -DCMAKE_INSTALL_PREFIX:PATH=/your/path/to/project`
- `make -j8`
- make install
---

>   ```
>   FetchContent_Declare(
>   Catch2
>   GIT_REPOSITORY https://github.com/catchorg/Catch2.git
>   GIT_TAG        devel
>    )
>   ```
@correaa Is it absolutely necessary to checkout the entire project to every single project? I really don't want to do that!

**Comment by correaa** [comment]
> @correaa Do you do a make install or something similar? Or do you somehow let CMake figure out the includes?

Sorry, if it was not clear. What I posted was not a solution, I was simply showing what I have in my CMake and found the same problem as you, which didn't occur some weeks ago.

And yes, `sudo make install` solves this problem because it installs the missing header system wide,  but I don't think this is the intent of using `FetchContent`, I expected these files should be generated by `FetchContent_MakeAvailable`.

> @correaa Is it absolutely necessary to checkout the entire project to every single project? I really don't want to do that!

I don't know. I used the `FetchContent` because that is what Catch2 recommended and it worked for a while. I am not an expert in CMake, far from it.

What we did to solve this problem was to pin the `GIT_TAG`  to a version before this problem appeared, but it is not ideal either.

```
message(STATUS "downloading Catch2 v3p3")
Include(FetchContent)
FetchContent_Declare(
	Catch2
	GIT_REPOSITORY https://github.com/catchorg/Catch2.git
	GIT_TAG        7cf2f88e50f0d1de324489c31db0314188423b6d
	)
FetchContent_MakeAvailable(Catch2)
include_directories(${catch2_SOURCE_DIR}/src)
```

As a side not: we had a lot of troubles with the change in design of Catch2, it used to be handy because it was a single header that didn't need compilation.
In the current state I don't see much advantage over Boost.Test.

**Comment by nandanvasudevan** [comment]
That's the thing when you do it this way I guess. I just have Catch2 externally and then simply export the required files which are generated by `make install`.

**Comment by correaa** [comment]
Then I don't understand the point of having `FetchContent_MakeAvailable` if it is not going to provide all the dependencies, binaries and processed headers in a subdirectory, at least, in some "uninstalled" form.

**Comment by nandanvasudevan** [comment]
> Then I don't understand the point of having `FetchContent_MakeAvailable` if it not going to provide all the dependencies, binaries and processed headers, at least in a subdirectory in some "uninstalled" form.

I don't know enough about CMake to comment on this. Sorry.

**Comment by horenmar** [comment]
@correaa I can't actually reproduce your issue.

```
$ cat CMakeLists.txt
cmake_minimum_required(VERSION 3.20)
project(foo LANGUAGES CXX)

message(STATUS "Fetching Catch2")
include(FetchContent)
FetchContent_Declare(
        Catch2
        GIT_REPOSITORY https://github.com/catchorg/Catch2.git
        GIT_TAG        devel
        )
FetchContent_MakeAvailable(Catch2)


add_executable(tests tests.cpp)
target_link_libraries(tests PRIVATE Catch2::Catch2WithMain)

$ cat tests.cpp
#include <catch2/catch_test_macros.hpp>
#include <catch2/catch_user_config.hpp>

$ cmake -Btest-build -H.
...
$ make -C test-build
<bunch of building>
[100%] Linking CXX executable tests
[100%] Built target tests
```

**Comment by correaa** [comment]
In the  directory generated by FetchContent and MakeAvailable I was never able to find `catch_user_config.hpp`, only `catch_user_config.hpp.in`.  The `hpp` file only appeared after manually doing `make install`.

More details here in this CI log,  https://gitlab.com/npneq/inq/-/jobs/2143880575#L2081

This is our workaround for now (tagging to a version before the header was introduced I guess).

```
message(STATUS "downloading Catch2 v3p3")
Include(FetchContent)
FetchContent_Declare(
	Catch2
	GIT_REPOSITORY https://github.com/catchorg/Catch2.git
	GIT_TAG        7cf2f88e50f0d1de324489c31db0314188423b6d
	)
FetchContent_MakeAvailable(Catch2)
include_directories(${catch2_SOURCE_DIR}/src)
```

full CMakeLists.txt file is here: https://gitlab.com/npneq/inq/-/blob/master/CMakeLists.txt

**Comment by horenmar** [comment]
```
FetchContent_MakeAvailable(Catch2)
include_directories(${catch2_SOURCE_DIR}/src)
```
This is not how you are supposed to use it. Use the provided CMake targets to handle the include paths for you properly.
