### ISSUE TITLE
Compilation error in v2.13.8 source code

### ISSUE THREAD

**Issue by anatolyvenzekov** [catchorg/Catch2#2375]
When I download and compile version 2.13.8 from source code (Catch2-2.13.8.tar.gz), it appears an error related to compilation flag comma-subscript.

![catch2](https://user-images.githubusercontent.com/67583198/155977500-e558eb62-3457-428c-9c13-7e8effe8f858.png)

My gcc version is 9.3.0.

![image](https://user-images.githubusercontent.com/67583198/155977977-8f628ffb-a67f-441f-adaf-f513b8789fce.png)

**Comment by horenmar** [comment]
That's an overly optimistic (in that it targets gcc versions that don't have the specific warning flag) warning suppression in a test file. I removed that particular warning from being considered as Werror.
