### ISSUE TITLE
Catch2 package for Ubuntu 20 any time soon?

### ISSUE THREAD

**Issue by aabramovrepo** [catchorg/Catch2#2381]
Dear All,

   are there any moves towards releasing Catch2 v3 package for Ubuntu 20 in the near future? Or [Installing Catch2 from git repository](https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md#installing-catch2-from-git-repository) is the way to go?

Thanks!

Best,
Alexey

**Comment by horenmar** [comment]
Hi,
I am not packaging Catch2 in any package manager, so this is not a good place to ask, as my answer is "IDK, someone else does that".
