### ISSUE TITLE
Documentation contains broken compiler explorer link

### ISSUE THREAD

**Issue by codeinred** [catchorg/Catch2#2396]
**Describe the bug**
Test Cases and Sections contains a broken compiler explorer link inside the BDD-Style Test Cases section. See: <https://github.com/catchorg/Catch2/blob/devel/docs/test-cases-and-sections.md#bdd-style-test-cases>

This is the broken link: <https://godbolt.org/z/e5vPPM>

**Expected behavior**
I expected that link to compile into a runnable example

**Reproduction steps**
- Go to the godbolt link
- Wait for it to attempt compilation

**Platform information:**
- GCC 7.3
- Whatever backend Godbolt is using

**Comment by horenmar** [comment]
Hmmm, I see two issues here.

1) CE doesn't properly install the library, thus the header that is generated during cmake configuration isn't present.
2) CE links probably shouldn't point to "trunk" version of Catch2 for stability.
