### ISSUE TITLE
With exactly 256 tests I get a warning saying there are no tests (using CMake)

### ISSUE THREAD

**Issue by Gruntfuggly** [catchorg/Catch2#2401]
```
CMake Warning at <hidden>/Catch2/v2.13.7/Catch2_Release/lib/cmake/Catch2/CatchAddTests.cmake:46 (message):
  Test executable
  '<hidden>'
  contains no tests!
```

Adding another test makes the error go away. :smile:

**Comment by horenmar** [comment]
Ooooh, that's a repeat of #797 due to the v2 versions using the number of listed tests (things in general) as the return code.

Should be easy enough to fix.
