### ISSUE TITLE
Preview release link to "migration docs" is broken

### ISSUE THREAD

**Issue by kiwixz** [catchorg/Catch2#2414]
It misses the `docs/` folder.

```diff
- https://github.com/catchorg/Catch2/blob/v3.0.0-preview5/migrate-v2-to-v3.md#top
+ https://github.com/catchorg/Catch2/blob/v3.0.0-preview5/docs/migrate-v2-to-v3.md#top
```

**Comment by horenmar** [comment]
Thanks, that's what I get from copy pasting the release notes from `docs/release-notes.md`. The original needs the link without the `docs/` part, as it lives next to the other file, but when it is copied over, it needs that `docs/` part because the path changes.
