### ISSUE TITLE
2.x: GCC7 pragma error - unknown option

### ISSUE THREAD

**Issue by susnux** [catchorg/Catch2#2416]
**Describe the bug**
Compiling with gcc7 (openSUSE Leap 15.3), the build fails with

```error: unknown option after '#pragma GCC diagnostic' kind```

in `projects/SelfTest/UsageTests/Message.tests.cpp`.

**Expected behavior**
Builds without an error.

**Reproduction steps**
Just compile with gcc version 7.

**Platform information:**

 - OS: **openSUSE Leap 15.3**
 - Compiler+version: **GCC 7.5.0**
 - Catch version: **v2.13.9**

**Additional context**
Patch solving the problem:

```diff
diff -Nur Catch2-2.13.9/projects/SelfTest/UsageTests/Message.tests.cpp new/projects/SelfTest/UsageTests/Message.tests.cpp
--- Catch2-2.13.9/projects/SelfTest/UsageTests/Message.tests.cpp	2022-04-12 22:38:17.000000000 +0200
+++ new/projects/SelfTest/UsageTests/Message.tests.cpp	2022-04-26 14:20:39.792719016 +0200
@@ -243,7 +243,7 @@
 
 // Clang and gcc have different names for this warning, and clang also
 // warns about an unused value
-#if defined(__GNUG__) && !defined(__clang__)
+#if defined(__GNUG__) && __GNUG__ >= 8 && !defined(__clang__)
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wcomma-subscript"
 #elif defined(__clang__)
@@ -262,7 +262,7 @@
     SUCCEED();
 }
 
-#ifdef __GNUG__
+#if defined(__GNUG__) && __GNUG__ >= 8
 #pragma GCC diagnostic pop
 #endif
 

```

**Comment by ghost** [comment]
Same here, gcc version 9.4.0.

**Comment by ghost** [comment]
According to [this](https://hackmd.io/@VZ/gcc-warnings), comma-subscript first appeared in 10.1, so I think you should change the version requirement.
