### ISSUE TITLE
Ability to isolate tests with DYNAMIC_SECTION / GENERATE

### ISSUE THREAD

**Issue by thijssteel** [catchorg/Catch2#2418]
**Description**
This issue is related to #2366. In short, I would like to be able to run only a single case from a test with generators in it.

Let's say I have the following test case:

```c++
    TEST_CASE("Test with generators")
    {
        auto value = GENERATE(1,3,5);
        DYNAMIC_SECTION("VALUE IS " << value) {
            ...
        }
    }
```

And let's say the test fails for `value == 3`. Because of the DYNAMIC_SECTION (thanks @neobrain ), I can see which value causes the failure. Now I want to debug the test and I'd love to run only the failing case (i.e. 3). However, If i try to run only that test, by using:

`./tester "Test with generators" -c "VALUE IS 3"`

The tester hangs. If I use a regular SECTION instead of DYNAMIC_SECTION, I get the expected result (but all generator values are run).

**Comment by horenmar** [comment]
I can't reproduce this with current devel:

```cpp
TEST_CASE( "Test 2418" ) {
    auto value = GENERATE( 1, 3, 5 );
    DYNAMIC_SECTION( "Value is " << value ) { std::cout << "In section\n"; }
}
```

```
./tests/SelfTest "Test 2418" -c "Value is 3"
Filters: Test 2418
Randomness seeded to: 4283675820
In section
===============================================================================
test cases: 1 | 1 passed
assertions: - none -
```

**Comment by thijssteel** [comment]
I'm still using V2. Good to hear that it's already solved (and sorry about not checking against the devel branch before reporting).
Looking forward to V3.
