### ISSUE TITLE
std::aligned_storage is deprecated in C++23

### ISSUE THREAD

**Issue by marcmutz** [catchorg/Catch2#2419]
`ObjectStorage` is using `std::aligned_storage`, but C++23 deprecates it, causing warnings in projects that already use `-std=c++2b`.

**Comment by marcmutz** [comment]
@horenmar Do you still plan to make a 2.13.10 release, or should Catch2 users now simply use HEAD?

**Comment by horenmar** [comment]
I completely forgot there were meaningful changes there.

https://github.com/catchorg/Catch2/releases/tag/v2.13.10
