### ISSUE TITLE
CATCH_TRAP doesn't work well on ARM Macs

### ISSUE THREAD

**Issue by stefanhaller** [catchorg/Catch2#2422]
**Describe the bug**
On ARM Macs ("Apple Silicon"), `CATCH_TRAP` does work correctly in that it does stop in the debugger. However, you can't single-step from there, or even continue; you are stuck at the same source line forever.

This can be fixed by using the instruction `d43e0000` instead of the `d4200000` that is used now. This instruction is generated by the `__builtin_debugtrap()` function, which is also available on i386 and x86_64 and generates the `int $3` instruction there. So a simple fix looks like this (against the `devel` branch):

```diff
diff --git a/src/catch2/internal/catch_debugger.hpp b/src/catch2/internal/catch_debugger.hpp
index c300da72..e3b0a24b 100644
--- a/src/catch2/internal/catch_debugger.hpp
+++ b/src/catch2/internal/catch_debugger.hpp
@@ -16,11 +16,7 @@ namespace Catch {
 
 #ifdef CATCH_PLATFORM_MAC
 
-    #if defined(__i386__) || defined(__x86_64__)
-        #define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
-    #elif defined(__aarch64__)
-        #define CATCH_TRAP()  __asm__(".inst 0xd4200000")
-    #endif
+    #define CATCH_TRAP() __builtin_debugtrap()
 
 #elif defined(CATCH_PLATFORM_IPHONE)
 
```

**Platform information:**

 - OS: macOS 12.3.1
 - Compiler+version: **Apple clang version 13.0.0 (clang-1300.0.29.30)**
 - Catch version: **v2.13.9** and **v3.0.0-preview5**

**Comment by horenmar** [comment]
Is this universally supported? Quick look around the internet suggests that this is supported by _some_ (most?) versions of Clang, but not e.g. GCC.

**Comment by stefanhaller** [comment]
You're right, it's clang-specific. I was fooled by [this claim](https://github.com/scottt/debugbreak/issues/13) that it works universally, without reading the comments further down that debunk it. Sorry.

In that case, the fix would be just to replace `0xd4200000` with `0xd43e0000` in the existing code. (It would of course be possible to check `__has_builtin(__builtin_debugtrap)` and use it if available, and fall back to assembly if not, but it doesn't seem worth it.)

**Comment by horenmar** [comment]
Is this also an issue for the iphone configuration? It also uses `0xd4200000` for dbg break.
