### ISSUE TITLE
Can you test classes based on c++20 features such as concepts?

### ISSUE THREAD

**Issue by alejandroarmas** [catchorg/Catch2#2425]
**Describe the bug**

Compiling Catch 3.01 results in an error for parsing c++20 concept keywords?

**Reproduction steps**
Steps to reproduce the bug.

Compiling using `make` is not working.

```
In file included from unittests/../include/strong_types.h:6:
unittests/../include/m_algorithms_concepts.h:11:1: error: unknown type name 'concept'
concept Integral = std::is_integral_v<T>;
```

**Platform information:**

 - OS: **arm64-apple-darwin21.4.0**
 - Compiler+version: **clang version 12.0.0 (git@github.com:OpenCilk/opencilk-project.git 5d2851d7d0e689ecb3b893aa6abd12390b838c4b)
**
 - Catch version: **v3.0.1**

**Comment by horenmar** [comment]
When you compiler complains that it doesn't understand `concept` keyword, why do you think that is a Catch2 issue?

**Comment by alejandroarmas** [comment]
You're right It was a typo. Thanks for understanding!
