### ISSUE TITLE
Redefinition of macro CATCH_CONFIG_CONSOLE_WIDTH

### ISSUE THREAD

**Issue by stephen-hqxu** [catchorg/Catch2#2431]
**Describe the bug**
Compiler throws warning about a macro `CATCH_CONFIG_CONSOLE_WIDTH` being redefined if user has modified the default value before building.

**Expected behavior**
No compiler warning regarding this issue should be generated regardless of the value changed to.

**Reproduction steps**
Change the default console width in CMake cache `CATCH_CONFIG_CONSOLE_WIDTH` before compilation to anything other than the default 80.

**Platform information:**
 - OS: Windows 10 and Rocky Linux 8.5
 - Compiler+version: MSVC 16.11.14 and GCC 9.2.0
 - Catch version: v3.0.1

**Additional context**
I have noticed that there are two files making definition to this macro.

1.
https://github.com/catchorg/Catch2/blob/605a34765aa5d5ecbf476b4598a862ada971b0cc/src/catch2/catch_user_config.hpp.in#L190

2.
https://github.com/catchorg/Catch2/blob/605a34765aa5d5ecbf476b4598a862ada971b0cc/src/catch2/internal/catch_console_width.hpp#L11-L13

File indicated in 2. has a guard while file 1. does not, which means 2. is included before 1. somewhere in the code.

Maybe another guard should be added to file 1., or is file 2. still neccessary? Because file 1. is generated by CMake configuration and it should have guranteed `CATCH_CONFIG_CONSOLE_WIDTH` to exist by the time it is used.

**Comment by horenmar** [comment]
Can you provide longer repro? I don't want to make the define in the user_config file conditional, as that could cause the user specified config to end up overridden due to include order.

**Comment by stephen-hqxu** [comment]
> Can you provide longer repro?

Yes sure:

1. Assume you are currently at the project root of Catch2.

2. Generate the build tree.

```sh

mkdir build
cd ./build
cmake ../

```

3. Open `CMakeCache.txt` and find the option:

```txt

//Read docs/configuration.md for details. Must form a valid integer
// literal.
CATCH_CONFIG_CONSOLE_WIDTH:STRING=80

```

It is default to 80. To reproduce, modify the value to anything else, say 120.

4. Save the cache and build.

```sh

# Compile with MSVC
cmake --build ./ --config Release --target ALL_BUILD

```

It should now start compiling and at some point the compiler throws a warning similar to this:

> /Catch2-3.0.1/build/generated-includes/catch2/catch_user_config.hpp(190,1): warning C40
05: 'CATCH_CONFIG_CONSOLE_WIDTH': macro redefinition [\Catch2-3.0.1\build\src\Catch2.vc
xproj]

I have tested on MSVC and GCC and both of them emit a similar warning message.
