### ISSUE TITLE
Branch for v3

### ISSUE THREAD

**Issue by nandanvasudevan** [catchorg/Catch2#2435]
**Description**
Catch2 v3 is still in devel branch. Is there any particular reason for this?
Can we create a new branch for v3?

**Additional context**
-

**Comment by horenmar** [comment]
`devel` branch is where the ongoing development happens.

The reason v1 and v2 have their own branches (`Catch1.x` and `v2.x` respectively) is that they are now legacy, and new development doesn't target them by default anymore. v3 will get its own branch when v4 becomes enough of a thing to be the default branch.
