### ISSUE TITLE
SelfTest fails to compile when using MinGW

### ISSUE THREAD

**Issue by Swat-SomeBug** [catchorg/Catch2#2447]
**Describe the bug**
Error when compiling `UsageTests/Misc.tests.cpp:517:5` with MinGW
```
error: expected 'catch' before '__except'
  517 |     __except (1)
```

**Expected behavior**
Compilation with error.

**Reproduction steps**
Steps to reproduce the bug.
Using MinGW (tested on Fedora) run the following command inside the `build` directory
```
cmake .. -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ -DCMAKE_BUILD_TYPE=Debug -DCATCH_DEVELOPMENT_BUILD=ON
cmake --build . --target SelfTest
```

**Platform information:**

 - OS: **Fedora 36**
 - Compiler+version: **x86_64-w64-mingw32-g++ (GCC) 11.2.1 20211019 (Fedora MinGW 11.2.1-5.fc36)**
 - Catch version: **v3.0.1**

**Additional context**
On first reading the function `throw_and_catch()` defined in `tests/SelfTest/UsageTests/Misc.tests.cpp` is used to test SEH on windows. The section is enabled using `CATCH_PLATFORM_WINDOWS` which includes MinGW. Maybe disable this section for MinGW?

**Comment by horenmar** [comment]
Thanks for the report.
