### ISSUE TITLE
Conan Package missing Catch.cmake

### ISSUE THREAD

**Issue by mjohnsonwy** [catchorg/Catch2#2455]
**Describe the bug**

The Conan package for version 3.0.1 seems to no longer include the `Catch.cmake` and `CatchAddTests.cmake` files, so the [CMake integration](https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md#automatic-test-registration) no longer works like it did in the 2.X versions of the package.

**Reproduction steps**

`conanfile.txt`:
```
[requires]
catch2/3.0.1

[generators]
cmake_find_package
```

`CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.5)

project(foo LANGUAGES CXX VERSION 0.0.1)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}")

find_package(Catch2 REQUIRED)

include(CTest)
include(Catch) # does not work
```

Build commands:
```sh
conan install . --build=missing
cmake .
```

**Comment by gegles** [comment]
Yes, this is an issue for us too and seemingly the only blocker for us to move to using the official Conan package for Catch2 v3.x.

**Comment by mjohnsonwy** [comment]
Looks like [this](https://github.com/catchorg/Catch2/blob/20d413b8b6803c6d456874935d7014fe684e9426/conanfile.py#L30) might be the line that missing from the v3.0 Conan recipe?
