### ISSUE TITLE
5 tests failed on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [catchorg/Catch2#2458]
**Describe the bug**
```
The following tests FAILED:
	 27 - FilteredSection::GeneratorsDontCauseInfiniteLoop-2 (Failed)
	 28 - ApprovalTests (Failed)
	 42 - Benchmarking::SkipBenchmarkMacros (Failed)
	 50 - Outputs::DashAsOutLocationSendsOutputToStdout (Failed)
	 51 - Reporters::DashAsLocationInReporterSpecSendsOutputToStdout (Failed)
```
**Platform information:**
 - OS: FreeBSD 13.1
 - Compiler+version: clang-13
 - Catch version: 3.0.1

**Additional context**
[Detailed test log.](https://people.freebsd.org/~yuri/catch-3-tests.txt)

**Comment by horenmar** [comment]
This is down to #2449, but tests that exactly check the output should probably disable colours explicitly instead 🤔 .
