### ISSUE TITLE
[Documentation] "Test cases and sections" page refers to non-existent file path

### ISSUE THREAD

**Issue by jefgen** [catchorg/Catch2#2471]
**Describe the bug**
The documentation page on "Test cases and sections" here https://github.com/catchorg/Catch2/blob/devel/docs/test-cases-and-sections.md#special-tags says this about the Benchmark tag:

> `[!benchmark]` - this test case is actually a benchmark. This is an experimental feature, and currently has no documentation. If you want to try it out, look at `projects/SelfTest/Benchmark.tests.cpp` for details.

However, there is no such file path as `projects/SelfTest/Benchmark.tests.cpp` in the repo.

Maybe it should say https://github.com/catchorg/Catch2/blob/devel/tests/SelfTest/UsageTests/Benchmark.tests.cpp instead? (I'm not sure...)

Also, the document seems to imply that benchmarks have no documentation ("This is an experimental feature, and currently has no documentation."). But there is a whole page on Benchmarks here: 
https://github.com/catchorg/Catch2/blob/devel/docs/benchmarks.md

**Expected behavior**
File path in the docs exists.

**Reproduction steps**
- Visit the documentation page. :)

**Platform information:**
- N/A

**Comment by horenmar** [comment]
Yeah, it should point to the same file but under `tests/`. We've moved all testing related stuff there and apparently didn't update all links.

**Comment by jefgen** [comment]
Thanks for fixing this! :)
