### ISSUE TITLE
Add container matchers for `<algorithm>`-compatible types

### ISSUE THREAD

**Issue by famastefano** [catchorg/Catch2#2473]
**Description**
It would be nice to extend the container's matchers to any collection that provide an STL-like interface with begin/end.

My example here uses Qt's types as that's my usecase _now_. But for personal projects I use my own collections.

It would be nice of have the matchers like this:
```cpp
// Inside a SECTION
...
using namespace Catch::Matchers;
QVector<QString> expected{ "A", "B", "C" };
QVector<QString> data = someFunction();
REQUIRE_THAT(data, SizeIs(expected.size()) && Equals(expected));
```

**Comment by Vi1i** [comment]
This would be nice, especially with the constrained versions.
@nandanvasudevan gave a simple work around in #2531.

@famastefano, if you are still looking/wondering, commit https://github.com/catchorg/Catch2/commit/efca9a0f1826885c1574ed44fc37c8d82ded4546 introduces algorithm into the dev branch.
Have not tested/used the header yet, need to get our packages updated for my team first.

**Comment by Vi1i** [comment]
It is on https://github.com/catchorg/Catch2/releases/tag/v3.3.2

**Comment by Vi1i** [comment]
@horenmar Not sure if you care to much, there are two issues here that can be cleaned up after release v3.3.2.

**Comment by horenmar** [comment]
@Vi1i Thanks
