### ISSUE TITLE
nvcc compile error

### ISSUE THREAD

**Issue by nielskm** [catchorg/Catch2#2476]
**Describe the bug**
The `const` version of `Catch::Benchmark::Detail::ObjectStorage::stored_object` does not compile with nvcc (invalid type cast). The problem is solved by first casting to `const void*` and then to `void*` using `const_cast`.

I will make a PR ASAP.

**Comment by horenmar** [comment]
Which nvcc version is that?

**Comment by nielskm** [comment]
I tested it with CUDA 11.7 (compiler version 11.7.64).

**Comment by jbadwaik** [comment]
Could you please post the complete error? I'm a little confused at the situation.

`nvcc` is a device compiler, it offloads the host side compilation to the underlying host compiler (which is most probably gcc). And since Catch does not have any `__device__` annotations, the error should actually come from the underlying host GCC compiler. Hence, my curiousity.

**Comment by nielskm** [comment]
I understand completely, and I agree that the error should come from the host compiler.

I get the following error:
`/path/to/catch2/benchmark/catch_constructor.hpp(62): error: invalid type conversion`
When compiling the attached example with version 11.7 of the CUDA toolkit.
[catch2_nvcc_error.tar.gz](https://github.com/catchorg/Catch2/files/9044572/catch2_nvcc_error.tar.gz)

**Comment by nielskm** [comment]
By the way, I am testing this on Ubuntu 22.04 where the default GCC version is 11.2. I suppose that is the one used by `nvcc`.

**Comment by jbadwaik** [comment]
Thank you. Yes. You are correct. I can reproduce this.
```cpp
T const& stored_object() const {
    return *static_cast<T const*>(static_cast<void const*>(data));
}
```

I suggest the above fix instead, which does not need any const cast.

**Comment by jbadwaik** [comment]
As a workaround for now, I will suggest not using `catch/catch_all.hpp` if possible but instead using fine-grained headers `catch_test_macros.hpp` and `catch_approx.hpp`. That will remove the problem of using the `benchmark` headers.
