### ISSUE TITLE
Bazel support: read test specs from TESTBRIDGE_TEST_ONLY

### ISSUE THREAD

**Issue by jfirebaugh** [catchorg/Catch2#2490]
**Description**
Similarly to how Catch2 reads the `BAZEL_TEST` and `XML_OUTPUT_FILE` environment variables to support JUnit XML for Bazel, it should read [test specs](https://github.com/catchorg/Catch2/blob/devel/docs/command-line.md#specifying-which-tests-to-run) from the `TESTBRIDGE_TEST_ONLY` environment variable, which [will be set](https://bazel.build/reference/test-encyclopedia#initial-conditions) when running `bazel test` with a [`--test_filter`](https://bazel.build/reference/command-line-reference#flag--test_filter) argument.

**Comment by horenmar** [comment]
That's the worst env variable name I've ever seen.
