### ISSUE TITLE
Permit compiling on Win32 using Clang

### ISSUE THREAD

**Issue by mdavis199** [catchorg/Catch2#2492]
I am using clang version 14.0.6 on Windows.  The compiler options `file-prefix-map` is invalid for this platform.

If you could just surround the following function with `if(NOT WIN32)` ... `endif()`, it would be fantastic.

https://github.com/catchorg/Catch2/blob/997a7d4165b3939347f1a95f9311a3e3c066ee0b/CMake/CatchMiscFunctions.cmake#L112-L120

**Comment by horenmar** [comment]
#2517
