### ISSUE TITLE
Add a TAG_AUTODISCOVERY option to catch_discover_tests

### ISSUE THREAD

**Issue by reddwarf69** [catchorg/Catch2#2494]
catch_discover_tests is modelled after CMake's gtest_discover_tests. I don't think Google Test supports tags? That may be why it doesn't have a TAG_AUTODISCOVERY option. But such an option would be useful for catch_discover_tests.

Currently, there is a need to translate Catch "tags" into CTest "labels", and the process is very manual. When there are multiple tags the process gets impossibly complex.
Let's say you have two tags: TAG_A and TAG_B. To allow CTest to filter according to them you would need to do something like

```
catch_discover_tests(my_test
    TEST_SPEC ~[TAG_A]~[TAG_B]
)
catch_discover_tests(my_test
    TEST_SPEC [TAG_A][TAG_B]
    PROPERTIES LABELS TAG_A;TAG_B
)
catch_discover_tests(my_test
    TEST_SPEC [TAG_A]
    PROPERTIES LABELS TAG_A
)
catch_discover_tests(my_test
    TEST_SPEC [TAG_B]
    PROPERTIES LABELS TAG_B
)
```
(I'm not even sure the case for tests tagged with both TAG_A and TAG_B is correct).
Add more tags and the complexity increases.

Ideally, catch_discover_tests would have a TAG_AUTODISCOVERY option that would make it automatically add a CTest label for each tag a test has in a single catch_discover_tests call.

**Comment by david-fong** [comment]
Is this discussion already covered by / would this discussion be better moved to #1590?

**Comment by reddwarf69** [comment]
Yeah, it's duplicated.
