### ISSUE TITLE
Allow including untagged tests with other tag filters

### ISSUE THREAD

**Issue by itsfrank** [catchorg/Catch2#2498]
### Description
I believe it is currently not possible to run untagged tests at the same time as some hidden tags.

Say I have tests written like this:
```c++
TEST_CASE("Foo") { ... }
TEST_CASE("Bar") { ... }
TEST_CASE("Baz", [.optional]) { ... }
TEST_CASE("Qux", [.different-optional]) { ... }
```

I would like to be able to invoke my test exe such that I can run a combination of untagged tests and hidden tests at the same time.

#### 1. Leverage the empty tag `[]` 

Currently, running `./myTests []` is the same as running `./myTests`, however the empty tag doesn't behave as expected when combined with `,`.

E.g. current behavior on the file above:
1. `./myTests []` will run `Foo` and `Bar`
2. `./myTests [],[.optional]` will only run `Baz`
3. `./myTests [],[.optional],[.different-optional]` will only run `Baz` and `Qux`

Intuitively, I would expect that since I'm using the `,` separator, all the tests ran in 1 would have been included in 2 and 3.

#### 2. Give untagged tests some new default tag

This unfortunately runs the risk of colliding with existing user tags, e.g. using `[default]` for this is probably no acceptable. But if for some reason, solution 1. above is not feasible, maybe we can find some unique enough default tag pattern such that the impact to existing users will be minimal.

#### 3. Add a new cli option
This is least likely to disrupt any existing workflows, but also not really consistent with the current cli as no other options impact the filter behavior.

Something like `./myTests [.optional] --include-untagged`

**Comment by itsfrank** [comment]
I see here https://github.com/catchorg/Catch2/issues/2367#issuecomment-1046310279 what we are currently unhappy with the behavior of the empty tag. Would it make sense to define the empty tag as explicitly selecting tests that have no tags?

This would mean that any **and** combination of the empty tag would always match 0 tests:

e.g. `./myTests [][foo]` would always match 0 tests.

This still leaves the question of what to do when a test is defined with the empty tag explicitly: `TEST_CASE("Foo", "[]")` which seems like is currently not an error.

**Comment by itsfrank** [comment]
Put up a draft PR implementing option 1: https://github.com/catchorg/Catch2/pull/2499

It's a pretty small-footprint change and passes all tests; I left it as draft since we have not yet had the discussion on whether or not giving the empty tag explicit behavior as a filter is the right way to go.

**Comment by horenmar** [comment]
Why do you want to run all untagged tests at the same time as hidden tests? The simpler example in the PR is easy enough to do, `./tests '*'` will run everything including hidden tests, but I don't understand the motivation behind making `./tests [][optional]` run "Foo", "Bar", "Baz".

**Comment by horenmar** [comment]
To make myself more clear, I don't understand why you have a situation where you have tests without tags (so they aren't meant to be grouped), but have other tests with tags, and the no-tags group is meaningful enough, that you need to be able to use it with positive group selection.

**Comment by itsfrank** [comment]
Well when running catch we also implicitly have 2 sets of tests:
1. The set of tests that run with no filter
2. The set of tests that are ignored with no filter

For me, almost all of my tests have no tags, since I want them to run all of the time (tests that are short and fully deterministic).

Then I have some tests that I want to exclude form the "default" run. One reason is that some of my tests send real network requests, I tag those with `[.network]`. I don't want those to run all of the time, only occasionally.

I may not be using the tag system exactly as you envision, but really what I want is to be able to tell catch "run every test you would normally run without a filter, but also add these tests that are hidden by default (e.g. `[.network]`)."

With my current setup I would be able to achieve that with `[],[.network]`. If `[]` matched untagged tests.

One reason this would be nice, is say: For PR gated checks, I only want to run the default set of tests, but as a pre-deployment smoke-test I would like to run all my default tests AND my network test. This is currently achievable by running catch twice, but that's a bit annoying and gets more complex as your number of hidden tags increases.

My current fix has been to add the `["base"]` tag to all of my non-hidden tests. This way I can get the behavior I want above with `./tests [base],[.network]`, but while doing that it felt like there was something missing about untagged tests. 

They all share a common characteristic in their tag field (absence of one), it should be possible to select for that characteristic. So that led to my PR linked above, since the empty tag is forbidden to be set explicitly, it felt natural that the empty tag filter would match untagged tests.

Note that it doesn't actually solve my full problem since `[]` will lead to non-hidden tests with tags to be excluded, but it did make the tag filter system feel more complete to me.

To truly solve my issue, we would need some mechanism to tell catch to include all non-hidden tests. One way that would simultaneously make the filter system more expressive, could be via a negative filter (i.e. select all tests that **don't** have this tag). Let's pretend for a moment we use `negate`. Then I could do `./tests negate:[.],[.optional]`. And that would select all my non-hidden tests plus the hidden groups I explicitly want to allow.

So there really are 2 requests/questions in my reply here:
1. Can we add a way to select untagged tests
2. Can we add a way to select all non-hidden tests

The PR I made only addresses 1. I'd love to eventually see a solution to 2. as well

**Comment by horenmar** [comment]
For your use case, all non-hidden tests is just `~[.]`. If you want to run "everything run by default, and also everything under `[network]` tag", then that's `~[.],[network]`.

For the "select untagged tests" case, I am still not convinced that treating untagged tests as a tag group makes sense.

**Comment by itsfrank** [comment]
Oh of course! `~[.]` does exactly what I need! Not sure how I came up with all my "solutions" above without realizing that... sorry!

As for the empty tag filter, I personally don't need it anymore; in my mind it still makes sense that it should select untagged tests. But, as you point out, I can't come up with a reasonable use-case for selecting untagged tests anymore, so there's no need to add complexity until a real use-case exists; if one does come up, we know that adding that filter would be pretty simple.

It might be worth considering adding a warning to the cli that the `[]` filter does nothing; right now calling `./tests []` is identical to `./tests`. I know when I tried it it led me to believe that `[]` was doing something. It took me a few more runs tinkering with `./tests [],[.network]` to figure out it was being ignored.

I'll close both this issue and my PR; thank you for helping me with this!

**Comment by horenmar** [comment]
`./tests []` doing nothing is a bug, but the test spec parsing code is gnarly and I am putting off rewriting it until I really have to. The issue with making it warn is that first I would have to fix up the code, and at that point I can make it error out, the way it is supposed to 😃
