### ISSUE TITLE
Versioning on .so files

### ISSUE THREAD

**Issue by jonathanspw** [catchorg/Catch2#2500]
**Description**
Can you please add versioning to `.so` files?  This is required for OS packaging (in this case Fedora/EPEL).

Ex output from rpmlint:

```
catch2.x86_64: E: invalid-soname /usr/lib64/libCatch2Main.so libCatch2Main.so
```

**Additional context**
If this can be straightened out then Catch2 will be packaged in Fedora and EPEL repositories :)

**Comment by horenmar** [comment]
#2516
