### ISSUE TITLE
Contradiction in license: All rights reserved vs. Boost Software License

### ISSUE THREAD

**Issue by jonasstein** [catchorg/Catch2#2506]
**Describe the bug**
The header of the .hpp file shows
"All rights reserved." and "Boost Software License" which is a contradiction as far I know.

```
/*
 *  Catch v2.13.9
 *  Generated: 2022-04-12 22:37:23.260201
 *  ----------------------------------------------------------
 *  This file has been merged from multiple headers. Please don't edit it directly
 *  Copyright (c) 2022 Two Blue Cubes Ltd. All rights reserved.
 *
 *  Distributed under the Boost Software License, Version 1.0. (See accompanying
 *  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
 */

```
It would be great to have a machine and human readable [SPDX standard header](https://spdx.dev/). 
So it would be easier to embed the file in projects following the SPDX standard or using the [reuse tool](https://reuse.software/).

**Comment by horenmar** [comment]
v3 should not have this issue, and includes a SPDX header for BSL. I do not plan to go back and make the changes for v2.
