### ISSUE TITLE
Build Error on Cygwin

### ISSUE THREAD

**Issue by rkaminsk** [catchorg/Catch2#2529]
**Describe the bug**

I get the following error using gcc 11.3.0 on cygwin:
```
/cygdrive/c/projects/clingo/third_party/catch/src/catch2/../catch2/catch_tostring.hpp:214:33: error: there are no arguments to 'strnlen' that depend on a template parameter, so a declaration of 'strnlen' must be available [-fpermissive]
  214 |                 StringRef( str, strnlen( str, SZ ) ) );
```

What about using `strnlen_s` instead? The only problem I see is that additional macros would have to be defined but since the templates are fully instantiated, the required code could be moved to the source file.

There might also be another header providing a `strnlen`. I could dig a little deeper if help is required.

**Platform information:**

 - OS: **Windows + Cygwin**
 - Compiler+version: **GCC v11.3.0**
 - Catch version: **v3.1.0**

**Comment by rkaminsk** [comment]
I just saw that this has already been reported in #2511.

**Comment by rkaminsk** [comment]
Just a  simple workaround that could easily be extended to other platforms:
```c++
inline std::size_t catch_strnlen(const char *str, std::size_t n)
{
#ifdef __CYGWIN__
    if (str == nullptr || n == 0) {
        return 0;
    }

    std::size_t len = 0;
    while (len < n && str[len] != '\0') {
        ++len;
    }

    return len;
#else
    return strnlen(str, n);
#endif
}
```

**Comment by dimztimz** [comment]
There is a better solution with `memchr()` or with its C++ equivalent `std::char_traits::find()`.

**Comment by rkaminsk** [comment]
So then this can be written portably in C++11 using
```c++
inline std::size_t catch_strnlen(const char *str, std::size_t n)
{
    auto ret = std::memchr(str, '\0', n);
    if (ret != nullptr) {
        return ret - str;
    }
    return n;
}
```
without resorting to macros.

**Comment by neheb** [comment]
you sure it's not hidden behind _GNU_SOURCE?

**Comment by rkaminsk** [comment]
> you sure it's not hidden behind _GNU_SOURCE?

It is part of the strings library: <https://en.cppreference.com/w/cpp/string/byte/memchr>.
