### ISSUE TITLE
Unclear how to compare generic ranges against equalitiy

### ISSUE THREAD

**Issue by Viatorus** [catchorg/Catch2#2531]
By reading the docs as linked here:

https://github.com/catchorg/Catch2/blob/devel/docs/matchers.md#generic-range-matchers

I don't get what the required include is or the API to compare two generic ranges.

I would like to compare std::span's against equality, like this:

```cpp
CHECK_THAT(std::span<char>{}, Catch::Matchers::Equals(std::span<char>{}));
```

But this doesn't compile. Isn't this supported or do I use the wrong syntax?

**Comment by nandanvasudevan** [comment]
Maybe something like this could be implemented?
Its not perfect, but here is a rough attempt.

https://nandanv.godbolt.org/z/sova6bMoW

**Comment by nandanvasudevan** [comment]
Isn't this very similar to #2473?

**Comment by Vi1i** [comment]
> Maybe something like this could be implemented? Its not perfect, but here is a rough attempt.
> 
> https://nandanv.godbolt.org/z/sova6bMoW

This works in the current release still, thank you for the easy work around.

**Comment by Vi1i** [comment]
@Viatorus, if you are still looking/wondering, commit https://github.com/catchorg/Catch2/commit/efca9a0f1826885c1574ed44fc37c8d82ded4546 introduces algorithm into the dev branch.

**Comment by Viatorus** [comment]
@Vi1i Great, thank you very much. :)
