### ISSUE TITLE
Ability to get current seed value

### ISSUE THREAD

**Issue by KivApple** [catchorg/Catch2#2535]
**Description**
I would like to have an ability to obtain current random seed value to use in my own random numbers generation during the test. For the moment I don't see such possibility in the documentation. I see this value in `Config::rngSeed()`, but I don't understand how to get the current configuration while using default `main`.

**Comment by horenmar** [comment]
With sufficiently new version: https://github.com/catchorg/Catch2/commit/dc001fa935d71b4b77f263fce405c9dbdfcbfe28

With older ones, copy paste the impl of `getSeed` into your own project.
