### ISSUE TITLE
Documentation off-by-one error

### ISSUE THREAD

**Issue by SirNate0** [catchorg/Catch2#2547]
The documentation specifies that:

> It is an error to specify a shard index greater than the number of shards.

However, the section it is in describes the shard index as starting at 0, so shouldn't this be greater than or equal to the number of shards?

https://github.com/catchorg/Catch2/blob/devel/docs/command-line.md#test-sharding

**Comment by horenmar** [comment]
Hmmm, I guess the answer is yes. To be honest, it did not occur to me that someone could read it differently.
