### ISSUE TITLE
Remove bad tag

### ISSUE THREAD

**Issue by xkszltl** [catchorg/Catch2#2548]
**Describe the bug**

<img width="416" alt="image" src="https://user-images.githubusercontent.com/5203025/195166963-e999c6c6-2a73-40fb-bb6f-048a3fedcf0c.png">

There's a weird tag `v.1.7.0` in repo, probably a typo, and `v1.7.0` exists as well.
We initially found this when building on Ubuntu 22.04 and trigger that `SIGSTKSZ` bug, and realized we're on a very old version because our version script thing `v.1.7.0 > v3.1.0`.

Please consider removing this from repo.

**Comment by horenmar** [comment]
I quickly searched for links to the bad tag, I haven't found any that are reasonably current. Deleted.

**Comment by xkszltl** [comment]
BTW people who have write permission to repo may push that tag again, so recommend to do a `git fetch --tags --prune` locally as well.
