### ISSUE TITLE
v3.1.1 not part of repo?

### ISSUE THREAD

**Issue by Swat-SomeBug** [catchorg/Catch2#2552]
Hi,
I’m getting a strange message from GitHub that the tag `v3.1.1` may not be a part of this repo.
Indeed I cannot checkout locally using the tag and `git tag` doesn’t show `v3.1.1`.
Any idea what’s happening?
![0A83A0D5-0263-4C91-B4D5-0A8090D9C35C](https://user-images.githubusercontent.com/83545272/196621346-7ae30689-fdf5-4427-b2f8-1cf2b210fb74.png)

**Comment by horenmar** [comment]
Huh, that's weird, but I can confirm the issue. Interestingly I don't see a difference between the `v3.1.1` commit on `devel` branch (5df88da16e276f853cc0c45f4b570419be77dd43) and `v3.1.1` tagged commit (35dc247ade4be79c4362533d222d6aa660df4f01).

I am going to retag the commit later today.

**Comment by horenmar** [comment]
Should be fixed now. Thanks for bringing this to my attention.
