### ISSUE TITLE
Add support for user callout before / after each test

### ISSUE THREAD

**Issue by Alan-Jowett** [catchorg/Catch2#2556]
**Description**
An option to call a user-defined method before and after each test. 

**Additional context**
I am building a framework to perform systematic low-memory testing and I need to set a thread_local variable to enable it during each test.

Systematic low-memory testing:
The goal is verify that the program under tests handles low memory conditions by failing each possible allocation.

For now, I can add a line to each test case to set/clear the thread_local, but this is fragile.

**Comment by horenmar** [comment]
Do you have multiple threads in the `TEST_CASE`? Because if yes, multiple threads interacting with Catch2 are not currently supported and I don't have plans for the close future to change that. If not, then you want Event Listeners.

**Comment by Alan-Jowett** [comment]
That looks perfect thanks. I will close out this issue as the feature already exists.
