### ISSUE TITLE
TEMPLATE_TEST_CASE gives undefined reference linker error

### ISSUE THREAD

**Issue by dariusarnold** [catchorg/Catch2#2558]
**Describe the bug**
I am trying to trick TEMPLATE_TEST_CASE into parametrizing non type template parameters as types which hold a value. My intent was to test a function templated on a non type for which GENERATE can not be used since the values produced by the generator are not constant expressions. I decided to store the values in a static member variable of a class. The whole approach is similar to [https://github.com/catchorg/Catch2/issues/1531](https://github.com/catchorg/Catch2/issues/1531).

**Expected behavior**
Since I can access the stored non type template parameter in line 13, I expected it to work the same in the CHECK-macro.

**Reproduction steps**
I have created a godbolt example which reproduces this error: [https://godbolt.org/z/shvGTf1T5](https://godbolt.org/z/shvGTf1T5)
Commenting in the CHECK-macro produces the following linker error:
```
/opt/compiler-explorer/gcc-10.3.0/lib/gcc/x86_64-linux-gnu/10.3.0/../../../../x86_64-linux-gnu/bin/ld: /tmp/example-146218.o: in function `BinaryExpr':
/opt/compiler-explorer/libs/catch2/v3.0.0-preview3/src/catch2/internal/catch_decomposer.hpp:78: undefined reference to `IntHolder<1>::x'
/opt/compiler-explorer/gcc-10.3.0/lib/gcc/x86_64-linux-gnu/10.3.0/../../../../x86_64-linux-gnu/bin/ld: /opt/compiler-explorer/libs/catch2/v3.0.0-preview3/src/catch2/internal/catch_decomposer.hpp:78: undefined reference to `IntHolder<2>::x'
/opt/compiler-explorer/gcc-10.3.0/lib/gcc/x86_64-linux-gnu/10.3.0/../../../../x86_64-linux-gnu/bin/ld: /opt/compiler-explorer/libs/catch2/v3.0.0-preview3/src/catch2/internal/catch_decomposer.hpp:78: undefined reference to `IntHolder<3>::x'
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Platform information:**
 - OS: Linux
 - Compiler+version: clang 15.0 and gcc 12.2
 - Catch version: 3.0.0-preview3

**Comment by horenmar** [comment]
[Works with newer versions of Catch2](https://godbolt.org/z/34sofKdhj), and in the old version [with ODR-usable definition for `x`](https://godbolt.org/z/W3svYx4ds).

The decomposition ODR uses both sides of the decomposed expression. The reason newer versions of Catch2 compile your code is that we added overload that does not ODR-use the expression, but only for types where `std::is_arithmetic<T>` is true.

**Comment by dariusarnold** [comment]
Thank you for the quick response and the explanation. Using an enum instead of the integer works for my use case.
