### ISSUE TITLE
Logo is hidden when using GitHub dark theme

### ISSUE THREAD

**Issue by tocic** [catchorg/Catch2#2573]
The logo is partially hidden when you look at it using the default dark theme.

"Dark default" vs "Light default" for the `README`:

![dark](https://user-images.githubusercontent.com/22129543/203033611-ca04f820-0dd4-4d89-90b5-6715af546f08.png)

![light](https://user-images.githubusercontent.com/22129543/203033816-1178381b-df23-49e3-bca9-5dd89374f079.png)

This is caused by the fact that the corresponding PNG image has a transparent background. Consider changing it to white.

Transparent vs white PNG background (make sure [to set the dark mode](https://github.com/settings/appearance) to see the difference):

![catch2-logo-small](https://user-images.githubusercontent.com/22129543/203035125-0a24f8b7-dd9b-41ca-a013-3cc592c47eb9.png)

![catch2-logo-small-white-background](https://user-images.githubusercontent.com/22129543/203035177-20035ff7-4cdf-44b1-8097-ae6ea2e9308e.png)

Inspired by [this](https://youtu.be/q7Gv4J3FyYE?t=249).

**Comment by horenmar** [comment]
You are supposed to use the white mode 😛
