### ISSUE TITLE
-Wsign-conversion error in catch hpp

### ISSUE THREAD

**Issue by omnibench** [catchorg/Catch2#2583]
Catch2 is causing my build to fail with -Wsign-conversion on:
```
[build] build/_deps/catch2-src/src/catch2/..\catch2/internal/catch_clara.hpp:126:59: error: implicit conversion changes signedness: 'std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<std::basic_string<char>>>>::difference_type' (aka 'long long') to 'unsigned long long' [-Werror,-Wsign-conversion]
[build]                     return m_tokenBuffer.size() + ( itEnd - it );
[build]                            
```

**Comment by ChrisThrasher** [comment]
I tried fixing the sign conversion warnings in Catch2 and it was not easy. You're better off marking the Catch2 include directories as `SYSTEM` include directories (if you're using CMake) to disable warnings in Catch headers.

**Comment by topazus** [comment]
```cmake
add_compile_options(-Wno-error=conversion)
add_compile_options(-Wno-error=sign-conversion)
```
Does this method is recommended?

**Comment by ChrisThrasher** [comment]
That will get the job done but what I said before is the recommended answer. You should not be applying extra compiler warnings to Catch2 itself. All compilers have ways of saying that headers in a given directory belong to other projects and thus don't emit warnings about them. The CMake abstraction for this is something called "`SYSTEM` include directories".

**Comment by topazus** [comment]
Thanks. After digging into this, I got your points. I also found your efforts of suppressing Catch2 warnings in SFML project.

https://github.com/SFML/SFML/blob/e45628e2ebc5843baa3739781276fa85a54d4653/test/CMakeLists.txt#L18-L22

**Comment by louwers** [comment]
The CMake guide should probably be updated to reflect that this is needed: https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md

I tried

```
FetchContent_Declare(
  Catch2
  GIT_REPOSITORY https://github.com/catchorg/Catch2.git
  GIT_TAG        v3.7.1
  SYSTEM
)
```

but I still get the warning.

For me the warning comes from a source file:

```
/Users/bart/src/geometry.hpp/build/_deps/catch2-src/src/catch2/reporters/catch_reporter_console.cpp:354:44: error: implicit conversion changes signedness: 'int' to 'size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
  354 |         auto colInfo = tp.m_columnInfos[tp.m_currentColumn];
      |                        ~~               ~~~^~~~~~~~~~~~~~~
```

**Comment by ChrisThrasher** [comment]
> For me the warning comes from a source file:

This is because you told CMake to build Catch2 with extra warnings enabled. I'm guessing you have an `add_compile_options` line above where you call `FetchContent_Declare` which is adding compiler warnings. This isn't something Catch2 can solve on your behalf. You have to use an alternative means of applying compiler warnings. I'd recommend using `target_compile_options` to apply warnings to each individual target in your project rather than setting them globally.

**Comment by louwers** [comment]
Oops, yep, I was setting global warnings indeed (not `add_compile_options`, but `CMAKE_CXX_FLAGS`). Thank you.
