### ISSUE TITLE
README Bug: Microbenchmark Example

### ISSUE THREAD

**Issue by JLospinoso** [catchorg/Catch2#2589]
**Describe the bug**
`README` contains several errors in the microbenchmark example.
1. Mismatch between `fibonacci` and `Fibonacci`. Will not compile.
2. All three assertions fail.

Here's an update:

```
#include <catch2/catch_test_macros.hpp>
#include <catch2/benchmark/catch_benchmark.hpp>

#include <cstdint>

uint64_t fibonacci(uint64_t number) {
  return number < 2 ? 1 : fibonacci(number - 1) + fibonacci(number - 2);
}

TEST_CASE("Benchmark fibonacci") {
  REQUIRE(fibonacci(5) == 8);

  REQUIRE(fibonacci(20) == 10'946);
  BENCHMARK("fibonacci 20") {
    return fibonacci(20);
  };

  REQUIRE(fibonacci(25) == 121'393);
  BENCHMARK("fibonacci 25") {
    return fibonacci(25);
  };
}
```

**Expected behavior**
For the program to compile and give passing tests when run.

**Reproduction steps**
Try to compile the example:

```
#include <catch2/catch_test_macros.hpp>
#include <catch2/benchmark/catch_benchmark.hpp>

#include <cstdint>

uint64_t fibonacci(uint64_t number) {
    return number < 2 ? 1 : fibonacci(number - 1) + fibonacci(number - 2);
}

TEST_CASE("Benchmark Fibonacci", "[!benchmark]") {
    REQUIRE(Fibonacci(5) == 5);

    REQUIRE(Fibonacci(20) == 6'765);
    BENCHMARK("Fibonacci 20") {
        return Fibonacci(20);
    };

    REQUIRE(Fibonacci(25) == 75'025);
    BENCHMARK("Fibonacci 25") {
        return Fibonacci(25);
    };
}
```

**Platform information:**

 - OS: **Mac OSX**
 - Compiler+version: **arm64-apple-darwin22.1.0*
 - Catch version: **v3.2.0**

**Additional context**
None

**Comment by horenmar** [comment]
I fixed it at some point, but for the record: the values are correct, but the implementation had an off-by-one error causing it to return `fib(n + 1)` given `n` as the input.
