### ISSUE TITLE
undefined reference to (Catch2 v3)

### ISSUE THREAD

**Issue by yoowonsuk** [catchorg/Catch2#2590]
**Describe the bug**
There isn't Catch::AssertionHandler::AssertionHandler and etc

source
![image](https://user-images.githubusercontent.com/52575749/206334310-a841bbb7-c2df-4da4-a59f-e72dfd7c2afa.png)

error message
![image](https://user-images.githubusercontent.com/52575749/206334181-de725fdb-b37d-4101-9a9f-e2b65756f9be.png)

grep keyword
![image](https://user-images.githubusercontent.com/52575749/206336893-b384e26a-e56d-4cb5-8bb7-c429d6a7318a.png)

**Expected behavior**
**success in deploying binary and pass the test!!**

**Reproduction steps**
Steps to reproduce the bug.

1.  sudo cmake --build build/ --target install
2. g++ -std=c++14 -Wall test.cpp

**Platform information:**

 - OS: **Ubuntu**
 - Compiler+version: **G++ v5.4.0**
 - Catch version: **devel** If not available, I'd like to do with one of the v3 versions

**Additional context**

**Comment by horenmar** [comment]
You need to link against the compiled library.

You should be using either `pkg-config` or `cmake` to provide you with the right link command. If you cannot for some reason, you can link `libCatch2.a` (and `libCatch2d.a` for debug libs) yourself.

**Comment by yoowonsuk** [comment]
Thank you @horenmar 
I got to next step and it said "undefined reference to main".
I tried putting "#define CATCH_CONFIG_MAIN", never to fail.
![image](https://user-images.githubusercontent.com/52575749/206855369-44dc9518-647e-4aa8-9bbe-fcf8ece6aee6.png)



ONE additional Question
is it v3 that I'm attempting? otherwise is there an example for it?
I wanna experience both actually.

**Comment by horenmar** [comment]
Yes, you are working with v3. The `CATCH_CONFIG_MAIN` macro no longer exists, if you want the main from Catch2, link with `-lCatch2Main -lCatch2`. The second library provides only the main, so you have to link both (and in this order), because the main relies on symbols from `libCatch2`.

**Comment by yoowonsuk** [comment]
@horenmar It appears to settle that matter but no working so far.
sorry for much requests.
I added "-lCatch2Main" to the command
![image](https://user-images.githubusercontent.com/52575749/206935706-53f3f5d6-db11-43d3-92cf-26b5cefd401b.png)

Do you think I should take advantage of transition from v2 to v3?

**Comment by dheater** [comment]
I don't believe you need to link both. At least according to the cmake documentation [here](https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md).  You should have a custom `main` linked with `Catch2` **or** link with `Catch2Main` with no main (Catch2 provides the main), both not both.

**Comment by yoowonsuk** [comment]
@dheater oh you're right. I forgot both are different to use.
But I've tried the number of cases, it failed either.
![image](https://user-images.githubusercontent.com/52575749/207211742-b1837440-e140-471f-806b-b8c66a286789.png)

Do i have to include some of ".cmake" files in extras folder to root CMakeLists?
I could find some functions in catch_amalgamated.hpp which shows undefined reference

**Comment by horenmar** [comment]
Again, you have to link `Catch2Main` before `Catch2`. You linked it after, so it could not find the symbols from `libCatch2.a` it needs.

@dheater That is for CMake (or pkg-config). CMake allows for expressing dependencies between targets, so when the binary links to `Catch2WithMain` (notice the different spelling)` target, the dependency to `Catch2` is added automatically.

**Comment by yoowonsuk** [comment]
@horenmar it was so manifest as to be misunderstood xD
@dheater thank you for questioning me. it's been much helpful
