### ISSUE TITLE
Reference section should indicate which header files are needed

### ISSUE THREAD

**Issue by Bautastein** [catchorg/Catch2#2609]
**Description**
The migration guide for Catch2 v3 indicates that one should include files sparingly for improved compilation times, rather than using `catch_all.hpp`. However, the reference section does not always indicate which header files are needed for the documented features to work. For example, the entry on [generators](https://github.com/catchorg/Catch2/blob/devel/docs/generators.md#top) does not indicate which header files are needed. The examples will not compile without including extra files, in addition to `catch2/catch_test_macros.hpp` that is indicated in the README file and tutorial.

The feature would be appreciated for new users like me, so we can more easily get started, without having to browse the source tree to find the necessary header files.

**Additional context**
No extra context needed.

**Comment by Bautastein** [comment]
OK, I see this is a duplicate of [this issue](https://github.com/catchorg/Catch2/issues/2519), so I'm closing my own issue.

**Comment by horenmar** [comment]
I don't think anyone disagrees, but it is work that _someone_ needs to do. 🤷
