### ISSUE TITLE
Run `--help` on a catch test without constructing statics

### ISSUE THREAD

**Issue by knzivid** [catchorg/Catch2#2614]
I have a test that checks a static variable's properties.

```cpp
static Hardware hardware;

TEST_CASE("hardware is valid", "[hardware]")
{
    REQUIRE(hardware.isValid());
}
```

Unfortunately `Hardware` depends on custom hardware being available at runtime and we do not want to make this hardware available during the build step. Note that our build step runs unit tests excluding the `hardware` label. But `catch_discover_tests` adds a POST_BUILD hook that invokes this test anyway, requiring us to make the hardware available during the build. 

Are there any workarounds here other than to wrap `static Hardware hardware` as `static Hardware &hardware()` to delay construction until first use?

**Comment by horenmar** [comment]
Global statics are constructed before `main` is entered, thus before commandline is parsed and before Catch2 can get control over the control flow.

So yes, you need to turn this into a function level static.

**Comment by knzivid** [comment]
Thanks
