### ISSUE TITLE
Generator Constructor Exception causes a Null-Pointer-Dereference

### ISSUE THREAD

**Issue by BurningEnlightenment** [catchorg/Catch2#2615]
**Describe the bug**
If a constructor of a generator throws a `Catch::GeneratorException` to indicate initialization failure, the catch framework attempts to dereference a null pointer which causes the application to crash. This precludes running any test cases scheduled to run afterwards.

**Expected behavior**
The test application should not crash and run any remaining test cases.

**Reproduction steps / MCVE**
```cpp
#include <catch2/catch_test_macros.hpp>
#include <catch2/generators/catch_generator_exception.hpp>
#include <catch2/generators/catch_generators.hpp>
#include <catch2/generators/catch_generators_range.hpp>

class test_generator : public Catch::Generators::IGenerator<int>
{
public:
    explicit test_generator()
    {
        // removing the following line will cause the program to terminate gracefully.
        throw Catch::GeneratorException("failure to init");
    }

    [[nodiscard]] auto get() const -> int const & override
    {
        static constexpr int value = 1;
        return value;
    }

    [[nodiscard]] auto next() -> bool override
    {
        return false;
    }
};

auto make_test_generator() -> Catch::Generators::GeneratorWrapper<int>
{
    return {new test_generator()};
}

TEST_CASE("this will segfault")
{
    // this should fail the test case, but not abort the application
    auto sample = GENERATE(make_test_generator());
    // this assertion shouldn't trigger
    REQUIRE(sample == 0U);
}

TEST_CASE("this won't run")
{
    // this assertion should trigger and be reported
    REQUIRE(1U == 0U);
}
```
[MCVE on godbolt]

**Platform information:**

|OS|Compiler|Catch version|
|---|---|---|
|Win10|MSVC 14.34.31933|v3.1.1|
|compiler-explorer linux image|GCC 12.2|trunk/v3.2.1|

**Additional context**
None

[MCVE on godbolt]: https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:45,positionColumn:2,positionLineNumber:45,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:'%23include+%3Ccatch2/catch_test_macros.hpp%3E%0A%23include+%3Ccatch2/generators/catch_generator_exception.hpp%3E%0A%23include+%3Ccatch2/generators/catch_generators.hpp%3E%0A%23include+%3Ccatch2/generators/catch_generators_range.hpp%3E%0A%0Aclass+test_generator+:+public+Catch::Generators::IGenerator%3Cint%3E%0A%7B%0Apublic:%0A++++explicit+test_generator()%0A++++%7B%0A++++++++//+removing+the+following+line+will+cause+the+program+to%0A++++++++//+terminate+gracefully.%0A++++++++throw+Catch::GeneratorException(%22failure+to+init%22)%3B%0A++++%7D%0A%0A++++%5B%5Bnodiscard%5D%5D+auto+get()+const+-%3E+int+const+%26+override%0A++++%7B%0A++++++++static+constexpr+int+value+%3D+1%3B%0A++++++++return+value%3B%0A++++%7D%0A%0A++++%5B%5Bnodiscard%5D%5D+auto+next()+-%3E+bool+override%0A++++%7B%0A++++++++return+false%3B%0A++++%7D%0A%7D%3B%0A%0Aauto+make_test_generator()+-%3E+Catch::Generators::GeneratorWrapper%3Cint%3E%0A%7B%0A++++return+%7Bnew+test_generator()%7D%3B%0A%7D%0A%0ATEST_CASE(%22this+will+segfault%22)%0A%7B%0A++++//+this+should+fail+the+test+case,+but+not+abort+the+application%0A++++auto+sample+%3D+GENERATE(make_test_generator())%3B%0A++++//+this+assertion+shouldn!'t+trigger%0A++++REQUIRE(sample+%3D%3D+0U)%3B%0A%7D%0A%0ATEST_CASE(%22this+won!'t+run%22)%0A%7B%0A++++//+this+assertion+should+trigger+and+be+reported%0A++++REQUIRE(1U+%3D%3D+0U)%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g122,deviceViewOpen:'1',filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:catch2,ver:trunk)),options:'-std%3Dc%2B%2B20',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+12.2+(Editor+%231)',t:'0'),(h:executor,i:(argsPanelShown:'1',compilationPanelShown:'0',compiler:g122,compilerOutShown:'0',execArgs:'',execStdin:'',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:catch2,ver:trunk)),options:'-std%3Dc%2B%2B20+-lCatch2Maind',source:1,stdinPanelShown:'1',tree:'1',wrap:'1'),l:'5',n:'0',o:'Executor+x86-64+gcc+12.2+(C%2B%2B,+Editor+%231)',t:'0')),k:50,l:'4',m:100,n:'0',o:'',s:1,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

**Comment by horenmar** [comment]
Okay, I see the issue, I'll have to think a bit about the best way to fix this. The code as is assumes that a generator tracker will always have a generator to, well, track. However, when the generator throws an exception from the constructor, the tracker will keep existing, but won't have a generator. Then, when the test case is exited, the tracker tries to check with the generator to see if it has any more values (and so the test case should be ran again), or not.

I can probably hot-fix this by having the tracker check whether it does have a generator before trying to use it, but I am not convinced that a tracker should exist empty. The problem is that a significant refactoring would be needed to stop trackers from existing if constructing the generator fails.

**Comment by BurningEnlightenment** [comment]
I agree that an empty generator tracker doesn't sound like it should exist. I don't think a hotfix is necessary as generator constructors are usually reliable which makes this a rare edge case.
