### ISSUE TITLE
TEMPLATE_TEST_CASE with non-type argument

### ISSUE THREAD

**Issue by igtrnt** [catchorg/Catch2#2616]
**Description**
As C++ allows templates by non-type, e.g. `template<int N> class C`, it would be nice for TEMPLATE_TEST_CASE to support this (or to introduce another macro that supports non-type templates).

**Comment by horenmar** [comment]
[From the very same doc page that shows `TEMPLATE_TEST_CASE`](https://github.com/catchorg/Catch2/blob/devel/docs/test-cases-and-sections.md#signature-based-parametrised-test-cases)
