### ISSUE TITLE
Catch2 v3 and Visual C++ 2015 Update 3

### ISSUE THREAD

**Issue by trueqbit** [catchorg/Catch2#2624]
Visual C++ Update 3 reports itself as being capable of C++14 but is still lacking
- Extended constexpr
- Aggregates with default member initializers

It would be great to keep VC++ 2015 Update 3 for a while longer, as long as Microsoft still supports it (extended support until the end of 2025) and/or vcpkg lists it as a minimum requirement.

It is usually not difficult to keep a few things in mind, and it is good practice to test certain C++ functions, which you do anyway.

A concrete use case is [sqlite_orm](https://github.com/fnc12/sqlite_orm) (v1.8), which still runs appveyor unit tests using Visual C++ 2015 Update 3 as the minimal C++14 base compiler.

When updating the test dependency of sqlite_orm to Catch2 v3, I encountered the following compile error:

> catch2/internal/catch_stringref.hpp(58): error C3249: illegal statement or sub-expression for 'constexpr' function
> catch2/internal/catch_stringref.hpp(76): error C3249: illegal statement or sub-expression for 'constexpr' function

This is because pre-C++14 contexpr function's body can only be a single return statement. Everything else gets rejected, specifically:
```c++
constexpr auto StringRef::operator[] ( size_type index ) const noexcept -> char {
    assert(index < m_size);
    return m_start[index];
}

constexpr StringRef StringRef::substr(size_type start, size_type length) const noexcept {
    if (start < m_size) {
        const auto shortened_size = m_size - start;
        return StringRef(m_start + start, (shortened_size < length) ? shortened_size : length);
    } else {
        return StringRef();
    }
}
```

**Comment by horenmar** [comment]
Sorry, but I am not interested in keeping VS 2015 compatibility.
