### ISSUE TITLE
What is the difference between CHECKED_IF and CHEC_NOFAIL

### ISSUE THREAD

**Issue by 0xfk0** [catchorg/Catch2#2633]
**Describe the bug**

**Expected behavior**

**Reproduction steps**
Steps to reproduce the bug.

**Platform information:**

 - OS: **Windows NT**
 - Compiler+version: **GCC v2.9.5**
 - Catch version: **v1.2.3**

**Additional context**

**Comment by ThePhD** [comment]
`CHECKED_IF` just allows the stringification / printing to wrap an existing expression and show the control flow of a test.

`CHECK_NOFAIL` will print output if it fails but will not actually fail the whole test.

As of latest, neither will ail the build, but `CHECKED_IF` provides flow control.

You can read about both, here: https://github.com/catchorg/Catch2/blob/devel/docs/other-macros.md
