### ISSUE TITLE
Missing std::launder() calls

### ISSUE THREAD

**Issue by marcmutz** [catchorg/Catch2#2638]
Catch2 and Catch3 contain `std::optional`-like code that uses a `char` array as storage for object created there with placement new. In C++17, this pattern may be undefined, because accessing the `T` through a cast pointer from `char[]` breaks strict aliasing rules.

Catch2's `Option` is not affected, since it stores the return value of placement new, circumventing the issue. But `ObjectStorage` has the issue.

I didn't look at Catch3 code, yet, but it seems the affected code is still present there, too.

**Comment by marcmutz** [comment]
My resident committee member says that the only remaining use-case for launder() is as a de-virtualization barrier. C++20 made types with const and reference members transparently replaceable, and the only compiler that was optimizing on this, IBM xlc++, non-conformant. Even then, xlc++ only applied the optimization for static-storage-duration objects. So I guess we can do without.

**Comment by horenmar** [comment]
Going by one of the PRs, this is an issue only for C++17 mode with IBM xlc++?

Yeah, I am going to say that if someone actually runs into this, they can make xlc-specific PR at that point. Thanks for the effort though.
