### ISSUE TITLE
BENCHMARK_ADVANCED doesn't allow arbitrary setup and teardown on each iteration?

### ISSUE THREAD

**Issue by VioletGiraffe** [catchorg/Catch2#2644]
Here's the benchmark that was randomly failing, and it took me quite a bit of time to understand why:
```
BENCHMARK_ADVANCED("Opening existing empty file for reading with fopen")(Catch::Benchmark::Chronometer meter) {
	FILE* f = nullptr;
	meter.measure([&] {
		f = ::fopen(filePath, "rb");
		if (!f)
			std::cout <<  ::strerror(errno) << std::endl;
	});
	REQUIRE(::fclose(f) == 0);
	f = nullptr;
};
```

As you can see, I want to benchmark just `fopen` without also measuring `fclose`. And it turned out that `fopen` was failing with "Too many open files", so obviously this code doesn't work as expected - `measure` is called multiple times, but `fclose` - only once.

Is there a way to do this with Catch2?

**Comment by horenmar** [comment]
I explained it in an earlier issue: https://github.com/catchorg/Catch2/issues/2510#issuecomment-1781752592

Seeing how this has come up multiple times, I am tagging this with a revisit + docs to remind myself to add more examples to the benchmarking docs.
