### ISSUE TITLE
Vector Equals Matcher uses `!=` for comparisons

### ISSUE THREAD

**Issue by js-nano** [catchorg/Catch2#2648]
The vector `Equals` matcher uses `!=` to compare elements:

https://github.com/catchorg/Catch2/blob/584973a485160bea0feb8764c28bb65d03b988ac/src/catch2/matchers/catch_matchers_vector.hpp#L91

I'd expect it to use `==` to compare elements (as implied by the Matcher's name 🙂)

Impacts are:
- Prior to C++20, an `operator!=` needs to be supplied for user types (in addition to `operator==`).
    - If you _are_ using C++20, the situation is happier as your compiler can rewrite `!=` to use `operator==` (provided your compiler supports [P1185R2](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1185r2.html))
- If you're a monster and your `operator==` and `operator!=` are not the inverse of each other, the "wrong" operator would unexpectedly be used (again, based on the Matcher's name).

---

NB - In addition, `!=` is used for `approx` matching here, though I don't think that would cause any of the issues noted above?

https://github.com/catchorg/Catch2/blob/584973a485160bea0feb8764c28bb65d03b988ac/src/catch2/matchers/catch_matchers_vector.hpp#L114

**Comment by horenmar** [comment]
I'll change this, but I have to say that in this case

> If you're a monster and your operator== and operator!= are not the inverse of each other

it is the user's fault and I don't care.

**Comment by js-nano** [comment]
Thanks for this!

As regards

> it is the user's fault and I don't care.

Yes, I agree completely!
