### ISSUE TITLE
catch_test_case_info.cpp: Assertion `inTag` failed

### ISSUE THREAD

**Issue by xvitaly** [catchorg/Catch2#2650]
**Describe the bug**
Catch2 fails when running spdlog tests in Debug configuration (check this PR https://github.com/gabime/spdlog/pull/2661). Release configuration works without issues.

Catch2 is included via `FetchContent`.

**Expected behavior**
Successful tests run.

**Reproduction steps**
```
git clone https://github.com/xvitaly/spdlog.git
git checkout catchv3
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Debug ..
cmake --build
ctest
```

**Platform information:**

 - OS: **Linux (tested on Ubuntu and Fedora)**
 - Compiler+version: **GCC 11, 12; Clang 10, 12**
 - Catch version: **v3.3.2**

**Additional context**
```
spdlog-utests: src/catch2/catch_test_case_info.cpp:147: Catch::TestCaseInfo::TestCaseInfo(Catch::StringRef, const Catch::NameAndTags&, const Catch::SourceLineInfo&): Assertion `inTag' failed.
```

**Comment by phforesteot** [comment]
Hi,
as a note I've got the same assert which was caused because in my test:
`TEST_CASE("lookup_apostrophes", "[ut][lookup]apo][itapo]")`
I was missing a '[' in the tags. But that is not very clear from the assert.
my2cents
