### ISSUE TITLE
vector matchers for other sequence types

### ISSUE THREAD

**Issue by timblechmann** [catchorg/Catch2#2652]
**Description**
`UnorderedEquals` etc are only supporting `std::vector`. i have a few use cases where i want to do similar checks with other sequence types (e.g. `boost::container`'s small/static vectors). it would be great if those could somehow be supported. i've ended up mixing in `UnorderedElementsAreArray` from gmock for such functionality for now ...

**Comment by horenmar** [comment]
Do you mean like the [generic range matchers](https://github.com/catchorg/Catch2/blob/devel/docs/matchers.md#generic-range-matchers)?

**Comment by timblechmann** [comment]
yes 😬

my bad, i was still on v3.2
