### ISSUE TITLE
Chunks of generated size compilation error

### ISSUE THREAD

**Issue by igtrnt** [catchorg/Catch2#2662]
While this code compiles and works as expected:
```
    int const n = 10;
    auto vec = GENERATE(take(1, chunk(n, random(0.0f, 10.0f))));
```
this code does not compile:
```
    int const n = GENERATE(10, 20);
    auto vec = GENERATE(take(1, chunk(n, random(0.0f, 10.0f))));
```
The error is in the second line:
`error: variable 'n' cannot be implicitly captured in a lambda with no capture-default specified`.

Is it a bug or expected compiler error?

How do I achieve what I want?

**Comment by horenmar** [comment]
> For safety reasons, you cannot use variables inside the GENERATE macro. This is done because the generator expression will outlive the outside scope and thus capturing references is dangerous. If you need to use variables inside the generator expression, make sure you thought through the lifetime implications and use GENERATE_COPY or GENERATE_REF.

[From here](https://github.com/catchorg/Catch2/blob/devel/docs/generators.md#top)
