### ISSUE TITLE
v3 compilation issues using cmake FetchContent

### ISSUE THREAD

**Issue by Ziemien** [catchorg/Catch2#2663]
**Describe the bug**
v3 compilation issues using cmake FetchContent

**Expected behavior**
should compile

**Platform information:**

 - OS: Linux
 - Compiler+version: Clang 15.0.7
 - Catch version: v3.3.2

```
ld.lld: error: undefined symbol: Catch::StringMaker<std::__1::basic_string_view<char, std::__1::char_traits<char>>, void>::convert(std::__1::basic_string_view<char, std::__1::char_traits<char>>)
>>> referenced by catch_tostring.hpp:151 
```

```
FetchContent_Declare(
        catch2
        URL https://github.com/catchorg/Catch2/archive/refs/tags/v3.3.2.zip)

FetchContent_MakeAvailable(catch2)

list(APPEND CMAKE_MODULE_PATH ${catch2_SOURCE_DIR}/extras)

include(Catch)
```

**Comment by stertingen** [comment]
I had the same issue. This is because you might be using C++17 for some targets, but Catch2 builds with the compiler's default, thus not building C++17-specific functionality.
The solution would be to add a CMake option to enable C++17 for Catch2, but as I workaround I set CMAKE_CXX_STANDARD globally to 17.

**Comment by ChrisThrasher** [comment]
> The solution would be to add a CMake option to enable C++17 for Catch2

This is what `CMAKE_CXX_STANDARD` already exists to serve. Besides, there are CMake options for enabling C++17 features like `std::string_view` formatting.

Here's another option:

https://github.com/SFML/SFML/blob/3c4c1d32667e823f820af04f5051a02391df97d8/test/CMakeLists.txt#L15-L16
