### ISSUE TITLE
Add an option to disable building SelfTest with meson

### ISSUE THREAD

**Issue by Ali-Amir** [catchorg/Catch2#2666]
**Description**
Today, there is an option `BUILD_TESTING` to disable building SelfTest with cmake, however that is not available for meson. The proposal is to add a [meson option](https://mesonbuild.com/Build-options.html) to building tests directory in `Catch2/meson.build`:
```
if get_option('tests')
  subdir('tests')
endif
```
And add an options file `Catch2/meson_options.txt`:
```
option('tests', type: 'boolean', value: true, description: 'Build the unit tests')
```

**Additional context**
We're using catch2 as a [wrapdb](https://mesonbuild.com/Wrapdb-projects.html) [subproject](https://mesonbuild.com/Subprojects.html) in meson. This allows us to build our code on different platforms without having to install dependencies manually. Since catch2 always includes SelfTest in its meson.build, we end up running SelfTest along with our unit tests when we run `meson test`.

**Comment by aholster** [comment]
@Ali-Amir You should probably propose this at the [Meson repository](https://github.com/mesonbuild/wrapdb?ts=4) instead, as they maintain the Wrapdb meson build definitions

**Comment by Ali-Amir** [comment]
@aholster it looks like the change needs to happen in this repository, doesn't it? In order for Wrapdb to pass these options to Catch2, Catch2 build file needs to support them. Please, let me know if I'm missing something.

**Comment by horenmar** [comment]
I'll merge a PR that adds this.

**Comment by Ali-Amir** [comment]
Thanks @horenmar. I created a PR for this: #2693.
