### ISSUE TITLE
catch_discover_tests: xml reporter vs. XML reporter (lower/upper case mismatch)

### ISSUE THREAD

**Issue by arnemertz** [catchorg/Catch2#2668]
**Describe the bug**
According to the documentation, `--reporter xml` with lower case "xml" should work, but using `catch_discover_tests` with `REPORTER xml` leads to an error  `"xml" is not a valid reporter!` in CatchAddTests.cmake:85 (as of Catch 3.3.2). On the other hand, `REPORTER XML` with upper case "XML" works.

Listing the reporters produces 
```
   Available reporters:
    Automake:   Reports test results in the format of Automake .trs files
    compact:    Reports test results on a single line, suitable for IDEs
    console:    Reports test results as plain lines of text
    JUnit:      Reports test results in an XML format that looks like Ant's
                  junitreport target
    SonarQube:  Reports test results in the Generic Test Data SonarQube XML
                  format
    TAP:        Reports test results in TAP format, suitable for test harnesses
    TeamCity:   Reports test results as TeamCity service messages
    XML:        Reports test results as an XML document
```
(Note the upper case XML)

**Expected behavior**
Using the reporter feature in `catch_discover_tests` should be consistent with the documented command line option or case-insensitive.
- See https://github.com/catchorg/Catch2/blob/devel/docs/command-line.md#choosing-a-reporter-to-use where the example uses lower case "xml"
- See https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md#automatic-test-registration where it explicitly mentioned that the argument is passed to the test runner as `--reporter reporter`

This broke some time between 2.13.9 and 3.3.2 (see https://github.com/cpp-best-practices/cmake_conan_boilerplate_template/blob/main/test/CMakeLists.txt where it still works)

**Reproduction steps**
CMake section:
```
find_package(Catch2 CONFIG REQUIRED)

include(Catch)

include(test_sources.cmake)
add_executable(tests tests.cpp)
target_link_libraries(tests PUBLIC Catch2::Catch2WithMain)

# automatically discover tests that are defined in catch based test files you can modify the unittests. Set TEST_PREFIX
# to whatever you want, or use different for different binaries
catch_discover_tests(
  tests
  REPORTER  xml
  OUTPUT_SUFFIX  .xml)
```

fails at compilation time.

Also note that the method used in CatchAddTests.cmake:85 is very crude, e.g. I could choose a reporter "suitable" without a failing build since that word happens to appear in the --list-reporters output.

**Comment by horenmar** [comment]
Right, for current Catch2 version it should instead check the error code after specifying the target reporter -> existing reporter returns 0 (call e.g. `--list-tags [does-not-exist-xxxxxxx]`), non-existant reporter returns 255.

**Comment by arnemertz** [comment]
As far as I can see, depending on the amount of tests (and tags) `--list-tags` may take some time. How about `--reporter ${reporter} --list-reporters`? The combination might seem silly, but `--list-reporters` seems to be the one thing that has stable runtime even when facing huge numbers of tests.
