### ISSUE TITLE
Compile error when using raw string literal inside CHECK() macro

### ISSUE THREAD

**Issue by gertvanhoey** [catchorg/Catch2#2673]
The following compiles with Catch3 v3.3.1, but fails to compile with Catch2 v3.3.2 (Linux, gcc 7.5).

```
SECTION("String literal")
    {
        const auto notEmpty = [](std::string value) {
            return value.size() > 0;
        };

        CHECK(notEmpty(R"(text
                         more text)"));
    }
```

**Comment by horenmar** [comment]
[Seems to be a preprocessor bug related to pasting raw strings as prepro token. Versions 8 and up actually handle this fine.](https://godbolt.org/z/Y44a5dMWz)

You will have to either use a newer compiler, avoid this pattern, or try to workaround provided for MSVC raw string literal issues (see docs).

**Comment by gertvanhoey** [comment]
Thank you for your response. I will avoid the pattern (e.g. assign the raw string to an intermediate variable) until I can use a more recent compiler.
