### ISSUE TITLE
`MatcherBase::match()` runs before `EventListenerBase::assertionStarting()`

### ISSUE THREAD

**Issue by vberlier** [catchorg/Catch2#2678]
**Describe the bug**
The docs say that `assertionStarting` is called after the expression is captured, but before the assertion expression is evaluated. For custom matchers the `match` member function is in charge of evaluating the assertion expression, but by the time the `assertionStarting` event is dispatched `match` has already been invoked.

**Expected behavior**
`assertionStarting` should run before custom matchers.

**Reproduction steps**
```cpp
class DummyCatchListener : public Catch::EventListenerBase {
public:
    using Catch::EventListenerBase::EventListenerBase;

    void assertionStarting(Catch::AssertionInfo const& assertionInfo) override {
        std::cout << assertionInfo.lineInfo.file << ":" << assertionInfo.lineInfo.line << std::endl;
    }
};

CATCH_REGISTER_LISTENER(DummyCatchListener)

class DummyMatcher : public Catch::Matchers::MatcherBase<int> {
public:
    bool match(int const& in) const override {
        std::cout << "match " << in << std::endl;
        return true;
    }
};

TEST_CASE("Dummy") {
    CHECK_THAT(123, DummyMatcher{});
}
```
```
match 123
path/to/dummy_test.cpp:42
```

**Additional context**
I'm trying to use a listener to update global variables to be able to access the current assertion file and line in a custom matcher. If there's another way to do it let me know :)

**Comment by horenmar** [comment]
That's definitely not the intended behaviour, I'll have to check how hard it will be to fix.

**Comment by horenmar** [comment]
Okay, so it might be a larger surgery. The basic assertions currently behave in the same way, and I would have to ensure that the proper information is wired around before the expression is evaluated.

**Comment by vberlier** [comment]
Thanks for the fix! Have a good day :)
