### ISSUE TITLE
Can't get TEMPLATE_PRODUCT_TEST_CASE_SIG to work with NTTP

### ISSUE THREAD

**Issue by VioletGiraffe** [catchorg/Catch2#2684]
Hi. Not a bug, but I believe I'm following the docs faithfully and can't get it to work. What's wrong with this test case declaration?
```
TEMPLATE_PRODUCT_TEST_CASE_SIG("name", "[test]", ((int V), V), 0, 1500, 20000)
{}
```
Catch2 v2.13.10
https://godbolt.org/z/z15najvYj

**Comment by GTruf** [comment]
@VioletGiraffe, You are using `TEMPLATE_PRODUCT_TEST_CASE_SIG` wrong, for your case you need `TEMPLATE_TEST_CASE_SIG`.
The way `TEMPLATE_PRODUCT_TEST_CASE_SIG` works is that you specify the signature first, then the type that matches that signature, and then the arguments to instantiate that signature.
For example, in the following example from the [documentation](https://github.com/catchorg/Catch2/blob/devel/docs/test-cases-and-sections.md#examples) you first define the signature of the class, then the types that match that signature (e.g. std::array and Bar), and then the parameters to be inserted there:
```cpp
template<typename T, size_t S>
struct Bar {
    size_t size() { return S; }
};

TEMPLATE_PRODUCT_TEST_CASE_SIG("A template product test case with array signature", "[template][product][nttp]", ((typename T, size_t S), T, S), (std::array, Bar), ((int, 9), (float, 42)) {
    TestType x;
    REQUIRE(x.size() > 0);
}
```

**Comment by VioletGiraffe** [comment]
Oh wow, so I just typed (copy-pasted, more likely) the wrong macro and never noticed. Ouch. Thank you! (and sorry.)
