### ISSUE TITLE
FAIL macro leads to linker failure

### ISSUE THREAD

**Issue by mattbaumann** [catchorg/Catch2#2692]
While compiling a FAIL("reason"); I receive a linking error that `Catch::ReusableStringStream::str[abi:cxx11]() const' is unavailable in the linker context. I know FAIL is not a "officially" documented MACRO, but immensly useful. Plus, it is neither deprecated in [Release Notes](https://github.com/catchorg/Catch2/blob/devel/docs/release-notes.md) nor documented as do not use. I assume therefore, I'm still allowed to use it.

As a last side-note, using any other macro like `CHECK(true);` will lead to successful linking.

I've the following CMAKE file:
```cmake
cmake_minimum_required(VERSION 3.25)
project(catch2test)

set(CMAKE_CXX_STANDARD 23)

find_package(Catch2 3 REQUIRED)
add_executable(catch2test main.cpp)
target_link_libraries(catch2test PRIVATE Catch2::Catch2WithMain)
```
And for simplicity the following main.cpp:

```c++
#include <catch2/catch_all.hpp>

TEST_CASE("Test") {
    FAIL("anything");
}
```
This gives me the follwing output (slightly shortened for brevity):
```
====================[ Build | catch2test | Debug ]==============================
/opt/clion-2023.1.2/bin/cmake/linux/x64/bin/cmake --build /<user_home_dir>/CLionProjects/catch2test/cmake-build-debug --target catch2test -j 4
[2/2] Linking CXX executable catch2test
FAILED: catch2test 
: && /usr/bin/clang++ -g  CMakeFiles/catch2test.dir/main.cpp.o -o catch2test -L/<user_home_dir>/.conan2/p/b/catchc49e1c6546aa5/p/lib -Wl,-rpath,/<user_home_dir>/.conan2/p/b/catchc49e1c6546aa5/p/lib  /<user_home_dir>/.conan2/p/b/catchc49e1c6546aa5/p/lib/libCatch2Maind.a  -lm  /<user_home_dir>/.conan2/p/b/catchc49e1c6546aa5/p/lib/libCatch2d.a && :
/usr/bin/ld: CMakeFiles/catch2test.dir/main.cpp.o: in function `CATCH2_INTERNAL_TEST_0()':
/<user_home_dir>/CLionProjects/catch2test/main.cpp:4: undefined reference to `Catch::ReusableStringStream::str[abi:cxx11]() const'
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
Some context information:
Manjaro Linux 05-07-23

clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

GNU ld (GNU Binutils) 2.40
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

catch2/3.3.2 as downloaded by conan and compiled with /usr/bin/clang++

**Comment by mattbaumann** [comment]
Conan played fool with me. Sorry for bothering.

**Comment by horenmar** [comment]
Yeah I suspected something like that.
