### ISSUE TITLE
tvOS build fails

### ISSUE THREAD

**Issue by benthevining** [catchorg/Catch2#2694]
**Describe the bug**
When building with:
```sh
cmake -D CMAKE_SYSTEM_NAME=tvOS -D CMAKE_XCODE_EFFECTIVE_PLATFORMS=-appletvos 
```
I get the following compilation error:
```
/Users/benvining/Documents/MyRepos/lfilesystem/Builds/tvOS/_deps/catch2-src/src/catch2/internal/catch_fatal_condition_handler.cpp:183:9: error: 
      'sigaltstack' is unavailable: not available on tvOS
        sigaltstack(&oldSigStack, nullptr);
        ^
In file included from /Users/benvining/Documents/MyRepos/lfilesystem/Builds/tvOS/_deps/catch2-src/src/catch2/internal/catch_fatal_condition_handler.cpp:143:
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS15.4.sdk/usr/include/signal.h:87:5: note: 
      'sigaltstack' has been explicitly marked unavailable here
int     sigaltstack(const stack_t * __restrict, stack_t * __restrict)  _...
        ^
/Users/benvining/Documents/MyRepos/lfilesystem/Builds/tvOS/_deps/catch2-src/src/catch2/internal/catch_fatal_condition_handler.cpp:222:9: error: 
      'sigaltstack' is unavailable: not available on tvOS
        sigaltstack(&sigStack, &oldSigStack);
        ^
In file included from /Users/benvining/Documents/MyRepos/lfilesystem/Builds/tvOS/_deps/catch2-src/src/catch2/internal/catch_fatal_condition_handler.cpp:143:
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS15.4.sdk/usr/include/signal.h:87:5: note: 
      'sigaltstack' has been explicitly marked unavailable here
int     sigaltstack(const stack_t * __restrict, stack_t * __restrict)  _...
        ^
2 errors generated.
```

**Expected behavior**
Catch2 should compile on tvOS.

**Reproduction steps**
Try to build a simple executable that links to `Catch2::Catch2WithMain` with the CMake configure options: `-D CMAKE_SYSTEM_NAME=tvOS -D CMAKE_XCODE_EFFECTIVE_PLATFORMS=-appletvos `

**Platform information:**

 - OS: MacOS
 - Compiler+version: AppleClang 13.1.6.13160021
 - Catch version: 3.3.2

**Comment by benthevining** [comment]
Note that I get the same error when cross-compiling for watchOS, with the CMake configure options `-D CMAKE_SYSTEM_NAME=watchOS -D CMAKE_XCODE_EFFECTIVE_PLATFORMS=-watchos`

**Comment by horenmar** [comment]
As the error message tells you, tvOS explicitly disables posix signal-related functions, even thought it is a nominally POSIX platform. And as [the documentation says](https://github.com/catchorg/Catch2/blob/devel/docs/configuration.md#other-toggles) you can ask for signal handling to be disabled.

**Comment by benthevining** [comment]
Thank you, once I added `CATCH_CONFIG_NO_POSIX_SIGNALS`, the tvOS and watchOS builds succeed. I would suggest making this the default on these platforms though, so that Catch works out of the box.
