### ISSUE TITLE
Question regarding the right include paths for e.g. clang++ linter

### ISSUE THREAD

**Issue by matthewcarbone** [catchorg/Catch2#2703]
I have a question about the right way to specify paths for e.g. the `clang++` linter. I have no problems using `CMake` to build and link the library to my own code, but it's quite annoying to code in e.g. Sublime Text, with the linter yelling at me and making it very hard to debug the rest of the code.

For example, even though the code links/compiles/runs correctly, I have not been able to figure out the right combinations of paths to include in my linter to disable this error and enable syntax/type checking for the rest  of my testing code:

```c++
#include "catch2/catch_test_macros.hpp"
```

produces a linter error 

```
`catch2/catch_test_macros.hpp` file not found
```

I can disable this error by filtering errors,

```json
"filter_errors": ["'catch2/catch_test_macros.hpp'"]
```

but this seems to both disable listing for the rest of the file, and also disables the ability to do the right type checking (since of course the linter doesn't know where to look for the files). Obviously the linting part is not germane to Catch2, I'm really asking about the right include paths here.

Obviously this wasn't an issue with the previous version of Catch2 (single-header-only version), but I would like to use the most recent version if possible.

Thanks in advance for the help, and thank you for the wonderful library!

**Comment by horenmar** [comment]
Hopefully your editor understands the clang compile database, [which you can get from CMake](https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html).

**Comment by matthewcarbone** [comment]
@horenmar thanks for the response. To be honest I'm not exactly understanding what you mean here. What exactly is your proposed solution? My current solution is to just include the old header only version of Catch2, then comment it out and use the more recently library version import of Catch 2 at compile time. Not exactly optimal...

**Comment by ChrisThrasher** [comment]
> To be honest I'm not exactly understanding what you mean here. What exactly is your proposed solution?

To use CMake to generate a compile_commands.json file which your C++ language server can use to know where to find headers and thus give you sensible diagnostics while writing code. This is a very common practice in C++ development so I expect you can find resources online to help you with your particular IDE.

Because this issue is not a problem to Catch2 itself I will be closing this issue. Please come to [the Discord server](https://discord.gg/4CWS9zD) if you'd like more troubleshooting help.

**Comment by matthewcarbone** [comment]
@ChrisThrasher thanks for the response. I actually figured this out in the meantime while setting up my clang LSP server with vim 😁. Agreed this is a non-issue. Thanks!
