### ISSUE TITLE
error adding symbols: archive has no index; run ranlib to add one

### ISSUE THREAD

**Issue by Dich0tomy** [catchorg/Catch2#2705]
**Describe the bug**
I have a meson project (located [here](https://github.com/b4mbus/haumea), **testing** branch) using catch2.

I try to build it in release, with the following configuration:
```meson
meson configure --buildtype release -Db_sanitize=none --optimization 3 -Db_lto=true -Dcpp_debugstl=false {{ release_build_dir }}
```
Which produces this build command:
```
clang++
-o
subprojects/Catch2-3.2.0/tests/SelfTest
subprojects/Catch2-3.2.0/tests/SelfTest.p/SelfTest_helpers_parse_test_spec.cpp.o
.. more files here
-flto
-Wl,--as-needed
-Wl,--no-undefined
-Wl,-O1
-Wl,--start-group
subprojects/Catch2-3.2.0/src/catch2/libCatch2Main.a
subprojects/Catch2-3.2.0/src/catch2/libCatch2.a
-Wl,--end-group
```

But I get this error:
```
../bin/ld: subprojects/Catch2-3.2.0/src/catch2/libCatch2Main.a: error adding symbols: archive has no index; run ranlib to add one
```

I tried both with `dependency(.., static: false)` believing it has something to do with 

**Expected behavior**
Should link fine.

**Reproduction steps**
Clone this repo (contains one single test file, meson.build, subprojects/catch2.wrap and a nix flake): [b4mbus/testasdasd](https://github.com/b4mbus/testasdasd)

Run the following command:

```shell
$ meson setup build_release
  && meson configure --buildtype release -Db_sanitize=none --optimization 3 -Db_lto=true -Dcpp_debugstl=false build_release
  && meson compile -C build_release
```
It should fail with a similar message to this:
```
/bin/ld: subprojects/Catch2-3.3.2/src/catch2/libCatch2Main.a: error adding symbols: archive has no index; run ranlib to add one
```

**Platform information:**
- OS: NixOS 23.05
- Compiler+version: clang version 15.0.7
- Catch version: 3.3.2

**Additional context**
I'm on NixOS and using Nix it may be somehow related, but I don't think so. I'm pretty sure it worked fine before. Haven't seen anyone else having similar issues too.

**Comment by horenmar** [comment]
Does this also happen without LTO?

**Comment by Dich0tomy** [comment]
No, it doesn't happen without LTO, weird. But honestly would be nice if I could keep it, how does LTO affect this?

**Comment by horenmar** [comment]
IIRC, with LTO, the static archive will contain LTO metadata and not actual binary symbols. I've had to deal with this in work project once. IIRC Clang and GCC also handle static libraries like this a bit differently and the whole thing is kinda messy. 🤷

From what I remember, you should use llvm's ranlib and ar (and maybe lld as well?) instead of the ones that come from your system's GCC.

**Comment by Dich0tomy** [comment]
All I had to do was change the linker to `lld`, thanks a lot!
