### ISSUE TITLE
Catch2 is not ready for c++23

### ISSUE THREAD

**Issue by piotrrak** [catchorg/Catch2#2744]
**Description**
There wasn't many issues so far with what g++/clang++ implement now (for meson build)

This one test won't work due to lack of `std::vector::operator[] (int, int, int)`

``` diff
diff --git a/tests/SelfTest/UsageTests/Message.tests.cpp b/tests/SelfTest/UsageTests/Message.tests.cpp
index a5e69582..40ab8316 100644
--- a/tests/SelfTest/UsageTests/Message.tests.cpp
+++ b/tests/SelfTest/UsageTests/Message.tests.cpp
@@ -256,7 +256,7 @@ std::ostream& operator<<(std::ostream& out, helper_1436<T1, T2> const& helper) {
 #endif
 
 TEST_CASE("CAPTURE can deal with complex expressions involving commas", "[messages][capture]") {
-    CAPTURE(std::vector<int>{1, 2, 3}[0, 1, 2],
+    CAPTURE(std::vector<int>{1, 2, 3}[(0, 1, 2)],
             std::vector<int>{1, 2, 3}[(0, 1)],
             std::vector<int>{1, 2, 3}[0]);
     CAPTURE((helper_1436<int, int>{12, -12}),
```

**Additional context**
When the time comes, that c++23 is supported.

**Comment by horenmar** [comment]
This should be fixed by having custom type with multi-arg `operator[]` guarded by the `__cpp_multidimensional_subscript` feature macro. If multiarg `[]` is not available, the CAPTURE will be evaluated with the comma operator, if it is, as an multiarg `[]`.

**Comment by piotrrak** [comment]
> This should be fixed by having custom type with multi-arg `operator[]` guarded by the `__cpp_multidimensional_subscript` feature macro. If multiarg `[]` is not available, the CAPTURE will be evaluated with the comma operator, if it is, as an multiarg `[]`.

Indeed.

**Comment by piotrrak** [comment]
@horenmar  Thank you
