### ISSUE TITLE
catch_discover_tests DISCOVERY_MODE PRE_TEST does not work with Xcode. 

### ISSUE THREAD

**Issue by z-ukalnins** [catchorg/Catch2#2746]
**Describe the bug**
Adding `DISCOVERY_MODE "PRE_TEST"` to `catch_discover_tests` causes cmake errors during project generation if Xcode generator is used. 

Example error:
```
CMake Error in Tests/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   <Path To Project>/Tests/test-core_include-b12d07c.cmake
```

**Expected behavior**

No errors during make project generation and test discovery mode delayed until test execution.

**Reproduction steps**
Project setup:
```
// test.cpp 
#include <catch2/catch_test_macros.hpp>

TEST_CASE("Empty", "[Empty]")
{
}

// CMakeLists.txt
cmake_minimum_required(VERSION 3.27)
project(Test LANGUAGES C CXX)
include(FetchContent)
FetchContent_Declare(
  Catch2
  GIT_REPOSITORY https://github.com/catchorg/Catch2.git
  GIT_TAG        v3.4.0
)
FetchContent_MakeAvailable(Catch2)
list(APPEND CMAKE_MODULE_PATH ${catch2_SOURCE_DIR}/extras)
include(Catch)
add_executable(test-core test.cpp)
target_link_libraries(test-core PRIVATE Catch2::Catch2WithMain)
catch_discover_tests(test-core WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" DISCOVERY_MODE "PRE_TEST")
```

Command to execute:
```
cmake -G Xcode
```

**Platform information:**
 - OS: **macOS-13.5.2**
 - Compiler+version: **Xcode-15**
 - Catch version: **v3.4.0**

**Additional context**
I suspect that DISCOVERY_MODE fails to account for multi config build systems.

**Comment by horenmar** [comment]
> I suspect that DISCOVERY_MODE fails to account for multi config build systems.

This is correct, see #2739
