### ISSUE TITLE
__has_feature is not supported by GCC

### ISSUE THREAD

**Issue by cschwan** [catchorg/Catch2#275]
Commit ce6598599b90e033698840d57cfd5f1e46539a7d introduced a check that uses a clang specific preprocessor-extension: `__has_feature`. It's not supported by any version of GCC; I tested that with both `gcc version 4.7.3 (Gentoo 4.7.3-r1 p1.4, pie-0.5.5)` and `gcc version 4.10.0 20140423 (experimental) (GCC)`.

Looking at that the changes the commit introduced, it seems that the author assumes `throw()` to be equivalent with the new `noexcept` which is **not** the case, see e.g. the articles on [cppreference.com](http://en.cppreference.com/w/cpp/language/noexcept_spec) and [stackoverflow.com](http://stackoverflow.com/questions/12833241/difference-between-c03-throw-specifier-c11-noexcept).

Since `throw()` is deprecated in C++11 now one could think of removing it altogether.

**Comment by markhallutah** [comment]
I am seeing this error in clang 3.7.0 with gcc 5.1.1. 

specifically /usr/include/wchar.h has 
#include <stddef.h> 
and it is somehow finding the one in /usr/lib/clang/3.7.0/include  (why?)

which uses __has_features(modules)

Is there a clang specific header I could include first, that would invoke the protections/fix ?
