### ISSUE TITLE
Catch2 throws exceptions during stack unwind

### ISSUE THREAD

**Issue by Alan-Jowett** [catchorg/Catch2#2752]
**Describe the bug**
While performing low memory simulation using a catch2 based test, there are cases where the catch2 framework allocates memory during a destructor, which triggers undefined behavior by throwing an exception while unwinding the stack.

**Expected behavior**
Catch2 should not call throwing functions during destructors. 

**Reproduction steps**
Emulate low memory simulation using a tool like [Application Verifier Low Resource Simualtion](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/application-verifier-tests-within-application-verifier#low-resource-simulation).
Run the catch2 tests.

This causes std::terminate to be called if the new throws std::bad_alloc while new is being called in a destructor.

**Platform information:**
All platforms.

**Additional context**
No.

**Comment by horenmar** [comment]
> Catch2 should not call throwing functions during destructors.

Yeah, that's not happening.

**Comment by horenmar** [comment]
Sorry, that likely came over harsher than it was supposed to. It is realistic to avoid sources of exceptions that are not from allocating memory, but as long as Catch2 is expected to provide output on test errors, I do not think it is reasonable to expect no allocations in destructors.

**Comment by Alan-Jowett** [comment]
Thanks, I appreciate the feedback. Will need to workaround this in our project.
