### ISSUE TITLE
using fetchContent cannot include catch2

### ISSUE THREAD

**Issue by patcmorneau** [catchorg/Catch2#2764]
cmake:

```
Include(FetchContent)
FetchContent_Declare(
  Catch2
  GIT_REPOSITORY https://github.com/catchorg/Catch2.git
  GIT_TAG        v3.0.1
)
FetchContent_MakeAvailable(Catch2)

add_executable(tests src/tests/tests.cpp ${CXX_FILES})
target_link_libraries(tests PRIVATE Catch2::Catch2WithMain ${PCL_LIBRARIES} Qt5::Widgets)
```

c++:
```


#include <catch2/catch_test_macros.hpp>

#include "../../project/ImportLidarCloudWorker.h"

TEST_CASE( "Lidar point cloud reader") {
	ImportLidarCloudWorker importLidarCloudWorker(nullptr,nullptr,"../data/lidarCloud.xyz");
	REQUIRE(importLidarCloudWorker);
}
```

error:

`fatal error: catch2/catch_test_macros.hpp: No such file or directory
    1 | #include <catch2/catch_test_macros.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.`

**Comment by stiggy87** [comment]
I added `list(APPEND CMAKE_MODULE_PATH ${Catch2_SOURCE_DIR} ${Catch2_SOURCE_DIR}/extras)` to my builds and it seemed to make it work.

**Comment by patcmorneau** [comment]
Forgot i had that open.

The solution i found was to use an other tag `GIT_TAG        v2.13.9`

and instead of `target_link_libraries(tests PRIVATE Catch2::Catch2WithMain )`
i used: `Catch2::Catch2`
