### ISSUE TITLE
one test fails for 2.5.1 release building with gcc 11/10 on i686-linux

### ISSUE THREAD

**Issue by jollm** [catchorg/Catch2#2796]
**Describe the bug**
The `REQUIRE_THAT( generated, Catch::Matchers::RangeEquals( uniform_fp_test_params<TestType>::expected ) )` test fails when building with gcc on i686-linux. (for type float?)

**Expected behavior**
The test should pass as long as a supported compiler is used. (It does pass when building with clang++-10)

**Reproduction steps**
Build either with gcc 11.3 or gcc 10 targeting i686-linux.

Flags used:
```
-DCATCH_DEVELOPMENT_BUILD=ON
-DCATCH_ENABLE_WERROR=OFF
-DBUILD_SHARED_LIBS=ON
```

**Platform information:**

 - OS: Linux
 - Compiler+version: **GCC v11.3.0**
 - Catch version: **v2.5.1**

**Additional context**
See https://gitlab.com/nonguix/nonguix/-/issues/307 for downstream discovery and discussion.

**Comment by horenmar** [comment]
Looks like I underestimated how many people still build 32 bit packages without SSE2 for floats.

Those tests will fail when compiled for the old x86 fpu.

**Comment by podiki** [comment]
Thanks for the info on the core reason. This was found on Guix as we don't usually enable any extra architecture features by default. So at least for Guix I've enabled SSE2 so things build/test on i686 (see https://issues.guix.gnu.org/68429).

**Comment by jollm** [comment]
Thanks for the explanation!, Feel free to close this for my part
