### ISSUE TITLE
Running a windows GUI application does not allow me to run Catch2 tests!

### ISSUE THREAD

**Issue by juandent** [catchorg/Catch2#2797]
**Describe the bug**
I have a windows GUI application built with MFC (it's a dialog type app) and wanted to write some tests but they don't execute.
I am including the catch2 headers and linking with Catch2Maind.lib;Catch2d.lib.
My relevant code is: 

```C++
#pragma once
#undef max
#undef min
#include <algorithm>
using std::max;
using std::min;
#include <catch2/catch_all.hpp>
#include "GridCtrl_src/GridCtrl.h"


class CGridCtrlTest :   public CGridCtrl
{
public:
	int* p = nullptr;
	int* get() const { return p; }
};


TEST_CASE_METHOD(CGridCtrlTest, "Test method")
{
	p = new int{ 44 };
	auto x = get();
	REQUIRE(p != nullptr);
}

TEST_CASE("test function")
{
	REQUIRE(1 == 1);
}
```

How can I run these tests ? I see that program control goes into the event loop for the dialog and never reaches the test cases...

**Platform information:**
 - OS: **Windows 11 Pro**
 - Compiler+version: **Visual Studio 2022**
 - Catch version: **?**

**Comment by juandent** [comment]
The application starts with _tWinMain not with main()!!

See this code is executed at startup


```C++
extern "C" int WINAPI
_tWinMain(_In_ HINSTANCE hInstance, _In_opt_ HINSTANCE hPrevInstance,
	_In_ LPTSTR lpCmdLine, _In_ int nCmdShow)
#pragma warning(suppress: 4985)
{
	// call shared/exported WinMain
	return AfxWinMain(hInstance, hPrevInstance, lpCmdLine, nCmdShow);
}
```

how to make it run main() in Catch2 library??

Also, I choose right click on the solution in VS2022 and choose run unit tests but they don't get executed...

**Comment by ChrisThrasher** [comment]
You're probably better off not using Catch2WithMain and instead providing your own entry point that calls into Catch2.

**Comment by p4vook** [comment]
@juandent did this fix the issue for you?
See the documentation on running Catch2 with your own main:
https://github.com/catchorg/Catch2/blob/devel/docs/own-main.md
