### ISSUE TITLE
find command | return the relevant panel

### ISSUE THREAD

**Issue by interfan7** [catchorg/Catch2#2803]
**Description**
In our case there are abundance of panels, and many dashboards. 
When we search by a query we get result of dashboard which is better than nothing but not much helpful, especially as users already have some idea which dashboards to look at. It's the panels that are the biggest pain in searching where a given query is defined.

**Comment by horenmar** [comment]
This makes no sense for this repo.

**Comment by interfan7** [comment]
My bad! Was meant to another repo. Shall I delete?

Sorry.

**Comment by horenmar** [comment]
Eh, I can delete it myself.
