### ISSUE TITLE
I place a benchmark inside a TEST_CASE() and I don't see the results

### ISSUE THREAD

**Issue by juandent** [catchorg/Catch2#2814]
I place this code:

```C++
TEST_CASE("Benchmark")
{
	BENCHMARK("simple") {
		return long_computation();
	};
}
```

I don't get any display in the console -- actually there is no console, why??

I am working in VS2022 v 17.9.0 Community Edition....

I would expect to see timing results!!

 - OS: **Windows 11 Pro**
 - Compiler+version: **VS2022 v17.9.0**
 - Catch version: **?** latest

**Additional context**
I am using a VS2022 addon called Resharper C++
I chose the unit test "Benchmark" from Resharper C++ Unit Test Sessions

**Comment by horenmar** [comment]
Sounds like issue with Resharper, try running the binary outside of VS.

**Comment by juandent** [comment]
Thank you that solves the problem RegardsJuan dentSent from my iPhoneOn 17 Feb 2024, at 4:06 PM, Martin Hořeňovský ***@***.***> wrote:﻿
Sounds like issue with Resharper, try running the binary outside of VS.
