### ISSUE TITLE
Bring back Single-Header capability

### ISSUE THREAD

**Issue by shleym2000** [catchorg/Catch2#2834]
**Description**
 **Single-header** testing framework was the shtick of the Catch2 library. You should think of bringing it back in v.3.x.x
 
**By dropping single-header feature in v3, Catch2 project becomes worse than Google and Boost testing frameworks**,
because guaranteed support and improvements for those 2 widely used products is not guaranteed for Catch2 project.

**Additional context**
If you for some strange reason insist that you need a static/dynamic library component, make it an optional thing for separate well defined additional testing features.

Something like _"Single header would give me well functioning testing framework, but the following list of features will be additionally available if you would build a library and use these additional headers"_

**Comment by horenmar** [comment]
No.

**Comment by shleym2000** [comment]
OK. Nice to know
