### ISSUE TITLE
Combine test filters with filenames

### ISSUE THREAD

**Issue by itacud95** [catchorg/Catch2#2847]
**Description**
Say I have the following tests 
```
// file: bar.cpp
TEST_CASE("basic") { CHECK(true); }
TEST_CASE("windows", "[.][windows]") { CHECK(true); }
TEST_CASE("linux", "[.][linux]") { CHECK(true); }
TEST_CASE("macos", "[.][macos]") { CHECK(true); }
TEST_CASE("both", "[.][linux][windows][macos]") { CHECK(true); }
```
```
// file: foo.cpp
TEST_CASE("basic") { CHECK(true); }
TEST_CASE("linux", "[.][linux]") { CHECK(true); }
TEST_CASE("macos", "[.][macos]") { CHECK(true); }
```
Since there are duplicate test names, I am starting the test with `--filenames-as-tags`. 

Now I am able to use the filter to run all tests without any tag and tagged linux with: 
```
./testbinary --filenames-as-tags [linux],~[.] 
// runs following tests: 
bar.cpp: basic, linux, both
foo.cpp: basic, linux
```

The question is; 
How can I run the same set of filters, but only on the bar.cpp file? 
Is it possible? 

I have tried different combinations of this filter `[#bar][linux],~[.]`, but I am not able to get the desired result.

**Comment by horenmar** [comment]
If I understand what you want, you are missing `[#bar]` on the second part of the selection:

```
$ ./tests --filenames-as-tags [linux][#bar],~[.][#bar] --list-tests
Matching test cases:
  basic
      [#bar]
  linux
      [.][linux][#bar]
  both
      [.][linux][macos][windows][#bar]
3 matching test cases
```

**Comment by itacud95** [comment]
Thank you @horenmar, this is indeed what I was looking for.
