### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by cyrusbehr** [catchorg/Catch2#2889]
![image](https://github.com/user-attachments/assets/480cda95-67d6-42b3-8307-9ba72367e451)

Should say `Catch2Main`

**Comment by horenmar** [comment]
No, it should not. This is the intended usage with default main:

```cmake
target_link_libraries(benches
  PRIVATE
    Catch2::Catch2WithMain
)
```

**Comment by cyrusbehr** [comment]
I see, sorry about the confusion. I was using `(target_link_libraries ...)` with the library name, which required me to use `Catch2Main`.

![image](https://github.com/user-attachments/assets/510ae59b-8e75-4b60-8ce1-e6950ab3d37c)
