### ISSUE TITLE
Feature: Capture multiple variables in one statement

### ISSUE THREAD

**Issue by PetterS** [catchorg/Catch2#289]
I think the following could be useful:

```
CAPTURE(a, b, c)
```

It would mean the same thing as:

```
CAPTURE(a); CAPTURE(b); CAPTURE(c);
```

Right now the first expression compiles, but only a is captured.

**Comment by JoeyGrajciar** [comment]
Seems to be implemented by #1448

**Comment by horenmar** [comment]
Yep.
