### ISSUE TITLE
Visual Studio Code IntelliSense Error

### ISSUE THREAD

**Issue by Riley-horrix** [catchorg/Catch2#2890]
**Describe the bug**
The following intellisense error is occurring in all of my testing suites.

<img width="1123" alt="Screenshot 2024-07-22 at 22 50 12" src="https://github.com/user-attachments/assets/5c9530ee-fef9-4fd2-920b-e83073ae4536">

When compiling and executing this code, all tests pass and there are no errors.

**Expected behavior**
This should not be an error.

**Platform information:**

 - OS: MacOS Sonoma 14.5
 - Compiler+version: Clang 15.0.0
 - Catch version: 3.6.0

**Comment by lfmunoz** [comment]
Works for me paste your c_cpp_properties.json file inside the .vscode directory. Are you pointing to catch2 header file folder?

![image](https://github.com/user-attachments/assets/97c47615-52d7-4cc6-9b51-8c1f24c7e301)

**Comment by Riley-horrix** [comment]
Hi,

Regarding your recent email, my c_cpp_properties looked like the attached image.
Adding the standard, 
Completely fixed the error and removed the intellisense warning.

Many thanks
Riley

--
  ***@***.***
