### ISSUE TITLE
Very slow run time with DYNAMIC_SECTION

### ISSUE THREAD

**Issue by SirNate0** [catchorg/Catch2#2900]
**Describe the bug**
When using a DYNAMIC_SECTION to include the output of a moderately large generated range of values, the test runs *extremely* slowly. Over a second for 500 integer equality REQUIREs. Further, run time scales non-linearly (approximately n²) with the number iterations (data at the bottom).

**Expected behavior**
While runtime is expected to be a bit slower, it should be much closer to the 2 millisecond run time without the DYNAMIC_SECTION 

**Reproduction steps**
Link with catch_main provided by meson's wrap file, with `-O3 -g`.
```cpp
#include "catch2/catch_test_macros.hpp"

TEST_CASE("Very Slow", "[1000]") {
    SECTION("Full range") {
        for (int i = -0; i<1000; ++i)
            DYNAMIC_SECTION("I="<<i) 
                REQUIRE(i == i+1-(i/i));
    }
}
```

**Platform information:**
 - OS: **Kubuntu 22.04**
 - Compiler+version: **gcc version 11.4.0**
 - Catch version: **3.6.0**

**Performance data**

| count | user time (s)|
|-------|--------------|
| 100 | 0.02 |
| 200 | 0.10 |
| 300 | 0.30 |
| 400 | 0.70 |
| 500 | 1.38 |
| 600 | 2.38 |
| 700 | 3.80 |
| 800 | 4.87 |
| 900 | 7.00 |
| 1000 | 9.53 |

![image](https://github.com/user-attachments/assets/d846c7ed-05a8-4a30-8d16-e3d68d256112)

**Profile results**

My (perhaps incorrect) attempt to profile it suggests that these functions are the most costly:
```
Catch::TestCaseTracking::operator==(Catch::TestCaseTracking::NameAndLocation const&, Catch::TestCaseTracking::NameAndLocationRef const&)
Catch::TestCaseTracking::ITracker::findChild(Catch::TestCaseTracking::NameAndLocationRef const&)::{lambda(Catch::Detail::unique_ptr<> const&)#1}::operator()(Catch::Detail::unique_ptr<> const&) const
Catch::StringRef::operator==(Catch::StringRef) const
Catch::StringRef::StringRef(std::__cxx11::basic_string<> const&)
```

---

This may be a duplicate of https://github.com/catchorg/Catch2/issues/2601, but I'm not sure, as there were no DYNAMIC_SECTIONs in that bug, and it's reproduction code runs in milliseconds for me (perhaps that issue can be closed?).

**Comment by SirNate0** [comment]
If I use CAPTURE on the iteration variable instead I get much better performance. Perhaps this is even the preferred way to do it, though I don't think that is clear. For example, the [docs](https://github.com/catchorg/Catch2/blob/devel/docs/limitations.md#sections-nested-in-loops) suggest DYNAMIC_SECTION inside a loop (granted, because normal SECTION won't work), and [this comment](https://github.com/catchorg/Catch2/issues/2366#issuecomment-1033891394) directly illustrates using DYNAMIC_SECTION for GENERATOR output (granted the next comment suggests CAPTURE).

**Comment by horenmar** [comment]
Sections inherently scale quadratically-or-worse. Consider

```cpp
TEST_CASE() {
    SECTION("A") {}
    SECTION("B") {}
    SECTION("C") {}
    SECTION("D") {}
}
```

This test case will have 4 partial runs, and each of the partial test runs has to check each of the 4 sections to decide whether it should enter. In your case you are creating a 1k+ of them, which gives you nice 1M+ of section checks to finish running.

The actual performance ends up being worse due to other factors in tracking, e.g. looking through all child sections of another section is a linear check.
