### ISSUE TITLE
Different folder structure in VS Solution between 2.13.0 and 2.13.1

### ISSUE THREAD

**Issue by pisoir** [catchorg/Catch2#2917]
**Describe the bug**
We are using catch2 version 2.13.0, cmake version 3.29.0 and after running cmake, the .sln solution contains folders `CMakePredefinedTargets` and `Shared`

![image](https://github.com/user-attachments/assets/cf0e64e5-ec7a-4317-9981-fbb93d1b05a6)

However, updating the version to 2.13.1 the folder structure changes completely and I see additional projects

![image](https://github.com/user-attachments/assets/79a28fd3-3b5f-4e57-9258-4845d5f89ed3)

I checked the changes in the versions but I cannot find out where is this coming from. Where is this coming from?

**Expected behavior**
The folder structure should stay the same.

**Comment by pisoir** [comment]
It seems this is related to the change that line `set_property(GLOBAL PROPERTY USE_FOLDERS ON)` has been removed. Why was this removed?

**Comment by horenmar** [comment]
Probably lost during some CMakeLists refactoring.
