### ISSUE TITLE
Issue with clang, tuple and c++23

### ISSUE THREAD

**Issue by mattgodbolt** [catchorg/Catch2#2923]
**Describe the bug**

`CHECK()`-ing `tuple`s on clang (using GCC's stdlib) gives a compile error when compiled with `-std=c++23`

```cpp
#include <catch2/catch_test_macros.hpp>
#include <tuple>

using namespace std::literals;

TEST_CASE("tuples") {
    std::tuple<int, int> bob;
    CHECK(bob == std::make_tuple(4, 2));
}
```

Compiler error is:
```
error: implicit instantiation of undefined template 'std::tuple_size<Catch::Decomposer>'
```

Demo: https://compiler-explorer.com/z/hce5jxYWc

**Expected behavior**
It should compile.

**Reproduction steps**

As above, using clang with -std=c++23 , but `-std=c++20` is OK

**Platform information:**
Catch version: 3.7.* and onward

**Additional context**
Entirely possible this is a clang/gcc interop bug. But I figured I'd file here in case someone goes "Oh! I know what that is..."

**Comment by mattgodbolt** [comment]
A disgusting workaround is:
```cpp
namespace std {
template<> struct tuple_size<Catch::Decomposer> { static constexpr size_t value = 1; };
}
```

**Comment by horenmar** [comment]
So, GCC + libstdc++ works, Clang + libc++ works, Clang + libstdc++ does not.

I am going to call this a third party bug for now, it would not be the first time there was breakage from mixing Clang and libstdc++ in specific version.

**Comment by mattgodbolt** [comment]
thanks @horenmar

**Comment by horenmar** [comment]
Confirmed as Clang's issue: https://github.com/llvm/llvm-project/issues/113087

**Comment by mattgodbolt** [comment]
Oh amazing! Thank you for taking the time to file the clang issue!

**Comment by unhappy-ending** [comment]
I'm getting this same problem on a Gentoo system but with clang 20.1 & libc++ 20.1. It's failing on a test file:

FAILED: tests/CMakeFiles/SelfTest.dir/SelfTest/UsageTests/Misc.tests.cpp.o

Better to use a pastebin:

https://pastebin.com/fmD0kQsj
