### ISSUE TITLE
Compilation warning/error catch_random_integer_helpers.hpp

### ISSUE THREAD

**Issue by ak-mcooper** [catchorg/Catch2#2924]
**Describe the bug**
In file catch_random_integer_helpers.hpp, templated function
- template<typename TargetType, typename Generator> fillBitsFrom()

makes calls to
- Generator::min
- Generator::max

The compiler reports the following warnings:
- warning C4003: not enough arguments for function-like macro invocation 'min'
- warning C4003: not enough arguments for function-like macro invocation 'max'

**Expected behavior**
No warnings.

**Reproduction steps**
- Linking to Catch2 (no main).
- Includes used:
  - #include <catch2/catch_test_macros.hpp>
  - #include <catch2/catch_approx.hpp>
  - #include <catch2/generators/catch_generators.hpp>
  - #include <catch2/generators/catch_generators_random.hpp>
- No need for anything fancy, nor any use of a generator (random or otherwise).

**Platform information:**
 - OS: **Windows 11**
 - Compiler+version: **MSVC 17.8.14**
 - Catch version: **v3.7.1**

** Suggested fix:**
- Add enclosing parenthesis to Generator::min and Generator::max calls.

**Additional context**

**Comment by horenmar** [comment]
Don't leak `min` and `max` macros into 3rd party projects.
