### ISSUE TITLE
Breaking changes between catch 2.x and catch 3.x

### ISSUE THREAD

**Issue by rerdavies** [catchorg/Catch2#2929]
**Describe the bug**
Building on Raspberry Pi OS (Debian 12), I include <catch2/catch.hpp> (`apt install catch2` installs catch  2.13.10-1).

But when building on Ubuntu 24.04, my build breaks because `apt install catch2` installs catch  3.4.0-1build1.

For those of us who are trying to support multi-platform builds this is an incredibly painful nightmare. 

Please don't do this again!

**Expected behavior**

`apt install catch2` should install a non-breaking version of catch 2.x.

Catch 3.x is a monstrously breaking build and should be installed using `apt install catch3`. Files should be installed in /usr/include/catch3.

And similarly for Catch 4.x.

**Reproduction steps**
Install Raspberry Pi OS Bookworm.  Run `apt install catch2`. This installs 2.13.10-1. Headers are placed in /usr/include/catch2

Install Ubuntu 24.04 LTS. Run `apt install catch2` installs installs catch  3.4.0-1build1. Headers are also placed in /usr/include/catch2.
Steps to reproduce the bug.

**Platform information:**

 - OS:  Raspberry Pi OS Bookworm  (Linux [omitted] 6.6.51+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux
 
 - Compiler+version: **GCC 12**
 - Catch version: **2.13.10-1**

 - OS:  Ubuntu 24.04 LTS
  (Linux [omitted] 6.8.0-48-generic #48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux)
 - Compiler+version: **GCC 12**
 - Catch version: **2.13.10-1**
 -

**Additional context**

**Comment by horenmar** [comment]
1) What makes you think I am the one doing packaging for Ubuntu/Debian?
2) If you are building on a different platforms, relying on `apt` packages is foolish; use a dependency manager.
