### ISSUE TITLE
Speedup compilation with precompiled header for catch.hpp

### ISSUE THREAD

**Issue by mnloop** [catchorg/Catch2#299]
I'm using `g++ -O2 -Wall -x c++-header test/catch.hpp -o test/catch.hpp.gch` to generate the PCH File, and reduced the compiling time from 9 seconds to 2 seconds for main.o!

However, the compilation stop at link stage.

```
Undefined symbols for architecture x86_64:
"Catch::SourceLineInfo::SourceLineInfo(char const*, unsigned long)", referenced from:
  __GLOBAL__I_a in main.o
"Catch::AutoReg::AutoReg(void (*)(), Catch::SourceLineInfo const&, Catch::NameAndDesc const&)", referenced from:
  __GLOBAL__I_a in main.o
"Catch::AutoReg::~AutoReg()", referenced from:
  __GLOBAL__I_a in main.o
"_main", referenced from:
 implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [aatest] Error 1
```

NOTE:
1. I'm able to link successfully without "-include catch.hpp" option when compile main.cpp

**Comment by kinjal63** [comment]
> Just for your information, I abandon using precompiled header to reduce compiling time, as I not able to use multiple/separate test case cpp implementation file this way.
> 
> Now, I found a way which only take 1 second or less to re-compile the modified project(even g++ optimization enabled), if only one line of code has been changed. It's really simple, the main.cpp file is dedicated to include the catch.hpp and main() function, and all other test cases are wrote in separate implement files(*.cpp). Just looks like:
> 
> ```
> // --- main.cpp ---
> #define CATCH_CONFIG_RUNNER
> #include "catch.hpp"
> 
> int main( int argc, char* const argv[] )
> {
>   // global setup...
>   int result = Catch::Session().run( argc, argv );
>   // global clean-up...
>   return result;
> }
> ```
> 
> ```
> // --- test.cpp ---
> #include "catch.hpp"
> 
> TEST_CASE( "Demo", "[Demo]" ) {
>     int jd = 0;
>     REQUIRE(jd == 0);
> }
> ```
> 
> I almost turned to the Google Test yesterday, due to the compilation taking so long time. But now, I really enjoys to use CATCH. Thanks for your great work!

The seperate test.cpp file is not getting compiled, can you please provide the steps how go run the test.cpp file after compiling main.cpp
