### ISSUE TITLE
--force-color flag

### ISSUE THREAD

**Issue by jargv** [catchorg/Catch2#305]
My workflow entails building and running the tests from a script (watch/change loop), so I only get colors if I manually invoke the tests. It'd be really nice if there were a simple --force-color flag to unconditionally apply colors for workflows like mine.

**Comment by peterhuene** [comment]
Adding a "me too" to this.  It'd be nice to see color output from CMake's ctest wrapper when using Catch.

**Comment by peterhuene** [comment]
I've thrown together a PR at https://github.com/philsquared/Catch/pull/374 in case we do want this.  It's sufficient for my needs, at least (getting ctest to output color with Catch).  Thanks!
