### ISSUE TITLE
target embedded devices?

### ISSUE THREAD

**Issue by m-mcgowan** [catchorg/Catch2#328]
I work with embedded devices. I've started using Catch to write tests that verify the hardware independent C++ code in my project, compiled using gcc.

It would be super awesome to be able to run the same tests on the embedded device also. On the embedded device (a STM32) there's about 40K of free program memory to play with, so not much, but the ARM gcc compiler does a good job of optimizing code. Are there features in Catch that could be made compile-time optional to squeeze Catch into this constrained environment?  Also since there is no stdout could a global stream be made available for all output, so embedded programs can direct output elsewhere (e.g. over a TCP socket or over a serial connection) by setting that global output stream?

There are existing test frameworks for embedded, such as [Arduino Unit](https://github.com/mmurdoch/arduinounit), but this uses a different syntax to Catch and so means keeping separate source code for on device tests vs off device tests.

Embedded devices are already in the billions and will continue to grow over the coming years. 
I hope this possibility gives food for thought - looking forward to an engaging conversation!

**Comment by Trass3r** [comment]
Any news on this, @m-mcgowan?

**Comment by mgcrea** [comment]
Not sur if I should start a new thread, but I've been trying to compile tests for a library that is supposed to run on Arduino. And so far I'm stuck on `error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information` errors.

Here is my Makefile:

```

ARDUINO_DIR   = /Applications/ArduinoLegacy.app/Contents/Resources/Java
SOURCES = TestMain.cpp
OBJECTS = $(patsubst %.cpp, %.o, $(SOURCES))
# CXX = $(ARDUINO_DIR)/hardware/tools/arm/bin/arm-none-eabi-g++
CXX = g++
ARDFLAGS = -include Arduino.h -MMD -c -DLAYOUT_US_ENGLISH -DUSB_SERIAL -mthumb -nostdlib -D__MK20DX256__ -DTEENSYDUINO=123 -x c++ -include Arduino.h -mcpu=cortex-m4 -DF_CPU=96000000 -DARDUINO=106 -DARDUINO_ARCH_ARM -D__PROG_TYPES_COMPAT__ -I$(ARDUINO_DIR)/hardware/teensy/cores/teensy3 -I$(ARDUINO_DIR)/hardware/teensy/arm/variants/
CXXFLAGS = $(ARDFLAGS) -I.. -Wall -Wno-extra-tokens -ffunction-sections -fdata-sections -Os -fno-rtti -felide-constructors -fno-exceptions -std=gnu++0x

#-std=c++11

CatchTest: $(OBJECTS)
	$(CXX) -o $@ $^

test: CatchTest
	./CatchTest

clean:
	rm -f $(OBJECTS) CatchTest


# Working Teensy3.1 build command
# /Applications/ArduinoLegacy.app/Contents/Resources/Java/hardware/tools/arm/bin/arm-none-eabi-g++
# -x c++ -include Arduino.h -MMD -c -DLAYOUT_US_ENGLISH -DUSB_SERIAL -mthumb -nostdlib -D__MK20DX256__ -DTEENSYDUINO=123
# -mcpu=cortex-m4 -DF_CPU=96000000 -DARDUINO=106 -DARDUINO_ARCH_ARM -D__PROG_TYPES_COMPAT__
# -I/Applications/ArduinoLegacy.app/Contents/Resources/Java/hardware/teensy/cores/teensy3 -I/Applications/ArduinoLegacy.app/Contents/Resources/Java/hardware/teensy/arm/variants/
# -I/Users/olivier/Projects/foo/teensy-table/lib/ArduinoJson   -I/Users/olivier/Projects/foo/teensy-table/lib/EEPROMEx   -I/Users/olivier/Projects/foo/teensy-table/lib/Firmata   -I/Users/olivier/Projects/foo/teensy-table/lib/OctoWS2811   -I/Users/olivier/Projects/foo/teensy-table/lib/Tween
# -Wall -ffunction-sections -fdata-sections -Os -fno-rtti -felide-constructors -fno-exceptions -std=gnu++0x app.ino -o build-teensy31/app.o
```

If it is easy to achieve, it would be great to add this to the docs.

**Comment by philsquared** [comment]
Reviewing old tickets: It looks like the original issue, here, was potentially resolved - but subsequent issues arose (and it's not clear, now, what the status of those is).
There's a whole set of potential issues when working in the embedded space and it's going to be an ongoing effort to raise specific issues and work through them.

So I'm marking this for closure soon unless someone (@m-mcgowan?) has more to add here?
For other issues relating to embedded targets please raise further tickets as appropriate.

**Comment by rgrover** [comment]
I am keen to use Catch for my project based on a ARM Cortex-M with only 256K of flash (code) space. Even though Catch allows me to replace std::cout etc with my own lightweight streams/stream-buffers, it still requires me to work with std::ostream. Ostream pulls in a huge amount of locale, time... related support in IOStreams. This is non-essential and bloats my test application to a size beyond the available flash--this in spite of using reasonable compiler/linker flags for optimizing space and removing the unnecessary bits.

The following report contains a table of symbol-sizes and symbol-names (in decreasing order of symbol-size) for the code that gets pulled into the binary as a result of introducing Catch:
[report1.txt](https://github.com/philsquared/Catch/files/1046175/report1.txt)
It was generated using

`nm --demangle --print-size --size-sort --reverse-sort --radix d`

Here are a few items from the top of the list (first column is size [in decimal], second column is symbol-type [according to nm]):

> 00001812 T std::locale::_Impl::_Impl(unsigned int)
00001812 T std::locale::_Impl::_Impl(unsigned int)
00001484 W std::__cxx11::time_get<...>::_M_extract_via_format(...) const
00001480 W std::__cxx11::time_get<...>::_M_extract_via_format(...) const
00001064 T std::locale::facet::_M_sso_shim(std::locale::id const*) const
...

A lot of these are un-necessary and come un-invited as a result of depending on iostreams.

I'd love to use Catch on my embedded device, and advocate its use to my colleagues.

**Comment by Trass3r** [comment]
> Even though Catch allows me to replace std::cout etc with my own lightweight streams/stream-buffers, it still requires me to work with std::ostream. Ostream pulls in a huge amount of locale, time... related support in IOStreams.

Thanks for clarifying that it is iostream striking again. Maybe doctest could work in an embedded setting?

**Comment by BitFis** [comment]
@rgrover Whats the current state of this, did you kept trying to find a way or did you stop?

**Comment by KKoovalsky** [comment]
@horenmar Could you comment why this is closed? Is it implemented?

**Comment by horenmar** [comment]
@KKoovalsky Because the issue has run its course.

The current status is that Catch2 provides some reasonable support for targets with limited C++ support (noexceptions mode is supported, you can avoid cout/cerr/clog streams), but the dependence on C++ stdlib, dynamic allocations and ostreams are here to stay.
