### ISSUE TITLE
Use assertion and log macros without TEST_CASE

### ISSUE THREAD

**Issue by luckyrandom** [catchorg/Catch2#330]
The assertion and log macros  can be used in body of functions as an elegant replacement of `assert`, which behaves unfriendly even for testing. It can be very useful, when some conditions, such as the status of iterator in the end of loop, can only be checked easily in the body of functions.

Currently, these macros work well if the functions were called in TEST_CASE, which is doable in most of case for the purpose of testing.

If the functions were called without TEST_CASE, it will throw an exception `std::logic_error: No result capture instance`. Is it possible to add support for such usage? I might be wrong, as I'm just exposed to Capture, it seems can be implemented by adding a default global result capturer.

**Comment by eyepatchParrot** [comment]
+1 to an assert replacement library.

**Comment by horenmar** [comment]
Sorry, but I do not intent for Catch2 to provide assertion macros that work outside the confines of tests.

However, if someone wants to tear out the assertion and decomposition code and make it into a separate library, they are welcome to though. (As long as they keep to the terms of Boost Software Licence obviously)
