### ISSUE TITLE
Linux Eclipse output console strange characters.

### ISSUE THREAD

**Issue by wimrijnders** [catchorg/Catch2#346]
This is a presentation-only issue. The unit testing appears to work fine.

Attached a screen-dump of the eclipse output console (copy-paste doesn't work):

![sd](https://cloud.githubusercontent.com/assets/769037/4659402/a02b7cac-550c-11e4-8dca-99aa87c57f1c.png)

This looks like ANSI control characters in the output, which aren't handled by the Eclipse console.

Is it possible to make ASCII-only output? Perhaps the option is already available but I can't find it.

**Comment by articuluxe** [comment]
I know this is an older issue, sorry.  But would it also be possible to disable the color if the TERM environment variable="DUMB"?
