### ISSUE TITLE
OnUnusedOptions::Ignore doesn't work for --option=value

### ISSUE THREAD

**Issue by tavianator** [catchorg/Catch2#386]
For example, with this `main()` implementation:

``` cpp
int
main(int argc, char** argv)
{
  Catch::Session session;
  session.applyCommandLine(argc, argv, Catch::Session::OnUnusedOptions::Ignore);
  return session.run();
}
```

when you do `./tests --foo=bar`, it responds with `No tests ran`.  It looks like `bar` is being interpreted as the name of a test, as if the command line was `./tests bar`.

**Comment by vpashka** [comment]
Try this:
./tests -- --foo=bar

before "--"  the arguments for catch
after "--" for your program

**Comment by VictorEijkhout** [comment]
Thanks!

Would it be an idea to add this factoid to https://github.com/philsquared/Catch/blob/master/docs/command-line.md ?

**Comment by philsquared** [comment]
I realise this is old and I'm not sure if this is still relevant to @tavianator, but the issue still stands.
This is one of the major problems with the way the arguments passthrough currently works - and is why it is undocumented.
If I'm honest it's unlikely this will get fixed until Catch2 and a new version of Clara (the underlying command line parser), which will be C++11 based.
I'll leave this ticket open as a feature request, though.

**Comment by horenmar** [comment]
I am going to close this, as the old Clara isn't going to get changed anymore.

**Comment by philsquared** [comment]
And, just got the record, it did get fixed in Catch2/Clara1.0 (parsers are now composable)
