### ISSUE TITLE
MSVC vs2012 lacks thread-safe static initialization

### ISSUE THREAD

**Issue by socantre** [catchorg/Catch2#388]
warning C4640: 's_instance' : construction of local static object is not thread-safe    d:\projects\acis\acis_adapter\test\catch.hpp    5991
warning C4640: 's_instance' : construction of local static object is not thread-safe    d:\projects\acis\acis_adapter\test\catch.hpp    6057
warning C4640: 'instance' : construction of local static object is not thread-safe  d:\projects\acis\acis_adapter\test\catch.hpp    7184

If thread-safety is not need in these functions, the warnings should be suppressed.

**Comment by Trass3r** [comment]
Finally implemented in VS2015 :)

**Comment by horenmar** [comment]
VS2012 is no longer supported
