### ISSUE TITLE
provide source location in the list of tests

### ISSUE THREAD

**Issue by Trass3r** [catchorg/Catch2#413]
To be able to register test cases in Visual Studio with a custom test adapter I need some information about them up-front, in particular source file and line number of the test case is not available currently.

I did some successful tests by hacking that into the --list-tests output in Catch::listTests:

``` cpp
    Catch::cout() << Text(testCaseInfo.lineInfo.file, tagsAttr) << ":" << std::to_string(testCaseInfo.lineInfo.line) << std::endl;
```

But in general it should be in a format better suited for automatic processing I guess.

**Comment by SeanCline** [comment]
I approached @philsquared about this via email a few months back for my own prototype of a Visual Studio test adapter. [https://github.com/SeanCline/CatchVsTestAdapter](https://github.com/SeanCline/CatchVsTestAdapter)

If I recall, his response was that he'd like to have multiple test listers that register themselves, similarly to how reporters currently do. (See `catch_reporter_registry.hpp` for a starting point in understanding how that works.)

I started implementing an xml test lister in addition to factoring out the current logic into a console lister. Unfortunately, I didn't end up getting it to a point where I was comfortable submitting it as a pull request.

I'd be curious to see Phil chime in about what it would take to get this feature added.

(At the very least, maybe we should consider combining efforts on a single Visual Studio extension.)

**Comment by Trass3r** [comment]
Ha interesting, my one is @ https://github.com/Trass3r/CppTestRunner
But Catch support is not public yet as I need to refactor it quite a bit.

**Comment by philsquared** [comment]
Actually my point was that test listing should be routed through the reporters - rather than being a separately registered system.

**Comment by Trass3r** [comment]
That sounds sound.

**Comment by kkutsner** [comment]
Resharper C++ for Visual Studio supports Catch 1.x very nicely. I requested support for Catch 2.0. There is an issue https://youtrack.jetbrains.com/issue/RSCPP-20082. Please comment, vote.

**Comment by philsquared** [comment]
@kkutsner making sure the latest Catch2 build works with R++ has been on my list for a while, but I've been having problems getting into Windows :-s
Are you seeing specific problems with it?
Perhaps you could raise a new ticket here?

**Comment by kkutsner** [comment]
@philsquared Unfortunately, I'm new to R++ and I have no idea for now how to troubleshoot it. I tried one of the most recent prelease versions of Catch 2.0 and R++ was not able to pick it up - it didn't recognize that project has unit tests inside, however it worked fine on the same project when I switched to older Catch header file of version 1.10.

So I decided to reach JetBrains guys to see if they can fix problem on their side so they just logged that issue. @hmich is assigned to that issue.

@hmich I just tried to search for GitHub user Igor Akhemtov assuming it's you and you have some relationship to Resharper product. Sorry if you are not that person - just ignore this message.

**Comment by Trass3r** [comment]
You should also make some noise @ https://blogs.msdn.microsoft.com/vcblog/2017/11/02/unit-testing-test-adapter-for-boost-test-goes-in-box/

**Comment by kkutsner** [comment]
@Trass3r I did:) - I talked to Microsoft guys at CppCon 2017 and I was asking them in person:) 
I got feeling they were keeping it in plans.

**Comment by Trass3r** [comment]
Yeah they've said multiple times already they received a bunch of requests for Catch support already but no visible actions yet.

**Comment by hmich** [comment]
@kkutsner This week's EAP build (should be available from https://www.jetbrains.com/resharper/eap/ on Friday) will support Catch2.

**Comment by Trass3r** [comment]
Woohoo! Then I can switch to C2.

**Comment by philsquared** [comment]
@kkutsner yeah, I spoke to MS guys about Catch support at CppCon, too :-)
Mind you, if I can't even get R++ integration right, then it's not a good sign! I'm actually planning some changes to help with IDE integration, so hopefully this will be more stable going forward.

**Comment by horenmar** [comment]
This is actually support now, via `--list-tests --verbosity high`.

The output looks like this:
```
  Floating point matchers: float
    /mnt/c/Users/Xarn/Documents/GitHub/Catch/projects/SelfTest/UsageTests/
    Matchers.tests.cpp:296
    (NO DESCRIPTION)
      [floating-point][matchers]
  Floating point matchers: double
    /mnt/c/Users/Xarn/Documents/GitHub/Catch/projects/SelfTest/UsageTests/
    Matchers.tests.cpp:334
    (NO DESCRIPTION)
      [floating-point][matchers]
```
