### ISSUE TITLE
GitHub Releases

### ISSUE THREAD

**Issue by cinemast** [catchorg/Catch2#430]
Hi!

First, great software. Thank you for developing and maintaining it.

Could you please create regular releases for your software? GitHub provides that automatically if you just use tags to mark your versions.

https://wiki.debian.org/Creating%20signed%20GitHub%20releases

That would be great.

**Comment by philsquared** [comment]
Sorry for not getting back sooner. I've done a bit of tweaking to support Semantic Versioning and am now tagging "release" commits.

**Comment by cinemast** [comment]
Great, thank you!

Could you also take a look about signing releases using GPG/PGP? That would be great.

**Comment by philsquared** [comment]
I'll look into that @cinemast - looks like quite a bit of work to get set up

**Comment by cinemast** [comment]
I get that. But I really put more screenshots in there than required, to make everything as clear as possible. 

Basically its:
- Generate a gpg key
- download/create tarball
- sign it using gpg
- upload signature as attachment to the release.

If you have any questions, just conact me (also off list, my mail is on my github account site).

Thanks for considering it.

**Comment by horenmar** [comment]
Well it took a while but the latest release is properly signed*

\* In that the constituent tag and released headers are signed, I am not planning to be signing the tarball as it is not intended for distribution.
