### ISSUE TITLE
Support C++11 pseudo-random generators

### ISSUE THREAD

**Issue by prapin** [catchorg/Catch2#443]
CATCH has a command line option `--rng-seed` to initialize pseudo-random generator before running unit tests, either with a fixed value or based on time.

It currently only calls `srand` with the specified value, to prepare next calls to `rand`.

The problem is that `srand` and `rand` are _legacy_ C functions inherited by C++98.
In C++11, a whole new and quite complete API has been developed for pseudo-random generators (http://en.cppreference.com/w/cpp/numeric/random)

My proposal is to add in CATCH a global variable `Catch::random`, of type `Catch::random_t` that can be defined as for example as `std::default_random_engine`. That variable is initialized before each test (see issue #442) with the same seed as `srand`. Then, unit tests can use that variable to generate random numbers with `std::uniform_int_distribution` or any similar function.

Of course, to continue supporting old C++98 compilers, that feature has to be in a `#if` compilation switch block.

**Comment by f-koehler** [comment]
I support this idea, would be great!

**Comment by philsquared** [comment]
I've taken a first step in this direction.
First, `srand()` is now called (with the same seed) before every test case is invoked.
Secondly, the value of the seed is now globally available (from test case) by calling `Catch::rngSeed()` - so you can use it to see your own generator deterministically and repeatably.
I do plan to provide an alternate to the current use of `srand()`, `rand()` and `std::random_shuffle()` for C++14+ compilers - but I believe what I've done already should meet your immediate needs?
It's available in the `v1..2.1-develop.2` build.

**Comment by Morwenn** [comment]
@philsquared I like that `Catch::rngSeed()` exists, but is there a way to know whether `--rng-seed` has been passed to the command-line, like `Catch::rngWasSeeded()`? When running my test suite in CI I want to seed it with `--rng-seed`, but otherwise I don't care that much and might automatize the generation from within the test suite itself with a poor man's seed.

**Comment by philsquared** [comment]
@Morwenn - a bit late, I know - but `Catch::rngSeed()` returns 0 if it has not been set.

**Comment by Morwenn** [comment]
Oh, fair enough, thanks :)
