### ISSUE TITLE
Compare byte arrays

### ISSUE THREAD

**Issue by espenalb** [catchorg/Catch2#451]
First of all: Thanks for an excellent framework! I am working on converting our unit tests to Catch, after learning about catch at NDC2015. :smile: 

I sometimes need to compare two arrays - and I would like to know if there is an efficient way to do this in Catch.
What I would like to do is
`REQUIRE_BYTE(actual == expected, sizeof(expected))`
or just 
`ASSERT_ARRAY_EQUALS(expected,actual,sizeof(expected))`

Is this possible in Catch today? 
I wrote a macro wrapper for this, which uses a for loop something like

```
for (int ix=0;ix<sizeof(expected);ix++) { \
     CAPTURE(ix); \
     REQUIRE( actual[ix] == expected[ix]); }
```

But this macro gives a poor error message - and has unacceptable performance...

I guess I _could_ go via a `std::array` or something similar - but I was hoping someone had a better idea...

**Comment by philsquared** [comment]
Hi @espenalb,

Thanks for trying Catch - and thanks for letting me know you saw it at NDC Oslo :-)
If you were in my talk (or did you watch the video?) you'll know that there is also a, half-baked, Matchers implementation in the framework (with an undecided future). That would be exactly the right place for such functionality - but, as I said, it's not in a production ready state right now.

**Comment by shreyasbharath** [comment]
+1, this would really be handy for testing C codebases.

**Comment by shreyasbharath** [comment]
@horenmar Can I implement this? Can you point me in the right direction?

**Comment by philsquared** [comment]
@shreyasbharath docs are here: https://github.com/philsquared/Catch/blob/master/docs/matchers.md

Let me know if you need more help.
