### ISSUE TITLE
junit and classname/name inconsistency with sections

### ISSUE THREAD

**Issue by mintyc** [catchorg/Catch2#486]
If I have a test case without sections, the junit output writes differently than if it does have sections

Example showing first a test case with sections (last section entry shown) and second a test case with no sections

```
<testcase classname="SimpleStringTest::testAssign" name="ConstCharAssignIsNull" time="0.000023"/>
<testcase classname="global" name="SimpleStringTest::testCStr" time="0.000023"/>
```

Would you consider the second form becoming

```
<testcase classname="SimpleStringTest::testCStr" name="global" time="0.000023"/>
```

This maintains consistency of test case names and avoids having lots of simple testcases all being grouped under a single classname "global"

ie generally classname= testcase name, name = section name or some default where no section exists
[and perhaps replacing "global" with "default" or "" in name field]

**Comment by englishb** [comment]
I just ran into this issue as well, and it took me about 3 hours to figure out that there's nothing wrong with my unit test or my Jenkins configuration where I saw the result.

I had added a new unit test by copy+pasting a previous unit test .cpp file, and then changing the names & tags in the TEST_CASE macro and modifying the contents of the test.  Intuitively I would have thought a difference like this would come from my TEST_CASE macro, but these were nearly identical, so I had to hunt through includes and see if any #defines were affecting it, etc.  It was very obscure that it is affected by the presence of sections.  Sample from my output:

```
<testcase classname="TestSuite.DitherShader.TemporalPatternTest" name="Every value in the temporal pattern is unique" time="0.000104"/>
<testcase classname="global" name="TestSuite.NewShader.TestWithReferenceRasterizer" time="2.174213"/>
```
