### ISSUE TITLE
switch to disable stdout redirect

### ISSUE THREAD

**Issue by philsquared** [catchorg/Catch2#49]
stdout (and stderr) are redirected (internally to an ostringstream), so they can be reported later as part of the test results.
Sometimes it is desirable to see the output immediately - especially while debugging.

A command line switch could be provided to allow this option.

**Comment by ikanor** [comment]
Might be a good idea to capture it and display only if the test fails – a behaviour I've seen in other testing frameworks.

**Comment by nabijaczleweli** [comment]
:+1: Very user-friendly behaviour
