### ISSUE TITLE
JUnit output does not include all INFO messages

### ISSUE THREAD

**Issue by whanhee** [catchorg/Catch2#500]
Here are some sanitized outputs. The first message from my test is a description of all the test parameters. It works with the default output:

> ```
> qaTests.exe is a Catch v1.2.1 host application.
> Run with -? for options
> 
> -------------------------------------------------------------------------------
> MyTest
> -------------------------------------------------------------------------------
> MyTest.cpp(45)
> ...............................................................................
> 
> MyTest.cpp(181): FAILED:
>  CHECK( bMatchCount )
> with expansion:
>  false
> with message:
>  Block Test
>    Population: 200
>    Duration: 600
> 
> 
> ===============================================================================
> test cases:  1 |  0 passed | 1 failed
> assertions: 46 | 45 passed | 1 failed
> ```

And this is the JUnit output, only listing the check that failed.

> <testsuites>
>   <testsuite name="all tests" errors="0" failures="1" tests="46" hostname="tbd" time="6.76967" timestamp="tbd">
>     <testcase classname="global" name=MyTest" time="6.769014">
>       <failure message="false" type="CHECK">
> at MyTest.cpp(181)
>       </failure>
>     </testcase>
>     <system-out/>
>     <system-err/>
>   </testsuite>
> </testsuites>

Some of the tests do actually output more information, but only when the INFO is directly ahead of the CHECK.

**Comment by whanhee** [comment]
Here's a minimal example that should demonstrate the issue:

> TEST_CASE( "foo" )
> {
>     INFO( "hello!" );
>     CHECK( true );
>     CHECK( false );
> }

Compiling then running this with `test foo` prints the hello while `test foo -r junit` does not.

**Comment by horenmar** [comment]
I tried to reproduce this with current build and it seems fixed.

This is the test file:
```
#include "catch.hpp"

TEST_CASE("foo") {
    INFO("hello!");
    CHECK(true);
    CHECK(false);
}
```
and this is the output
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="CatchWork.exe" errors="0" failures="1" tests="2" hostname="tbd" time="0.000717" timestamp="2017-11-03T17:03:21Z">
    <testcase classname="CatchWork.exe.global" name="foo" time="0.000297">
      <failure message="false" type="CHECK">
hello!
at c:\users\xarn\documents\github\catchwork17\catchwork\test1.cpp(6)
      </failure>
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>
```
The message is there...
