### ISSUE TITLE
Feature Request: Export for DLL

### ISSUE THREAD

**Issue by Darelbi** [catchorg/Catch2#515]
What about adding a EXPORT MACRO inside catch? 

Actually with GCC/CLANG I can just CATCH_CONFIG_MAIN inside a DLL and link with executables. However the same is not possible with visual studio because it insist to say that "libCatch.lib" cannot be opened. (I'm using Cmake to automate most stuff, after investigation I found that's the error for missing exported symbols). The problem is fixed using Catch as static library, however the static library means instead of getting many executables of 170 Kb, I get many executables of ~1MB, wich could become an issue If later I have hundreds test files.

I want to be able to define a CATCH_EXPORT macro or something similiar beside CATCH_CONFIG_MAIN so I can use shared library also with visual studio.

The use case scenario is.

1 Catch.dll
Many test executables (each one separately linked and runeed against the DLL).

Possibly I want just to compile the following file to get the DLL (right know I think Catch just deduces Import/export settings assuming all test cases are linked togheter into 1 executable, however that has the serious problem that if 1 test fail CMake execution of tests will interrupt, while with my current setup all tests are runned indipendently of wich fails)

**Catch.cpp**

```
#define CATCH_CONFIG_MAIN
#define CATCH_EXPORT
#include "Catch.hpp"
```

**Comment by Darelbi** [comment]
If you are curious about how I'm using Catch here's my Repo:
(not for spamming eh, I see you are using only travis, so you could be interested in adding support to windows builds like I just did in these days)

https://github.com/Darelbi/Infectorpp2

**Comment by fschuh** [comment]
Any updates on this request?
This would be very nice to have, my use case also involves test code spread across multiple DLLs.

**Comment by jwuttke** [comment]
Must have; otherwise catch2 does not qualify for cross-platform development

**Comment by randaz81** [comment]
ping

**Comment by horenmar** [comment]
https://github.com/catchorg/Catch2/blob/devel/docs/faq.md#can-i-compile-catch2-into-a-dynamic-library

**Comment by jwuttke** [comment]
Martin, that link only says you won't support DLLs under Windows. Why not? Little change to your code, big gain in usability!
