### ISSUE TITLE
Conan package for Catch

### ISSUE THREAD

**Issue by bjoernpollex** [catchorg/Catch2#569]
I've created a [Conan package for Catch](https://github.com/bjoernpollex/catch_conan_package). It needs some polishing, but should work. It is rather trivial, as Catch has no dependencies, and is header-only. Still I've only been able to test it on Mac OS, so if someone could see if it works on other platforms too?

Finally, I'd wanted to ask if the author of Catch is fine with me uploading the package to the central Conan repository.

**Comment by horenmar** [comment]
@bjoernpollex We are ok with uploading Catch to Conan, but I would prefer to some sort of infodump, about how to keep the package up to date as new versions are released, so we can integrate packaging new versions to Conan as part of our releases.

**Comment by memsharded** [comment]
This is being done in https://github.com/philsquared/Catch/pull/943 to upload to Bintray conan-center.

**Comment by JoeyGrajciar** [comment]
Closing as Catch2 Conan package is already out there.
