### ISSUE TITLE
Invalid enum caught by gcc sanitize in 1.3.0

### ISSUE THREAD

**Issue by tamboril** [catchorg/Catch2#583]
Got this with gcc's `-fsanitize=undefined :` 

```
/catch.hpp:6271:18: runtime error: load of value 3200171710, which is not a valid value for type 'InWhatOrder'
```

That line is:
`if(  m_currentSortOrder != config.runOrder() || m_sortedFunctions.empty() ) {`

**Comment by JoeyGrajciar** [comment]
Can not reproduce with latest release 2.5.0

**Comment by tamboril** [comment]
Thanks!
