### ISSUE TITLE
[Feature] Option to output summary only 

### ISSUE THREAD

**Issue by criptych** [catchorg/Catch2#613]
I've been using Catch with a very large set of tests, and the current state of the project I'm testing is such that most of them fail.  The tests are automatically generated from known test vectors, so they fail in pretty much the same way, and I'm more interested in just knowing _how many_ failed than which ones and where, so I'd like to get just the total without the error log.

Somewhat related (perhaps it should be another issue?), what about adding a summary by tag, e.g.

```
[this-tag]: 10 passed, 12 failed
[that-tag]: 5 passed, 0 failed
```

Which would be handy for seeing if there is a common type of test that is failing a lot?

**Comment by horenmar** [comment]
Coming back to this, I think this is out of scope for Catch, and should be solved by [using the Reporters interface to create your own reporter that can format the output in whatever way you want](https://github.com/catchorg/Catch2/blob/master/docs/reporters.md#writing-your-own-reporter).
