### ISSUE TITLE
Passing arguments to a test

### ISSUE THREAD

**Issue by mrzv** [catchorg/Catch2#622]
I'd like to write a test that takes some arguments on the command line and based on those performs some action. A simple example would be some of the `vector` tests from the documentation that take the initial vector size on the command-line.

The only way I see how to do this is to create a fixture that has the arguments as static members, then to provide my own `main` that parses the command-line arguments, initializes the fixture member variables, and passes control to `session.run()`. That seems a little verbose. Is there no simpler way to do this?

**Comment by DraTeots** [comment]
I've found this [here](https://github.com/philsquared/Catch/blob/master/docs/own-main.md)

> Adding your own command line options

>Catch embeds a powerful command line parser which you can also use to parse your own options out. This capability is still in active development but will be documented here when it is ready.

So what is the status of it? Maybe it is kind of more ready now? 

What I need to do is to pass different connection strings corresponding to different databases to check that all tests are passing with all supported databases. Now I do this with environment variables but it is... mmm... dirty?.. I would definitely prefer to CATCH to handle it with its argument parser, giving the values to the tests that require them.

**Comment by lightmare** [comment]
Take a look at https://github.com/mapnik/mapnik/blob/master/test/unit/run.cpp (adds options `--prefix` and `--working-directory`). For this to work you'll need to change `Catch::Session:cli()` return type to non-const reference. I think you can omit the single-letter variants, which I'd recommend as those are more likely to clash with future additions to basic Catch options.

TODO: I have one that adds a boolean option somewhere, will find it and link in an edit.

**Comment by czipperz** [comment]
This is the command line parser https://github.com/philsquared/Clara.

**Comment by KingDuckZ** [comment]
I'm also interested in this, or at least int a way to get the list of unprocessed parameters back from Catch/Clara.

**Comment by dhaumann** [comment]
Any news on this, even if preliminary?

**Comment by horenmar** [comment]
See #793.

The short version is that Catch2 makes it fairly easy to add arguments.
