### ISSUE TITLE
Is it possible to use Catch with -fno-exceptions?

### ISSUE THREAD

**Issue by hh9527** [catchorg/Catch2#703]
As title

**Comment by alecazam** [comment]
Agreed, most of the apps that I work explicitly forbid exceptions (f.e. Emscripten based targets).  We turned on exceptions for Catch, but it slows down the compile times, and the runtime immensely.   I appreciate the cleanliness of the API, but a set/longjump approach when exceptions are off would open this unit test framework up to more codebase.  There doesn't appear to be a way to only enable exceptions on the unit test cpp files.  I prefer to run unit test at startup of the actual app, so you can always be testing.

**Comment by kirbyfan64** [comment]
> but a set/longjump approach when exceptions are off would open this unit test framework up to more codebase

Pretty sure what completely screw up RAII and stack unwinding...

**Comment by GatoRat** [comment]
setjmp/longjmp are unreliable and should never be used.

Seems the best solution would be to create a separate GitHub project for it.

**Comment by nabijaczleweli** [comment]
The `longjmp()` function family is literal cancer.

**Comment by alecazam** [comment]
I'm well aware of what set/longjmp do and their ramifications on destructors, and goto are evil too, but when you need them you need them.  The reliance on exceptions in this unit test framework leaves little in the way of alternatives.  

I'm not too concerned about leaking memory from the Catch framework, and aren't the exceptions only used on failures?  The typical use case here is to launch with unit test at that start, and then fail the application from running if the unit tests do.  So the stack unwinding doesn't seem too serious in this case.

**Comment by alecazam** [comment]
Setting some sort of error state with early returns before the next macro is another alternative.

**Comment by nabijaczleweli** [comment]
Just use C if you want `*jmp*()`. Dabble not in C++ therewith. I might or might not have done Very Bad things to a PC with 'em.

**Comment by alecazam** [comment]
Here's an excerpt from the Google unit test framework.  Catch would be a lot more useful if it followed suit:

https://github.com/google/googletest/blob/master/googletest/docs/Primer.md
Google C++ Testing Framework works on different OSes, with different compilers (gcc, MSVC, and others), **with or without exceptions**, so Google C++ Testing Framework tests can easily work with a variety of configurations.

**Comment by nabijaczleweli** [comment]
Catch != GTest. If you want `-fno-exceptions` then use GTest. `-fno-exceptions` is out of scope for Catch.
/thread

**Comment by alecazam** [comment]
I understand that you like exceptions.

**Comment by ruipacheco** [comment]
`-fno-exceptions` would be nice.

**Comment by magreenblatt** [comment]
How about adding a configuration that #ifdef's out all functionality (THROWS macros, etc.) related to exception handling? Existing usage of "throw X" could be wrapped in a macro or function and implemented differently in cases where exceptions are disabled (for example, print an error message and crash). That seems like a reasonably clean approach that also preserves stack traces.

**Comment by nlohmann** [comment]
I would also like a version that is compilable with `-fno-exceptions`. While it is nice to have the `-e` command line parameter, it does not help if the code to be testet needs to rely on the STL not throwing.

**Comment by Leandros** [comment]
Still out of scope for catch?

**Comment by horenmar** [comment]
I thought about this some more and supporting `-fno-exceptions` would mean a call to `abort` on failed test.

This does not seem like a good idea for testing framework.

**Comment by nlohmann** [comment]
I would expect all `CHECK_THROW` macros to be skipped when `-fno-exceptions` is set.

**Comment by horenmar** [comment]
You can do that already via ` -e, --nothrow                             skip exception tests`. This allows you to also skip test cases tagged with `[!throws]`.

The problem with `-fno-exceptions` is that `REQUIRE` throws an exception upon failed assert and the standard solution to that is to call `abort` instead.

**Comment by ruipacheco** [comment]
No way to just return?

**Comment by nlohmann** [comment]
If that is the case, then I can understand that this issue cannot be easily solved. :-/

**Comment by horenmar** [comment]
@ruipacheco Just returning works for assertions directly inside a test case, but assertions are specifically intended to support nested function, e.g. this
```cpp
void check_bits(uint32_t val) {
    REQUIRE(val & 1 == 1);
    REQUIRE(val & 2 == 0);
    REQUIRE(val & 4 == 4);
}

TEST_CASE("foo") {
    uint32_t val = getval();
    check_bits(val);
}
```

the only way to support this is via exceptions, or exception-like mechanism. This leads to the problem where the only way to support `-fno-exceptions` is to hard abort on failed assertion, which is... suboptimal for a test framework.

**Comment by ruipacheco** [comment]
Bubble up error codes?

**Comment by fschuh** [comment]
Apparently Google Test also aborts the test during an assert if Exceptions are disabled.
We follow a similar approach in our application by using a custom test reporter that will abort the test as soon as an assert comes up.

We just need to override:
    `bool assertionEnded(Catch::AssertionStats const& assertionStats)`

The nice thing is that it allows you to print any information you want about the assertion before exiting.
It's not optimal but still usable (and requires no changes on Catch).

To avoid compilation errors with `-fno-exceptions`, we `#define CATCH_CONFIG_FAST_COMPILE`, which gets rid of the try/catch blocks and allows compilation to succeed.

**Comment by TorstenRobitzki** [comment]
@fschuh how did you managed to work around the `throw Catch::TestFailureException();` in `AssertionHandler::complete()`?

**Comment by fschuh** [comment]
@TorstenRobitzki you want to fail early, so that `throw Catch::TestFailureException();` never gets executed.

`AssertionHandler::complete()` runs after `assertionEnded()`, so you have the opportunity to do that. 
Just make sure to exit the application before `assertionEnded()` returns.

You can print out the assertion information before exiting though, which will give you feedback for the first error that occurred.

**Comment by iam** [comment]
I created a pull request to in an attempt to support catch2 with ```-fno-exceptions```. It doesn't yet handle the ```AssertionHandler::complete()``` problem since I'm not sure what is the most appropriate solution.

If anyone wants to take a look #1358  , feedback is appreciated. Maybe it is redundant to ```#define CATCH_CONFIG_FAST_COMPILE``` but I am not sure.
