### ISSUE TITLE
compilation error : a type of global namespace

### ISSUE THREAD

**Issue by faithandbrave** [catchorg/Catch2#757]
Hi, I am using `__int128` type of GCC/Clang. The type defined in global namespace. When I define `operator<<` in global namespace, happen compilation error.

```cpp
#include <iostream>

//namespace std { // workaround for Catch bug
// http://stackoverflow.com/questions/25114597/how-to-print-int128-in-g
std::ostream&
operator<<( std::ostream& dest, __int128 value )
{
    std::ostream::sentry s( dest );
    if ( s ) {
        __int128 tmp = value < 0 ? -value : value;
        char buffer[ 128 ];
        char* d = std::end( buffer );
        do
        {
            -- d;
            *d = "0123456789"[ tmp % 10 ];
            tmp /= 10;
        } while ( tmp != 0 );
        if ( value < 0 ) {
            -- d;
            *d = '-';
        }
        int len = std::end( buffer ) - d;
        if ( dest.rdbuf()->sputn( d, len ) != len ) {
            dest.setstate( std::ios_base::badbit );
        }
    }
    return dest;
}
//}

#define CATCH_CONFIG_MAIN
#include "catch.hpp"

TEST_CASE("compare of 128-bits integer") {
    __int128 a = 1, b = 1;
    CHECK(a == b);
}
```

```
$ clang++ main.cpp -std=c++14 -I /repository/GitHub/Catch/include
In file included from main.cpp:33:
In file included from /repository/GitHub/Catch/include/catch.hpp:34:
In file included from /repository/GitHub/Catch/include/internal/../reporters/../internal/catch_capture.hpp:11:
In file included from /repository/GitHub/Catch/include/internal/catch_result_builder.h:96:
In file included from /repository/GitHub/Catch/include/internal/catch_expression_lhs.hpp:13:
/repository/GitHub/Catch/include/internal/../reporters/../internal/catch_tostring.h:91:49: error:
      use of overloaded operator '<<' is ambiguous (with operand types 'std::ostream'
      (aka 'basic_ostream<char>') and 'const __int128')
        enum { value = sizeof( testStreamable(s << t) ) == sizeof( TrueType ) };
                                              ~ ^  ~
/repository/GitHub/Catch/include/internal/../reporters/../internal/catch_tostring.h:149:37: note:
      in instantiation of template class 'Catch::Detail::IsStreamInsertable<__int128>' requested here
    Detail::StringMakerBase<Detail::IsStreamInsertable<T>::value> {};
```

I changed `IsStreamInsertable` implementation to using Expression SFINAE (C++11 feature) for fix compile.

```cpp
    //struct BorgType {
    //    template<typename T> BorgType( T const& );
    //};

    //struct TrueType { char sizer[1]; };
    //struct FalseType { char sizer[2]; };

    //TrueType& testStreamable( std::ostream& );
    //FalseType testStreamable( FalseType );

    //FalseType operator<<( std::ostream const&, BorgType const& );

    //template<typename T>
    //struct IsStreamInsertable {
    //    static std::ostream &s;
    //    static T  const&t;
    //    enum { value = sizeof( testStreamable(s << t) ) == sizeof( TrueType ) };
    //};

    struct IsStreamInsertableImpl {
        template <class T>
        static auto check(T*) -> decltype(
        std::declval<std::ostream&>() << std::declval<const T&>(),
        std::true_type());

        template <class T>
        static auto check(...) -> std::false_type;
    };

    template <class T>
    struct IsStreamInsertable
        : decltype(IsStreamInsertableImpl::check<T>(nullptr)) {};
```

However, Catch library seems support C++03.
If the library drop support C++03, I'll send pull request the change.

My use version is https://github.com/philsquared/Catch/commit/2be372710ec496922bb583e55386fc2ca8d646c5 .
Thanks.

**Comment by faithandbrave** [comment]
FYI, `sizeof( testStreamable(s << t) )` is maybe undefined behavior. SFINAE happens from function signature (parameter or return type context, not argument).

**Comment by horenmar** [comment]
Catch isn't dropping C++03 support, but a new rewrite for C++11 and up will be made at some point.

**Comment by lightmare** [comment]
At first I thought this was a name lookup issue, but after trying with gcc 4.8 through 6.2 and clang 3.5 through 4.0 and getting essentially the same error, and none of them even mentioning the `operator<<` overload for `__int128` as a viable candidate, it seems the compilers are right.

Here's what happens. The lookup for `operator << ` starts with the current scope (that is namespace `Catch::Detail`) plus what's added by ADL. The first argument is `std::ostream` so it adds namespace `std` to the search, the second argument is fundamental type `__int128` so it doesn't add anything (`[basic.lookup.argdep] clause 2`). Thus it finds `Catch::Detail::operator<<` overload for `BorgType`, the "you will all be assimilated" proxy, and a bunch of `std::operator<<` overloads. Lookup stops once a name is found, it doesn't continue searching enclosing namespaces (including the global namespace).

User-side solution:
Put the `operator<<` overload for `__int128`
 - either in namespace `std`, so that it's found through ADL
 - or in namespace `Catch::Detail`, so that it's found through unqualified name lookup (but then it'll only be available to Catch)

Catch-side solution:
```c++
// global namespace
Catch::Detail::FalseType operator<<(std::ostream&, Catch::Detail::BorgType const&);

namespace Catch {
namespace Detail {
using ::operator<<;
...
```

**Comment by lightmare** [comment]
@horenmar This issue is not C++11 specific. The example code only uses `std::end(buffer)`, which can be replaced with `buffer + sizeof(buffer)`.

**Comment by horenmar** [comment]
I won't be touching this in Catch Classic, but it will work in Catch 2.

**Comment by JoeyGrajciar** [comment]
Seems that this issue is fixed by https://github.com/catchorg/Catch2/commit/6cede0101ada18017c817e1afa68a4835f785e0c

**Comment by horenmar** [comment]
I am not 100% sure, but I think it does.

If it doesn't, someone can reopen this issue.
