### ISSUE TITLE
Name of project

### ISSUE THREAD

**Issue by BMBurstein** [catchorg/Catch2#769]
I know this is not likely to change, but it is very hard to search for anything related to this project, such as tutorials or help on SO, since the name of the project is also a keyword in c++. It would help if the project was renamed to something else that is less likely to appear anyway in a c++ context.

**Comment by polyvertex** [comment]
You mean it's pretty hard to catch up with it on the Internet? :)

**Comment by nabijaczleweli** [comment]
v0v ![image](https://cloud.githubusercontent.com/assets/6709544/21638801/3c11feea-d26d-11e6-8aa8-0e4b40e74622.png)

**Comment by BMBurstein** [comment]
Yes, the library itself comes up first. But searching for related things (help, tutorials) is hard. Look at your example search. Most of the results have nothing to do with this library.

**Comment by philsquared** [comment]
I will soon be forking Catch - the next generation version will be C++11 only. I'm going to call it Catch2 - and try to push this name to be used everywhere in the hope that it ameliorates the situation enough.

**Comment by GatoRat** [comment]
How about Catch11?

**Comment by horenmar** [comment]
Catch22, because two twos are better than one.

(Not actually serious suggestion)

**Comment by polyvertex** [comment]
Reminder for the refactoring: #697

**Comment by SoftwareApe** [comment]
@horenmar Actually that makes sense Catch version 2? C++ 11? 2 * 11 = 22

**Comment by philsquared** [comment]
TBH, @SoftwareApe, that was precisely what I was thinking when I went with it!

**Comment by horenmar** [comment]
We ended up with Catch2, see [Phil's new blog post](http://www.levelofindirection.com/journal/2017/11/3/catch2-released.html).
