### ISSUE TITLE
INFO macro isn't compiled with types from std

### ISSUE THREAD

**Issue by KVic** [catchorg/Catch2#880]
## Description
The compilation error occurs in the INFO macro with some type from std namespace. It seems that operator << overload for std::ostream doesn't work properly for a types from std namespace in the INFO macro.

### Steps to reproduce
```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include <chrono>

using SomeStdType = std::chrono::system_clock::time_point;

std::ostream& operator << ( std::ostream& os, SomeStdType const& std_value )
{
    os << "std type convertion"; // << std_value
    return os;
}

TEST_CASE( "INFO of SomeStdType" )
{
    SomeStdType std_value;
    INFO( "std_value = " << std_value );
    CHECK( std_value == SomeStdType() );
}
```
```
catch.hpp:1970: error: no match for 'operator<<' (operand types are 'std::ostringstream {aka std::__cxx11::basic_ostringstream<char>}' and 'const std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long long int, std::ratio<1ll, 1000000000ll> > >')
             m_stream << value;
             ~~~~~~~~~^~~~~~~~
```

### Extra information
* Catch version: **v1.8.2**
* Operating System: **Windows 7 x64**
* Compiler+version: **mingw 5.3.0 32bit, mingw 6.3.0 32bit, msvc 2015 32bit**

**Comment by lightmare** [comment]
Looks very similar (in effect) to #757 .

Name lookup starts with namespace `Catch`, ADL adds namespace `std` because the first argument is `std::ostream` and `std::chrono` because the second is `std::chrono::system_clock::time_point`. It yields a bunch of overloads, none of which matches. Global namespace is not searched.

Put the overload into namespace `Catch`. It's a bit weird, but the C++ standard doesn't allow adding overloads into namespace `std`.

**Comment by KVic** [comment]
Ok, let's see the next code:

```
// other_catch.hpp
#ifndef OTHER_CATCH_HPP_INCLUDED
#define OTHER_CATCH_HPP_INCLUDED

#include <sstream>

namespace OtherCatch
{
struct MessageBuilder
{
    MessageBuilder() {}

    template<typename T>
    MessageBuilder& operator << ( T const& value ) {
        m_stream << value;
        return *this;
    }

    std::ostringstream m_stream;
};
}

#endif // OTHER_CATCH_HPP_INCLUDED
```

```
// main.cpp
#include <ostream>
#include <chrono>

using SomeStdType = ::std::chrono::system_clock::time_point;

::std::ostream& operator << ( ::std::ostream& os, SomeStdType const& )
{
    os << "std type convertion"; // << std_value
    return os;
}

#include "catch.hpp"
#include "other_catch.hpp"

int main (int, char * [])
{
    SomeStdType std_value;

    // Error
    Catch::MessageBuilder( "INFO", CATCH_INTERNAL_LINEINFO, Catch::ResultWas::Info ) << std_value;
    // Ok
    OtherCatch::MessageBuilder() << std_value;

    return 0;
}
```
What's the difference between Catch::MessageBuilder and OtherCatch::MessageBuilder?

**Comment by KVic** [comment]
Maybe operator<< overloads ( such as  [std::ostream& operator << ( std::ostream& os, SourceLineInfo const& info );](https://github.com/philsquared/Catch/blob/v1.8.2/single_include/catch.hpp#L468) ) must be outside of the Catch namespace?

**Comment by lightmare** [comment]
> What's the difference between Catch::MessageBuilder and OtherCatch::MessageBuilder?

The difference is that namespace `OtherCatch` doesn't contain any `operator<<` overloads, so lookup continues in its enclosing (global) namespace.
But `Catch` contains *some* `operator <<` overloads, so lookup stops there.

**Comment by lightmare** [comment]
> Maybe operator<< overloads must be outside of the Catch namespace?

Yes and no. Operator overloads should be in the namespace where one of their argument types is defined, so that ADL can find them. So to remove them from the `Catch` namespace, the streamable classes (`SourceLineInfo` et al) should be moved into `Catch::Detail` along with their operators.

**Comment by KVic** [comment]
> Operator overloads should be in the namespace where one of their argument types is defined, so that ADL can find them.

Why "should"? What's wrong with operator overloads in the global namespace?

```
// catch.hpp
namespace Catch
{
struct SourceLineInfo {};
}

std::ostream& operator << ( std::ostream& os, Catch::SourceLineInfo const& )
{ 
    ...
    return os;
}
```
```
// main()
    ...
    Catch::SourceLineInfo info;
    Catch::MessageBuilder( "INFO", Catch::SourceLineInfo(), Catch::ResultWas::Info ) << info;
    ...
```

**Comment by lightmare** [comment]
> Why "should"? What's wrong with operator overloads in the global namespace?

Because if an operator is not defined in the same namespace as one of its argument types, it won't be found from within another namespace that also overloads that operator, even for completely unrelated types:
```c++
#include <ostream>

namespace Good
{
    struct Foo {};

    std::ostream& operator << (std::ostream& os, Foo);
}

namespace Wrong
{
    struct Bar {};
}

std::ostream& operator << (std::ostream& os, Wrong::Bar);

namespace User
{
    struct Zan {};

    std::ostream& operator << (std::ostream& os, Zan);

    void dump(std::ostream& os)
    {
        // name lookup in all three statements below finds
        //  User::operator<<(std::ostream&, User::Zan)
        // and a set of standard overloads for fundamental types
        // (brought via ADL because of std::ostream)
        //  std::operator<<(std::ostream&, **fundamental type**)

        os << Zan() << std::endl;

        os << Good::Foo() << std::endl; // OK
        // in addition to overloads from namespaces User and std,
        // ADL brings Good::operator<<(std::ostream&, Good::Foo)

        os << Wrong::Bar() << std::endl; // ERROR
        // ::operator<<(ostream&, Wrong::Bar) won't be found
    }
}
```

**Comment by KVic** [comment]
@lightmare, thank you for a good explanation!

I guess that a name lookup for an operator overloads  should start from the global namespace, not from the Catch namespace. So a streaming operations in a template methods ( [StringMakerBase::convert()](https://github.com/philsquared/Catch/blob/v1.8.2/single_include/catch.hpp#L1618), [MessageBuilder::operator<<()](https://github.com/philsquared/Catch/blob/v1.8.2/single_include/catch.hpp#L1970), [IsStreamInsertable::value](https://github.com/philsquared/Catch/blob/v1.8.2/single_include/catch.hpp#L1576), and others) should be moved into function in the global namespace. Somehow like [this](https://github.com/KVic/Catch/commit/8fa81473ee61a5d32c06a9e99604e46f6cb1ea50).

**Comment by lightmare** [comment]
> I guess that a name lookup for an operator overloads should start from the global namespace, not from the Catch namespace.

I think it's better when name lookup works the same for operator and non-operator functions.
```c++
namespace A
{
    struct X { int value; };
}

A::X foo(A::X x, int i) { return { x.value + i }; }

namespace B
{
    using A::X;
    struct Y { double value; };
  
    Y foo(X x, double d) { return { x.value + d }; }

    void see() {
        X x = { 3 };
        Y y = foo(x, 5); // calls B::foo(X, double)
        // lookup stops when a name is found,
        // in other words B::foo shadows ::foo
    }
}

// now replace `foo` with `operator+`
// same rules apply
```

**Comment by KVic** [comment]
```
TEST_CASE( "INFO of SomeStdType" )
{
    SomeStdType std_value;
    INFO( "std_value = " << std_value );
    CAPTURE( std_value );
    CHECK( std_value == SomeStdType() );
}
```

For a normal operation, should name lookup for operator<< in the INFO macro (CAPTURE, CHECK and so on) start from the Catch namespace or from the global namespace? My last commit and fix is exactly about this case with Catch. What's wrong with [this solution](https://github.com/KVic/Catch/commit/8fa81473ee61a5d32c06a9e99604e46f6cb1ea50)?

**Comment by lightmare** [comment]
@KVic I misunderstood you last time. I thought you were questioning how name lookup works, as per standard (I've read `[basic.lookup]` a few times and am still not 100% sure I got it right, it's pretty dense). Now I agree with you that forcing lookup in the global namespace might actually be better, less surprising to users, and only a small change in Catch. Another option would be to remove all `operator<<` overloads from the Catch namespace, which would likely require more changes.

**Comment by horenmar** [comment]
I haven't had time to keep up properly and the exact ADL rules tend to make me cross-eyed :smile:

Anyway, I think that explicitly pulling in global `operator<<` before performing the ADL lookup is preferable to poluting global namespace with weirdly named function, and should have the same results.


There would still be issues in Catch with ADL calls, IIRC `toString` is usually called qualified as `Catch::toString`, even in places where it is supposed to be a customization point, but that can be solved later.

**Comment by horenmar** [comment]
I spent some time digging through various stringification issues and I believe that they need to be fixed in Catch 2, with larger rework of the stringification layer.

**Comment by horenmar** [comment]
This will now work in Catch2, if you declare the `operator<<` overload before including catch header. Theoretically it would be possible to make it work even when the overload is declared after including catch header, but not while supporting MSVC (or at least I was unable to find a workaround, that compiles).

**Comment by horenmar** [comment]
Tested this against the released Catch 2, and the results are as above. It works, but `operator<<` overload needs to be declared before including `catch.hpp`.
