### ISSUE TITLE
Wrong line number (code location) reported in failing tests

### ISSUE THREAD

**Issue by turha654** [catchorg/Catch2#881]
## Description
It seems in some cases the extra lines in other files are added to the line number of a failing test. Not sure if this is just an issue on my system, VS or with Catch. Read the below sample to better understand the issue.

### Steps to reproduce
In Visual Studio 2015 I created empty C++ project and copied the catch.hpp file to the source folder and then created three new files:
main.cpp
```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
```

test1.cpp
```
#include "catch.hpp"
// Notice the empty lines below

// This comment also adds one to the test2.cpp failing test cases reported line number


TEST_CASE("test1", "") {
	REQUIRE(1 == 1);
}
```

test2.cpp
```
#include "catch.hpp"

TEST_CASE("test2", "") {
	REQUIRE(1 == 2);
}
```

Outcome
```
test2
-------------------------------------------------------------------------------
test2.cpp(3)
...............................................................................
test2.cpp(8): FAILED:
  REQUIRE( 1 == 2 )

===============================================================================
test cases: 2 | 1 passed | 1 failed
assertions: 2 | 1 passed | 1 failed
```

I would expect test2.cpp(8) to be test2.cpp(4).

I also noticed that if I add a test0.cpp with same content as test2.cpp except TEST_CASE name changed to test0 then it again works as expected.

Note that I also saw in some cases that the test2.cpp(3) line was wrong too, but this simplified sample doesn't demonstrate that.

### Extra information
* Catch version: **Catch v1.8.1**
* Operating System: **Windows 7 x64**
* Compiler+version: **MS Visual Studio 2015 VC++**

**Comment by horenmar** [comment]
This is interesting, I stepped into the REQUIRE and by the time `SourceLineInfo` is constructed, we already receive line 8 as line info.

Even more interestingly, if I change `test2.cpp` to this
```cpp
#include "catch.hpp"

#include <iostream>

TEST_CASE("test2", "") {
    std::cout << __LINE__ << '\n';
    REQUIRE(1 == 2);
}
```
I get this output
```
8

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CatchWork.exe is a Catch v1.8.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
test2
-------------------------------------------------------------------------------
c:\users\xarn\documents\github\catchwork\catchwork\test2.cpp(5)
...............................................................................

c:\users\xarn\documents\github\catchwork\catchwork\test2.cpp(9): FAILED:
  REQUIRE( 1 == 2 )
```
which suggests, that somehow `TEST_CASE` increases the line count generated by compiler.

However, when I add yet another test case to the file, it works as expected, that is, it prints out the proper line numbers:
```cpp
#include "catch.hpp"

#include <iostream>

TEST_CASE("test2") {
    std::cout << __LINE__ << '\n';
    REQUIRE(1 == 2);
}

TEST_CASE("test3") {
    std::cout << __LINE__ << '\n';
    REQUIRE(1 == 2);
}
```

```
8

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CatchWork.exe is a Catch v1.8.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
test2
-------------------------------------------------------------------------------
c:\users\xarn\documents\github\catchwork\catchwork\test2.cpp(5)
...............................................................................

c:\users\xarn\documents\github\catchwork\catchwork\test2.cpp(9): FAILED:
  REQUIRE( 1 == 2 )

11
-------------------------------------------------------------------------------
test3
-------------------------------------------------------------------------------
c:\users\xarn\documents\github\catchwork\catchwork\test2.cpp(10)
...............................................................................

c:\users\xarn\documents\github\catchwork\catchwork\test2.cpp(12): FAILED:
  REQUIRE( 1 == 2 )
```

**Comment by turha654** [comment]
I tried expanding the macro manually and at some point it starts giving correct results, I didn't expand the INTERNAL_CATCH_TESTCASE2 macro further because the UNIQUE_NAME macro expansion started to give correct line numbers, so I don't know if expanding the TESTCASE2 further would also have started to give proper results. Also possibly worth noting is the fact that all the wrong line numbers are the same (8) in this test. Hopefully this might help find the actual root of the problem.

My comments in the file expect that only one TEST_CASE is uncommented at a time. At the bottom is the test case with just single macro expansion done manually and from there every TEST_CASE above is one further expansion. The first one gives correct results.
```
#include "catch.hpp"

// Expanding the TEST_CASE macro manually

///*
// The below one produces correct results, 7 and 8
INTERNAL_CATCH_TESTCASE2(INTERNAL_CATCH_UNIQUE_NAME_LINE2(____C_A_T_C_H____T_E_S_T____, __COUNTER__), "test3.4", "") {
	REQUIRE(1 == 34);
}
//*/




// All of the below ones produce wrong results (the TEST_CASE line correct, the REQUIRE line wrong)


/*
// Produces 20 (correct) and 8 (incorrect)
INTERNAL_CATCH_TESTCASE2(INTERNAL_CATCH_UNIQUE_NAME_LINE(____C_A_T_C_H____T_E_S_T____, __COUNTER__), "test3.3", "") {
REQUIRE(1 == 33);
}
*/


/*
// Produces 28 (correct) and 8 (incorrect)
INTERNAL_CATCH_TESTCASE2(INTERNAL_CATCH_UNIQUE_NAME(____C_A_T_C_H____T_E_S_T____), "test3.2", "") {
	REQUIRE(1 == 32);
}
*/


/*
// Produces 36 (correct) and 8 (incorrect)
INTERNAL_CATCH_TESTCASE("test3.1", "") {
	REQUIRE(1 == 31);
}
*/


/*
// Produces 44 (correct) and 8 (incorrect)
TEST_CASE("test3.0", "") {
	REQUIRE(1 == 30);
}
*/
```

**Comment by horenmar** [comment]
So I got back around to this and I found an interesting thing. This bug does not manifest itself when compiling tests in release mode.

I opened a Microsoft Connect bug (goddamn, that is the worst bug reporting experience I've had, its like they don't want people to report bugs) and will see where it goes from here.

**Comment by nabijaczleweli** [comment]
People can't tell your software is dogshit if they can't report *why* it's dogshit.

![black man pointing at own temple](http://i0.kym-cdn.com/photos/images/facebook/001/217/711/afd.jpg_large)

**Comment by horenmar** [comment]
As an update, the issue is "under investigation", so... who knows.

**Comment by briterator** [comment]
Just a note for individuals coming across this in the future: we were experiencing a similar issue, but it was caused by visual studio's /ZI option (edit and continue) which is documented to not work correctly with __LINE__
