### ISSUE TITLE
lldb: script to allow "step-in" to skip the Catch frames

### ISSUE THREAD

**Issue by jaredgrubb** [catchorg/Catch2#904]
Has anyone developed any lldb (or gdb) scripts that set it up to allow lldb to skip stepping into Catch code?

For example, if I have this:
   CHECK(foo());
and I am debugging, I want to step-into the foo function, but right now, it steps into all the CHECK infrastructure and it's annoying to try to get into foo directly. 

Debuggers have ways to inform them that certain frames are not interesting and should be skipped when doing debugging. 

Has anyone developed such scripts for Catch? I can maybe take a stab, but I figure someone may have already done it, and I think it'd be a great addition to the Catch repo.

**Comment by horenmar** [comment]
There are none that I know of, but if you create one I'd definitely add it to the `contrib` part of repo.
