### ISSUE TITLE
Request: a REQUIRE that is not counted as a test

### ISSUE THREAD

**Issue by paulharris** [catchorg/Catch2#915]
There can be a lot of code involved in setting up a test.

I want to use a lot of assert()s to ensure I do things right, but I don't want to use the standard assert() since I want the tests to go ahead even when NDEBUG is defined.

Using REQUIRE is nice, but the test-setup-asserts should not be counted as a "successful" test.

In the meantime, I'll just define REQUIRE_NOTTEST() macro that throws a logic exception.
Was hoping the library would provide a nice macro to do this.

**Comment by horenmar** [comment]
So if I understand this correctly, you have a test like this

```cpp
TEST_CASE("Example 1") {
    // -- Init --
    auto foo = 1;
    REQUIRE(foo == 1);

    // -- More init --
    auto bar = 2;
    REQUIRE(bar == 2);

    auto foobar = foo + bar;
    REQUIRE(foobar == 3);
}
```
with this output
```
===============================================================================
All tests passed (3 assertions in 1 test case)
```
and would prefer it to have this output
```
===============================================================================
All tests passed (1 assertion in 1 test case)
```
by using a new macro for the `REQUIRE`s during initialization? This is easy enough if you don't want the expression decomposition to work, as you have found out, but integrating it with Catch leads to some open questions, like "Should a REQUIRE_INIT count as failed assertion?" and "If not, is it reasonable to output "0 failed assertions, 1 failed test case?".

**Comment by paulharris** [comment]
You have the right idea,

With respect to:
> "Should a REQUIRE_INIT count as failed assertion?" and "If not, is it reasonable to output "0 failed assertions, 1 failed test case?"

If REQUIRE_INIT fails, it should abort the test in a fail-fast way.  Its not testing the software, its testing that the test was written correctly.

Note that its not just in the INIT phase,
it could be...

INIT (fail-fast asserts)
TEST SOMETHING (standard REQUIRE)
ADJUST TEST FOR NEXT STEP
CHECK ADJUSTMENT (fail-fast asserts)
TEST SOMETHING (standard REQUIRE)

So once the test is written correctly (and doesn't fail-fast), it then runs for ever more.
But its only really testing the target library with 2 tests.  It would be misleading for the test to say that 5 tests passed when the reality is that only 2 of the tests was actually testing the target software.

The difference between using a standard ASSERT and REQUIRE_INIT would be that the REQUIRE_INIT is always executed (it ignores NDEBUG).

I don't think it requires parameter expansion either.  It just has to test that the test is configured correctly.

Anyway, thats what I think.
