### ISSUE TITLE
Conan recipe for Catch project

### ISSUE THREAD

**Issue by uilianries** [catchorg/Catch2#926]
## Description
I have written Conan recipes for Catch, since version 1.4.1, you can see [here](https://github.com/uilianries/conan-catch). However, would be nice if Catch provides its own recipe in the project.

I can help with this, starting to write the recipe.

**Comment by philsquared** [comment]
That's awesome - thanks @uilianries.
It's been on my list of things to do to look into automating getting Catch onto Conan.
Ideally I'd like it to be automated as part of our release scripts - do you think that's possible?

**Comment by uilianries** [comment]
Sure! Conan Package Tools checks the branch name and submits to target channel. e.g. master branch is used as stable channel. So, we can use the same rule create new releases in the recipe.

**Comment by philsquared** [comment]
So now the recipe is in, do we need to do anything else on each release for Conan to get it?

**Comment by uilianries** [comment]
Each new release will update your conan recipe, but won't create and push Catch package to Conan remote.  
For each new release you need to create the package after provide the single_header and push to Conan repository.  
You will need create a Bintray account.
See [here](http://docs.conan.io/en/latest/packaging/bintray/move.html) for more information about Conan + Bintray.
Anyway, you could use CI (Travis/AppVeyor/Gitlab) to automate each package push. I can help to develop this feature.

**Comment by philsquared** [comment]
Thanks. Yes I suspected there was still an extra step.
I'd appreciate any help with that!

**Comment by uilianries** [comment]
Nice!  
Should I use the same issue? I could close this issue and open a new, with a appropriated description. (one issue = one feature)

**Comment by memsharded** [comment]
HI @philsquared 
I think the best would be to create a "catch" organization in bintray, so you can easily bring people in it to collaborate (though in this case maintenance will be absolutely straightforward), then a repo inside the organization. Also, publishing to this repo can be done with just one CI, no need to upload from all of them, as header-only package will always be the same). 

Which release approach to bintray would you like? Do you want to upload conan packages to bintray for "master", or just the tagged releases? How do you identify your releases in CI? Thanks!

**Comment by philsquared** [comment]
@uilianries creating a new issue is probably "how it should be done" - but I'm fine with just continuing here.

@memsharded Thanks for the guidance. A Catch "release" really just consists of updating some version numbers (which, thanks to @uilianries now updates the conanFile.py, too), "building" the single include and tagging the commit (with the form vX.X.X).
Currently the CI scripts make no distinction between a normal code change commit and a "release". If we're going to push to Conan from the CI we'd a way to identify that (for example seeing if the version file has been changed in this commit).

**Comment by uilianries** [comment]
By default, Conan uses a branch pattern to identify the stable channel, we could use release tag, e.g. `CONAN_STABLE_BRANCH_PATTERN=v\d+\.\d+\.\d+`. So, when a new tag is created, the package will be pushed to Conan remote by Travis build.

Okay, I'll use the same issue to develop.
