### ISSUE TITLE
Unfinished sentence in docs/assertions.md

### ISSUE THREAD

**Issue by daixtrose** [catchorg/Catch2#942]
## Description

One sentence in `assertions.md` reads 
> scale - scale serves to adjust the base for comparison used by epsilon, **can be used when [???] By default**  set to 1.0.

* Catch version: **master**
* Operating System: **OS independent**
* Compiler+version: **none**

**Comment by horenmar** [comment]
That one is on me I think, I remember trying to expand `Approx` documentation and having to go figure out what scale is good for.

Apparently after I figured it out, I didn't write it down.

**Comment by horenmar** [comment]
This has been fixed since.
