### ISSUE TITLE
Tests failed with address sanitizer.

### ISSUE THREAD

**Issue by slepasteur** [catchorg/Catch2#967]
### Description
Executing Catch's tests compiler with address sanitizer enabled with g++ 7.1.1 produces a stack-use-after-scope error.

### Steps to reproduce
Add sanitizer flags to CMakeLists.txt:
`set(CMAKE_CXX_FLAGS` "${CMAKE_CXX_FLAGS} -fsanitize=address `-fno-omit-frame-pointer")`
Build and run the tests.

### Extra information
* Catch version: **v1.9.6**
* Operating System: **Arch Linux 4.9.37-1-lts**
* Compiler+version: **g++ (GCC) 7.1.1 20170630**

**Comment by JoeyGrajciar** [comment]
Can not reproduce with v2.5.0
