### ISSUE TITLE
[Documentation suggestion] provide table of contents on larger-than-screen pages

### ISSUE THREAD

**Issue by martinmoene** [catchorg/Catch2#970]
For example:

**Contents**
[**Getting Catch**](https://github.com/philsquared/Catch/blob/1e59ccee41f269440310979a0b6ab7e4dbb1e453/docs/tutorial.md#getting-catch)
[Where to put it?](https://github.com/philsquared/Catch/blob/1e59ccee41f269440310979a0b6ab7e4dbb1e453/docs/tutorial.md#where-to-put-it)
[**Writing tests**](https://github.com/philsquared/Catch/blob/1e59ccee41f269440310979a0b6ab7e4dbb1e453/docs/tutorial.md#writing-tests)
[What did we do here?]()
[Test cases and sections]()
[BDD-Style]()
[Scaling up]()
[Next steps]()

**Comment by horenmar** [comment]
I really don't want to do this manually, GitHub's markdown doesn't support generating ToC and most solutions I saw started like "install node.js" which for me is a no go.

**Comment by martinmoene** [comment]
One writer suffers, many readers (may) benefit, as opposed to vv,  or at least so goes the thinking.

I think a TOC can be quite helpful to readers to scan if a page might contain the information they are looking for, or to easily see which section to head to.

Although it would be preferable for such TOC to come free, I resist the thinking that it must be.

**Comment by martinmoene** [comment]
Supporting information.

Number of sections:
```
$ grep --count  "^## " docs/*.md
docs/assertions.md:4
docs/build-systems.md:4
docs/command-line.md:22
docs/commercial-users.md:0
docs/configuration.md:2
docs/contributing.md:3
docs/event-listeners.md:2
docs/limitations.md:3
docs/logging.md:3
docs/matchers.md:3
docs/opensource-users.md:2
docs/own-main.md:3
docs/Readme.md:0
docs/release-notes.md:7
docs/release-process.md:2
docs/reporters.md:2
docs/slow-compiles.md:4
docs/test-cases-and-sections.md:3
docs/test-fixtures.md:0
docs/tostring.md:3
docs/tutorial.md:7
docs/why-catch.md:3
```
---
Aside:  in contrast with the majority of other document pages, `docs/build-systems.md` , `docs/configuration.md` and `docs/release-notes.md` have more than one toplevel page title.

Number of 'page' titles:
```
$ grep --count "^# " docs/*.md
docs/assertions.md:1
docs/build-systems.md:7
docs/command-line.md:1
docs/commercial-users.md:1
docs/configuration.md:9
docs/contributing.md:1
docs/event-listeners.md:1
docs/limitations.md:1
docs/logging.md:1
docs/matchers.md:1
docs/opensource-users.md:1
docs/own-main.md:1
docs/Readme.md:1
docs/release-notes.md:14
docs/release-process.md:1
docs/reporters.md:1
docs/slow-compiles.md:1
docs/test-cases-and-sections.md:1
docs/test-fixtures.md:1
docs/tostring.md:1
docs/tutorial.md:1
docs/why-catch.md:1
```

**Comment by horenmar** [comment]
Yeah, our formatting isn't really consistent across files.

**Comment by martinmoene** [comment]
Any desire to consitensify?

**Comment by horenmar** [comment]
Definitely, but without ToC present, the inconsistency wasn't too noticeable and I was content to keep formatting consistent inside a page, rather than redo the documentation in the same style.

**Comment by martinmoene** [comment]
? Shall I give a shot at
- TOCs for pages with # sections >= 4
- Page (chapter) title at level 1, sections at level 2

**Comment by horenmar** [comment]
Page titles should be level 1 and should be only 1 per page. I see three offenders that need fixing. Of those, I would give exception to the release notes, where I would like to have a structure like
```
# <current release>
# Older releases
## v1.9.7
## v1.9.6
## v1.9.5
...
```
There might be some value in grouping the older releases by major/minor/patch (and giving these progressively lower levels), like
```
## v1.9.x
### v1.9.7
### v1.9.6
...
### v1.9.0
## v1.8.x
...
```


As far as ToCs are concerned, after thinking about them for a bit longer, they should be easy enough to create using some Python. The real question is, how deep should they go (all levels, versus 2 levels, versus ...) and when is the page long enough for one. Starting with pages with 4 sections seems good enough for now.

**Comment by martinmoene** [comment]
For the Tutorial I went for a single-level ToC. The change from having no ToC to having one is will for always remain the biggest step ;)

**Comment by martinmoene** [comment]
Plan

- [ ] Withdraw PR #1002 , Add table of contents to Tutorial
- [ ] Fix heading levels, except in docs/release-notes.md
- [ ] Fix heading levels, except in docs/release-notes.md
- [ ] Add table of contents, using script, see below
- [ ] Revert files with less than 4 entries in table of contents

---
Use [markdown-toclify](https://github.com/rasbt/markdown-toclify) by Sebastian Raschk (@rasbt) with "Table of Contents" modified to "Contents" and list modified to ...

catch-toclify.bat
```
@echo off & setlocal enableextensions
::
:: ./Catch-toclify.bat - ... (https://github.com/rasbt/markdown-toclify)
::
if [%1] == [] goto :Usage

set files= %*%

set root=%~dp0
set toclify=%root%\markdown-toclify.py

echo Converting:
for %%f in ( %files% ) do (
    echo "%%f
    python "%toclify%" --github --exclude_h 1,3 %%f -o %%f.tmp
    copy /y %%f.tmp %%f >nul
    del %%f.tmp
)
endlocal & goto :EOF

:Usage
echo %0 [file...]
endlocal & goto :EOF

rem
rem end of file
rem
```

**Comment by horenmar** [comment]
Can you also open a PR to commit the modified script to Catch?

**Comment by martinmoene** [comment]
Will do; is that including the script `catch-toclify.py ` that drives `markdown-toclify.py ` or excluding?

**Comment by horenmar** [comment]
Including, preferably it would be as easy to use as `fixWhitespace.py`, which runs automatically over all files in the repository.

**Comment by martinmoene** [comment]
Argh, only saw your remark after I created PR #1008 .

**Comment by martinmoene** [comment]
Perhaps expand this PR to arrive at a single script `addDocumentToC.py` or better `updateDocumentToC.py` that uses `scriptCommon.py`?

**Comment by martinmoene** [comment]
Hi @horenmar, I'd like to make several addional changes to `updateDocumentToC.py`. Shall I add them to the current PR #1008, or create a new one once the latter has been merged?

---

Additional changes for `updateDocumentToC.py`

- [ ] Content of main -> function updateDocumentsTocMain()
- [ ] Parameterize minTocEntries
- [ ] Return number-of-changed-files from updateDocumentToC
- [ ] Return is-changed from updateSingleDocumentToC()
- [ ] Return is-changed from markdownToclify()
- [ ] Skip file-rename dance if unchanged in updateSingleDocumentToC()
- [ ] Use named parameters in calls to update[ Single ]DocumentToC()

**Comment by horenmar** [comment]
Add them to the current PR. Feel free to rebase and force push to clean it up as you want.

**Comment by martinmoene** [comment]
Will do.

**Comment by martinmoene** [comment]
Done.

**Comment by martinmoene** [comment]
Hi @horenmar, currently the table of contents is never removed, e.g. if min-toc-entries is increased from 3 to 4. Is it still possible to make some further changes to PR #1008 ?

What should `updateDocumentToC.py.` report? Number of _changed_ files (ToC added/removed/updated), number of files with ToC added/removed ... ?

Further changes:

- [ ] Fix updateDocumentToC tot remove TOC if min-toc-entries requests so
- [ ] Add option --remove-toc

**Comment by horenmar** [comment]
Feel free to make further changes, I won't be able to review it for some time.

**Comment by martinmoene** [comment]
Ok, thanks.

**Comment by martinmoene** [comment]
@horenmar ... a bit busy... hope to have something in about a week...

**Comment by martinmoene** [comment]
@horenmar `updateDocumentToC.py` now also _removes_ a table of contents if needed. Also added option `--remove-toc` (equivalent to `--min-toc-entries 99`).

**Comment by horenmar** [comment]
This is in
