### ISSUE TITLE
Light Yellow instead of Yellow for Warning Color in Windows

### ISSUE THREAD

**Issue by M-Fabian** [catchorg/Catch2#979]
This is only a tiny issue. The non-light colors in Win32 Console are all very dim and boring. Hence, you already use the bright green and bright red. I wonder if you could also use bright yellow for warnings. You use Colour::Yellow for warnings and reconstructed expressions. I have no opinion about whether reconstructed expressions should be yellow or bright yellow.

Since I would like to use bright yellow in my reporter, I would already be happy if you added Colour::BrightYellow.

Also, it took me a while to understand that there are no colors when a debugger is active. I found --use-color, but I don't understand why color and the debugger could harm each other. Could you please explain this briefly?

**Comment by horenmar** [comment]
I'll test how the different colours would look later, but

>Also, it took me a while to understand that there are no colors when a debugger is active. I found --use-color, but I don't understand why color and the debugger could harm each other. Could you please explain this briefly?

You are not the first one to ask this, see #590. Looking through that and performing a cursory google search says that some debug consoles (in IDEs and stuff) can run into trouble with escape codes.

I actually disabled that check for Catch 2 and it is likely to stay disabled (users with trouble can run catch with `--use-colour no`).

**Comment by M-Fabian** [comment]
I see. Fingers crossed for BrightYellow ;-)

**Comment by M-Fabian** [comment]
Now that version 2 is out, I had hoped for BrightYellow. It is actually quite simple:

`case Colour::BrightYellow:    return setTextAttribute( FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY);`

Would you please consider adding BrightYellow, as the normal Yellow in Windows Console is muddy and dim...

**Comment by M-Fabian** [comment]
Awesome, thank you! Catch continues to be my favorite Unittest framework :-)

**Comment by horenmar** [comment]
Thanks, and sorry for the long wait. The issue kinda slipped my mind and the backlog is still huge.

**Comment by M-Fabian** [comment]
Could you please also add BrightYellow to Catch1?
It seems that Catch1 is still under active development, which I appreciate since I cannot switch to Catch2 yet (because of my old compiler I am bound to use in my current projects),
Please consider it for the next release 1.12.3.

I cannot reopen this issue. Do I need to make a new issue for this request?
