### ISSUE TITLE
Nested section in for

### ISSUE THREAD

**Issue by lordofinsomnia** [catchorg/Catch2#993]
## Description
Nested section in for

### Steps to reproduce

```c++
TEST_CASE("test vector sizes") {
    int vecSizes[] = {
        0, 10, 1000
    };

    for (auto size : vecSizes) {
        std::vector<int> vec(size);

        SECTION("array is created with helper function fromStdVector") {
            SECTION("compare sizes") {
                CHECK(true);
            }
            SECTION("manually count items in array)") {
                CHECK(true);
            }
        }

        SECTION("array is created with constructor with pointer and size") { // here i got Debug error when size = 10.
            CHECK(true);
        }
}
```

```
This is debug error
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Error!

Program: test.exe

R6010

- abort() has been called



(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore   
---------------------------
```

### Extra information

* Catch version: **v1.9.7**
* Operating System: **W7x64**
* Compiler+version: **vc110**

Maybe I am using catch wrong, but i need this kind of functionality.

**Comment by horenmar** [comment]
You are indeed using it wrong (or rather, our documentation about this issue sucks).

I won't go into the underlying reason, but to fix you have to make the `SECTION`s different for each iteration. The best way is to incorporate the loop's counter into `SECTION`'s name, like so:

```cpp
TEST_CASE( "..." ) {
    for (int i = 0; i < 5; ++i) {
        SECTION("FooBarBaz" + std::to_string(i)) {
            // ...
        }
    }
}
```

**Comment by lordofinsomnia** [comment]
Thank you it works. I find out that subsections does need to be numbered. Here is code that works.

```c++
TEST_CASE( "..." ) {
    for (int i = 0; i < 5; ++i) {
        SECTION("FooBarBaz" + std::to_string(i)) {
            SECTION("subFooBarBaz") { //here numbering is not needed
            // ...
            }
        }
    }
}
```

**Comment by svadimr** [comment]
Hi, for me this code doesn't work. When I have a SECTION inside for, only the iteration enters the SECTION. 

TEST_CASE(` "..." ) {
    for (int i = 0; i < 5; ++i) {
        SECTION("FooBarBaz" + std::to_string(i)) {
            // this code performed only for i = 0, which is a problem
        }
    }
}

**Comment by philsquared** [comment]
reviewing some older unclosed tickets... @svadimr are you sure? It should re-enter the whole test case again and go into the section for one iteration on each re-execution.

like this:

0 -> execute
1 -> skip
2 -> skip
3 -> skip
4 -> skip

0 -> skip
1 -> execute
2 -> skip
3 -> skip
4 -> skip

0 -> skip
1 -> skip
2 -> execute
3 -> skip
4 -> skip

etc...
